import { Scholarship } from './types';

export const scholarships: Scholarship[] = [
  // ========================================
  // 1. TAMIL NADU STATE GOVERNMENT SCHEMES
  // ========================================
  
  // Gender-Based Scholarships
  {
    id: 'tn-pudhumai-penn',
    name: 'Pudhumai Penn Scheme',
    provider: 'Tamil Nadu Government (UMIS)',
    type: 'government',
    amount: '₹1,000/month (Until Degree Ends)',
    eligibility: ['Girl Students', 'Studied 6th-12th in Govt Schools', 'UG Students'],
    deadline: 'Always Open',
    deadlineStatus: 'always-open',
    educationLevel: ['ug'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'female',
    state: 'Tamil Nadu',
    description: 'Monthly financial support for girl students who studied from 6th to 12th in government schools. Continues until degree completion.',
    applicationUrl: 'https://umis.tn.gov.in',
    helpline: '044-25361520',
    documents: ['School TC (Govt School)', 'College Admission Letter', 'Aadhaar Card', 'Bank Passbook', 'Photo'],
    howToApply: ['Apply through UMIS portal', 'Submit govt school TC (6th-12th)', 'Bank account verification', 'Monthly disbursement begins'],
    benefits: [{ label: 'Monthly Amount', value: '₹1,000' }, { label: 'Annual Total', value: '₹12,000' }, { label: 'Duration', value: 'Until Degree Ends' }]
  },
  {
    id: 'tn-tamil-pudhalvan',
    name: 'Tamil Pudhalvan Scheme',
    provider: 'Tamil Nadu Government (UMIS)',
    type: 'government',
    amount: '₹1,000/month (Until Degree Ends)',
    eligibility: ['Boy Students', 'Studied 6th-12th in Govt Schools', 'UG Students'],
    deadline: 'Always Open',
    deadlineStatus: 'always-open',
    educationLevel: ['ug'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'male',
    state: 'Tamil Nadu',
    description: 'Monthly financial support for boy students who studied from 6th to 12th in government schools. Continues until degree completion.',
    applicationUrl: 'https://umis.tn.gov.in',
    helpline: '044-25361520',
    documents: ['School TC (Govt School)', 'College Admission Letter', 'Aadhaar Card', 'Bank Passbook', 'Photo'],
    howToApply: ['Apply through UMIS portal', 'Submit govt school TC (6th-12th)', 'Bank account verification', 'Monthly disbursement begins'],
    benefits: [{ label: 'Monthly Amount', value: '₹1,000' }, { label: 'Annual Total', value: '₹12,000' }, { label: 'Duration', value: 'Until Degree Ends' }]
  },

  // Community-Based Scholarships
  {
    id: 'tn-bc-mbc-post-matric',
    name: 'BC/MBC Post-Matric Scholarship',
    provider: 'BC/MBC Welfare Department, TN (TNSSP)',
    type: 'government',
    amount: 'Tuition Fee + Exam Fee Coverage',
    eligibility: ['BC/MBC/DNC Category', 'Family Income < ₹2.5 Lakhs', 'Post-Matric Studies'],
    deadline: 'Dec 31, 2025',
    deadlineStatus: 'closing-soon',
    educationLevel: ['12th-passed', 'ug', 'pg', 'diploma', 'professional'],
    category: ['bc-mbc', 'obc'],
    incomeLimit: '2.5',
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Full tuition and exam fee coverage for BC/MBC/DNC students with family income below ₹2.5 Lakhs.',
    applicationUrl: 'https://bcmbcmw.tn.gov.in',
    helpline: '044-25670065',
    documents: ['BC/MBC Certificate', 'Income Certificate (< ₹2.5L)', 'Aadhaar Card', 'Marksheets', 'Bank Details'],
    howToApply: ['Register on TNSSP portal', 'Fill application form', 'Upload documents', 'College verification', 'Fee reimbursement'],
    benefits: [{ label: 'Tuition Fee', value: 'Full Coverage' }, { label: 'Exam Fee', value: 'Covered' }, { label: 'Income Limit', value: '< ₹2.5 Lakhs' }]
  },
  {
    id: 'tn-sc-st-post-matric',
    name: 'SC/ST Post-Matric Scholarship',
    provider: 'Adi Dravidar Welfare Dept, TN (TNSSP)',
    type: 'government',
    amount: 'Full Fee Reimbursement + Hostel Support',
    eligibility: ['SC/ST/SCC Category', 'Family Income < ₹2.5 Lakhs', 'Post-Matric Studies'],
    deadline: 'Dec 31, 2025',
    deadlineStatus: 'closing-soon',
    educationLevel: ['12th-passed', 'ug', 'pg', 'diploma', 'professional'],
    category: ['sc', 'st'],
    incomeLimit: '2.5',
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Complete fee reimbursement and hostel support for SC/ST/SCC students pursuing post-matric education.',
    applicationUrl: 'https://adwelfare.tn.gov.in',
    helpline: '044-25670065',
    documents: ['SC/ST/SCC Certificate', 'Income Certificate (< ₹2.5L)', 'Aadhaar Card', 'Marksheets', 'Hostel Admission (if applicable)', 'Bank Details'],
    howToApply: ['Register on TNSSP portal', 'Submit caste certificate', 'Income verification', 'College attestation', 'Full fee reimbursement'],
    benefits: [{ label: 'Fee Reimbursement', value: 'Full Amount' }, { label: 'Hostel Support', value: 'Additional Allowance' }, { label: 'Income Limit', value: '< ₹2.5 Lakhs' }]
  },

  // First Graduate Scholarship
  {
    id: 'tn-first-graduate',
    name: 'First Graduate (FG) Scholarship',
    provider: 'Tamil Nadu Government (TNSSP)',
    type: 'government',
    amount: 'Significant Tuition Fee Concession',
    eligibility: ['First Generation College Student', 'TN Domicile', 'UG Studies'],
    deadline: 'Jan 15, 2026',
    deadlineStatus: 'one-month',
    educationLevel: ['ug'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Special tuition fee concession for first generation college students - those who are the first in their family to pursue higher education.',
    applicationUrl: 'https://scholarships.gov.in',
    helpline: '1800-121-3513',
    documents: ['Parent Education Declaration', 'Income Certificate', 'College Bonafide', 'Aadhaar Card', 'Bank Passbook'],
    howToApply: ['Apply on TNSSP portal', 'Submit first graduate declaration', 'Parent education affidavit', 'College verification', 'Fee concession applied'],
    benefits: [{ label: 'Fee Concession', value: 'Significant' }, { label: 'Criteria', value: 'First in Family' }, { label: 'For', value: 'UG Students' }]
  },

  // Merit-Based Scholarship
  {
    id: 'tn-7-5-horizontal-reservation',
    name: '7.5% Horizontal Reservation Scheme',
    provider: 'Tamil Nadu Government',
    type: 'government',
    amount: '100% Fees Paid by Government',
    eligibility: ['Govt School Students (6th-12th)', 'Professional Courses (Engg/Medical)', 'JEE/NEET Qualified'],
    deadline: 'Based on Counseling',
    deadlineStatus: 'open',
    educationLevel: ['professional'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Special 7.5% horizontal reservation in professional courses for government school students who studied from 6th to 12th in TN government schools.',
    applicationUrl: 'https://tnea.ac.in',
    helpline: '044-22300500',
    documents: ['School TC (Govt School 6th-12th)', 'JEE/NEET Score Card', '12th Marksheet', 'Aadhaar Card', 'Community Certificate'],
    howToApply: ['Qualify in JEE/NEET', 'Apply under 7.5% quota during counseling', 'Submit govt school proof', 'Seat allotment', 'Full fees covered'],
    benefits: [{ label: 'Fee Coverage', value: '100% by Government' }, { label: 'Quota', value: '7.5% Seats Reserved' }, { label: 'Courses', value: 'Engineering/Medical' }]
  },

  // Tech/Digital Scheme
  {
    id: 'tn-ulagam-ungal-kaiyil',
    name: 'Ulagam Ungal Kaiyil (Free Laptop)',
    provider: 'Tamil Nadu Government',
    type: 'government',
    amount: 'Free Laptop (~₹30,000 Value)',
    eligibility: ['Final Year Students', 'Government Colleges', 'UG Courses'],
    deadline: 'Academic Year Based',
    deadlineStatus: 'open',
    educationLevel: ['ug'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Free laptop distribution scheme for final year students in government and government-aided colleges to enhance digital literacy.',
    applicationUrl: 'https://tn.gov.in',
    helpline: '044-25361520',
    documents: ['College ID Card', 'Final Year Bonafide', 'Aadhaar Card', 'Photo'],
    howToApply: ['Automatic eligibility for final year students', 'College prepares list', 'Government verification', 'Laptop distribution event'],
    benefits: [{ label: 'Benefit', value: 'Free Laptop' }, { label: 'Value', value: '~₹30,000' }, { label: 'For', value: 'Final Year Students' }]
  },

  // Additional TN State Schemes
  {
    id: 'tn-moovalur',
    name: 'Moovalur Ramamirtham Scheme',
    provider: 'Tamil Nadu Government',
    type: 'government',
    amount: '₹1,000/month',
    eligibility: ['Female Students', 'Government School Background', 'UG Studies'],
    deadline: 'Always Open',
    deadlineStatus: 'always-open',
    educationLevel: ['ug'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'female',
    state: 'Tamil Nadu',
    description: 'Monthly financial support for girl students from government schools pursuing higher education.',
    applicationUrl: 'https://scholarships.gov.in',
    helpline: '044-25361520',
    documents: ['School TC', 'College Admission', 'Aadhaar Card', 'Bank Account', 'Photo'],
    howToApply: ['Apply through college', 'Submit govt school TC', 'Bank verification', 'Monthly disbursement'],
    benefits: [{ label: 'Monthly Amount', value: '₹1,000' }, { label: 'Annual Total', value: '₹12,000' }, { label: 'For', value: 'Girl Students' }]
  },
  {
    id: 'tn-minority-welfare',
    name: 'Minority Welfare Scholarship',
    provider: 'Minority Welfare Department, TN',
    type: 'government',
    amount: 'Up to ₹15,000/year',
    eligibility: ['Minority Community', 'Income < ₹2 Lakh', 'TN Domicile'],
    deadline: 'Feb 15, 2026',
    deadlineStatus: 'open',
    educationLevel: ['12th-passed', 'ug', 'pg', 'diploma'],
    category: ['minority'],
    incomeLimit: '2',
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Scholarship for minority community students pursuing higher education.',
    applicationUrl: 'https://scholarships.gov.in',
    helpline: '1800-121-3513',
    documents: ['Minority Certificate', 'Income Certificate', 'Aadhaar Card', 'College Bonafide', 'Bank Details'],
    howToApply: ['Apply on NSP', 'Submit minority proof', 'Income verification', 'College attestation', 'Disbursement'],
    benefits: [{ label: 'Annual Amount', value: 'Up to ₹15,000' }, { label: 'Income Limit', value: '< ₹2 Lakh' }, { label: 'Community', value: 'Minority' }]
  },
  {
    id: 'tn-tribal-welfare',
    name: 'Tribal Welfare Scholarship',
    provider: 'Tribal Welfare Department, TN',
    type: 'government',
    amount: 'Up to ₹40,000/year',
    eligibility: ['ST Category', 'TN Domicile', 'Higher Education'],
    deadline: 'Feb 28, 2026',
    deadlineStatus: 'open',
    educationLevel: ['12th-passed', 'ug', 'pg', 'professional'],
    category: ['st'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Comprehensive scholarship for tribal students pursuing higher education.',
    applicationUrl: 'https://tribalwelfare.tn.gov.in',
    helpline: '044-28544490',
    documents: ['ST Certificate', 'Income Certificate', 'Admission Letter', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Apply through tribal welfare office', 'Submit ST certificate', 'Document verification', 'Scholarship release'],
    benefits: [{ label: 'Annual Amount', value: 'Up to ₹40,000' }, { label: 'Hostel', value: 'Additional Allowance' }, { label: 'Books', value: 'Grant Included' }]
  },
  {
    id: 'tn-differently-abled',
    name: 'Differently Abled Scholarship',
    provider: 'Dept for Welfare of Differently Abled, TN',
    type: 'government',
    amount: 'Up to ₹25,000/year',
    eligibility: ['40%+ Disability', 'TN Domicile', 'Any Course'],
    deadline: 'Mar 15, 2026',
    deadlineStatus: 'open',
    educationLevel: ['12th-passed', 'ug', 'pg', 'diploma', 'professional'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Scholarship for students with disabilities pursuing education.',
    applicationUrl: 'https://welfare.tn.gov.in',
    helpline: '044-25670066',
    documents: ['Disability Certificate', 'Medical Certificate', 'Admission Letter', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Apply on welfare portal', 'Submit disability certificate', 'Medical verification', 'Scholarship disbursement'],
    benefits: [{ label: 'Annual Amount', value: 'Up to ₹25,000' }, { label: 'Special Aids', value: 'Additional Support' }, { label: 'Transport', value: 'Allowance' }]
  },

  // ========================================
  // 2. CENTRAL GOVERNMENT SCHOLARSHIPS (NSP)
  // ========================================
  
  {
    id: 'pm-usp-central-sector',
    name: 'PM-USP (Central Sector Scheme)',
    provider: 'Ministry of Education, Govt of India',
    type: 'government',
    amount: '₹12,000/year (UG) | ₹20,000/year (PG)',
    eligibility: ['Top 20th Percentile in 12th Board', 'Income < ₹8 Lakh', 'UG/PG Students'],
    deadline: 'Dec 31, 2025',
    deadlineStatus: 'closing-soon',
    educationLevel: ['ug', 'pg'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    incomeLimit: '8',
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Central Sector Scholarship for students in the top 20th percentile of their 12th Board examination. Apply through NSP with One Time Registration (OTR).',
    applicationUrl: 'https://scholarships.gov.in',
    helpline: '1800-121-3513',
    documents: ['12th Marksheet', 'Board Percentile Certificate', 'Income Certificate', 'College Admission', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Complete OTR on NSP', 'Fill application form', 'Upload 12th percentile proof', 'College verification', 'Scholarship credited'],
    benefits: [{ label: 'UG Amount', value: '₹12,000/year' }, { label: 'PG Amount', value: '₹20,000/year' }, { label: 'Based on', value: 'Top 20th Percentile' }]
  },
  {
    id: 'inspire-she',
    name: 'INSPIRE (SHE) Scholarship',
    provider: 'DST, Govt of India',
    type: 'government',
    amount: '₹80,000/year',
    eligibility: ['Top 1% in 12th Marks', 'Basic Sciences (B.Sc/M.Sc)', 'Merit Based'],
    deadline: 'Dec 15, 2025',
    deadlineStatus: 'closing-soon',
    educationLevel: ['ug', 'pg'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Innovation in Science Pursuit for Inspired Research (INSPIRE) - Scholarship for Higher Education (SHE). For top 1% students pursuing Basic Sciences.',
    applicationUrl: 'https://online-inspire.gov.in',
    helpline: '011-26590349',
    documents: ['12th Marksheet', 'Top 1% Rank Certificate', 'Science Course Admission', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Verify top 1% eligibility', 'Apply on INSPIRE portal', 'Submit rank proof', 'Verification', 'Scholarship credited'],
    benefits: [{ label: 'Annual Amount', value: '₹80,000' }, { label: 'Summer Project', value: '₹20,000 extra' }, { label: 'For', value: 'B.Sc/M.Sc Students' }]
  },
  {
    id: 'aicte-pragati',
    name: 'AICTE Pragati Scholarship (Girls)',
    provider: 'AICTE, Govt of India',
    type: 'government',
    amount: '₹50,000/year',
    eligibility: ['Female Students', 'Technical Courses (B.E/B.Tech/Diploma)', 'Income < ₹8 Lakh'],
    deadline: 'Dec 31, 2025',
    deadlineStatus: 'closing-soon',
    educationLevel: ['diploma', 'professional'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    incomeLimit: '8',
    gender: 'female',
    state: 'Tamil Nadu',
    description: 'Exclusive scholarship for girl students in Technical courses including B.E., B.Tech, and Diploma programs.',
    applicationUrl: 'https://scholarships.gov.in',
    helpline: '011-29581000',
    documents: ['Income Certificate', 'Admission Letter', '12th Marksheet', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Apply on NSP', 'Select AICTE Pragati', 'Upload documents', 'Institute verification', 'Scholarship release'],
    benefits: [{ label: 'Annual Amount', value: '₹50,000' }, { label: 'For', value: 'Girls in Tech' }, { label: 'Courses', value: 'B.E/B.Tech/Diploma' }]
  },
  {
    id: 'gate-scholarship',
    name: 'GATE Scholarship',
    provider: 'MHRD, Govt of India',
    type: 'government',
    amount: '₹12,400/month',
    eligibility: ['GATE Exam Qualified', 'M.E/M.Tech Students', 'Admitted to IIT/NIT/Govt Colleges'],
    deadline: 'Based on Admission',
    deadlineStatus: 'open',
    educationLevel: ['pg'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Monthly stipend for PG students (M.E/M.Tech) who have qualified the GATE exam and admitted to recognized institutions.',
    applicationUrl: 'https://scholarships.gov.in',
    helpline: '011-26182813',
    documents: ['GATE Score Card', 'M.E/M.Tech Admission Letter', 'UG Degree Certificate', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Clear GATE exam', 'Get admission to M.E/M.Tech', 'Apply through institute', 'Scholarship credited monthly'],
    benefits: [{ label: 'Monthly Stipend', value: '₹12,400' }, { label: 'Duration', value: '2 Years (M.Tech)' }, { label: 'Contingency', value: '₹20,000/year' }]
  },
  {
    id: 'aicte-saksham',
    name: 'AICTE Saksham Scholarship (Disabled)',
    provider: 'AICTE, Govt of India',
    type: 'government',
    amount: '₹50,000/year',
    eligibility: ['40%+ Disability', 'Technical Courses', 'Income < ₹8 Lakh'],
    deadline: 'Dec 31, 2025',
    deadlineStatus: 'closing-soon',
    educationLevel: ['diploma', 'professional'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    incomeLimit: '8',
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Scholarship for differently abled students in technical education.',
    applicationUrl: 'https://scholarships.gov.in',
    helpline: '011-29581000',
    documents: ['Disability Certificate', 'Income Certificate', 'Admission Letter', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Apply on NSP', 'Select AICTE Saksham', 'Upload disability proof', 'Institute verification', 'Scholarship release'],
    benefits: [{ label: 'Annual Amount', value: '₹50,000' }, { label: 'For', value: 'Disabled Students' }, { label: 'Courses', value: 'Technical' }]
  },
  {
    id: 'pm-yasasvi',
    name: 'PM YASASVI Scholarship',
    provider: 'Ministry of Social Justice, Govt of India',
    type: 'government',
    amount: '₹75,000 - ₹1,25,000/year',
    eligibility: ['OBC/EBC/DNT', 'Income < ₹2.5 Lakh', 'Class 9-12'],
    deadline: 'Sep 30, 2025',
    deadlineStatus: 'open',
    educationLevel: ['12th-studying'],
    category: ['obc', 'bc-mbc', 'ews'],
    incomeLimit: '2.5',
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'PM Young Achievers Scholarship for OBC/EBC/DNT students.',
    applicationUrl: 'https://yet.nta.ac.in',
    helpline: '011-40759000',
    documents: ['Caste Certificate', 'Income Certificate', 'School Bonafide', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Clear YASASVI entrance test', 'Apply on NTA portal', 'Document verification', 'Scholarship awarded'],
    benefits: [{ label: 'Class 9 Amount', value: '₹75,000/year' }, { label: 'Class 11 Amount', value: '₹1,25,000/year' }]
  },
  {
    id: 'nmms',
    name: 'National Merit Scholarship (NMMS)',
    provider: 'Ministry of Education, Govt of India',
    type: 'government',
    amount: '₹12,000/year',
    eligibility: ['Class 9-12 Students', 'Merit Based', 'Income < ₹3.5 Lakh'],
    deadline: 'Nov 30, 2025',
    deadlineStatus: 'closing-soon',
    educationLevel: ['12th-studying'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    incomeLimit: '3.5',
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'National merit scholarship for meritorious students from economically weaker sections.',
    applicationUrl: 'https://scholarships.gov.in',
    helpline: '1800-121-3513',
    documents: ['Income Certificate', 'Marksheets', 'Aadhaar Card', 'School Bonafide', 'Bank Details'],
    howToApply: ['Clear NMMS selection test', 'Apply through NSP', 'Submit documents', 'State verification', 'Scholarship awarded'],
    benefits: [{ label: 'Annual Amount', value: '₹12,000' }, { label: 'Duration', value: 'Class 9-12' }, { label: 'Selection', value: 'Merit Test' }]
  },
  {
    id: 'nsigse',
    name: 'National Scheme of Incentives for Girls (NSIGSE)',
    provider: 'Ministry of Education, Govt of India',
    type: 'government',
    amount: '₹3,000 (One-time)',
    eligibility: ['SC/ST Girls', 'Class 10 Pass', 'Enrollment in Class 11'],
    deadline: 'Rolling',
    deadlineStatus: 'open',
    educationLevel: ['12th-studying'],
    category: ['sc', 'st'],
    gender: 'female',
    state: 'Tamil Nadu',
    description: 'Incentive for SC/ST girl students to continue education after 10th.',
    applicationUrl: 'https://scholarships.gov.in',
    helpline: '1800-121-3513',
    documents: ['10th Marksheet', 'Class 11 Admission', 'SC/ST Certificate', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Apply on NSP after Class 10', 'Submit caste certificate', 'Enrollment proof in 11th', 'One-time amount credited'],
    benefits: [{ label: 'One-time Amount', value: '₹3,000' }, { label: 'For', value: 'SC/ST Girls' }, { label: 'Purpose', value: 'Continue Higher Secondary' }]
  },

  // ========================================
  // 3. CORPORATE & CSR SCHOLARSHIPS
  // ========================================
  
  {
    id: 'reliance-foundation-ug',
    name: 'Reliance Foundation Scholarship (UG)',
    provider: 'Reliance Foundation (Vidyasaarathi)',
    type: 'corporate',
    amount: 'Up to ₹2 Lakhs',
    eligibility: ['UG Students', 'Online Aptitude Test', 'Merit + Need Based'],
    deadline: 'Mar 31, 2026',
    deadlineStatus: 'open',
    educationLevel: ['ug'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Undergraduate scholarship based on online aptitude test performance. Apply through Vidyasaarathi portal.',
    applicationUrl: 'https://www.vidyasaarathi.co.in',
    helpline: '1800-419-8800',
    documents: ['12th Marksheet', 'College Admission Letter', 'Income Certificate', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Register on Vidyasaarathi', 'Apply for Reliance Foundation', 'Clear online aptitude test', 'Document verification', 'Scholarship awarded'],
    benefits: [{ label: 'Maximum Amount', value: 'Up to ₹2 Lakhs' }, { label: 'Selection', value: 'Aptitude Test' }, { label: 'Level', value: 'UG Students' }]
  },
  {
    id: 'reliance-foundation-pg',
    name: 'Reliance Foundation Scholarship (PG)',
    provider: 'Reliance Foundation (Vidyasaarathi)',
    type: 'corporate',
    amount: 'Up to ₹6 Lakhs',
    eligibility: ['PG Students', 'AI/Computer Science/Life Sciences', 'Merit Based'],
    deadline: 'Mar 31, 2026',
    deadlineStatus: 'open',
    educationLevel: ['pg'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Postgraduate scholarship with focus on AI, Computer Science, and Life Sciences. Higher scholarship amount for specialized courses.',
    applicationUrl: 'https://www.vidyasaarathi.co.in',
    helpline: '1800-419-8800',
    documents: ['UG Degree Certificate', 'PG Admission Letter', 'Academic Transcripts', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Register on Vidyasaarathi', 'Apply for PG scholarship', 'Submit specialization proof', 'Selection process', 'Scholarship disbursement'],
    benefits: [{ label: 'Maximum Amount', value: 'Up to ₹6 Lakhs' }, { label: 'Focus Areas', value: 'AI, CS, Life Sciences' }, { label: 'Level', value: 'PG Students' }]
  },
  {
    id: 'hdfc-parivartan-ecss',
    name: 'HDFC Bank Parivartan ECSS',
    provider: 'HDFC Bank (Vidyasaarathi)',
    type: 'corporate',
    amount: 'Up to ₹75,000',
    eligibility: ['12th to PG Students', 'Merit-cum-Means', 'Income < ₹2.5 Lakh'],
    deadline: 'Feb 28, 2026',
    deadlineStatus: 'open',
    educationLevel: ['12th-studying', '12th-passed', 'ug', 'pg'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    incomeLimit: '2.5',
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Educational Crisis Scholarship Support for students from 12th to PG level based on merit and financial need.',
    applicationUrl: 'https://www.vidyasaarathi.co.in',
    helpline: '1800-419-8800',
    documents: ['Income Certificate', 'Academic Records', 'Admission Letter', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Register on Vidyasaarathi', 'Select HDFC Parivartan', 'Submit merit + income proof', 'Verification', 'Scholarship credited'],
    benefits: [{ label: 'Maximum Amount', value: '₹75,000' }, { label: 'Type', value: 'Merit-cum-Means' }, { label: 'Range', value: '12th to PG' }]
  },
  {
    id: 'infosys-stem-stars',
    name: 'Infosys Foundation STEM Stars',
    provider: 'Infosys Foundation',
    type: 'corporate',
    amount: 'Up to ₹1,00,000',
    eligibility: ['Girl Students Only', 'STEM Fields (Science, Tech, Eng, Math)', 'UG Students'],
    deadline: 'Mar 15, 2026',
    deadlineStatus: 'open',
    educationLevel: ['ug'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'female',
    state: 'Tamil Nadu',
    description: 'Specifically for girl students entering STEM fields - Science, Technology, Engineering, and Mathematics.',
    applicationUrl: 'https://www.infosys.com/infosys-foundation',
    helpline: '080-41581111',
    documents: ['12th Marksheet (Science)', 'STEM Course Admission', 'Income Certificate', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Apply on Infosys Foundation portal', 'Submit STEM course proof', 'Academic verification', 'Selection', 'Scholarship awarded'],
    benefits: [{ label: 'Maximum Amount', value: '₹1,00,000' }, { label: 'For', value: 'Girls in STEM' }, { label: 'Fields', value: 'Science/Tech/Eng/Math' }]
  },
  {
    id: 'kotak-kanya-scholarship',
    name: 'Kotak Kanya Scholarship',
    provider: 'Kotak Education Foundation',
    type: 'corporate',
    amount: 'Up to ₹1,50,000',
    eligibility: ['Meritorious Girl Students', 'After 12th', 'Low-Income Families'],
    deadline: 'Mar 31, 2026',
    deadlineStatus: 'open',
    educationLevel: ['12th-passed', 'ug'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'female',
    state: 'Tamil Nadu',
    description: 'Financial aid for meritorious girl students from low-income families after 12th standard.',
    applicationUrl: 'https://www.kotakeducation.org',
    helpline: '022-66056666',
    documents: ['12th Marksheet', 'Income Certificate', 'College Admission', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Apply on Kotak Education portal', 'Submit merit + income proof', 'Selection process', 'Scholarship disbursement'],
    benefits: [{ label: 'Maximum Amount', value: '₹1,50,000' }, { label: 'For', value: 'Girls after 12th' }, { label: 'Criteria', value: 'Merit + Need' }]
  },
  {
    id: 'tata-trusts-scholarship',
    name: 'Tata Trusts Scholarship',
    provider: 'Tata Trusts',
    type: 'corporate',
    amount: 'Up to ₹50,000',
    eligibility: ['Medical/Engineering Students', 'Need Based', 'Merit Performers'],
    deadline: 'Feb 28, 2026',
    deadlineStatus: 'open',
    educationLevel: ['professional'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Scholarship for meritorious students in Medical and Engineering courses.',
    applicationUrl: 'https://tatatrusts.org',
    helpline: '022-66658282',
    documents: ['Entrance Exam Score', 'Course Admission', 'Income Certificate', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Apply on Tata Trusts portal', 'Submit documents', 'Selection', 'Scholarship awarded'],
    benefits: [{ label: 'Amount', value: 'Up to ₹50,000' }, { label: 'For', value: 'Medical/Engineering' }]
  },
  {
    id: 'larsen-toubro-scholarship',
    name: 'L&T Build India Scholarship',
    provider: 'Larsen & Toubro',
    type: 'corporate',
    amount: 'Up to ₹50,000',
    eligibility: ['Engineering Students', 'Income < ₹6 Lakh', 'Merit Based'],
    deadline: 'Mar 31, 2026',
    deadlineStatus: 'open',
    educationLevel: ['professional'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    incomeLimit: '6',
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Scholarship for engineering students from economically weaker sections.',
    applicationUrl: 'https://www.lntecc.com',
    helpline: '022-67525656',
    documents: ['JEE Score Card', 'Engineering Admission', 'Income Certificate', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Apply through L&T portal', 'Submit documents', 'Selection', 'Scholarship awarded'],
    benefits: [{ label: 'Amount', value: 'Up to ₹50,000' }, { label: 'For', value: 'Engineering' }]
  },
  {
    id: 'wipro-scholarship',
    name: 'Wipro Education Scholarship',
    provider: 'Wipro Foundation',
    type: 'corporate',
    amount: 'Up to ₹75,000',
    eligibility: ['Tech/Science Students', 'UG Courses', 'Merit Based'],
    deadline: 'Mar 15, 2026',
    deadlineStatus: 'open',
    educationLevel: ['ug'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Scholarship for students pursuing technology and science courses.',
    applicationUrl: 'https://www.wipro.com/corporate-responsibility',
    helpline: '080-28440011',
    documents: ['12th Marksheet', 'Course Admission', 'Income Certificate', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Apply on Wipro portal', 'Submit documents', 'Selection', 'Scholarship awarded'],
    benefits: [{ label: 'Amount', value: 'Up to ₹75,000' }, { label: 'For', value: 'Tech/Science' }]
  },
  {
    id: 'icici-vidyasaarathi',
    name: 'ICICI Foundation Scholarship',
    provider: 'ICICI Foundation',
    type: 'corporate',
    amount: 'Up to ₹50,000',
    eligibility: ['UG/Professional Students', 'Income < ₹3 Lakh', 'Merit Based'],
    deadline: 'Feb 28, 2026',
    deadlineStatus: 'open',
    educationLevel: ['ug', 'professional'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    incomeLimit: '3',
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Scholarship for undergraduate and professional course students.',
    applicationUrl: 'https://www.vidyasaarathi.co.in',
    helpline: '1800-419-8800',
    documents: ['Academic Records', 'Course Admission', 'Income Certificate', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Apply on Vidyasaarathi', 'Submit documents', 'Selection', 'Scholarship awarded'],
    benefits: [{ label: 'Amount', value: 'Up to ₹50,000' }]
  },

  // ========================================
  // 4. NGO & FOUNDATION SCHOLARSHIPS
  // ========================================
  
  {
    id: 'agaram-vidhai',
    name: 'Agaram Foundation (Vidhai)',
    provider: 'Agaram Foundation',
    type: 'ngo',
    amount: 'Full Education + Hostel Fees',
    eligibility: ['First-Generation Rural Students', 'Economically Weak', 'Higher Education'],
    deadline: 'Rolling (Home Visits)',
    deadlineStatus: 'open',
    educationLevel: ['12th-passed', 'ug', 'professional'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Supports first-generation rural students with full education and hostel fees. Involves personal interviews and home visits to verify need.',
    applicationUrl: 'https://www.agaramfoundation.org',
    helpline: '044-42047474',
    documents: ['Parent Education Declaration', 'Income Certificate', 'Rural Residence Proof', 'Academic Records', 'Aadhaar Card'],
    howToApply: ['Apply on Agaram website', 'Submit background documents', 'Personal interview', 'Home visit verification', 'Full support begins'],
    benefits: [{ label: 'Fee Coverage', value: 'Full Education' }, { label: 'Hostel', value: 'Full Coverage' }, { label: 'For', value: 'First-Gen Rural Students' }]
  },
  {
    id: 'maatram-foundation',
    name: 'Maatram Foundation Scholarship',
    provider: 'Maatram Foundation',
    type: 'ngo',
    amount: 'Tuition + Hostel + Transport',
    eligibility: ['Underprivileged Students', 'Partner College Admission', 'Need Based'],
    deadline: 'Rolling',
    deadlineStatus: 'open',
    educationLevel: ['12th-passed', 'ug', 'professional'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Provides free higher education including Tuition, Hostel, and Transport by partnering with colleges like Sathyabama, SRM, and others.',
    applicationUrl: 'https://www.maatram.org',
    helpline: '044-24621555',
    documents: ['Income Certificate', 'Academic Records', 'College Admission', 'Aadhaar Card', 'Family Background Details'],
    howToApply: ['Apply through Maatram website', 'Document submission', 'Interview process', 'Partner college admission', 'Full support provided'],
    benefits: [{ label: 'Tuition', value: 'Full Coverage' }, { label: 'Hostel', value: 'Covered' }, { label: 'Transport', value: 'Included' }]
  },
  {
    id: 'vidyadhan-sdf',
    name: 'Vidyadhan (Sarojini Damodaran Foundation)',
    provider: 'Sarojini Damodaran Foundation',
    type: 'ngo',
    amount: '₹10,000 - ₹75,000/year',
    eligibility: ['After 10th/12th Students', 'Economically Weak', 'Merit Based'],
    deadline: 'Post 10th/12th Results',
    deadlineStatus: 'open',
    educationLevel: ['12th-studying', '12th-passed', 'ug', 'pg'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Selects students after 10th/12th. Provides ₹10k to ₹75k per year depending on the course pursued.',
    applicationUrl: 'https://www.vidyadhan.org',
    helpline: '080-40952020',
    documents: ['10th/12th Marksheet', 'Income Certificate', 'Course Admission', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Apply after 10th/12th results', 'Submit documents', 'Selection test', 'Interview', 'Scholarship begins'],
    benefits: [{ label: 'Range', value: '₹10,000 - ₹75,000' }, { label: 'Based on', value: 'Course Type' }, { label: 'Selection', value: 'Post 10th/12th' }]
  },
  {
    id: 'ffe-scholarship',
    name: 'Foundation For Excellence (FFE)',
    provider: 'Foundation For Excellence',
    type: 'ngo',
    amount: 'Up to ₹1,50,000/year',
    eligibility: ['Engineering/Medical/B.Pharm Students', 'High Entrance Rank (JEE/NEET)', 'Low Income Family'],
    deadline: 'Post Counseling',
    deadlineStatus: 'open',
    educationLevel: ['professional'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Supports students in Engineering, Medical, and B.Pharm. Requires high entrance rank (JEE/NEET) and financial need.',
    applicationUrl: 'https://www.ffe.org',
    helpline: '080-67315555',
    documents: ['JEE/NEET Score Card', 'Counseling Allotment', 'Income Certificate', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Apply after counseling allotment', 'Submit entrance rank proof', 'Income verification', 'Selection', 'Multi-year support'],
    benefits: [{ label: 'Maximum Amount', value: '₹1,50,000/year' }, { label: 'Courses', value: 'Engg/Medical/B.Pharm' }, { label: 'Criteria', value: 'Rank + Need' }]
  },
  {
    id: 'hope-foundation-scholarship',
    name: 'HOPE Foundation Scholarship',
    provider: 'HOPE Foundation',
    type: 'ngo',
    amount: 'Up to ₹50,000',
    eligibility: ['Orphan/Semi-Orphan Students', 'Higher Education', 'TN Domicile'],
    deadline: 'Rolling',
    deadlineStatus: 'open',
    educationLevel: ['12th-passed', 'ug', 'pg'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Special scholarship for orphan and semi-orphan students pursuing higher education.',
    applicationUrl: 'https://www.hopefoundation.org.in',
    helpline: '044-24350707',
    documents: ['Parent Death Certificate (if applicable)', 'Guardian Details', 'Income Proof', 'Academic Records', 'Aadhaar Card'],
    howToApply: ['Apply on HOPE Foundation website', 'Submit documents', 'Verification', 'Scholarship awarded'],
    benefits: [{ label: 'Amount', value: 'Up to ₹50,000' }, { label: 'For', value: 'Orphan/Semi-Orphan' }]
  },
  {
    id: 'giveindia-education',
    name: 'GiveIndia Education Scholarship',
    provider: 'GiveIndia Foundation',
    type: 'ngo',
    amount: 'Up to ₹40,000',
    eligibility: ['Economically Weak', 'UG Studies', 'Need Based'],
    deadline: 'Rolling',
    deadlineStatus: 'open',
    educationLevel: ['ug'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Scholarship for economically weak students through GiveIndia platform.',
    applicationUrl: 'https://www.giveindia.org',
    helpline: '080-67456000',
    documents: ['Income Certificate', 'Course Admission', 'Academic Records', 'Aadhaar Card'],
    howToApply: ['Apply through GiveIndia NGO partner', 'Submit documents', 'Selection', 'Scholarship awarded'],
    benefits: [{ label: 'Amount', value: 'Up to ₹40,000' }]
  },
  {
    id: 'fair-and-lovely-foundation',
    name: 'Fair & Lovely Foundation Scholarship',
    provider: 'Fair & Lovely Foundation',
    type: 'ngo',
    amount: 'Up to ₹50,000',
    eligibility: ['Female Students', 'Class 12 to PG', 'Economic Need'],
    deadline: 'Feb 28, 2026',
    deadlineStatus: 'open',
    educationLevel: ['12th-studying', '12th-passed', 'ug', 'pg'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'female',
    state: 'Tamil Nadu',
    description: 'Scholarship exclusively for female students from economically weaker backgrounds.',
    applicationUrl: 'https://www.fairandlovelyfoundation.org',
    helpline: '022-39832000',
    documents: ['Income Certificate', 'Academic Records', 'Course Admission', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Apply on foundation website', 'Submit documents', 'Selection', 'Scholarship awarded'],
    benefits: [{ label: 'Amount', value: 'Up to ₹50,000' }, { label: 'For', value: 'Female Students' }]
  },
  {
    id: 'isha-vidya-scholarship',
    name: 'Isha Vidhya Scholarship',
    provider: 'Isha Foundation',
    type: 'ngo',
    amount: 'Full Education Support',
    eligibility: ['Rural Students', 'School Education', 'TN Villages'],
    deadline: 'Rolling',
    deadlineStatus: 'open',
    educationLevel: ['12th-studying'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Free quality education for rural children in Tamil Nadu villages.',
    applicationUrl: 'https://www.ishavidhya.org',
    helpline: '0422-2515345',
    documents: ['Rural Residence Proof', 'Family Income Details', 'Academic Records', 'Aadhaar Card'],
    howToApply: ['Apply through Isha Vidhya schools', 'Home verification', 'Admission test', 'Free education begins'],
    benefits: [{ label: 'Coverage', value: 'Full Education' }, { label: 'For', value: 'Rural Students' }]
  },
  {
    id: 'akshaya-patra-scholarship',
    name: 'Akshaya Patra Scholarship',
    provider: 'Akshaya Patra Foundation',
    type: 'ngo',
    amount: 'Up to ₹25,000',
    eligibility: ['Government School Students', 'Higher Education', 'Beneficiary Children'],
    deadline: 'Mar 31, 2026',
    deadlineStatus: 'open',
    educationLevel: ['12th-passed', 'ug'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Scholarship for students who were beneficiaries of Akshaya Patra mid-day meal program.',
    applicationUrl: 'https://www.akshayapatra.org',
    helpline: '1800-425-8622',
    documents: ['Beneficiary Proof', 'School Records', 'College Admission', 'Aadhaar Card'],
    howToApply: ['Apply through Akshaya Patra center', 'Verify beneficiary status', 'Selection', 'Scholarship awarded'],
    benefits: [{ label: 'Amount', value: 'Up to ₹25,000' }]
  },
  {
    id: 'nanhi-kali-scholarship',
    name: 'Nanhi Kali Scholarship',
    provider: 'K.C. Mahindra Education Trust',
    type: 'ngo',
    amount: 'Up to ₹30,000',
    eligibility: ['Girl Students', 'School Education', 'Underprivileged'],
    deadline: 'Rolling',
    deadlineStatus: 'open',
    educationLevel: ['12th-studying'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'female',
    state: 'Tamil Nadu',
    description: 'Education support for underprivileged girl children.',
    applicationUrl: 'https://www.nanhikali.org',
    helpline: '022-24901100',
    documents: ['Income Certificate', 'School Admission', 'Academic Records', 'Aadhaar Card'],
    howToApply: ['Apply through Nanhi Kali partner', 'Verification', 'Selection', 'Support begins'],
    benefits: [{ label: 'Amount', value: 'Up to ₹30,000' }, { label: 'Materials', value: 'Books + Uniform' }]
  },

  // ========================================
  // 5. SPORTS SCHOLARSHIPS
  // ========================================

  {
    id: 'sai-sports-scholarship',
    name: 'SAI Sports Scholarship',
    provider: 'Sports Authority of India (SAI)',
    type: 'sports',
    amount: '₹10,000 - ₹50,000/year',
    eligibility: ['National/State Level Athletes', 'Age 14-25', 'Training at SAI Centers'],
    deadline: 'Throughout Year',
    deadlineStatus: 'open',
    educationLevel: ['12th-studying', '12th-passed', 'ug', 'pg'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Financial support for talented sportspersons training at SAI centers. Covers training, equipment, and competition expenses.',
    applicationUrl: 'https://sportsauthorityofindia.nic.in',
    helpline: '011-26165655',
    documents: ['Sports Achievement Certificates', 'State/National Participation Proof', 'Age Proof', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Apply through SAI center', 'Submit sports achievements', 'Selection trials', 'Scholarship granted'],
    benefits: [{ label: 'Annual Amount', value: '₹10,000-₹50,000' }, { label: 'Training', value: 'SAI Centers' }, { label: 'Equipment', value: 'Support Included' }]
  },
  {
    id: 'khelo-india-scholarship',
    name: 'Khelo India Scholarship',
    provider: 'Ministry of Youth Affairs & Sports',
    type: 'sports',
    amount: '₹6.28 Lakh/year (For 8 years)',
    eligibility: ['Selected Khelo India Athletes', 'Age Below 21', 'Medal Winners'],
    deadline: 'Post Khelo India Games',
    deadlineStatus: 'open',
    educationLevel: ['12th-studying', '12th-passed', 'ug'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Comprehensive scholarship for top performers at Khelo India Games. Includes training, coaching, diet, and education support for 8 years.',
    applicationUrl: 'https://kheloindia.gov.in',
    helpline: '011-24360808',
    documents: ['Khelo India Medal Certificate', 'Age Proof', 'Education Certificate', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Perform at Khelo India Games', 'Selection by Sports Ministry', 'Documentation', '8-year support begins'],
    benefits: [{ label: 'Annual Support', value: '₹6.28 Lakh' }, { label: 'Duration', value: '8 Years' }, { label: 'Includes', value: 'Training + Education' }]
  },
  {
    id: 'tn-sports-quota-scholarship',
    name: 'TN Sports Quota Scholarship',
    provider: 'Tamil Nadu Sports Development Authority',
    type: 'sports',
    amount: 'Full Tuition Fee Waiver + ₹5,000/month',
    eligibility: ['State/National Level Players', 'TN Domicile', 'UG/PG Admission'],
    deadline: 'Based on Admission',
    deadlineStatus: 'open',
    educationLevel: ['ug', 'pg'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Special scholarship for TN athletes admitted under sports quota in colleges. Includes fee waiver and monthly stipend.',
    applicationUrl: 'https://sdat.tn.gov.in',
    helpline: '044-25672222',
    documents: ['Sports Achievement Certificates', 'State Selection Proof', 'College Sports Quota Admission', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Get sports quota admission', 'Apply through college', 'Submit sports certificates', 'Scholarship approved'],
    benefits: [{ label: 'Tuition Fee', value: 'Full Waiver' }, { label: 'Monthly Stipend', value: '₹5,000' }, { label: 'For', value: 'Sports Quota Students' }]
  },
  {
    id: 'olympic-gold-quest',
    name: 'Olympic Gold Quest (OGQ) Scholarship',
    provider: 'OGQ Foundation',
    type: 'sports',
    amount: 'Up to ₹25 Lakh/year',
    eligibility: ['Elite Athletes', 'Olympic/International Potential', 'Selection by OGQ'],
    deadline: 'By Invitation',
    deadlineStatus: 'open',
    educationLevel: ['12th-studying', '12th-passed', 'ug', 'pg'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Premium support for elite athletes with Olympic potential. Covers world-class training, international exposure, coaching, and equipment.',
    applicationUrl: 'https://www.olympicgoldquest.in',
    helpline: '022-26605856',
    documents: ['Sports Achievement Record', 'International Rankings', 'Recommendation Letters', 'Aadhaar Card'],
    howToApply: ['Nomination by sports federation', 'OGQ selection committee', 'Athlete assessment', 'Long-term support program'],
    benefits: [{ label: 'Annual Support', value: 'Up to ₹25 Lakh' }, { label: 'International', value: 'Training & Exposure' }, { label: 'Equipment', value: 'World-class' }]
  },
  {
    id: 'tata-trusts-sports',
    name: 'Tata Trusts Sports Scholarship',
    provider: 'Tata Trusts',
    type: 'sports',
    amount: 'Up to ₹5 Lakh/year',
    eligibility: ['Promising Athletes', 'Age 12-25', 'Merit-cum-Means'],
    deadline: 'Rolling Applications',
    deadlineStatus: 'open',
    educationLevel: ['12th-studying', '12th-passed', 'ug'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Support for promising athletes from economically weaker sections. Covers training, equipment, competition, and education expenses.',
    applicationUrl: 'https://www.tatatrusts.org',
    helpline: '022-66657070',
    documents: ['Sports Achievements', 'Income Certificate', 'School/College Proof', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Apply through partner organizations', 'Submit achievements', 'Selection process', 'Scholarship awarded'],
    benefits: [{ label: 'Annual Amount', value: 'Up to ₹5 Lakh' }, { label: 'Training', value: 'Full Support' }, { label: 'Equipment', value: 'Covered' }]
  },
  {
    id: 'jsw-sports-excellence',
    name: 'JSW Sports Excellence Program',
    provider: 'JSW Foundation',
    type: 'sports',
    amount: 'Up to ₹10 Lakh/year',
    eligibility: ['National Level Athletes', 'Multiple Sports Disciplines', 'Age 15-25'],
    deadline: 'Rolling',
    deadlineStatus: 'open',
    educationLevel: ['12th-studying', '12th-passed', 'ug', 'pg'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Comprehensive support program for national-level athletes in various sports including athletics, wrestling, boxing, and more.',
    applicationUrl: 'https://www.jsw.in/foundation',
    helpline: '022-43467000',
    documents: ['National Level Certificates', 'Sports Federation Recommendation', 'Education Proof', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Apply through JSW Sports', 'Trials and assessment', 'Selection', 'Training program begins'],
    benefits: [{ label: 'Annual Support', value: 'Up to ₹10 Lakh' }, { label: 'Training', value: 'World-class' }, { label: 'Exposure', value: 'International' }]
  },
  {
    id: 'university-sports-scholarship',
    name: 'University Sports Scholarship (AIU)',
    provider: 'Association of Indian Universities',
    type: 'sports',
    amount: '₹15,000 - ₹50,000/year',
    eligibility: ['University Level Players', 'Inter-University Participants', 'UG/PG Students'],
    deadline: 'Based on University Calendar',
    deadlineStatus: 'open',
    educationLevel: ['ug', 'pg'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Scholarship for students participating in inter-university sports competitions. Supports education while pursuing sports excellence.',
    applicationUrl: 'https://www.aiu.ac.in',
    helpline: '011-23232429',
    documents: ['Inter-University Participation Proof', 'University ID', 'Sports Achievements', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Participate in university sports', 'Apply through university', 'Submit achievements', 'Scholarship released'],
    benefits: [{ label: 'Amount', value: '₹15,000-₹50,000' }, { label: 'For', value: 'University Athletes' }, { label: 'Coverage', value: 'Fees + Allowance' }]
  },
  {
    id: 'tn-cm-sports-award',
    name: 'TN CM Sports Award & Scholarship',
    provider: 'Tamil Nadu Government',
    type: 'sports',
    amount: '₹3 Lakh - ₹5 Crore (Based on Medal)',
    eligibility: ['TN Athletes', 'National/International Medal Winners', 'Olympic/Asian/Commonwealth Games'],
    deadline: 'Post Competition',
    deadlineStatus: 'open',
    educationLevel: ['12th-studying', '12th-passed', 'ug', 'pg', 'professional'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Cash awards and scholarships for TN athletes winning medals at major international and national competitions.',
    applicationUrl: 'https://sdat.tn.gov.in',
    helpline: '044-25672222',
    documents: ['Medal Certificate', 'Sports Federation Proof', 'TN Domicile', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Win medal at recognized competition', 'Apply through SDAT', 'Verification', 'Award disbursement'],
    benefits: [{ label: 'Olympic Gold', value: '₹5 Crore' }, { label: 'Asian Games Gold', value: '₹2 Crore' }, { label: 'National Games', value: '₹3-10 Lakh' }]
  }
];

export const getScholarshipsByType = (type: string) => {
  return scholarships.filter(s => s.type === type);
};

// Removed getJKKNScholarships - no longer used

export const getGovernmentScholarships = () => {
  return scholarships.filter(s => s.type === 'government');
};

export const getCorporateScholarships = () => {
  return scholarships.filter(s => s.type === 'corporate');
};

export const getNGOScholarships = () => {
  return scholarships.filter(s => s.type === 'ngo');
};

export const getSportsScholarships = () => {
  return scholarships.filter(s => s.type === 'sports');
};
