export interface TNEASportsCollege { code: string; name: string; type: 'Govt' | 'Govt-Aided' | 'Private' | 'Central Govt' | 'Govt Deemed'; }
export interface DistrictColleges { district: string; districtTamil: string; colleges: TNEASportsCollege[]; }

export const tneaSportsQuotaColleges: DistrictColleges[] = [
  { district: 'Ariyalur', districtTamil: 'அரியலூர்', colleges: [
    { code: '3016', name: 'University College of Engineering, Ariyalur', type: 'Govt' },
    { code: '3466', name: 'Nelliandavar Institute of Technology', type: 'Private' },
    { code: '3462', name: 'Ariyalur Engineering College', type: 'Private' },
  ]},
  { district: 'Chennai', districtTamil: 'சென்னை', colleges: [
    { code: '0001', name: 'Anna University – CEG Campus', type: 'Govt' },
    { code: '0002', name: 'Anna University – ACT Campus', type: 'Govt' },
    { code: '1101', name: 'Aalim Muhammed Salegh College of Engineering', type: 'Private' },
    { code: '1106', name: 'Jaya Engineering College', type: 'Private' },
    { code: '1114', name: 'S A Engineering College', type: 'Private' },
    { code: '1118', name: 'Vel Tech Multi Tech Engineering College', type: 'Private' },
    { code: '1120', name: 'Velammal Engineering College', type: 'Private' },
    { code: '1122', name: 'Vel Tech High Tech Engineering College', type: 'Private' },
    { code: '1123', name: 'Gojan School of Business and Technology', type: 'Private' },
    { code: '1125', name: 'P M R Engineering College', type: 'Private' },
    { code: '1127', name: 'St. Peters College of Engineering and Technology', type: 'Private' },
    { code: '1131', name: 'Vel Tech', type: 'Private' },
    { code: '1133', name: 'Annai Veilankannis College of Engineering', type: 'Private' },
    { code: '1149', name: 'St. Josephs Institute of Technology', type: 'Private' },
    { code: '1202', name: 'D M I College of Engineering', type: 'Private' },
    { code: '1210', name: 'Panimalar Engineering College', type: 'Private' },
    { code: '1213', name: 'S K R Engineering College', type: 'Private' },
    { code: '1217', name: 'Sree Sastha Institute of Engineering and Technology', type: 'Private' },
    { code: '1218', name: 'Sri Muthukumaran Institute of Technology', type: 'Private' },
    { code: '1221', name: 'Jaya College of Engineering and Technology', type: 'Private' },
    { code: '1225', name: 'Loyola Institute of Technology', type: 'Private' },
    { code: '1228', name: 'Alpha College of Engineering', type: 'Private' },
    { code: '1231', name: 'Panimalar Institute of Technology', type: 'Private' },
    { code: '1243', name: 'Madha Institute of Engineering and Technology', type: 'Private' },
    { code: '1304', name: 'Easwari Engineering College', type: 'Private' },
    { code: '1306', name: 'Jeppiar Engineering College', type: 'Private' },
    { code: '1309', name: 'Meenakshi Sundararajan Engineering College', type: 'Private' },
    { code: '1310', name: 'MNM Jain Engineering College', type: 'Private' },
    { code: '1311', name: 'K C G College of Technology', type: 'Private' },
    { code: '1313', name: 'SMK Fomra Institute of Technology', type: 'Private' },
    { code: '1317', name: 'St. Josephs College of Engineering', type: 'Private' },
    { code: '1319', name: 'Thangavelu Engineering College', type: 'Private' },
    { code: '1321', name: 'CIPET, Guindy', type: 'Central Govt' },
    { code: '1322', name: 'Dhanalakshmi Srinivasan College of Engg. & Tech.', type: 'Private' },
    { code: '1324', name: 'Sri Sai Ram Institute of Technology', type: 'Private' },
    { code: '1399', name: 'Chennai Institute of Technology', type: 'Private' },
    { code: '1405', name: 'Dhanalakshmi College of Engineering', type: 'Private' },
    { code: '1407', name: 'G K M College of Engineering and Technology', type: 'Private' },
    { code: '1411', name: 'Madha Engineering College', type: 'Private' },
    { code: '1414', name: 'Prince Shri Venkateshwara Padmavathy Engg. College', type: 'Private' },
    { code: '1416', name: 'Jaya Sakthi Engineering College', type: 'Private' },
    { code: '1419', name: 'Sri Sairam Engineering College', type: 'Private' },
    { code: '1420', name: 'Tagore Engineering College', type: 'Private' },
    { code: '1422', name: 'SRM Valliammai Engineering College', type: 'Private' },
    { code: '1424', name: 'Dhaanish Ahmed College of Engineering', type: 'Private' },
    { code: '1426', name: 'Sri Ramanujar Engineering College', type: 'Private' },
    { code: '1427', name: 'Sri Krishna Engineering College', type: 'Private' },
    { code: '1431', name: 'New Prince Shri Bhavani College of Engg. & Tech.', type: 'Private' },
    { code: '1437', name: 'Rrase College of Engineering', type: 'Private' },
    { code: '1442', name: 'Prince Dr. K Vasudevan College of Engg. & Tech.', type: 'Private' },
    { code: '1447', name: 'Jawahar Engineering College', type: 'Private' },
    { code: '1450', name: 'Loyola-ICAM College of Engineering and Technology', type: 'Private' },
    { code: '1452', name: 'PERI Institute of Technology', type: 'Private' },
    { code: '1509', name: 'Meenakshi College of Engineering', type: 'Private' },
  ]},
  { district: 'Coimbatore', districtTamil: 'கோயம்புத்தூர்', colleges: [
    { code: '2005', name: 'Government College of Technology', type: 'Govt' },
    { code: '2006', name: 'PSG College of Technology', type: 'Govt-Aided' },
    { code: '2007', name: 'Coimbatore Institute of Technology (CIT)', type: 'Govt-Aided' },
    { code: '2025', name: 'Anna University Regional Campus – Coimbatore', type: 'Govt' },
    { code: '2329', name: 'Rathinam Technical Campus', type: 'Private' },
    { code: '2338', name: 'Asian College of Engineering and Technology', type: 'Private' },
    { code: '2342', name: 'Sri Ranganathar Institute of Engg. and Technology', type: 'Private' },
    { code: '2349', name: 'Dhaanish Ahmed Institute of Technology', type: 'Private' },
    { code: '2354', name: 'Pollachi Institute of Engg. and Technology', type: 'Private' },
    { code: '2360', name: 'Suguna College of Engineering', type: 'Private' },
    { code: '2367', name: 'Arjun College of Technology', type: 'Private' },
    { code: '2377', name: 'PSG Institute of Technology and Applied Research', type: 'Private' },
    { code: '2650', name: 'Christ the King Engineering College', type: 'Private' },
    { code: '2704', name: 'Coimbatore Institute of Engg. and Technology', type: 'Private' },
    { code: '2706', name: 'Dr. Mahalingam College of Engg. and Technology', type: 'Private' },
    { code: '2708', name: 'Hindusthan College of Engg. and Technology', type: 'Private' },
    { code: '2710', name: 'Karpagam College of Engineering', type: 'Private' },
    { code: '2712', name: 'Kumaraguru College of Technology', type: 'Private' },
    { code: '2716', name: 'Park College of Engg. and Technology', type: 'Private' },
    { code: '2718', name: 'Sri Krishna College of Engg. and Technology', type: 'Private' },
    { code: '2719', name: 'Sri Ramakrishna Engineering College', type: 'Private' },
    { code: '2721', name: 'Tamilnadu College of Engineering', type: 'Private' },
    { code: '2722', name: 'Sri Krishna College of Technology', type: 'Private' },
    { code: '2725', name: 'Sri Ramakrishna Institute of Technology', type: 'Private' },
    { code: '2726', name: 'SNS College of Technology', type: 'Private' },
    { code: '2727', name: 'Sri Shakthi Institute of Engg. and Technology', type: 'Private' },
    { code: '2729', name: 'Nehru Institute of Engg. and Technology', type: 'Private' },
    { code: '2731', name: 'R V S College of Engg. and Technology', type: 'Private' },
    { code: '2732', name: 'INFO Institute of Engineering', type: 'Private' },
    { code: '2734', name: 'SNS College of Engineering', type: 'Private' },
    { code: '2735', name: 'Karpagam Institute of Technology', type: 'Private' },
    { code: '2736', name: 'Dr. N G P Institute of Technology', type: 'Private' },
    { code: '2739', name: 'Sri Eshwar College of Engineering', type: 'Private' },
    { code: '2740', name: 'Hindustan Institute of Technology', type: 'Private' },
    { code: '2741', name: 'P A College of Engg. and Technology', type: 'Private' },
    { code: '2743', name: 'Dhanalakshmi Srinivasan College of Engineering', type: 'Private' },
    { code: '2744', name: 'Adithya Institute of Technology', type: 'Private' },
    { code: '2745', name: 'Kathir College of Engineering', type: 'Private' },
    { code: '2749', name: 'EASA College of Engg. and Technology', type: 'Private' },
    { code: '2750', name: 'KIT – Kalaignar Karunanidhi Institute of Technology', type: 'Private' },
    { code: '2751', name: 'KGISL Institute of Technology', type: 'Private' },
    { code: '2753', name: 'P P G Institute of Technology', type: 'Private' },
    { code: '2755', name: 'Nehru Institute of Technology', type: 'Private' },
    { code: '2761', name: 'United Institute of Technology', type: 'Private' },
    { code: '2762', name: 'Jansons Institute of Technology', type: 'Private' },
    { code: '2763', name: 'Akshaya College of Engg. and Technology', type: 'Private' },
    { code: '2764', name: 'K P R Institute of Engg. and Technology', type: 'Private' },
    { code: '2765', name: 'Sriguru Institute of Technology', type: 'Private' },
    { code: '2768', name: 'Park College of Technology', type: 'Private' },
    { code: '2769', name: 'J C T College of Engg. and Technology', type: 'Private' },
    { code: '2772', name: 'C M S College of Engg. and Technology', type: 'Private' },
    { code: '2776', name: 'R V S Technical Campus – Coimbatore', type: 'Private' },
  ]},
  { district: 'Cuddalore', districtTamil: 'கடலூர்', colleges: [
    { code: '0005', name: 'Annamalai University Faculty of Engineering', type: 'Govt Deemed' },
    { code: '3019', name: 'University College of Engineering, Panruti', type: 'Govt' },
    { code: '3410', name: 'Krishnaswamy College of Engg. and Technology', type: 'Private' },
    { code: '3425', name: 'C K College of Engg. and Technology', type: 'Private' },
    { code: '3822', name: 'Dr. Navalar Nedunchezhian College of Engineering', type: 'Private' },
    { code: '3843', name: 'M R K Institute of Technology', type: 'Private' },
    { code: '3860', name: 'St. Annes College of Engg. and Technology', type: 'Private' },
  ]},
  { district: 'Dharmapuri', districtTamil: 'தர்மபுரி', colleges: [
    { code: '2369', name: 'Government College of Engineering, Dharmapuri', type: 'Govt' },
    { code: '2606', name: 'Jayam College of Engg. and Technology', type: 'Private' },
    { code: '2640', name: 'Jayalakshmi Institute of Technology', type: 'Private' },
    { code: '2641', name: 'Varuvan Vadivelan Institute of Technology', type: 'Private' },
    { code: '2683', name: 'Shreenivasa Engineering College', type: 'Private' },
  ]},
  { district: 'Dindigul', districtTamil: 'திண்டுக்கல்', colleges: [
    { code: '5022', name: 'University College of Engineering, Dindigul', type: 'Govt' },
    { code: '5530', name: 'SSM Institute of Engg. and Technology', type: 'Private' },
    { code: '5703', name: 'Christian College of Engg. and Technology', type: 'Private' },
    { code: '5720', name: 'Sri Subramanya College of Engg. and Technology', type: 'Private' },
    { code: '5832', name: 'N P R College of Engg. and Technology', type: 'Private' },
    { code: '5851', name: 'Veerammal Engineering College', type: 'Private' },
    { code: '5862', name: 'R V S Educational Trust Group of Institutions', type: 'Private' },
    { code: '5910', name: 'P S N A College of Engg. and Technology', type: 'Private' },
    { code: '5913', name: 'Ratnavel Subramaniam College of Engg. & Tech.', type: 'Private' },
    { code: '5930', name: 'SBM College of Engg. and Technology', type: 'Private' },
  ]},
  { district: 'Erode', districtTamil: 'ஈரோடு', colleges: [
    { code: '2332', name: 'Aishwarya College of Engg. and Technology', type: 'Private' },
    { code: '2652', name: 'Al-Ameen Engineering College', type: 'Private' },
    { code: '2702', name: 'Bannari Amman Institute of Technology', type: 'Private' },
    { code: '2707', name: 'Erode Sengunthar Engineering College', type: 'Private' },
    { code: '2709', name: 'Institute of Road and Transport Technology', type: 'Govt' },
    { code: '2711', name: 'Kongu Engineering College', type: 'Private' },
    { code: '2713', name: 'M P Nachimuthu M Jagannathan Engg. College', type: 'Private' },
    { code: '2715', name: 'Nandha Engineering College', type: 'Private' },
    { code: '2723', name: 'Velalar College of Engg. and Technology', type: 'Private' },
    { code: '2747', name: 'Shree Venkateshwara Hi-Tech Engg. College', type: 'Private' },
    { code: '2748', name: 'Surya Engineering College', type: 'Private' },
    { code: '2752', name: 'Nandha College of Technology', type: 'Private' },
    { code: '2758', name: 'J K K Muniraja College of Technology', type: 'Private' },
  ]},
  { district: 'Kanchipuram', districtTamil: 'காஞ்சிபுரம்', colleges: [
    { code: '0004', name: 'Anna University – MIT Campus', type: 'Govt' },
    { code: '1026', name: 'University College of Engineering, Kanchipuram', type: 'Govt' },
    { code: '1140', name: 'Jeppiaar Institute of Technology', type: 'Private' },
    { code: '1201', name: 'Arignar Anna Institute of Science and Technology', type: 'Private' },
    { code: '1206', name: 'Jeppiaar Maamallan Engineering College', type: 'Private' },
    { code: '1207', name: 'Kings Engineering College', type: 'Private' },
    { code: '1209', name: 'Pallavan College of Engineering', type: 'Private' },
    { code: '1211', name: 'Rajalakshmi Engineering College', type: 'Private' },
    { code: '1212', name: 'Rajiv Gandhi College of Engineering', type: 'Private' },
    { code: '1216', name: 'Saveetha Engineering College', type: 'Private' },
    { code: '1219', name: 'Sri Venkateswara College of Engineering', type: 'Private' },
    { code: '1222', name: 'P B College of Engineering', type: 'Private' },
    { code: '1226', name: 'P T Lee Chengalvaraya Naicker College of Engg. & Tech.', type: 'Private' },
    { code: '1230', name: 'Apollo Engineering College', type: 'Private' },
    { code: '1232', name: 'A R M College of Engg. and Technology', type: 'Private' },
    { code: '1233', name: 'Adhi College of Engg. and Technology', type: 'Private' },
    { code: '1234', name: 'Indira Gandhi College of Engg. & Tech. for Women', type: 'Private' },
    { code: '1301', name: 'Mohamed Sathak A J College of Engineering', type: 'Private' },
    { code: '1303', name: 'Anand Institute of Higher Technology', type: 'Private' },
    { code: '1315', name: 'Sri Sivasubramaniya Nadar College of Engineering (SSN)', type: 'Private' },
    { code: '1316', name: 'Agni College of Technology', type: 'Private' },
    { code: '1320', name: 'Jeppiaar SRR Engineering College', type: 'Private' },
    { code: '1325', name: 'St. Joseph College of Engineering', type: 'Private' },
    { code: '1333', name: 'Vi Institute of Technology', type: 'Private' },
    { code: '1334', name: 'ARS College of Engineering', type: 'Private' },
    { code: '1401', name: 'Adhiparasakthi Engineering College, Melmaruvathur', type: 'Private' },
    { code: '1409', name: 'Karpagavinayaga College of Engg. and Technology', type: 'Private' },
    { code: '1413', name: 'Sri Venkateswaraa College of Technology', type: 'Private' },
    { code: '1417', name: 'Shri Andal Alagar College of Engineering', type: 'Private' },
    { code: '1432', name: 'Rajalakshmi Institute of Technology', type: 'Private' },
    { code: '1435', name: 'Balaji Institute of Engg. and Technology', type: 'Private' },
    { code: '1444', name: 'Chendu College of Engg. & Technology', type: 'Private' },
    { code: '1517', name: 'Thirumalai Engineering College', type: 'Private' },
  ]},
  { district: 'Kanniyakumari', districtTamil: 'கன்னியாகுமரி', colleges: [
    { code: '4023', name: 'University College of Engineering, Nagercoil', type: 'Govt' },
    { code: '4670', name: 'Rohini College of Engg. & Technology', type: 'Private' },
    { code: '4672', name: 'Stella Marys College of Engineering', type: 'Private' },
    { code: '4677', name: 'Lourdes Mount College of Engg. and Technology', type: 'Private' },
    { code: '4686', name: 'Good Shepherd College of Engg. and Technology', type: 'Private' },
    { code: '4927', name: 'Maria College of Engg. and Technology', type: 'Private' },
    { code: '4928', name: 'MAR Ephraem College of Engg. & Technology', type: 'Private' },
    { code: '4929', name: 'M E T Engineering College', type: 'Private' },
    { code: '4938', name: 'Sivaji College of Engg. and Technology', type: 'Private' },
    { code: '4943', name: 'Satyam College of Engg. & Technology', type: 'Private' },
    { code: '4944', name: 'Arunachala College of Engineering for Women', type: 'Private' },
    { code: '4945', name: 'Vins Christian Womens College of Engineering', type: 'Private' },
    { code: '4946', name: 'D M I Engineering College', type: 'Private' },
    { code: '4948', name: 'Rajas International Institute of Technology for Women', type: 'Private' },
    { code: '4952', name: 'C S I Institute of Technology', type: 'Private' },
    { code: '4971', name: 'St. Xavier Catholic College of Engineering', type: 'Private' },
    { code: '4972', name: 'Amrita College of Engg. and Technology', type: 'Private' },
    { code: '4977', name: 'Narayanaguru College of Engineering', type: 'Private' },
    { code: '4978', name: 'Udaya School of Engineering', type: 'Private' },
    { code: '4981', name: 'Ponjesly College of Engineering', type: 'Private' },
    { code: '4982', name: 'Vins Christian College of Engineering', type: 'Private' },
    { code: '4983', name: 'Lord Jegannath College of Engg. and Technology', type: 'Private' },
    { code: '4984', name: 'Marthandam College of Engg. & Technology', type: 'Private' },
    { code: '4992', name: 'Bethlahem Institute of Engineering', type: 'Private' },
    { code: '4993', name: 'Loyola Institute of Technology and Science', type: 'Private' },
    { code: '4999', name: 'Annai Vailankanni College of Engineering', type: 'Private' },
  ]},
  { district: 'Karur', districtTamil: 'கரூர்', colleges: [
    { code: '2355', name: 'Cheran College of Engineering', type: 'Private' },
    { code: '2356', name: 'Arulmurugan College of Engineering', type: 'Private' },
    { code: '2608', name: 'M Kumarasamy College of Engineering', type: 'Private' },
    { code: '2622', name: 'V S B Engineering College', type: 'Private' },
    { code: '2649', name: 'Karur College of Engineering', type: 'Private' },
  ]},
  { district: 'Krishnagiri', districtTamil: 'கிருஷ்ணகிரி', colleges: [
    { code: '2601', name: 'Adhiyamaan College of Engineering', type: 'Private' },
    { code: '2603', name: 'Government College of Engineering, Bargur', type: 'Govt' },
    { code: '2621', name: 'Er. Perumal Manimekalai College of Engineering', type: 'Private' },
    { code: '2642', name: 'P S V College of Engg. and Technology', type: 'Private' },
  ]},
  { district: 'Madurai', districtTamil: 'மதுரை', colleges: [
    { code: '5008', name: 'Thiagarajar College of Engineering (TCE)', type: 'Govt-Aided' },
    { code: '5010', name: 'Anna University Regional Campus – Madurai', type: 'Govt' },
    { code: '5532', name: 'Vaigai College of Engineering', type: 'Private' },
    { code: '5536', name: 'Mangayarkarasi College of Engineering', type: 'Private' },
    { code: '5911', name: 'P T R College of Engg. and Technology', type: 'Private' },
    { code: '5914', name: 'Solaimalai College of Engineering', type: 'Private' },
    { code: '5915', name: 'SACS-MAVMM Engineering College', type: 'Private' },
    { code: '5942', name: 'Ultra College of Engg. & Technology', type: 'Private' },
    { code: '5986', name: 'Velammal College of Engg. and Technology', type: 'Private' },
    { code: '5990', name: 'Latha Mathavan Engineering College', type: 'Private' },
  ]},
  { district: 'Nagapattinam', districtTamil: 'நாகப்பட்டினம்', colleges: [
    { code: '3018', name: 'University College of Engineering, Thirukkuvalai', type: 'Govt' },
    { code: '3461', name: 'Arifa Institute of Technology', type: 'Private' },
    { code: '3760', name: 'Sir Issac Newton College of Engg. and Technology', type: 'Private' },
    { code: '3801', name: 'A V C College of Engineering', type: 'Private' },
    { code: '3806', name: 'E G S Pillay Engineering College', type: 'Private' },
    { code: '3859', name: 'Sembodai Rukmani Varatharajan Engg. College', type: 'Private' },
  ]},
  { district: 'Namakkal', districtTamil: 'நாமக்கல்', colleges: [
    { code: '2314', name: 'Muthayammal College of Engineering', type: 'Private' },
    { code: '2328', name: 'K S R Institute for Engg. and Technology', type: 'Private' },
    { code: '2602', name: 'Annai Mathammal Sheela Engineering College', type: 'Private' },
    { code: '2607', name: 'K S Rangasamy College of Technology', type: 'Private' },
    { code: '2609', name: 'Mahendra Engineering College', type: 'Private' },
    { code: '2610', name: 'Muthayammal Engineering College', type: 'Private' },
    { code: '2611', name: 'Paavai Engineering College', type: 'Private' },
    { code: '2612', name: 'P G P College of Engg. and Technology', type: 'Private' },
    { code: '2613', name: 'K S R College of Engineering', type: 'Private' },
    { code: '2614', name: 'S S M College of Engineering', type: 'Private' },
    { code: '2617', name: 'Sengunthar Engineering College', type: 'Private' },
    { code: '2620', name: 'Vivekanandha College of Engg. for Women', type: 'Private' },
    { code: '2624', name: 'Gnanamani College of Technology', type: 'Private' },
    { code: '2627', name: 'Selvam College of Technology', type: 'Private' },
    { code: '2628', name: 'Paavai College of Engineering', type: 'Private' },
    { code: '2629', name: 'Sengunthar College of Engineering', type: 'Private' },
    { code: '2632', name: 'Mahendra Institute of Technology', type: 'Private' },
    { code: '2633', name: 'Vidyaa Vikas College of Engg. and Technology', type: 'Private' },
    { code: '2634', name: 'Excel Engineering College', type: 'Private' },
    { code: '2638', name: 'Mahendra Engineering College for Women', type: 'Private' },
    { code: '2647', name: 'J K K Nataraja College of Engg. and Technology', type: 'Private' },
    { code: '2657', name: 'Paavai College of Technology', type: 'Private' },
    { code: '2660', name: 'Gnanamani College of Engineering', type: 'Private' },
    { code: '2661', name: 'Vivekanandha College of Technology for Women', type: 'Private' },
    { code: '2664', name: 'Excel College of Engg. and Technology', type: 'Private' },
    { code: '2665', name: 'Mahendra Institute of Engg. and Technology', type: 'Private' },
    { code: '2767', name: 'SRG Engineering College', type: 'Private' },
  ]},
  { district: 'Perambalur', districtTamil: 'பெரம்பலூர்', colleges: [
    { code: '3454', name: 'Sri Ramakrishna College of Engineering', type: 'Private' },
    { code: '3457', name: 'Dhanalakshmi Srinivasan College of Engineering', type: 'Private' },
    { code: '3805', name: 'Dhanalakshmi Srinivasan Engineering College', type: 'Private' },
    { code: '3817', name: 'Roever Engineering College', type: 'Private' },
    { code: '3823', name: 'Srinivasan Engineering College', type: 'Private' },
    { code: '3847', name: 'Roever College of Engg. and Technology', type: 'Private' },
  ]},
  { district: 'Pudukkottai', districtTamil: 'புதுக்கோட்டை', colleges: [
    { code: '3812', name: 'Mookambigai College of Engineering', type: 'Private' },
    { code: '3846', name: 'Mother Terasa College of Engg. and Technology', type: 'Private' },
    { code: '3852', name: 'Sri Bharathi Engineering College for Women', type: 'Private' },
    { code: '3854', name: 'Mahath Amma Institute of Engg. and Technology', type: 'Private' },
    { code: '3905', name: 'Kings College of Engineering', type: 'Private' },
    { code: '3908', name: 'Mount Zion College of Engg. and Technology', type: 'Private' },
    { code: '3918', name: 'Shanmuganathan Engineering College', type: 'Private' },
    { code: '3920', name: 'Sudharsan Engineering College', type: 'Private' },
    { code: '3923', name: 'M N S K College of Engineering', type: 'Private' },
    { code: '3925', name: 'M A R College of Engg. and Technology', type: 'Private' },
  ]},
  { district: 'Ramanathapuram', districtTamil: 'ராமநாதபுரம்', colleges: [
    { code: '5017', name: 'University College of Engineering, Ramanathapuram', type: 'Govt' },
    { code: '5907', name: 'Mohamed Sathak Engineering College', type: 'Private' },
    { code: '5921', name: 'Syed Ammal Engineering College', type: 'Private' },
    { code: '5924', name: 'Ganapathy Chettiar College of Engg. and Technology', type: 'Private' },
  ]},
  { district: 'Salem', districtTamil: 'சேலம்', colleges: [
    { code: '2302', name: 'Sri Shanmugha College of Engg. and Technology', type: 'Private' },
    { code: '2341', name: 'Ganesh College of Engineering', type: 'Private' },
    { code: '2343', name: 'Indian Institute of Handloom Technology', type: 'Central Govt' },
    { code: '2345', name: 'Dhirajlal Gandhi College of Technology', type: 'Private' },
    { code: '2346', name: 'Shree Sathyam College of Engg. and Technology', type: 'Private' },
    { code: '2347', name: 'AVS College of Technology', type: 'Private' },
    { code: '2615', name: 'Government College of Engineering, Salem', type: 'Govt' },
    { code: '2618', name: 'Sona College of Technology', type: 'Private' },
    { code: '2623', name: 'Mahendra College of Engineering', type: 'Private' },
    { code: '2625', name: 'The Kavery Engineering College', type: 'Private' },
    { code: '2636', name: 'A V S Engineering College', type: 'Private' },
    { code: '2639', name: 'Narasus Sarathy Institute of Technology', type: 'Private' },
    { code: '2643', name: 'Bharathiyar Institute of Engineering for Women', type: 'Private' },
    { code: '2646', name: 'Tagore Institute of Engg. and Technology', type: 'Private' },
    { code: '2648', name: 'Annaporna Engineering College', type: 'Private' },
    { code: '2653', name: 'Knowledge Institute of Technology', type: 'Private' },
    { code: '2658', name: 'V S A Group of Institutions', type: 'Private' },
    { code: '2659', name: 'Salem College of Engg. and Technology', type: 'Private' },
    { code: '2666', name: 'The Kavery College of Engineering', type: 'Private' },
  ]},
  { district: 'Sivaganga', districtTamil: 'சிவகங்கை', colleges: [
    { code: '5012', name: 'CECRI, Karaikudi', type: 'Central Govt' },
    { code: '5502', name: 'Sree Raaja Raajan College of Engg. & Technology', type: 'Private' },
    { code: '5533', name: 'Karaikudi Institute of Technology', type: 'Private' },
    { code: '5842', name: 'Madurai Institute of Engg. & Technology', type: 'Private' },
    { code: '5901', name: 'Alagappa Chettiar Govt. College of Engg. & Technology', type: 'Govt' },
    { code: '5903', name: 'K L N College of Information Technology', type: 'Private' },
    { code: '5904', name: 'K L N College of Engineering', type: 'Private' },
    { code: '5912', name: 'Pandian Saraswathi Yadav Engineering College', type: 'Private' },
    { code: '5919', name: 'St. Michael College of Engg. and Technology', type: 'Private' },
    { code: '5922', name: 'Vickram College of Engineering', type: 'Private' },
    { code: '5935', name: 'Fatima Michael College of Engg. & Technology', type: 'Private' },
  ]},
  { district: 'Thanjavur', districtTamil: 'தஞ்சாவூர்', colleges: [
    { code: '3021', name: 'University College of Engineering, Pattukkottai', type: 'Govt' },
    { code: '3456', name: 'K S K College of Engg. and Technology', type: 'Private' },
    { code: '3464', name: 'Government College of Engineering, Thanjavur', type: 'Govt' },
    { code: '3766', name: 'Star Lion College of Engg. & Technology', type: 'Private' },
    { code: '3804', name: 'Arasu Engineering College', type: 'Private' },
    { code: '3814', name: 'P R Engineering College', type: 'Private' },
    { code: '3825', name: 'St. Josephs College of Engg. and Technology', type: 'Private' },
    { code: '3833', name: 'Parisutham Institute of Technology and Science', type: 'Private' },
    { code: '3848', name: 'Vandayar Engineering College', type: 'Private' },
    { code: '3849', name: 'Annai College of Engg. and Technology', type: 'Private' },
    { code: '3855', name: 'As-Salam College of Engg. and Technology', type: 'Private' },
  ]},
  { district: 'Theni', districtTamil: 'தேனி', colleges: [
    { code: '5009', name: 'Government College of Engineering, Bodinayakkanur', type: 'Govt' },
    { code: '5865', name: 'Nadar Saraswathi College of Engg. and Technology', type: 'Private' },
    { code: '5902', name: 'Bharath Niketan Engineering College', type: 'Private' },
    { code: '5988', name: 'Theni Kammavar Sangam College of Technology', type: 'Private' },
  ]},
  { district: 'Thiruvallur', districtTamil: 'திருவள்ளூர்', colleges: [
    { code: '1107', name: 'Jaya Institute of Technology', type: 'Private' },
    { code: '1110', name: 'Prathyusha Engineering College', type: 'Private' },
    { code: '1112', name: 'R M D Engineering College', type: 'Private' },
    { code: '1113', name: 'R M K Engineering College', type: 'Private' },
    { code: '1115', name: 'Sri Ram Engineering College', type: 'Private' },
    { code: '1116', name: 'Sri Venkateswara College of Engg. and Technology', type: 'Private' },
    { code: '1121', name: 'Sri Venkateswara Institute of Science and Technology', type: 'Private' },
    { code: '1124', name: 'SAMS College of Engg. and Technology', type: 'Private' },
    { code: '1126', name: 'J N N Institute of Engineering', type: 'Private' },
    { code: '1128', name: 'R M K College of Engg. and Technology', type: 'Private' },
    { code: '1141', name: 'R V S Padmavathy College of Engg. and Technology', type: 'Private' },
    { code: '1150', name: 'Sri Jayaram Institute of Engg. and Technology', type: 'Private' },
    { code: '1229', name: 'Indira Institute of Engg. and Technology', type: 'Private' },
    { code: '1237', name: 'Velammal Institute of Technology', type: 'Private' },
    { code: '1238', name: 'GRT Institute of Engg. and Technology', type: 'Private' },
    { code: '1241', name: 'T J S Engineering College', type: 'Private' },
  ]},
  { district: 'Tiruvannamalai', districtTamil: 'திருவண்ணாமலை', colleges: [
    { code: '1015', name: 'University College of Engineering, Arni', type: 'Govt' },
    { code: '1503', name: 'Arulmigu Meenakshi Amman College of Engineering', type: 'Private' },
    { code: '1504', name: 'Arunai Engineering College', type: 'Private' },
    { code: '1508', name: 'Arunai College of Engineering', type: 'Private' },
    { code: '1512', name: 'S K P Engineering College', type: 'Private' },
    { code: '1513', name: 'Sri Balaji Chockalingam Engineering College', type: 'Private' },
    { code: '1518', name: 'Thiruvalluvar College of Engg. and Technology', type: 'Private' },
    { code: '1524', name: 'Annamalaiar College of Engineering', type: 'Private' },
    { code: '1529', name: 'Oxford College of Engineering', type: 'Private' },
    { code: '1439', name: 'S R I College of Engg. and Technology', type: 'Private' },
  ]},
  { district: 'Tiruvarur', districtTamil: 'திருவாரூர்', colleges: [
    { code: '3803', name: 'Anjalai Ammal-Mahalingam Engineering College', type: 'Private' },
    { code: '3821', name: 'A R J College of Engg. and Technology', type: 'Private' },
  ]},
  { district: 'Thoothukudi', districtTamil: 'தூத்துக்குடி', colleges: [
    { code: '4024', name: 'University V.O.C. College of Engg., Thoothukudi', type: 'Govt' },
    { code: '4931', name: 'Chandy College of Engineering', type: 'Private' },
    { code: '4933', name: 'St. Mother Theresa Engineering College', type: 'Private' },
    { code: '4934', name: 'Holy Cross Engineering College', type: 'Private' },
    { code: '4941', name: 'Unnamalai Institute of Technology', type: 'Private' },
    { code: '4954', name: 'Dr. Sivanthi Aditanar College of Engineering', type: 'Private' },
    { code: '4957', name: 'Jayaraj Annapackiam CSI College of Engineering', type: 'Private' },
    { code: '4962', name: 'National Engineering College', type: 'Private' },
    { code: '4975', name: 'Dr. G U Pope College of Engineering', type: 'Private' },
    { code: '4976', name: 'Infant Jesus College of Engineering', type: 'Private' },
  ]},
  { district: 'Tiruchirappalli', districtTamil: 'திருச்சிராப்பள்ளி', colleges: [
    { code: '3011', name: 'University College of Engineering, BIT Campus', type: 'Govt' },
    { code: '3458', name: 'Dhanalakshmi Srinivasan Institute of Research and Technology', type: 'Private' },
    { code: '3459', name: 'Dhanalakshmi Srinivasan Institute of Technology', type: 'Private' },
    { code: '3460', name: 'Sureya College of Engineering', type: 'Private' },
    { code: '3465', name: 'Government College of Engineering, Srirangam', type: 'Govt' },
    { code: '3701', name: 'K Ramakrishnan College of Technology', type: 'Private' },
    { code: '3782', name: 'OASYS Institute of Technology', type: 'Private' },
    { code: '3786', name: 'M.A.M. School of Engineering', type: 'Private' },
    { code: '3795', name: 'SRM TRP Engineering College', type: 'Private' },
    { code: '3802', name: 'Shri Angalamman College of Engg. and Technology', type: 'Private' },
    { code: '3807', name: 'J J College of Engg. and Technology', type: 'Private' },
    { code: '3808', name: 'Jayaram College of Engg. and Technology', type: 'Private' },
    { code: '3809', name: 'Kurinji College of Engg. and Technology', type: 'Private' },
    { code: '3810', name: 'M.A.M. College of Engineering', type: 'Private' },
    { code: '3811', name: 'M I E T Engineering College', type: 'Private' },
    { code: '3813', name: 'Oxford Engineering College', type: 'Private' },
    { code: '3815', name: 'Pavendhar Bharathidasan College of Engg. and Technology', type: 'Private' },
    { code: '3819', name: 'Saranathan College of Engineering', type: 'Private' },
    { code: '3820', name: 'Tiruchirappalli Engineering College', type: 'Private' },
    { code: '3826', name: 'Kongunadu College of Engg. and Technology', type: 'Private' },
    { code: '3829', name: 'M.A.M. College of Engg. and Technology', type: 'Private' },
    { code: '3830', name: 'K Ramakrishnan College of Engineering', type: 'Private' },
    { code: '3831', name: 'Indra Ganesan College of Engineering', type: 'Private' },
    { code: '3841', name: 'C.A.R.E Group of Institutions', type: 'Private' },
    { code: '3844', name: 'Shivani Engineering College', type: 'Private' },
    { code: '3845', name: 'Imayam College of Engineering', type: 'Private' },
    { code: '3850', name: 'Vetri Vinayaha College of Engg. and Technology', type: 'Private' },
    { code: '3857', name: 'Meenakshi Ramaswamy Engineering College', type: 'Private' },
  ]},
  { district: 'Tiruppur', districtTamil: 'திருப்பூர்', colleges: [
    { code: '2350', name: 'Jairupaa College of Engineering', type: 'Private' },
    { code: '2358', name: 'SCAD Institute of Technology', type: 'Private' },
    { code: '2651', name: 'Jai Shriram Engineering College', type: 'Private' },
    { code: '2656', name: 'Builders Engineering College', type: 'Private' },
    { code: '2714', name: 'Maharaja Engineering College', type: 'Private' },
    { code: '2717', name: 'Sasurie College of Engineering', type: 'Private' },
    { code: '2733', name: 'Angel College of Engg. and Technology', type: 'Private' },
  ]},
  { district: 'Vellore', districtTamil: 'வேலூர்', colleges: [
    { code: '1516', name: 'Thanthai Periyar Govt. Institute of Technology', type: 'Govt' },
    { code: '1137', name: 'Annai Mira College of Engg. and Technology', type: 'Private' },
    { code: '1438', name: 'Sree Krishna College of Engineering', type: 'Private' },
    { code: '1501', name: 'Adhiparasakthi College of Engineering, Kalavai', type: 'Private' },
    { code: '1505', name: 'C Abdul Hakeem College of Engg. and Technology', type: 'Private' },
    { code: '1506', name: 'G G R College of Engineering', type: 'Private' },
    { code: '1507', name: 'Ganadipathy Tulsis Jain Engineering College', type: 'Private' },
    { code: '1510', name: 'Priyadarshini Engineering College', type: 'Private' },
    { code: '1514', name: 'Sri Nandhanam College of Engg. and Technology', type: 'Private' },
    { code: '1515', name: 'Saraswathi Velu College of Engineering', type: 'Private' },
    { code: '1519', name: 'Bharathidasan Engineering College', type: 'Private' },
    { code: '1520', name: 'Kingston Engineering College', type: 'Private' },
    { code: '1521', name: 'Sri Sapthagiri Institute of Technology', type: 'Private' },
    { code: '1523', name: 'Global Institute of Engg. and Technology', type: 'Private' },
    { code: '1525', name: 'Podhigai College of Engg. and Technology', type: 'Private' },
    { code: '1526', name: 'Sri Krishna College of Engineering', type: 'Private' },
  ]},
  { district: 'Villupuram', districtTamil: 'விழுப்புரம்', colleges: [
    { code: '1013', name: 'University College of Engineering, Villupuram', type: 'Govt' },
    { code: '1014', name: 'University College of Engineering, Tindivanam', type: 'Govt' },
    { code: '1402', name: 'Annai Terasa College of Engineering', type: 'Private' },
    { code: '1406', name: 'Dr. Pauls Engineering College', type: 'Private' },
    { code: '1408', name: 'I F E T College of Engineering', type: 'Private' },
    { code: '1412', name: 'Mailam Engineering College', type: 'Private' },
    { code: '1415', name: 'T S M Jain College of Technology', type: 'Private' },
    { code: '1421', name: 'V R S College of Engg. and Technology', type: 'Private' },
    { code: '1428', name: 'E S Engineering College', type: 'Private' },
    { code: '1430', name: 'Maha Bharathi Engineering College', type: 'Private' },
    { code: '1434', name: 'Surya Group of Institutions', type: 'Private' },
    { code: '1436', name: 'A R Engineering College', type: 'Private' },
    { code: '1441', name: 'A K T Memorial College of Engg. and Technology', type: 'Private' },
    { code: '1445', name: 'Sri Rangapoopathi College of Engineering', type: 'Private' },
    { code: '1449', name: 'Saraswathy College of Engg. and Technology', type: 'Private' },
    { code: '1605', name: 'Idhaya Engineering College for Women', type: 'Private' },
  ]},
  { district: 'Virudhunagar', districtTamil: 'விருதுநகர்', colleges: [
    { code: '4676', name: 'Renganayagi Varatharaj College of Engineering', type: 'Private' },
    { code: '4678', name: 'Ramco Institute of Technology', type: 'Private' },
    { code: '4680', name: 'AAA College of Engg. and Technology', type: 'Private' },
    { code: '4917', name: 'Sethu Institute of Technology', type: 'Private' },
    { code: '4959', name: 'Kamaraj College of Engg. and Technology', type: 'Private' },
    { code: '4960', name: 'Mepco Schlenk Engineering College', type: 'Private' },
    { code: '4965', name: 'P S R Engineering College', type: 'Private' },
    { code: '4970', name: 'Sree Sowdambiga College of Engineering', type: 'Private' },
    { code: '4979', name: 'V P M M College of Engineering for Women', type: 'Private' },
    { code: '4995', name: 'P S R Rengasamy College of Engg. for Women', type: 'Private' },
    { code: '4996', name: 'Sri Vidhya College of Engg. and Technology', type: 'Private' },
  ]},
];

export const getTotalColleges = () => tneaSportsQuotaColleges.reduce((s, d) => s + d.colleges.length, 0);
export const getDistrictCount = () => tneaSportsQuotaColleges.length;
export const getGovtCount = () => tneaSportsQuotaColleges.reduce((s, d) => s + d.colleges.filter(c => c.type !== 'Private').length, 0);
