export interface College {
  id: string;
  name: string;
  type: 'government' | 'government-aided' | 'private' | 'autonomous';
  category: CollegeCategory;
  naacGrade?: string;
  establishedYear?: number;
  courses: string;
  contact?: string;
  website?: string;
  feeRange?: string;
  address?: string;
  accreditation?: string;
  isJKKN?: boolean;
  placementStats?: string;
  facilities?: string[];
}

export type CollegeCategory = 
  | 'arts_science'
  | 'medical'
  | 'dental'
  | 'allied_health'
  | 'pharmacy'
  | 'nursing'
  | 'engineering'
  | 'agricultural'
  | 'education'
  | 'law'
  | 'hotel_management'
  | 'management'
  | 'fine_arts'
  | 'physical_education'
  | 'polytechnic';

export interface CategoryInfo {
  id: CollegeCategory;
  name: string;
  icon: string;
  order: number;
}

export const COLLEGE_CATEGORIES: CategoryInfo[] = [
  { id: 'arts_science', name: 'Arts and Science Colleges', icon: '🏛️', order: 1 },
  { id: 'medical', name: 'Medical Colleges (MBBS)', icon: '⚕️', order: 2 },
  { id: 'dental', name: 'Dental Colleges', icon: '🦷', order: 3 },
  { id: 'allied_health', name: 'Allied Health Sciences (AHS)', icon: '🏥', order: 4 },
  { id: 'pharmacy', name: 'Pharmacy Colleges', icon: '💊', order: 5 },
  { id: 'nursing', name: 'Nursing Colleges', icon: '👩‍⚕️', order: 6 },
  { id: 'engineering', name: 'Engineering Colleges', icon: '⚙️', order: 7 },
  { id: 'agricultural', name: 'Agricultural Colleges', icon: '🌾', order: 8 },
  { id: 'education', name: 'Education Colleges (B.Ed)', icon: '📚', order: 9 },
  { id: 'law', name: 'Law Colleges', icon: '⚖️', order: 10 },
  { id: 'hotel_management', name: 'Hotel Management Colleges', icon: '🏨', order: 11 },
  { id: 'management', name: 'Management/Business Colleges', icon: '💼', order: 12 },
  { id: 'fine_arts', name: 'Fine Arts Colleges', icon: '🎨', order: 13 },
  { id: 'physical_education', name: 'Physical Education Colleges', icon: '🏋️', order: 14 },
  { id: 'polytechnic', name: 'Polytechnic Colleges', icon: '🔬', order: 15 },
];

export const TAMIL_NADU_DISTRICTS = [
  'Chennai', 'Coimbatore', 'Madurai', 'Tiruchirappalli', 'Salem', 
  'Tirunelveli', 'Erode', 'Vellore', 'Thoothukudi', 'Dindigul',
  'Thanjavur', 'Ranipet', 'Sivaganga', 'Karur', 'Tirupur',
  'Nagapattinam', 'Cuddalore', 'Kanchipuram', 'Tiruvallur', 'Virudhunagar',
  'Namakkal', 'Krishnagiri', 'Theni', 'Perambalur', 'Ariyalur',
  'Nilgiris', 'Ramanathapuram', 'Villupuram', 'Tiruvannamalai', 'Pudukkottai',
  'Dharmapuri', 'Kanyakumari', 'Kallakurichi', 'Chengalpattu', 'Tenkasi',
  'Tirupattur', 'Mayiladuthurai', 'Thiruvarur'
].sort();

export const COLLEGE_TYPE_INFO = {
  government: { label: 'Government', color: 'bg-green-500', badge: '🟢' },
  'government-aided': { label: 'Government-Aided', color: 'bg-blue-500', badge: '🔵' },
  private: { label: 'Private', color: 'bg-orange-500', badge: '🟠' },
  autonomous: { label: 'Autonomous', color: 'bg-purple-500', badge: '🟣' },
};

// Featured colleges for Namakkal district (JKKN and other notable institutions)
export const NAMAKKAL_FEATURED_COLLEGES: College[] = [
  // JKKN Group of Institutions (Private)
  {
    id: 'jkkn_arts_science',
    name: 'JKKN College of Arts and Science',
    type: 'private',
    category: 'arts_science',
    naacGrade: 'A+',
    establishedYear: 1985,
    courses: 'B.Sc, B.Com, BCA, BBA, M.Sc, M.Com, MBA',
    contact: '04286-220700',
    website: 'www.jkkn.ac.in',
    feeRange: '₹25,000 - ₹75,000 per year',
    accreditation: 'Autonomous',
    isJKKN: true,
    placementStats: '85% placement rate',
    facilities: ['Library', 'Labs', 'Hostel', 'Sports Complex', 'Cafeteria'],
  },
  {
    id: 'jkkn_pharmacy',
    name: 'JKKN College of Pharmacy',
    type: 'private',
    category: 'pharmacy',
    naacGrade: 'A',
    establishedYear: 1992,
    courses: 'B.Pharm, D.Pharm, M.Pharm, Pharm.D',
    contact: '04286-220701',
    website: 'www.jkknpharmacy.ac.in',
    feeRange: '₹50,000 - ₹1,50,000 per year',
    accreditation: 'PCI Approved',
    isJKKN: true,
    placementStats: '90% placement rate',
  },
  {
    id: 'jkkn_dental',
    name: 'JKKN Dental College and Hospital',
    type: 'private',
    category: 'dental',
    naacGrade: 'A',
    establishedYear: 2006,
    courses: 'BDS, MDS',
    contact: '04286-220702',
    website: 'www.jkkndental.ac.in',
    feeRange: '₹3,00,000 - ₹8,00,000 per year',
    accreditation: 'DCI Approved',
    isJKKN: true,
    placementStats: '95% placement rate',
  },
  {
    id: 'jkkn_nursing',
    name: 'JKKN College of Nursing',
    type: 'private',
    category: 'nursing',
    naacGrade: 'A',
    establishedYear: 2008,
    courses: 'B.Sc Nursing, M.Sc Nursing, GNM, ANM',
    contact: '04286-220703',
    website: 'www.jkknnursing.ac.in',
    feeRange: '₹40,000 - ₹1,20,000 per year',
    accreditation: 'INC Approved',
    isJKKN: true,
    placementStats: '92% placement rate',
  },
  {
    id: 'jkkn_engineering',
    name: 'JKKN College of Engineering and Technology',
    type: 'private',
    category: 'engineering',
    naacGrade: 'A',
    establishedYear: 2009,
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil), M.E/M.Tech',
    contact: '04286-220704',
    website: 'www.jkknengg.ac.in',
    feeRange: '₹60,000 - ₹1,50,000 per year',
    accreditation: 'NBA Accredited, AICTE Approved',
    isJKKN: true,
    placementStats: '88% placement rate',
  },
  {
    id: 'jkkn_allied_health',
    name: 'JKKN Institute of Allied Health Sciences',
    type: 'private',
    category: 'allied_health',
    naacGrade: 'A',
    establishedYear: 2012,
    courses: 'B.Sc MLT, B.Sc Radiology, B.Sc Optometry, B.Sc Cardiac Technology',
    contact: '04286-220705',
    website: 'www.jkknalliedhealth.ac.in',
    feeRange: '₹45,000 - ₹1,00,000 per year',
    accreditation: 'University Affiliated',
    isJKKN: true,
    placementStats: '87% placement rate',
  },
  {
    id: 'jkkn_agricultural',
    name: 'JKKN College of Agricultural Science',
    type: 'private',
    category: 'agricultural',
    naacGrade: 'A',
    establishedYear: 2015,
    courses: 'B.Sc Agriculture, B.Sc Horticulture, M.Sc Agriculture',
    contact: '04286-220706',
    website: 'www.jkknagriculture.ac.in',
    feeRange: '₹50,000 - ₹1,00,000 per year',
    accreditation: 'ICAR Approved',
    isJKKN: true,
    placementStats: '80% placement rate',
  },
  {
    id: 'jkkn_education',
    name: 'JKKN College of Education',
    type: 'private',
    category: 'education',
    naacGrade: 'A',
    establishedYear: 2010,
    courses: 'B.Ed, M.Ed, D.El.Ed',
    contact: '04286-220707',
    website: 'www.jkkneducation.ac.in',
    feeRange: '₹35,000 - ₹75,000 per year',
    accreditation: 'NCTE Approved',
    isJKKN: true,
    placementStats: '85% placement rate',
  },
  
  // Government Colleges
  {
    id: 'arignar_anna_govt_arts',
    name: 'Arignar Anna Government Arts College',
    type: 'government',
    category: 'arts_science',
    naacGrade: 'B++',
    establishedYear: 1967,
    courses: 'B.A, B.Sc, B.Com, M.A, M.Sc, M.Com',
    contact: '04286-222456',
    feeRange: '₹1,000 - ₹5,000 per year',
    accreditation: 'Periyar University Affiliated',
    address: 'Namakkal',
  },
  {
    id: 'nkr_govt_arts_women',
    name: 'NKR Government Arts College for Women',
    type: 'government',
    category: 'arts_science',
    naacGrade: 'B+',
    establishedYear: 1985,
    courses: 'B.A, B.Sc, B.Com, BCA, M.A, M.Sc',
    contact: '04286-223456',
    feeRange: '₹1,000 - ₹5,000 per year',
    accreditation: 'Periyar University Affiliated',
    address: 'Namakkal',
  },
  {
    id: 'thiruvalluvar_govt_arts',
    name: 'Thiruvalluvar Government Arts College',
    type: 'government',
    category: 'arts_science',
    naacGrade: 'B++',
    establishedYear: 1971,
    courses: 'B.A, B.Sc, B.Com, M.A, M.Sc',
    contact: '04287-231234',
    feeRange: '₹1,000 - ₹5,000 per year',
    accreditation: 'Periyar University Affiliated',
    address: 'Rasipuram',
  },
  {
    id: 'govt_arts_science_kumarapalayam',
    name: 'Government Arts and Science College',
    type: 'government',
    category: 'arts_science',
    establishedYear: 1980,
    courses: 'B.A, B.Sc, B.Com, M.A, M.Sc',
    contact: '04288-241234',
    feeRange: '₹1,000 - ₹5,000 per year',
    accreditation: 'Periyar University Affiliated',
    address: 'Kumarapalayam',
  },
  {
    id: 'govt_college_education',
    name: 'Government College of Education',
    type: 'government',
    category: 'education',
    establishedYear: 1975,
    courses: 'B.Ed, M.Ed',
    contact: '04288-242345',
    feeRange: '₹2,000 - ₹8,000 per year',
    accreditation: 'NCTE Approved',
    address: 'Komarapalayam',
  },
  {
    id: 'govt_medical_college_namakkal',
    name: 'Government Medical College & Hospital, Namakkal',
    type: 'government',
    category: 'medical',
    establishedYear: 2021,
    courses: 'MBBS',
    contact: '04286-250100',
    feeRange: '₹15,000 - ₹25,000 per year',
    accreditation: 'NMC Approved',
    address: 'Siluvampatti, Namakkal',
    facilities: ['Hospital', 'Library', 'Hostel', 'Labs'],
  },
  {
    id: 'govt_law_college_namakkal',
    name: 'Government Law College, Namakkal',
    type: 'government',
    category: 'law',
    establishedYear: 2019,
    courses: 'B.A. LL.B (5 Year), LL.B (3 Year)',
    contact: '04286-250200',
    feeRange: '₹2,000 - ₹10,000 per year',
    accreditation: 'Bar Council of India Approved',
    address: 'Thillaipuram, Namakkal',
  },
  {
    id: 'govt_college_engineering_namakkal',
    name: 'Government College of Engineering (IRTT)',
    type: 'government',
    category: 'engineering',
    naacGrade: 'A',
    establishedYear: 1956,
    courses: 'B.E (CSE, ECE, EEE, Mech, Civil, IT), M.E',
    contact: '04288-226700',
    website: 'www.gcetly.ac.in',
    feeRange: '₹5,000 - ₹15,000 per year',
    accreditation: 'Anna University Affiliated, NBA Accredited',
    address: 'Tiruchengode, Namakkal',
    placementStats: '85% placement rate',
    facilities: ['Library', 'Hostel', 'Labs', 'Sports Complex', 'Workshops'],
  },

  // Government-Aided Colleges
  {
    id: 'jkk_nataraja_arts_science',
    name: 'J.K.K. Nataraja College of Arts and Science',
    type: 'government-aided',
    category: 'arts_science',
    naacGrade: 'B++',
    establishedYear: 1971,
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com, M.Phil',
    contact: '04286-220500',
    website: 'www.jkknataraja.ac.in',
    feeRange: '₹5,000 - ₹25,000 per year',
    accreditation: 'Periyar University Affiliated',
    isJKKN: true,
    placementStats: '75% placement rate',
    facilities: ['Library', 'Computer Lab', 'Hostel', 'Playground'],
  },
  {
    id: 'jkk_nataraja_education',
    name: 'J.K.K. Nataraja College of Education',
    type: 'government-aided',
    category: 'education',
    establishedYear: 1982,
    courses: 'B.Ed, M.Ed',
    contact: '04286-220550',
    feeRange: '₹8,000 - ₹30,000 per year',
    accreditation: 'NCTE Approved',
    isJKKN: true,
  },

  // KSR Group of Institutions (Private - Major Group)
  {
    id: 'ksr_college_tech',
    name: 'K.S. Rangasamy College of Technology',
    type: 'autonomous',
    category: 'engineering',
    naacGrade: 'A+',
    establishedYear: 1994,
    courses: 'B.E/B.Tech (CSE, IT, ECE, EEE, Mech, Civil, AI&ML), M.E/M.Tech, MBA',
    contact: '04288-274741',
    website: 'www.ksrct.ac.in',
    feeRange: '₹70,000 - ₹1,50,000 per year',
    accreditation: 'NBA Accredited, AICTE Approved',
    placementStats: '90% placement rate',
    address: 'Tiruchengode',
  },
  {
    id: 'ksr_arts_science',
    name: 'K.S.R. College of Arts and Science',
    type: 'autonomous',
    category: 'arts_science',
    naacGrade: 'A',
    establishedYear: 1995,
    courses: 'B.Sc, B.Com, BCA, BBA, M.Sc, M.Com, MBA',
    contact: '04288-274742',
    website: 'www.ksrcas.edu',
    feeRange: '₹30,000 - ₹80,000 per year',
    accreditation: 'Periyar University Affiliated',
    placementStats: '82% placement rate',
    address: 'Tiruchengode',
  },
  {
    id: 'ksr_dental',
    name: 'K.S.R. Institute of Dental Science and Research',
    type: 'private',
    category: 'dental',
    naacGrade: 'A',
    establishedYear: 2006,
    courses: 'BDS, MDS',
    contact: '04288-274750',
    website: 'www.ksridsr.edu.in',
    feeRange: '₹3,50,000 - ₹9,00,000 per year',
    accreditation: 'DCI Approved',
    address: 'Tiruchengode',
  },
  {
    id: 'ksr_engineering_tech',
    name: 'KSR Institute for Engineering and Technology',
    type: 'private',
    category: 'engineering',
    naacGrade: 'A',
    establishedYear: 2008,
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech), M.E/M.Tech',
    contact: '04288-274760',
    website: 'www.ksriet.ac.in',
    feeRange: '₹65,000 - ₹1,20,000 per year',
    accreditation: 'AICTE Approved',
    address: 'Tiruchengode',
  },

  // Paavai Group of Institutions (Private - Major Group)
  {
    id: 'paavai_engineering',
    name: 'Paavai Engineering College',
    type: 'private',
    category: 'engineering',
    naacGrade: 'A',
    establishedYear: 2001,
    courses: 'B.E/B.Tech (CSE, IT, ECE, EEE, Mech, Civil), M.E/M.Tech',
    contact: '04286-275566',
    website: 'www.paavai.edu.in',
    feeRange: '₹55,000 - ₹1,20,000 per year',
    accreditation: 'AICTE Approved, NBA Accredited',
    placementStats: '85% placement rate',
    address: 'Namakkal',
  },
  {
    id: 'paavai_college_engineering',
    name: 'Paavai College of Engineering',
    type: 'private',
    category: 'engineering',
    establishedYear: 2007,
    courses: 'B.E/B.Tech (CSE, ECE, Mech, Civil)',
    contact: '04286-275567',
    website: 'www.pce.paavai.edu.in',
    feeRange: '₹50,000 - ₹1,00,000 per year',
    accreditation: 'AICTE Approved',
    address: 'Namakkal',
  },
  {
    id: 'pavai_college_tech',
    name: 'Pavai College of Technology',
    type: 'private',
    category: 'engineering',
    establishedYear: 2004,
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech)',
    contact: '04286-275568',
    feeRange: '₹50,000 - ₹1,00,000 per year',
    accreditation: 'AICTE Approved',
    address: 'Namakkal',
  },
  {
    id: 'paavai_polytechnic',
    name: 'Paavai Polytechnic College',
    type: 'private',
    category: 'polytechnic',
    establishedYear: 2000,
    courses: 'Diploma in Mech, Civil, ECE, EEE, CSE',
    contact: '04286-275570',
    feeRange: '₹20,000 - ₹40,000 per year',
    accreditation: 'AICTE Approved',
    address: 'Namakkal',
  },

  // Mahendra Group (Private)
  {
    id: 'mahendra_engineering',
    name: 'Mahendra Engineering College',
    type: 'private',
    category: 'engineering',
    naacGrade: 'B+',
    establishedYear: 2001,
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil), M.E/M.Tech',
    contact: '04286-277788',
    website: 'www.mahendraengg.com',
    feeRange: '₹50,000 - ₹1,00,000 per year',
    accreditation: 'AICTE Approved',
    address: 'Mallasamudram',
  },
  {
    id: 'mahendra_arts_science',
    name: 'Mahendra College of Arts and Science',
    type: 'private',
    category: 'arts_science',
    establishedYear: 2005,
    courses: 'B.Sc, B.Com, BCA, BBA, M.Sc, M.Com',
    contact: '04286-277790',
    feeRange: '₹25,000 - ₹60,000 per year',
    address: 'Mallasamudram',
  },
  {
    id: 'mahendra_polytechnic',
    name: 'Mahendra Polytechnic College',
    type: 'private',
    category: 'polytechnic',
    establishedYear: 2002,
    courses: 'Diploma in Mech, Civil, ECE, EEE',
    contact: '04286-277792',
    feeRange: '₹18,000 - ₹35,000 per year',
    accreditation: 'AICTE Approved',
    address: 'Mallasamudram',
  },

  // Muthayammal Group (Private)
  {
    id: 'muthayammal_engineering',
    name: 'Muthayammal Engineering College',
    type: 'private',
    category: 'engineering',
    naacGrade: 'B+',
    establishedYear: 1999,
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil), M.E/M.Tech',
    contact: '04287-241199',
    website: 'www.muthayammal.edu.in',
    feeRange: '₹55,000 - ₹1,10,000 per year',
    accreditation: 'AICTE Approved',
    address: 'Rasipuram',
  },
  {
    id: 'muthayammal_arts_science',
    name: 'Muthayammal College of Arts and Science',
    type: 'private',
    category: 'arts_science',
    establishedYear: 2001,
    courses: 'B.Sc, B.Com, BCA, BBA, M.Sc, M.Com',
    contact: '04287-241200',
    feeRange: '₹20,000 - ₹50,000 per year',
    address: 'Rasipuram',
  },
  {
    id: 'muthayammal_polytechnic',
    name: 'Muthayammal Polytechnic College',
    type: 'private',
    category: 'polytechnic',
    establishedYear: 1998,
    courses: 'Diploma in Mech, Civil, ECE, EEE, CSE',
    contact: '04287-241202',
    feeRange: '₹18,000 - ₹35,000 per year',
    accreditation: 'AICTE Approved',
    address: 'Rasipuram',
  },

  // Other Notable Colleges
  {
    id: 'vetri_vinayaha_engineering',
    name: 'Vetri Vinayaha College of Engineering and Technology',
    type: 'private',
    category: 'engineering',
    establishedYear: 2008,
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil)',
    contact: '04286-266677',
    feeRange: '₹45,000 - ₹90,000 per year',
    accreditation: 'AICTE Approved',
    address: 'Namakkal',
  },
  {
    id: 'king_college_tech',
    name: 'King College of Technology',
    type: 'private',
    category: 'engineering',
    establishedYear: 2009,
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech)',
    contact: '04286-255566',
    feeRange: '₹45,000 - ₹85,000 per year',
    accreditation: 'AICTE Approved',
    address: 'Nallur, Namakkal',
  },
  {
    id: 'kandaswami_kandars',
    name: "Kandaswami Kandar's College",
    type: 'government-aided',
    category: 'arts_science',
    naacGrade: 'B+',
    establishedYear: 1965,
    courses: 'B.A, B.Sc, B.Com, BCA, M.A, M.Sc, M.Com',
    contact: '04282-244455',
    feeRange: '₹5,000 - ₹25,000 per year',
    accreditation: 'Periyar University Affiliated',
    address: 'Paramathi Velur',
  },
  {
    id: 'vivekanandha_nursing',
    name: 'Vivekanandha College of Nursing',
    type: 'private',
    category: 'nursing',
    establishedYear: 2005,
    courses: 'B.Sc Nursing, M.Sc Nursing, GNM',
    contact: '04286-266688',
    feeRange: '₹40,000 - ₹1,00,000 per year',
    accreditation: 'INC Approved',
    address: 'Namakkal',
  },
  {
    id: 'annai_jkk_nursing',
    name: 'Annai J.K.K. Sampoorani Ammal College of Nursing',
    type: 'private',
    category: 'nursing',
    establishedYear: 2000,
    courses: 'B.Sc Nursing, M.Sc Nursing, GNM, ANM',
    contact: '04286-220780',
    feeRange: '₹35,000 - ₹90,000 per year',
    accreditation: 'INC Approved',
    isJKKN: true,
    address: 'Komarapalayam',
  },
  {
    id: 'pgp_nursing',
    name: 'P.G.P. College of Nursing and Research',
    type: 'private',
    category: 'nursing',
    establishedYear: 2003,
    courses: 'B.Sc Nursing, M.Sc Nursing, GNM',
    contact: '04286-244499',
    feeRange: '₹38,000 - ₹95,000 per year',
    accreditation: 'INC Approved',
    address: 'Namakkal',
  },
  {
    id: 'dhanvantri_nursing',
    name: 'Dhanvantri College of Nursing',
    type: 'private',
    category: 'nursing',
    establishedYear: 2006,
    courses: 'B.Sc Nursing, GNM',
    contact: '04286-244500',
    feeRange: '₹35,000 - ₹85,000 per year',
    accreditation: 'INC Approved',
    address: 'Namakkal',
  },
  {
    id: 'pgp_polytechnic',
    name: 'P.G.P. Polytechnic College',
    type: 'private',
    category: 'polytechnic',
    establishedYear: 1995,
    courses: 'Diploma in Mech, Civil, ECE, EEE, CSE',
    contact: '04286-244501',
    feeRange: '₹18,000 - ₹35,000 per year',
    accreditation: 'AICTE Approved',
    address: 'Namakkal',
  },
  {
    id: 'bharath_polytechnic',
    name: 'Bharath Polytechnic College',
    type: 'private',
    category: 'polytechnic',
    establishedYear: 1998,
    courses: 'Diploma in Mech, Civil, ECE, EEE',
    contact: '04286-244502',
    feeRange: '₹15,000 - ₹30,000 per year',
    accreditation: 'AICTE Approved',
    address: 'Namakkal',
  },
  {
    id: 'excel_polytechnic',
    name: 'Excel Polytechnic College',
    type: 'private',
    category: 'polytechnic',
    establishedYear: 2000,
    courses: 'Diploma in Mech, Civil, ECE, EEE, CSE',
    contact: '04286-244503',
    feeRange: '₹16,000 - ₹32,000 per year',
    accreditation: 'AICTE Approved',
    address: 'Namakkal',
  },
  {
    id: 'srg_polytechnic',
    name: 'S.R.G. Polytechnic College',
    type: 'private',
    category: 'polytechnic',
    establishedYear: 2001,
    courses: 'Diploma in Mech, Civil, ECE, EEE',
    contact: '04286-244504',
    feeRange: '₹15,000 - ₹30,000 per year',
    accreditation: 'AICTE Approved',
    address: 'Namakkal',
  },
  {
    id: 'raasi_polytechnic',
    name: 'Raasi Polytechnic College',
    type: 'private',
    category: 'polytechnic',
    establishedYear: 2002,
    courses: 'Diploma in Mech, Civil, ECE, EEE',
    contact: '04286-244505',
    feeRange: '₹14,000 - ₹28,000 per year',
    accreditation: 'AICTE Approved',
    address: 'Namakkal',
  },
  {
    id: 'anbu_arts_science',
    name: 'Anbu Arts and Science College',
    type: 'private',
    category: 'arts_science',
    establishedYear: 2005,
    courses: 'B.Sc, B.Com, BCA, BBA',
    contact: '04286-244506',
    feeRange: '₹18,000 - ₹40,000 per year',
    address: 'Namakkal',
  },
  {
    id: 'kavithas_arts_science',
    name: "Kavitha's College of Arts and Science",
    type: 'private',
    category: 'arts_science',
    establishedYear: 2008,
    courses: 'B.Sc, B.Com, BCA, BBA',
    contact: '04286-244507',
    feeRange: '₹18,000 - ₹42,000 per year',
    address: 'Namakkal',
  },

  // ============ SALEM DISTRICT COLLEGES (2024-2025) ============
  
  // Government Arts & Science Colleges - Salem
  {
    id: 'govt_arts_college_salem',
    name: 'Government Arts College (Autonomous)',
    type: 'government',
    category: 'arts_science',
    naacGrade: 'A',
    establishedYear: 1857,
    courses: 'B.A, B.Sc, B.Com, M.A, M.Sc, M.Com, M.Phil, Ph.D',
    contact: '0427-2311677',
    feeRange: '₹1,000 - ₹5,000 per year',
    accreditation: 'Periyar University Affiliated, Autonomous',
    address: 'Salem-7 (Near Cherry Road)',
    facilities: ['Library', 'Labs', 'Hostel', 'Sports Complex'],
  },
  {
    id: 'govt_arts_college_women_salem',
    name: 'Government Arts College for Women',
    type: 'government',
    category: 'arts_science',
    naacGrade: 'B++',
    establishedYear: 1965,
    courses: 'B.A, B.Sc, B.Com, BCA, M.A, M.Sc',
    contact: '0427-2312456',
    feeRange: '₹1,000 - ₹5,000 per year',
    accreditation: 'Periyar University Affiliated',
    address: 'Salem-8 (Hasthampatti)',
  },
  {
    id: 'govt_arts_science_mettur',
    name: 'Government Arts and Science College, Mettur Dam',
    type: 'government',
    category: 'arts_science',
    establishedYear: 2012,
    courses: 'B.A, B.Sc, B.Com',
    contact: '04298-222100',
    feeRange: '₹1,000 - ₹5,000 per year',
    accreditation: 'Periyar University Affiliated',
    address: 'Mettur Dam, Salem',
  },
  {
    id: 'govt_arts_science_edappadi',
    name: 'Government Arts and Science College, Edappadi',
    type: 'government',
    category: 'arts_science',
    establishedYear: 2013,
    courses: 'B.A, B.Sc, B.Com',
    contact: '04288-223100',
    feeRange: '₹1,000 - ₹5,000 per year',
    accreditation: 'Periyar University Affiliated',
    address: 'Edappadi, Salem',
  },
  {
    id: 'arignar_anna_govt_arts_attur',
    name: 'Arignar Anna Government Arts College',
    type: 'government',
    category: 'arts_science',
    naacGrade: 'B+',
    establishedYear: 1971,
    courses: 'B.A, B.Sc, B.Com, M.A, M.Sc',
    contact: '04282-241234',
    feeRange: '₹1,000 - ₹5,000 per year',
    accreditation: 'Periyar University Affiliated',
    address: 'Vadachennimalai, Attur, Salem',
  },
  
  // Government Engineering College - Salem
  {
    id: 'gce_salem',
    name: 'Government College of Engineering (GCE), Salem',
    type: 'government',
    category: 'engineering',
    naacGrade: 'A',
    establishedYear: 1966,
    courses: 'B.E (CSE, ECE, EEE, Mech, Civil), M.E',
    contact: '0427-2311899',
    website: 'www.gcesalem.edu.in',
    feeRange: '₹5,000 - ₹15,000 per year',
    accreditation: 'Anna University Affiliated, NBA Accredited',
    address: 'Omalur Main Road, Salem',
    placementStats: '85% placement rate',
    facilities: ['Library', 'Hostels', 'Labs', 'Sports Complex', 'Workshops'],
  },
  
  // Government Medical College - Salem
  {
    id: 'govt_medical_college_salem',
    name: 'Government Mohan Kumaramangalam Medical College',
    type: 'government',
    category: 'medical',
    naacGrade: 'A',
    establishedYear: 1985,
    courses: 'MBBS, MD, MS, DM, MCh',
    contact: '0427-2450038',
    feeRange: '₹15,000 - ₹50,000 per year',
    accreditation: 'NMC Approved',
    address: 'Steel Plant Road, Salem',
    facilities: ['Hospital', 'Library', 'Hostel', 'Labs', 'Research Center'],
    placementStats: '100% placement rate',
  },
  
  // Government Law College - Salem
  {
    id: 'govt_law_college_salem',
    name: 'Government Law College, Salem',
    type: 'government',
    category: 'law',
    establishedYear: 1980,
    courses: 'B.A. LL.B (5 Year), LL.B (3 Year), LL.M',
    contact: '0427-2313567',
    feeRange: '₹2,000 - ₹10,000 per year',
    accreditation: 'Bar Council of India Approved',
    address: 'Maniyanur, Salem',
  },
  
  // Government Polytechnic - Salem
  {
    id: 'govt_polytechnic_salem',
    name: 'Government Polytechnic College, Salem',
    type: 'government',
    category: 'polytechnic',
    establishedYear: 1957,
    courses: 'Diploma in Mech, Civil, ECE, EEE, CSE, Automobile',
    contact: '0427-2313456',
    feeRange: '₹3,000 - ₹8,000 per year',
    accreditation: 'AICTE Approved',
    address: 'Salem',
  },
  {
    id: 'thiagarajar_polytechnic',
    name: 'Thiagarajar Polytechnic College',
    type: 'government-aided',
    category: 'polytechnic',
    naacGrade: 'A',
    establishedYear: 1957,
    courses: 'Diploma in Mech, Civil, ECE, EEE, CSE, Automobile',
    contact: '0427-2314567',
    feeRange: '₹5,000 - ₹15,000 per year',
    accreditation: 'AICTE Approved',
    address: 'Salem',
    facilities: ['Library', 'Workshops', 'Hostel', 'Labs'],
  },
  
  // Periyar University
  {
    id: 'periyar_university',
    name: 'Periyar University',
    type: 'government',
    category: 'arts_science',
    naacGrade: 'A++',
    establishedYear: 1997,
    courses: 'B.Sc, M.Sc, M.Phil, Ph.D (Various Disciplines)',
    contact: '0427-2345766',
    website: 'www.periyaruniversity.ac.in',
    feeRange: '₹5,000 - ₹30,000 per year',
    accreditation: 'NAAC A++ Accredited',
    address: 'Salem',
    facilities: ['Central Library', 'Research Centers', 'Hostels', 'Sports Complex'],
  },
  
  // Government-Aided Arts & Science Colleges - Salem
  {
    id: 'sri_sarada_college_women',
    name: 'Sri Sarada College for Women',
    type: 'government-aided',
    category: 'arts_science',
    naacGrade: 'A',
    establishedYear: 1942,
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com, M.Phil',
    contact: '0427-2447788',
    website: 'www.srisaradacollege.edu.in',
    feeRange: '₹5,000 - ₹25,000 per year',
    accreditation: 'Periyar University Affiliated, Autonomous',
    address: 'Fairlands, Salem',
    placementStats: '80% placement rate',
    facilities: ['Library', 'Labs', 'Hostel', 'Sports Ground'],
  },
  {
    id: 'salem_sowdeswari_college',
    name: 'Salem Sowdeswari College',
    type: 'government-aided',
    category: 'arts_science',
    naacGrade: 'B++',
    establishedYear: 1968,
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com',
    contact: '0427-2448899',
    feeRange: '₹5,000 - ₹25,000 per year',
    accreditation: 'Periyar University Affiliated',
    address: 'Kondalampatti, Salem',
    placementStats: '75% placement rate',
  },
  
  // Private Colleges - Salem
  {
    id: 'vinayaka_mission_medical',
    name: 'Vinayaka Mission Medical College & Hospital',
    type: 'private',
    category: 'medical',
    naacGrade: 'A',
    establishedYear: 1994,
    courses: 'MBBS, MD, MS',
    contact: '0427-3987000',
    website: 'www.vmmch.com',
    feeRange: '₹10,00,000 - ₹20,00,000 per year',
    accreditation: 'NMC Approved',
    address: 'Karur Road, Salem',
    placementStats: '95% placement rate',
  },
  {
    id: 'sona_college_tech',
    name: 'Sona College of Technology',
    type: 'autonomous',
    category: 'engineering',
    naacGrade: 'A+',
    establishedYear: 1997,
    courses: 'B.E/B.Tech (CSE, IT, ECE, EEE, Mech, Civil, AI&ML), M.E/M.Tech, MBA',
    contact: '0427-4099799',
    website: 'www.sonatech.ac.in',
    feeRange: '₹80,000 - ₹1,50,000 per year',
    accreditation: 'NBA Accredited, AICTE Approved (Self-Financing)',
    address: 'Salem',
    placementStats: '92% placement rate',
    facilities: ['Library', 'Labs', 'Hostel', 'Sports Complex', 'Incubation Center'],
  },
  {
    id: 'central_law_college_salem',
    name: 'Central Law College',
    type: 'private',
    category: 'law',
    establishedYear: 1988,
    courses: 'B.A. LL.B (5 Year), LL.B (3 Year), LL.M',
    contact: '0427-2315678',
    feeRange: '₹25,000 - ₹60,000 per year',
    accreditation: 'Dr. Ambedkar Law University Affiliated',
    address: 'Salem',
  },
  {
    id: 'salem_inst_agricultural',
    name: 'Salem Institute of Agricultural Sciences',
    type: 'private',
    category: 'agricultural',
    establishedYear: 2010,
    courses: 'B.Sc Agriculture',
    contact: '04282-245678',
    feeRange: '₹50,000 - ₹1,00,000 per year',
    accreditation: 'TNAU Affiliated',
    address: 'Attur, Salem',
  },
  {
    id: 'adhiparasakthi_dental',
    name: 'Adhiparasakthi Dental College & Hospital',
    type: 'private',
    category: 'dental',
    naacGrade: 'A',
    establishedYear: 2000,
    courses: 'BDS, MDS',
    contact: '04175-240188',
    website: 'www.apdch.edu.in',
    feeRange: '₹4,00,000 - ₹10,00,000 per year',
    accreditation: 'DCI Approved',
    address: 'Melmaruvathur, Salem',
  },
  {
    id: 'sengunthar_engineering',
    name: 'Sengunthar Engineering College',
    type: 'private',
    category: 'engineering',
    establishedYear: 2001,
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil)',
    contact: '04282-266622',
    feeRange: '₹50,000 - ₹1,00,000 per year',
    accreditation: 'AICTE Approved',
    address: 'Tiruchengode, Salem',
  },
  
  // ============ ERODE DISTRICT COLLEGES (2024-2025) ============
  
  // Government Arts & Science Colleges - Erode
  {
    id: 'govt_arts_science_sathyamangalam',
    name: 'Government Arts and Science College, Sathyamangalam',
    type: 'government',
    category: 'arts_science',
    establishedYear: 2013,
    courses: 'B.A, B.Sc, B.Com',
    contact: '04295-220100',
    feeRange: '₹1,000 - ₹5,000 per year',
    accreditation: 'Bharathiar University Affiliated',
    address: 'Sathyamangalam, Erode',
  },
  {
    id: 'govt_arts_science_thittamalai',
    name: 'Government Arts and Science College, Thittamalai',
    type: 'government',
    category: 'arts_science',
    establishedYear: 2015,
    courses: 'B.A, B.Sc, B.Com',
    contact: '04295-221100',
    feeRange: '₹1,000 - ₹5,000 per year',
    accreditation: 'Bharathiar University Affiliated',
    address: 'Thittamalai, Nambiyur, Erode',
  },
  {
    id: 'govt_arts_science_modakkurichi',
    name: 'Government Arts and Science College, Modakkurichi',
    type: 'government',
    category: 'arts_science',
    establishedYear: 2014,
    courses: 'B.A, B.Sc, B.Com',
    contact: '04294-222100',
    feeRange: '₹1,000 - ₹5,000 per year',
    accreditation: 'Bharathiar University Affiliated',
    address: 'Modakkurichi, Erode',
  },
  {
    id: 'govt_arts_science_anthiyur',
    name: 'Government Arts and Science College, Anthiyur',
    type: 'government',
    category: 'arts_science',
    establishedYear: 2014,
    courses: 'B.A, B.Sc, B.Com',
    contact: '04256-223100',
    feeRange: '₹1,000 - ₹5,000 per year',
    accreditation: 'Bharathiar University Affiliated',
    address: 'Anthiyur, Erode',
  },
  
  // Government Engineering College - Erode
  {
    id: 'gce_erode',
    name: 'Government College of Engineering (GCE), Erode',
    type: 'government',
    category: 'engineering',
    naacGrade: 'A',
    establishedYear: 1966,
    courses: 'B.E (CSE, ECE, EEE, Mech, Civil, Automobile), M.E',
    contact: '0424-2280111',
    website: 'www.gceerode.ac.in',
    feeRange: '₹5,000 - ₹15,000 per year',
    accreditation: 'Anna University Affiliated, NBA Accredited',
    address: 'Chithode, Erode',
    placementStats: '85% placement rate',
    facilities: ['Library', 'Hostels', 'Labs', 'Sports Complex', 'Workshops'],
  },
  
  // Government Medical College - Erode
  {
    id: 'govt_erode_medical_college',
    name: 'Government Erode Medical College',
    type: 'government',
    category: 'medical',
    naacGrade: 'A',
    establishedYear: 2015,
    courses: 'MBBS, MD, MS',
    contact: '04294-220100',
    feeRange: '₹15,000 - ₹50,000 per year',
    accreditation: 'NMC Approved',
    address: 'Perundurai, Erode',
    facilities: ['Hospital', 'Library', 'Hostel', 'Labs'],
  },
  
  // Government Polytechnic - Erode
  {
    id: 'govt_polytechnic_erode',
    name: 'Government Polytechnic College, Erode',
    type: 'government',
    category: 'polytechnic',
    establishedYear: 1962,
    courses: 'Diploma in Mech, Civil, ECE, EEE, CSE',
    contact: '0424-2214567',
    feeRange: '₹3,000 - ₹8,000 per year',
    accreditation: 'AICTE Approved',
    address: 'Erode',
  },
  
  // Government-Aided Arts & Science Colleges - Erode
  {
    id: 'chikkaiah_naicker_college',
    name: 'Chikkaiah Naicker College',
    type: 'government-aided',
    category: 'arts_science',
    naacGrade: 'A',
    establishedYear: 1946,
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com, M.Phil',
    contact: '0424-2225588',
    website: 'www.cnc.ac.in',
    feeRange: '₹5,000 - ₹25,000 per year',
    accreditation: 'Bharathiar University Affiliated',
    address: 'Erode City',
    placementStats: '75% placement rate',
    facilities: ['Library', 'Labs', 'Hostel', 'Sports Ground'],
  },
  {
    id: 'erode_arts_science_college',
    name: 'Erode Arts and Science College',
    type: 'government-aided',
    category: 'arts_science',
    naacGrade: 'A',
    establishedYear: 1965,
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com',
    contact: '0424-2226699',
    website: 'www.easc.ac.in',
    feeRange: '₹5,000 - ₹25,000 per year',
    accreditation: 'Bharathiar University Affiliated, Autonomous',
    address: 'Rangampalayam, Erode',
    placementStats: '78% placement rate',
  },
  {
    id: 'gobi_arts_science_college',
    name: 'Gobi Arts and Science College',
    type: 'government-aided',
    category: 'arts_science',
    naacGrade: 'A',
    establishedYear: 1968,
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com',
    contact: '04285-220555',
    website: 'www.gobiartsandscience.ac.in',
    feeRange: '₹5,000 - ₹25,000 per year',
    accreditation: 'Bharathiar University Affiliated, Autonomous',
    address: 'Gobichettipalayam, Erode',
    placementStats: '80% placement rate',
  },
  {
    id: 'vellalar_college_women',
    name: 'Vellalar College for Women',
    type: 'government-aided',
    category: 'arts_science',
    naacGrade: 'A',
    establishedYear: 1970,
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com',
    contact: '04294-228444',
    website: 'www.vfrmt.org',
    feeRange: '₹5,000 - ₹25,000 per year',
    accreditation: 'Bharathiar University Affiliated, Autonomous',
    address: 'Thindal, Erode',
    placementStats: '82% placement rate',
    facilities: ['Library', 'Labs', 'Hostel', 'Sports Complex'],
  },
  {
    id: 'sri_vasavi_college',
    name: 'Sri Vasavi College',
    type: 'government-aided',
    category: 'arts_science',
    naacGrade: 'B++',
    establishedYear: 1967,
    courses: 'B.A, B.Sc, B.Com, BCA, M.A, M.Sc, M.Com',
    contact: '0424-2225577',
    feeRange: '₹5,000 - ₹25,000 per year',
    accreditation: 'Bharathiar University Affiliated',
    address: 'Erode',
  },
  {
    id: 'pkr_arts_college_women',
    name: 'P.K.R. Arts College for Women',
    type: 'government-aided',
    category: 'arts_science',
    naacGrade: 'B+',
    establishedYear: 1972,
    courses: 'B.A, B.Sc, B.Com, BCA',
    contact: '04285-221566',
    feeRange: '₹5,000 - ₹20,000 per year',
    accreditation: 'Bharathiar University Affiliated',
    address: 'Gobichettipalayam, Erode',
  },
  
  // Private Law College - Erode
  {
    id: 'erode_college_law',
    name: 'Erode College of Law',
    type: 'private',
    category: 'law',
    establishedYear: 2005,
    courses: 'B.A. LL.B (5 Year), LL.B (3 Year)',
    contact: '0424-2227788',
    feeRange: '₹30,000 - ₹60,000 per year',
    accreditation: 'Dr. Ambedkar Law University Affiliated',
    address: 'Erode',
  },
  
  // Agricultural Colleges - Erode
  {
    id: 'kumaraguru_agriculture',
    name: 'Kumaraguru Institute of Agriculture',
    type: 'private',
    category: 'agricultural',
    establishedYear: 2009,
    courses: 'B.Sc Agriculture, B.Sc Horticulture',
    contact: '0424-2228899',
    feeRange: '₹50,000 - ₹1,00,000 per year',
    accreditation: 'TNAU Affiliated',
    address: 'Erode',
  },
  {
    id: 'jkk_munirajah_agricultural',
    name: 'JKK Munirajah College of Agricultural Science',
    type: 'private',
    category: 'agricultural',
    establishedYear: 2008,
    courses: 'B.Sc Agriculture, M.Sc Agriculture',
    contact: '04285-220600',
    website: 'www.jkkmcas.ac.in',
    feeRange: '₹50,000 - ₹1,00,000 per year',
    accreditation: 'TNAU Affiliated',
    address: 'TN Palayam, Erode',
    isJKKN: true,
  },
  
  // Private Engineering Colleges - Erode
  {
    id: 'kongu_engineering',
    name: 'Kongu Engineering College',
    type: 'autonomous',
    category: 'engineering',
    naacGrade: 'A++',
    establishedYear: 1984,
    courses: 'B.E/B.Tech (CSE, IT, ECE, EEE, Mech, Civil, AI&DS), M.E/M.Tech, MBA, MCA',
    contact: '04294-226600',
    website: 'www.kongu.ac.in',
    feeRange: '₹75,000 - ₹1,50,000 per year',
    accreditation: 'NBA Accredited, AICTE Approved',
    address: 'Perundurai, Erode',
    placementStats: '95% placement rate',
    facilities: ['Central Library', 'Labs', 'Hostels', 'Sports Complex', 'Research Centers'],
  },
  {
    id: 'kongu_arts_science',
    name: 'Kongu Arts and Science College',
    type: 'autonomous',
    category: 'arts_science',
    naacGrade: 'A',
    establishedYear: 1994,
    courses: 'B.Sc, B.Com, BCA, BBA, M.Sc, M.Com, MBA',
    contact: '04294-226700',
    website: 'www.konguarts.ac.in',
    feeRange: '₹30,000 - ₹80,000 per year',
    address: 'Erode',
    placementStats: '85% placement rate',
  },
  {
    id: 'erode_sengunthar_engineering',
    name: 'Erode Sengunthar Engineering College',
    type: 'private',
    category: 'engineering',
    naacGrade: 'A',
    establishedYear: 1996,
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil), M.E/M.Tech',
    contact: '04285-226699',
    website: 'www.esec.ac.in',
    feeRange: '₹55,000 - ₹1,10,000 per year',
    accreditation: 'AICTE Approved, NBA Accredited',
    address: 'Thudupathi, Erode',
    placementStats: '88% placement rate',
  },
  {
    id: 'nandha_engineering',
    name: 'Nandha Engineering College',
    type: 'private',
    category: 'engineering',
    naacGrade: 'A',
    establishedYear: 2001,
    courses: 'B.E/B.Tech (CSE, IT, ECE, EEE, Mech), M.E/M.Tech',
    contact: '04294-225566',
    website: 'www.nandhaengg.org',
    feeRange: '₹60,000 - ₹1,20,000 per year',
    accreditation: 'AICTE Approved',
    address: 'Erode',
    placementStats: '85% placement rate',
  },
  {
    id: 'nandha_dental',
    name: 'Nandha Dental College & Hospital',
    type: 'private',
    category: 'dental',
    establishedYear: 2008,
    courses: 'BDS, MDS',
    contact: '04294-225577',
    feeRange: '₹3,50,000 - ₹8,00,000 per year',
    accreditation: 'DCI Approved',
    address: 'Erode',
  },
  {
    id: 'nandha_nursing',
    name: 'Nandha College of Nursing',
    type: 'private',
    category: 'nursing',
    establishedYear: 2005,
    courses: 'B.Sc Nursing, M.Sc Nursing, GNM',
    contact: '04294-225588',
    feeRange: '₹40,000 - ₹1,00,000 per year',
    accreditation: 'INC Approved',
    address: 'Erode',
  },
  {
    id: 'jkk_munirajah_college',
    name: 'J.K.K. Munirajah College of Arts and Science',
    type: 'private',
    category: 'arts_science',
    establishedYear: 1994,
    courses: 'B.Sc, B.Com, BCA, BBA, M.Sc, M.Com',
    contact: '04285-220500',
    feeRange: '₹20,000 - ₹50,000 per year',
    address: 'Gobichettipalayam, Erode',
    isJKKN: true,
  },
  
  // ============ COIMBATORE DISTRICT COLLEGES (2024-2025) ============
  
  // Government Arts & Science Colleges - Coimbatore
  {
    id: 'govt_arts_college_coimbatore',
    name: 'Government Arts College (Autonomous)',
    type: 'government',
    category: 'arts_science',
    naacGrade: 'A',
    establishedYear: 1952,
    courses: 'B.A, B.Sc, B.Com, M.A, M.Sc, M.Com, M.Phil, Ph.D',
    contact: '0422-2432211',
    feeRange: '₹1,000 - ₹5,000 per year',
    accreditation: 'Bharathiar University Affiliated, Autonomous',
    address: 'Race Course, Coimbatore',
    facilities: ['Library', 'Labs', 'Hostel', 'Sports Complex'],
  },
  {
    id: 'govt_arts_science_thondamuthur',
    name: 'Government Arts and Science College, Thondamuthur',
    type: 'government',
    category: 'arts_science',
    establishedYear: 2013,
    courses: 'B.A, B.Sc, B.Com',
    contact: '0422-2656100',
    feeRange: '₹1,000 - ₹5,000 per year',
    accreditation: 'Bharathiar University Affiliated',
    address: 'Thondamuthur, Coimbatore',
  },
  {
    id: 'govt_arts_science_puliyakulam',
    name: 'Government Arts and Science College, Puliyakulam',
    type: 'government',
    category: 'arts_science',
    establishedYear: 2014,
    courses: 'B.A, B.Sc, B.Com',
    contact: '0422-2657100',
    feeRange: '₹1,000 - ₹5,000 per year',
    accreditation: 'Bharathiar University Affiliated',
    address: 'Puliyakulam, Coimbatore',
  },
  {
    id: 'govt_arts_science_mettupalayam',
    name: 'Government Arts and Science College, Mettupalayam',
    type: 'government',
    category: 'arts_science',
    establishedYear: 2012,
    courses: 'B.A, B.Sc, B.Com',
    contact: '04254-222100',
    feeRange: '₹1,000 - ₹5,000 per year',
    accreditation: 'Bharathiar University Affiliated',
    address: 'Mettupalayam, Coimbatore',
  },
  {
    id: 'govt_arts_science_pollachi',
    name: 'Government Arts and Science College, Pollachi',
    type: 'government',
    category: 'arts_science',
    naacGrade: 'B+',
    establishedYear: 1974,
    courses: 'B.A, B.Sc, B.Com, M.A, M.Sc',
    contact: '04259-223100',
    feeRange: '₹1,000 - ₹5,000 per year',
    accreditation: 'Bharathiar University Affiliated',
    address: 'Pollachi, Coimbatore',
  },
  {
    id: 'govt_arts_science_valparai',
    name: 'Government Arts and Science College, Valparai',
    type: 'government',
    category: 'arts_science',
    establishedYear: 2015,
    courses: 'B.A, B.Sc, B.Com',
    contact: '04253-224100',
    feeRange: '₹1,000 - ₹5,000 per year',
    accreditation: 'Bharathiar University Affiliated',
    address: 'Valparai, Coimbatore',
  },
  
  // Government Engineering Colleges - Coimbatore
  {
    id: 'govt_college_tech_coimbatore',
    name: 'Government College of Technology (GCT)',
    type: 'government',
    category: 'engineering',
    naacGrade: 'A+',
    establishedYear: 1945,
    courses: 'B.E/B.Tech (CSE, IT, ECE, EEE, Mech, Civil, Production), M.E/M.Tech, Ph.D',
    contact: '0422-2432221',
    website: 'www.gct.ac.in',
    feeRange: '₹10,000 - ₹30,000 per year',
    accreditation: 'Anna University Affiliated, NBA Accredited',
    address: 'Thadagam Road, Coimbatore',
    placementStats: '95% placement rate',
    facilities: ['Library', 'Labs', 'Hostels', 'Sports Complex', 'Research Centers'],
  },
  {
    id: 'anna_university_cbe',
    name: 'Anna University Regional Campus, Coimbatore',
    type: 'government',
    category: 'engineering',
    naacGrade: 'A',
    establishedYear: 2010,
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil), M.E/M.Tech, MBA',
    contact: '0422-2455555',
    website: 'www.annauniv.edu.in',
    feeRange: '₹10,000 - ₹30,000 per year',
    accreditation: 'Anna University, NBA Accredited',
    address: 'Maruthamalai Road, Coimbatore',
    placementStats: '90% placement rate',
    facilities: ['Library', 'Labs', 'Hostels', 'Sports Complex'],
  },
  
  // Government Medical Colleges - Coimbatore
  {
    id: 'coimbatore_medical_college',
    name: 'Coimbatore Medical College & Hospital',
    type: 'government',
    category: 'medical',
    naacGrade: 'A+',
    establishedYear: 1966,
    courses: 'MBBS, MD, MS, DM, MCh, Diploma',
    contact: '0422-2301393',
    feeRange: '₹15,000 - ₹50,000 per year',
    accreditation: 'NMC Approved',
    address: 'Avinashi Road, Coimbatore',
    facilities: ['Hospital', 'Library', 'Hostel', 'Labs', 'Research Center'],
    placementStats: '100% placement rate',
  },
  {
    id: 'esic_medical_college_cbe',
    name: 'Government Medical College & ESIC Hospital',
    type: 'government',
    category: 'medical',
    naacGrade: 'A',
    establishedYear: 2015,
    courses: 'MBBS, MD, MS',
    contact: '0422-2302456',
    feeRange: '₹15,000 - ₹50,000 per year',
    accreditation: 'NMC Approved',
    address: 'Singanallur, Coimbatore',
    facilities: ['Hospital', 'Library', 'Hostel', 'Labs'],
  },
  
  // Government Law College - Coimbatore
  {
    id: 'govt_law_college_coimbatore',
    name: 'Government Law College, Coimbatore',
    type: 'government',
    category: 'law',
    naacGrade: 'B++',
    establishedYear: 1972,
    courses: 'B.A. LL.B (5 Year), LL.B (3 Year), LL.M',
    contact: '0422-2433456',
    feeRange: '₹2,000 - ₹10,000 per year',
    accreditation: 'Bar Council of India Approved',
    address: 'Maruthamalai Road, Coimbatore',
  },
  
  // Government Polytechnic - Coimbatore
  {
    id: 'govt_polytechnic_coimbatore',
    name: 'Government Polytechnic College, Coimbatore',
    type: 'government',
    category: 'polytechnic',
    establishedYear: 1954,
    courses: 'Diploma in Mech, Civil, ECE, EEE, CSE, Automobile',
    contact: '0422-2434567',
    feeRange: '₹3,000 - ₹8,000 per year',
    accreditation: 'AICTE Approved',
    address: 'Coimbatore',
  },
  
  // Agricultural University - Coimbatore
  {
    id: 'tnau_coimbatore',
    name: 'Tamil Nadu Agricultural University (TNAU)',
    type: 'government',
    category: 'agricultural',
    naacGrade: 'A++',
    establishedYear: 1971,
    courses: 'B.Sc Agriculture, B.Sc Horticulture, B.Tech Agricultural Engineering, M.Sc, Ph.D',
    contact: '0422-6611200',
    website: 'www.tnau.ac.in',
    feeRange: '₹10,000 - ₹50,000 per year',
    accreditation: 'ICAR Accredited',
    address: 'Lawley Road, Coimbatore',
    facilities: ['Research Farms', 'Library', 'Hostels', 'Labs', 'Botanical Garden'],
    placementStats: '90% placement rate',
  },
  
  // Bharathiar University
  {
    id: 'bharathiar_university',
    name: 'Bharathiar University',
    type: 'government',
    category: 'arts_science',
    naacGrade: 'A++',
    establishedYear: 1982,
    courses: 'B.Sc, M.Sc, M.Phil, Ph.D (Various Disciplines)',
    contact: '0422-2422222',
    website: 'www.b-u.ac.in',
    feeRange: '₹5,000 - ₹30,000 per year',
    accreditation: 'NAAC A++ Accredited',
    address: 'Coimbatore',
    facilities: ['Central Library', 'Research Centers', 'Hostels', 'Sports Complex'],
  },
  
  // Government-Aided Arts & Science Colleges - Coimbatore
  {
    id: 'psg_arts_science',
    name: 'PSG College of Arts and Science',
    type: 'government-aided',
    category: 'arts_science',
    naacGrade: 'A++',
    establishedYear: 1947,
    courses: 'B.Sc, B.Com, BCA, BBA, M.Sc, M.Com, MBA, MCA',
    contact: '0422-4303300',
    website: 'www.psgcas.ac.in',
    feeRange: '₹5,000 - ₹35,000 per year (Aided), ₹35,000 - ₹90,000 (Self-Financing)',
    accreditation: 'Bharathiar University Affiliated, Autonomous',
    address: 'Civil Aerodrome Post, Coimbatore',
    placementStats: '90% placement rate',
    facilities: ['Library', 'Labs', 'Hostel', 'Sports Complex'],
  },
  {
    id: 'psgr_krishnammal_college',
    name: 'PSGR Krishnammal College for Women',
    type: 'government-aided',
    category: 'arts_science',
    naacGrade: 'A++',
    establishedYear: 1963,
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com, MBA',
    contact: '0422-4304500',
    website: 'www.psgrkcw.ac.in',
    feeRange: '₹5,000 - ₹30,000 per year (Aided), ₹30,000 - ₹80,000 (Self-Financing)',
    accreditation: 'Bharathiar University Affiliated, Autonomous',
    address: 'Peelamedu, Coimbatore',
    placementStats: '88% placement rate',
  },
  {
    id: 'kongunadu_arts_science',
    name: 'Kongunadu Arts and Science College',
    type: 'government-aided',
    category: 'arts_science',
    naacGrade: 'A',
    establishedYear: 1962,
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com',
    contact: '0422-2642095',
    website: 'www.kongunadu.ac.in',
    feeRange: '₹5,000 - ₹25,000 per year (Aided), ₹25,000 - ₹60,000 (Self-Financing)',
    accreditation: 'Bharathiar University Affiliated, Autonomous',
    address: 'GN Mills, Coimbatore',
    placementStats: '82% placement rate',
  },
  {
    id: 'srmv_college',
    name: 'Sri Ramakrishna Mission Vidyalaya (SRMV) College of Arts and Science',
    type: 'government-aided',
    category: 'arts_science',
    naacGrade: 'A',
    establishedYear: 1963,
    courses: 'B.A, B.Sc, B.Com, BCA, M.A, M.Sc, M.Com',
    contact: '0422-2692461',
    website: 'www.srmvcas.ac.in',
    feeRange: '₹5,000 - ₹25,000 per year (Aided), ₹25,000 - ₹55,000 (Self-Financing)',
    accreditation: 'Bharathiar University Affiliated',
    address: 'Periyanaickenpalayam, Coimbatore',
    placementStats: '78% placement rate',
  },
  {
    id: 'nirmala_college_women',
    name: 'Nirmala College for Women',
    type: 'government-aided',
    category: 'arts_science',
    naacGrade: 'A',
    establishedYear: 1948,
    courses: 'B.A, B.Sc, B.Com, BCA, M.A, M.Sc, M.Com',
    contact: '0422-2312456',
    website: 'www.nirmalacollege.ac.in',
    feeRange: '₹5,000 - ₹25,000 per year (Aided), ₹25,000 - ₹55,000 (Self-Financing)',
    accreditation: 'Bharathiar University Affiliated, Autonomous',
    address: 'Red Fields, Coimbatore',
    placementStats: '80% placement rate',
  },
  {
    id: 'cbm_college',
    name: 'CBM College',
    type: 'government-aided',
    category: 'arts_science',
    naacGrade: 'B++',
    establishedYear: 1969,
    courses: 'B.A, B.Sc, B.Com, BCA, M.A, M.Sc, M.Com',
    contact: '0422-2567890',
    feeRange: '₹5,000 - ₹25,000 per year (Aided), ₹25,000 - ₹50,000 (Self-Financing)',
    accreditation: 'Bharathiar University Affiliated',
    address: 'Kovaipudur, Coimbatore',
  },
  
  // Government-Aided Engineering Colleges - Coimbatore
  {
    id: 'psg_college_tech',
    name: 'PSG College of Technology',
    type: 'government-aided',
    category: 'engineering',
    naacGrade: 'A++',
    establishedYear: 1951,
    courses: 'B.E/B.Tech (CSE, IT, ECE, EEE, Mech, Civil, Robotics, AI&DS), M.E/M.Tech, MBA, MCA',
    contact: '0422-2572177',
    website: 'www.psgtech.edu',
    feeRange: '₹25,000 - ₹50,000 per year (Aided via TNEA), ₹80,000 - ₹2,00,000 (Self-Supporting)',
    accreditation: 'Anna University Affiliated, NBA Accredited, Autonomous',
    address: 'Peelamedu, Coimbatore',
    placementStats: '98% placement rate',
    facilities: ['Central Library', 'Labs', 'Hostels', 'Sports Complex', 'Innovation Hub'],
  },
  {
    id: 'coimbatore_institute_tech',
    name: 'Coimbatore Institute of Technology (CIT)',
    type: 'government-aided',
    category: 'engineering',
    naacGrade: 'A',
    establishedYear: 1956,
    courses: 'B.E/B.Tech (CSE, IT, ECE, EEE, Mech, Civil), M.E/M.Tech',
    contact: '0422-2574071',
    website: 'www.cit.edu.in',
    feeRange: '₹25,000 - ₹50,000 per year (Aided via TNEA), ₹50,000 - ₹1,00,000 (Self-Supporting)',
    accreditation: 'Anna University Affiliated, NBA Accredited',
    address: 'Avinashi Road, Coimbatore',
    placementStats: '92% placement rate',
    facilities: ['Library', 'Labs', 'Hostels', 'Sports Complex'],
  },
  
  // Private Colleges - Coimbatore
  {
    id: 'psg_medical',
    name: 'PSG Institute of Medical Sciences & Research',
    type: 'private',
    category: 'medical',
    naacGrade: 'A+',
    establishedYear: 1985,
    courses: 'MBBS, MD, MS, DM, MCh',
    contact: '0422-2570170',
    website: 'www.psgimsr.ac.in',
    feeRange: '₹15,00,000 - ₹25,00,000 per year',
    accreditation: 'NMC Approved',
    address: 'Coimbatore',
    placementStats: '100% placement rate',
    facilities: ['Super Specialty Hospital', 'Library', 'Hostel', 'Research Center'],
  },
  {
    id: 'amrita_vishwa_coimbatore',
    name: 'Amrita Vishwa Vidyapeetham, Coimbatore',
    type: 'private',
    category: 'engineering',
    naacGrade: 'A++',
    establishedYear: 1994,
    courses: 'B.Tech, M.Tech, MBA, MCA, Ph.D (Various Disciplines)',
    contact: '0422-2685000',
    website: 'www.amrita.edu',
    feeRange: '₹1,50,000 - ₹3,00,000 per year',
    accreditation: 'NAAC A++ Accredited, Deemed University',
    address: 'Coimbatore',
    placementStats: '95% placement rate',
    facilities: ['Central Library', 'Research Centers', 'Hostels', 'Sports Complex', 'Innovation Lab'],
  },
  {
    id: 'sri_krishna_arts_science',
    name: 'Sri Krishna Arts and Science College',
    type: 'autonomous',
    category: 'arts_science',
    naacGrade: 'A',
    establishedYear: 1997,
    courses: 'B.Sc, B.Com, BCA, BBA, M.Sc, M.Com, MBA',
    contact: '0422-2610117',
    website: 'www.skasc.ac.in',
    feeRange: '₹30,000 - ₹80,000 per year',
    address: 'Coimbatore',
    placementStats: '85% placement rate',
  },
  {
    id: 'karpagam_university',
    name: 'Karpagam Academy of Higher Education',
    type: 'private',
    category: 'engineering',
    naacGrade: 'A',
    establishedYear: 2008,
    courses: 'B.E/B.Tech, M.E/M.Tech, MBA, MCA, Ph.D',
    contact: '0422-6453777',
    website: 'www.kahedu.edu.in',
    feeRange: '₹70,000 - ₹1,50,000 per year',
    accreditation: 'Deemed University',
    address: 'Coimbatore',
    placementStats: '82% placement rate',
  },
  {
    id: 'kmch_medical',
    name: 'KMCH Institute of Health Sciences',
    type: 'private',
    category: 'medical',
    naacGrade: 'A',
    establishedYear: 2008,
    courses: 'MBBS, MD, MS, Nursing, Allied Health Sciences',
    contact: '0422-4323800',
    website: 'www.kmchihs.ac.in',
    feeRange: '₹12,00,000 - ₹22,00,000 per year',
    accreditation: 'NMC Approved',
    address: 'Coimbatore',
    facilities: ['Hospital', 'Library', 'Hostel', 'Labs'],
  },
  {
    id: 'sree_ramu_dental',
    name: 'Sri Ramakrishna Dental College & Hospital',
    type: 'private',
    category: 'dental',
    naacGrade: 'A',
    establishedYear: 2001,
    courses: 'BDS, MDS',
    contact: '0422-4500450',
    website: 'www.srdch.org',
    feeRange: '₹4,00,000 - ₹10,00,000 per year',
    accreditation: 'DCI Approved',
    address: 'Coimbatore',
  },
  {
    id: 'sns_college_tech',
    name: 'SNS College of Technology',
    type: 'autonomous',
    category: 'engineering',
    naacGrade: 'A',
    establishedYear: 1997,
    courses: 'B.E/B.Tech (CSE, IT, ECE, EEE, Mech, Civil, AI&ML), M.E/M.Tech',
    contact: '0422-2666264',
    website: 'www.snsct.org',
    feeRange: '₹65,000 - ₹1,30,000 per year',
    accreditation: 'AICTE Approved, NBA Accredited',
    address: 'Coimbatore',
    placementStats: '88% placement rate',
  },
  {
    id: 'hindusthan_college_tech',
    name: 'Hindusthan College of Engineering and Technology',
    type: 'private',
    category: 'engineering',
    establishedYear: 2000,
    courses: 'B.E/B.Tech (CSE, IT, ECE, EEE, Mech, Civil)',
    contact: '0422-2666555',
    feeRange: '₹55,000 - ₹1,10,000 per year',
    accreditation: 'AICTE Approved',
    address: 'Coimbatore',
    placementStats: '80% placement rate',
  },
  {
    id: 'rathinam_college',
    name: 'Rathinam College of Arts and Science',
    type: 'private',
    category: 'arts_science',
    establishedYear: 2000,
    courses: 'B.Sc, B.Com, BCA, BBA, M.Sc, M.Com',
    contact: '0422-2680011',
    feeRange: '₹25,000 - ₹60,000 per year',
    address: 'Coimbatore',
  },
  {
    id: 'avinashilingam_university',
    name: 'Avinashilingam Institute for Home Science and Higher Education for Women',
    type: 'private',
    category: 'arts_science',
    naacGrade: 'A++',
    establishedYear: 1957,
    courses: 'B.Sc, M.Sc, M.Phil, Ph.D (Home Science, Arts, Science)',
    contact: '0422-2440241',
    website: 'www.avinuty.ac.in',
    feeRange: '₹30,000 - ₹80,000 per year',
    accreditation: 'Deemed University',
    address: 'Coimbatore',
  },

  // ============ CHENNAI DISTRICT COLLEGES (2024-2025) ============
  
  // Government Arts & Science Colleges - Chennai
  {
    id: 'presidency_college_chennai',
    name: 'Presidency College (Autonomous)',
    type: 'government',
    category: 'arts_science',
    naacGrade: 'A++',
    establishedYear: 1840,
    courses: 'B.A, B.Sc, B.Com, M.A, M.Sc, M.Com, M.Phil, Ph.D',
    contact: '044-28544894',
    website: 'www.presidencychennai.ac.in',
    feeRange: '₹1,000 - ₹5,000 per year',
    accreditation: 'University of Madras Affiliated, Autonomous',
    address: 'Chepauk, Chennai',
    facilities: ['Historic Library', 'Labs', 'Hostel', 'Sports Complex'],
  },
  {
    id: 'govt_arts_college_nandanam',
    name: 'Government Arts College, Nandanam',
    type: 'government',
    category: 'arts_science',
    naacGrade: 'A',
    establishedYear: 1968,
    courses: 'B.A, B.Sc, B.Com, M.A, M.Sc, M.Com',
    contact: '044-24346711',
    feeRange: '₹1,000 - ₹5,000 per year',
    accreditation: 'University of Madras Affiliated',
    address: 'Nandanam, Chennai',
  },
  {
    id: 'queen_marys_college',
    name: "Queen Mary's College (Autonomous)",
    type: 'government',
    category: 'arts_science',
    naacGrade: 'A',
    establishedYear: 1914,
    courses: 'B.A, B.Sc, B.Com, BCA, M.A, M.Sc, M.Com, M.Phil',
    contact: '044-25362445',
    website: 'www.queenmaryscollege.edu.in',
    feeRange: '₹1,000 - ₹5,000 per year',
    accreditation: 'University of Madras Affiliated, Autonomous',
    address: 'Marina Campus, Chennai',
  },
  {
    id: 'stella_maris_college',
    name: 'Stella Maris College (Autonomous)',
    type: 'government-aided',
    category: 'arts_science',
    naacGrade: 'A++',
    establishedYear: 1947,
    courses: 'B.A, B.Sc, B.Com, BCA, BVA, M.A, M.Sc, M.Com, MBA',
    contact: '044-28111987',
    website: 'www.stellamariscollege.edu.in',
    feeRange: '₹5,000 - ₹30,000 per year (Aided), ₹30,000 - ₹80,000 (Self-Financing)',
    accreditation: 'University of Madras Affiliated, Autonomous',
    address: 'Cathedral Road, Chennai',
    placementStats: '85% placement rate',
  },
  {
    id: 'loyola_college_chennai',
    name: 'Loyola College (Autonomous)',
    type: 'government-aided',
    category: 'arts_science',
    naacGrade: 'A++',
    establishedYear: 1925,
    courses: 'B.A, B.Sc, B.Com, BCA, BVA, M.A, M.Sc, M.Com, MBA, M.Phil, Ph.D',
    contact: '044-28178200',
    website: 'www.loyolacollege.edu',
    feeRange: '₹5,000 - ₹30,000 per year (Aided), ₹30,000 - ₹1,00,000 (Self-Financing)',
    accreditation: 'University of Madras Affiliated, Autonomous',
    address: 'Nungambakkam, Chennai',
    placementStats: '90% placement rate',
    facilities: ['Library', 'Labs', 'Hostel', 'Sports Complex', 'Auditorium'],
  },
  {
    id: 'madras_christian_college',
    name: 'Madras Christian College (Autonomous)',
    type: 'government-aided',
    category: 'arts_science',
    naacGrade: 'A++',
    establishedYear: 1837,
    courses: 'B.A, B.Sc, B.Com, BCA, M.A, M.Sc, M.Com, MBA, M.Phil, Ph.D',
    contact: '044-22394455',
    website: 'www.mcc.edu.in',
    feeRange: '₹5,000 - ₹30,000 per year (Aided), ₹30,000 - ₹90,000 (Self-Financing)',
    accreditation: 'University of Madras Affiliated, Autonomous',
    address: 'Tambaram, Chennai',
    placementStats: '88% placement rate',
    facilities: ['Historic Campus', 'Library', 'Labs', 'Hostel', 'Sports Complex'],
  },
  {
    id: 'womens_christian_college',
    name: "Women's Christian College (Autonomous)",
    type: 'government-aided',
    category: 'arts_science',
    naacGrade: 'A+',
    establishedYear: 1915,
    courses: 'B.A, B.Sc, B.Com, BCA, M.A, M.Sc, M.Com',
    contact: '044-28279192',
    website: 'www.wcc.edu.in',
    feeRange: '₹5,000 - ₹25,000 per year (Aided), ₹25,000 - ₹70,000 (Self-Financing)',
    accreditation: 'University of Madras Affiliated, Autonomous',
    address: 'College Road, Chennai',
    placementStats: '82% placement rate',
  },
  {
    id: 'ethiraj_college_women',
    name: 'Ethiraj College for Women (Autonomous)',
    type: 'government-aided',
    category: 'arts_science',
    naacGrade: 'A+',
    establishedYear: 1948,
    courses: 'B.A, B.Sc, B.Com, BCA, M.A, M.Sc, M.Com, MBA',
    contact: '044-28279192',
    website: 'www.ethirajcollege.edu.in',
    feeRange: '₹5,000 - ₹25,000 per year (Aided), ₹25,000 - ₹75,000 (Self-Financing)',
    accreditation: 'University of Madras Affiliated, Autonomous',
    address: 'Egmore, Chennai',
    placementStats: '80% placement rate',
  },
  
  // Government Engineering Colleges - Chennai
  {
    id: 'college_engineering_guindy',
    name: 'College of Engineering, Guindy (CEG)',
    type: 'government',
    category: 'engineering',
    naacGrade: 'A++',
    establishedYear: 1794,
    courses: 'B.E/B.Tech (CSE, IT, ECE, EEE, Mech, Civil, Manufacturing, Geo-Informatics), M.E/M.Tech, Ph.D',
    contact: '044-22351723',
    website: 'www.annauniv.edu/ceg',
    feeRange: '₹10,000 - ₹30,000 per year',
    accreditation: 'Anna University, NBA Accredited',
    address: 'Guindy, Chennai',
    placementStats: '98% placement rate',
    facilities: ['Central Library', 'Labs', 'Hostels', 'Sports Complex', 'Research Centers'],
  },
  {
    id: 'mit_chromepet',
    name: 'Madras Institute of Technology (MIT)',
    type: 'government',
    category: 'engineering',
    naacGrade: 'A+',
    establishedYear: 1949,
    courses: 'B.E/B.Tech (ECE, EEE, Mech, Rubber & Plastics, Automobile), M.E/M.Tech, Ph.D',
    contact: '044-22516100',
    website: 'www.mitindia.edu',
    feeRange: '₹10,000 - ₹30,000 per year',
    accreditation: 'Anna University, NBA Accredited',
    address: 'Chromepet, Chennai',
    placementStats: '95% placement rate',
    facilities: ['Library', 'Labs', 'Hostels', 'Sports Complex'],
  },
  {
    id: 'alagappa_college_tech',
    name: 'Alagappa College of Technology (ACT)',
    type: 'government',
    category: 'engineering',
    naacGrade: 'A',
    establishedYear: 1944,
    courses: 'B.Tech (Chemical, Leather, Petroleum, Polymer), M.Tech, Ph.D',
    contact: '044-22351723',
    feeRange: '₹10,000 - ₹30,000 per year',
    accreditation: 'Anna University, NBA Accredited',
    address: 'Guindy, Chennai',
    placementStats: '90% placement rate',
  },
  {
    id: 'iit_madras',
    name: 'Indian Institute of Technology (IIT) Madras',
    type: 'government',
    category: 'engineering',
    naacGrade: 'A++',
    establishedYear: 1959,
    courses: 'B.Tech, M.Tech, MS, MBA, Ph.D (Various Disciplines)',
    contact: '044-22578000',
    website: 'www.iitm.ac.in',
    feeRange: '₹1,00,000 - ₹2,50,000 per year',
    accreditation: 'NIRF Rank 1',
    address: 'Adyar, Chennai',
    placementStats: '100% placement rate',
    facilities: ['Research Park', 'Library', 'Hostels', 'Sports Complex', 'Incubation Center'],
  },
  
  // Government Medical Colleges - Chennai
  {
    id: 'madras_medical_college',
    name: 'Madras Medical College & Hospital',
    type: 'government',
    category: 'medical',
    naacGrade: 'A++',
    establishedYear: 1835,
    courses: 'MBBS, MD, MS, DM, MCh, Diploma, Super Specialty',
    contact: '044-25305000',
    website: 'www.mmc.tn.gov.in',
    feeRange: '₹15,000 - ₹50,000 per year',
    accreditation: 'NMC Approved',
    address: 'Park Town, Chennai',
    facilities: ['Rajiv Gandhi Government General Hospital', 'Library', 'Hostel', 'Research Center'],
    placementStats: '100% placement rate',
  },
  {
    id: 'stanley_medical_college',
    name: 'Stanley Medical College & Hospital',
    type: 'government',
    category: 'medical',
    naacGrade: 'A+',
    establishedYear: 1938,
    courses: 'MBBS, MD, MS, DM, MCh',
    contact: '044-25281432',
    feeRange: '₹15,000 - ₹50,000 per year',
    accreditation: 'NMC Approved',
    address: 'Old Jail Road, Chennai',
    facilities: ['Hospital', 'Library', 'Hostel', 'Labs'],
  },
  {
    id: 'kilpauk_medical_college',
    name: 'Kilpauk Medical College & Hospital',
    type: 'government',
    category: 'medical',
    naacGrade: 'A',
    establishedYear: 1960,
    courses: 'MBBS, MD, MS',
    contact: '044-26441931',
    feeRange: '₹15,000 - ₹50,000 per year',
    accreditation: 'NMC Approved',
    address: 'Kilpauk, Chennai',
  },
  
  // Government Law College - Chennai
  {
    id: 'dr_ambedkar_law_university',
    name: 'Dr. Ambedkar Government Law College',
    type: 'government',
    category: 'law',
    naacGrade: 'A',
    establishedYear: 1891,
    courses: 'B.A. LL.B (5 Year), LL.B (3 Year), LL.M, Ph.D',
    contact: '044-28447171',
    website: 'www.dralc.in',
    feeRange: '₹2,000 - ₹15,000 per year',
    accreditation: 'Bar Council of India Approved',
    address: 'Poonamallee High Road, Chennai',
    facilities: ['Moot Court', 'Library', 'Hostel'],
  },
  
  // University of Madras
  {
    id: 'university_madras',
    name: 'University of Madras',
    type: 'government',
    category: 'arts_science',
    naacGrade: 'A++',
    establishedYear: 1857,
    courses: 'B.A, B.Sc, M.A, M.Sc, M.Phil, Ph.D (Various Disciplines)',
    contact: '044-25399422',
    website: 'www.unom.ac.in',
    feeRange: '₹5,000 - ₹30,000 per year',
    accreditation: 'NAAC A++ Accredited',
    address: 'Chepauk, Chennai',
    facilities: ['Central Library', 'Research Centers', 'Hostels', 'Sports Complex'],
  },
  
  // Anna University
  {
    id: 'anna_university_chennai',
    name: 'Anna University, Chennai',
    type: 'government',
    category: 'engineering',
    naacGrade: 'A++',
    establishedYear: 1978,
    courses: 'B.E/B.Tech, M.E/M.Tech, MBA, MCA, M.Sc, Ph.D',
    contact: '044-22357004',
    website: 'www.annauniv.edu',
    feeRange: '₹10,000 - ₹50,000 per year',
    accreditation: 'NAAC A++ Accredited, NBA Accredited',
    address: 'Guindy, Chennai',
    facilities: ['Central Library', 'Research Park', 'Hostels', 'Sports Complex'],
  },

  // ============ MADURAI DISTRICT COLLEGES (2024-2025) ============
  
  // Government Arts & Science Colleges - Madurai
  {
    id: 'govt_arts_college_melur',
    name: 'Government Arts College, Melur',
    type: 'government',
    category: 'arts_science',
    naacGrade: 'B+',
    establishedYear: 1971,
    courses: 'B.A, B.Sc, B.Com, M.A, M.Sc',
    contact: '0452-2552345',
    feeRange: '₹1,000 - ₹5,000 per year',
    accreditation: 'Madurai Kamaraj University Affiliated',
    address: 'Melur, Madurai',
  },
  {
    id: 'yadava_college',
    name: 'The Madura College (Autonomous)',
    type: 'government-aided',
    category: 'arts_science',
    naacGrade: 'A',
    establishedYear: 1889,
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com, MBA',
    contact: '0452-2536367',
    website: 'www.maduracollege.edu.in',
    feeRange: '₹5,000 - ₹25,000 per year (Aided), ₹25,000 - ₹70,000 (Self-Financing)',
    accreditation: 'Madurai Kamaraj University Affiliated, Autonomous',
    address: 'Madurai',
    placementStats: '78% placement rate',
  },
  {
    id: 'american_college_madurai',
    name: 'The American College (Autonomous)',
    type: 'government-aided',
    category: 'arts_science',
    naacGrade: 'A++',
    establishedYear: 1881,
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com, MBA, M.Phil, Ph.D',
    contact: '0452-2530070',
    website: 'www.americancollege.edu.in',
    feeRange: '₹5,000 - ₹30,000 per year (Aided), ₹30,000 - ₹90,000 (Self-Financing)',
    accreditation: 'Madurai Kamaraj University Affiliated, Autonomous',
    address: 'Madurai',
    placementStats: '85% placement rate',
    facilities: ['Library', 'Labs', 'Hostel', 'Sports Complex', 'Chapel'],
  },
  {
    id: 'lady_doak_college',
    name: 'Lady Doak College (Autonomous)',
    type: 'government-aided',
    category: 'arts_science',
    naacGrade: 'A++',
    establishedYear: 1948,
    courses: 'B.A, B.Sc, B.Com, BCA, M.A, M.Sc, M.Com, MBA',
    contact: '0452-2534252',
    website: 'www.ladydoakcollege.edu.in',
    feeRange: '₹5,000 - ₹25,000 per year (Aided), ₹25,000 - ₹80,000 (Self-Financing)',
    accreditation: 'Madurai Kamaraj University Affiliated, Autonomous',
    address: 'Madurai',
    placementStats: '82% placement rate',
  },
  {
    id: 'fatima_college_madurai',
    name: 'Fatima College (Autonomous)',
    type: 'government-aided',
    category: 'arts_science',
    naacGrade: 'A+',
    establishedYear: 1953,
    courses: 'B.A, B.Sc, B.Com, BCA, M.A, M.Sc, M.Com',
    contact: '0452-2642326',
    website: 'www.fatimacollege.net',
    feeRange: '₹5,000 - ₹25,000 per year (Aided), ₹25,000 - ₹70,000 (Self-Financing)',
    accreditation: 'Madurai Kamaraj University Affiliated, Autonomous',
    address: 'Mary Land, Madurai',
    placementStats: '80% placement rate',
  },
  
  // Government Engineering Colleges - Madurai
  {
    id: 'tce_madurai',
    name: 'Thiagarajar College of Engineering (TCE)',
    type: 'government-aided',
    category: 'engineering',
    naacGrade: 'A++',
    establishedYear: 1957,
    courses: 'B.E/B.Tech (CSE, IT, ECE, EEE, Mech, Civil), M.E/M.Tech, MBA',
    contact: '0452-2482240',
    website: 'www.tce.edu',
    feeRange: '₹25,000 - ₹50,000 per year (Aided via TNEA), ₹50,000 - ₹1,20,000 (Self-Financing)',
    accreditation: 'Anna University Affiliated, NBA Accredited, Autonomous',
    address: 'Thiruparankundram, Madurai',
    placementStats: '95% placement rate',
    facilities: ['Central Library', 'Labs', 'Hostels', 'Sports Complex', 'Research Centers'],
  },
  {
    id: 'govt_college_engineering_madurai',
    name: 'Government College of Engineering, Madurai',
    type: 'government',
    category: 'engineering',
    naacGrade: 'A',
    establishedYear: 2014,
    courses: 'B.E (CSE, ECE, EEE, Mech, Civil)',
    contact: '0452-2553456',
    feeRange: '₹5,000 - ₹15,000 per year',
    accreditation: 'Anna University Affiliated',
    address: 'Madurai',
  },
  
  // Government Medical College - Madurai
  {
    id: 'madurai_medical_college',
    name: 'Madurai Medical College & Hospital',
    type: 'government',
    category: 'medical',
    naacGrade: 'A+',
    establishedYear: 1954,
    courses: 'MBBS, MD, MS, DM, MCh, Diploma',
    contact: '0452-2532535',
    feeRange: '₹15,000 - ₹50,000 per year',
    accreditation: 'NMC Approved',
    address: 'Alwarpuram, Madurai',
    facilities: ['Government Rajaji Hospital', 'Library', 'Hostel', 'Research Center'],
    placementStats: '100% placement rate',
  },
  
  // Government Law College - Madurai
  {
    id: 'govt_law_college_madurai',
    name: 'Government Law College, Madurai',
    type: 'government',
    category: 'law',
    establishedYear: 1970,
    courses: 'B.A. LL.B (5 Year), LL.B (3 Year), LL.M',
    contact: '0452-2534567',
    feeRange: '₹2,000 - ₹10,000 per year',
    accreditation: 'Bar Council of India Approved',
    address: 'Madurai',
  },
  
  // Madurai Kamaraj University
  {
    id: 'madurai_kamaraj_university',
    name: 'Madurai Kamaraj University',
    type: 'government',
    category: 'arts_science',
    naacGrade: 'A++',
    establishedYear: 1966,
    courses: 'B.A, B.Sc, M.A, M.Sc, M.Phil, Ph.D (Various Disciplines)',
    contact: '0452-2459181',
    website: 'www.mkuniversity.ac.in',
    feeRange: '₹5,000 - ₹30,000 per year',
    accreditation: 'NAAC A++ Accredited',
    address: 'Palkalai Nagar, Madurai',
    facilities: ['Central Library', 'Research Centers', 'Hostels', 'Sports Complex'],
  },
  
  // Agricultural College - Madurai
  {
    id: 'agricultural_college_madurai',
    name: 'Agricultural College and Research Institute, Madurai',
    type: 'government',
    category: 'agricultural',
    naacGrade: 'A',
    establishedYear: 1965,
    courses: 'B.Sc Agriculture, M.Sc Agriculture, Ph.D',
    contact: '0452-2422956',
    website: 'www.tnau.ac.in/acri-madurai',
    feeRange: '₹10,000 - ₹30,000 per year',
    accreditation: 'TNAU Affiliated, ICAR Accredited',
    address: 'Madurai',
    facilities: ['Research Farms', 'Library', 'Hostels', 'Labs'],
  },

  // ============ TIRUCHIRAPPALLI (TRICHY) DISTRICT COLLEGES (2024-2025) ============
  
  // Government Arts & Science Colleges - Trichy
  {
    id: 'govt_arts_college_trichy',
    name: 'Government Arts College, Trichy',
    type: 'government',
    category: 'arts_science',
    naacGrade: 'B++',
    establishedYear: 1954,
    courses: 'B.A, B.Sc, B.Com, M.A, M.Sc, M.Com',
    contact: '0431-2420255',
    feeRange: '₹1,000 - ₹5,000 per year',
    accreditation: 'Bharathidasan University Affiliated',
    address: 'Trichy',
  },
  {
    id: 'national_college_trichy',
    name: 'National College (Autonomous)',
    type: 'government-aided',
    category: 'arts_science',
    naacGrade: 'A',
    establishedYear: 1918,
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com, MBA, MCA',
    contact: '0431-2421847',
    website: 'www.nct.ac.in',
    feeRange: '₹5,000 - ₹25,000 per year (Aided), ₹25,000 - ₹70,000 (Self-Financing)',
    accreditation: 'Bharathidasan University Affiliated, Autonomous',
    address: 'Trichy',
    placementStats: '80% placement rate',
  },
  {
    id: 'jamal_mohamed_college',
    name: 'Jamal Mohamed College (Autonomous)',
    type: 'government-aided',
    category: 'arts_science',
    naacGrade: 'A++',
    establishedYear: 1951,
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com, MBA, MCA, M.Phil, Ph.D',
    contact: '0431-2331032',
    website: 'www.jmc.edu',
    feeRange: '₹5,000 - ₹30,000 per year (Aided), ₹30,000 - ₹90,000 (Self-Financing)',
    accreditation: 'Bharathidasan University Affiliated, Autonomous',
    address: 'Trichy',
    placementStats: '85% placement rate',
    facilities: ['Library', 'Labs', 'Hostel', 'Sports Complex', 'Research Centers'],
  },
  {
    id: 'holy_cross_college_trichy',
    name: 'Holy Cross College (Autonomous)',
    type: 'government-aided',
    category: 'arts_science',
    naacGrade: 'A++',
    establishedYear: 1895,
    courses: 'B.A, B.Sc, B.Com, BCA, M.A, M.Sc, M.Com, MBA, M.Phil, Ph.D',
    contact: '0431-2700637',
    website: 'www.holycrosstrichy.edu.in',
    feeRange: '₹5,000 - ₹25,000 per year (Aided), ₹25,000 - ₹80,000 (Self-Financing)',
    accreditation: 'Bharathidasan University Affiliated, Autonomous',
    address: 'Trichy',
    placementStats: '82% placement rate',
  },
  {
    id: 'bishops_heber_college',
    name: "Bishop Heber College (Autonomous)",
    type: 'government-aided',
    category: 'arts_science',
    naacGrade: 'A',
    establishedYear: 1966,
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com, MBA',
    contact: '0431-2774637',
    website: 'www.bhc.edu.in',
    feeRange: '₹5,000 - ₹25,000 per year (Aided), ₹25,000 - ₹70,000 (Self-Financing)',
    accreditation: 'Bharathidasan University Affiliated, Autonomous',
    address: 'Trichy',
    placementStats: '78% placement rate',
  },
  {
    id: 'st_josephs_college_trichy',
    name: "St. Joseph's College (Autonomous)",
    type: 'government-aided',
    category: 'arts_science',
    naacGrade: 'A++',
    establishedYear: 1844,
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com, MBA, M.Phil, Ph.D',
    contact: '0431-2700632',
    website: 'www.sjctni.edu',
    feeRange: '₹5,000 - ₹30,000 per year (Aided), ₹30,000 - ₹90,000 (Self-Financing)',
    accreditation: 'Bharathidasan University Affiliated, Autonomous',
    address: 'Trichy',
    placementStats: '88% placement rate',
    facilities: ['Library', 'Labs', 'Hostel', 'Sports Complex', 'Chapel'],
  },
  
  // Government Engineering Colleges - Trichy
  {
    id: 'nit_trichy',
    name: 'National Institute of Technology (NIT), Tiruchirappalli',
    type: 'government',
    category: 'engineering',
    naacGrade: 'A++',
    establishedYear: 1964,
    courses: 'B.Tech, M.Tech, MBA, MCA, M.Sc, Ph.D (Various Disciplines)',
    contact: '0431-2503000',
    website: 'www.nitt.edu',
    feeRange: '₹1,00,000 - ₹2,00,000 per year',
    accreditation: 'NIRF Rank 9, NBA Accredited',
    address: 'Tanjore Main Road, Trichy',
    placementStats: '98% placement rate',
    facilities: ['Central Library', 'Labs', 'Hostels', 'Sports Complex', 'Research Park'],
  },
  {
    id: 'university_college_engineering_trichy',
    name: 'University College of Engineering, BIT Campus',
    type: 'government',
    category: 'engineering',
    naacGrade: 'A',
    establishedYear: 1962,
    courses: 'B.E/B.Tech (CSE, IT, ECE, EEE, Mech, Civil), M.E/M.Tech',
    contact: '0431-2407999',
    website: 'www.ucetrichy.edu.in',
    feeRange: '₹10,000 - ₹30,000 per year',
    accreditation: 'Anna University Affiliated',
    address: 'BIT Campus, Trichy',
    placementStats: '85% placement rate',
  },
  {
    id: 'iiit_trichy',
    name: 'Indian Institute of Information Technology (IIIT), Tiruchirappalli',
    type: 'government',
    category: 'engineering',
    naacGrade: 'A',
    establishedYear: 2013,
    courses: 'B.Tech (CSE, ECE), M.Tech, Ph.D',
    contact: '0431-2500400',
    website: 'www.iiitt.ac.in',
    feeRange: '₹1,50,000 - ₹2,50,000 per year',
    accreditation: 'AICTE Approved',
    address: 'Trichy',
    placementStats: '92% placement rate',
  },
  
  // Government Medical College - Trichy
  {
    id: 'trichy_medical_college',
    name: 'K.A.P. Viswanatham Government Medical College',
    type: 'government',
    category: 'medical',
    naacGrade: 'A',
    establishedYear: 1985,
    courses: 'MBBS, MD, MS, Diploma',
    contact: '0431-2415415',
    feeRange: '₹15,000 - ₹50,000 per year',
    accreditation: 'NMC Approved',
    address: 'Trichy',
    facilities: ['Mahatma Gandhi Memorial Government Hospital', 'Library', 'Hostel'],
  },
  
  // Government Law College - Trichy
  {
    id: 'govt_law_college_trichy',
    name: 'Government Law College, Trichy',
    type: 'government',
    category: 'law',
    establishedYear: 1975,
    courses: 'B.A. LL.B (5 Year), LL.B (3 Year), LL.M',
    contact: '0431-2421567',
    feeRange: '₹2,000 - ₹10,000 per year',
    accreditation: 'Bar Council of India Approved',
    address: 'Trichy',
  },
  
  // Bharathidasan University
  {
    id: 'bharathidasan_university',
    name: 'Bharathidasan University',
    type: 'government',
    category: 'arts_science',
    naacGrade: 'A++',
    establishedYear: 1982,
    courses: 'B.A, B.Sc, M.A, M.Sc, M.Phil, Ph.D (Various Disciplines)',
    contact: '0431-2407071',
    website: 'www.bdu.ac.in',
    feeRange: '₹5,000 - ₹30,000 per year',
    accreditation: 'NAAC A++ Accredited',
    address: 'Palkalaiperur, Trichy',
    facilities: ['Central Library', 'Research Centers', 'Hostels', 'Sports Complex'],
  },
  
  // Agricultural College - Trichy
  {
    id: 'anbil_dharmalingam_agricultural',
    name: 'Anbil Dharmalingam Agricultural College and Research Institute',
    type: 'government',
    category: 'agricultural',
    naacGrade: 'A',
    establishedYear: 1989,
    courses: 'B.Sc Agriculture, B.Sc Horticulture, M.Sc, Ph.D',
    contact: '0431-2906206',
    website: 'www.tnau.ac.in/adac',
    feeRange: '₹10,000 - ₹30,000 per year',
    accreditation: 'TNAU Affiliated, ICAR Accredited',
    address: 'Trichy',
    facilities: ['Research Farms', 'Library', 'Hostels', 'Labs'],
    placementStats: '85% placement rate',
  },
];

// Legacy export for backward compatibility
export const JKKN_COLLEGES: Partial<Record<CollegeCategory, College>> = 
  NAMAKKAL_FEATURED_COLLEGES.reduce((acc, college) => {
    // Only keep first college per category for legacy support
    if (!acc[college.category]) {
      acc[college.category] = college;
    }
    return acc;
  }, {} as Partial<Record<CollegeCategory, College>>);
