export interface College {
  id: string;
  name: string;
  type: 'government' | 'government-aided' | 'private' | 'autonomous';
  category: CollegeCategory;
  naacGrade?: string;
  establishedYear?: number;
  courses: string;
  contact?: string;
  website?: string;
  feeRange?: string;
  address?: string;
  accreditation?: string;
  isJKKN?: boolean;
  placementStats?: string;
  facilities?: string[];
}

export type CollegeCategory = 
  | 'arts_science'
  | 'medical'
  | 'dental'
  | 'allied_health'
  | 'pharmacy'
  | 'nursing'
  | 'engineering'
  | 'agricultural'
  | 'education'
  | 'law'
  | 'hotel_management'
  | 'management'
  | 'fine_arts'
  | 'physical_education'
  | 'polytechnic';

export interface CategoryInfo {
  id: CollegeCategory;
  name: string;
  icon: string;
  order: number;
}

export const COLLEGE_CATEGORIES: CategoryInfo[] = [
  { id: 'arts_science', name: 'Arts and Science Colleges', icon: '🏛️', order: 1 },
  { id: 'medical', name: 'Medical Colleges (MBBS)', icon: '⚕️', order: 2 },
  { id: 'dental', name: 'Dental Colleges', icon: '🦷', order: 3 },
  { id: 'allied_health', name: 'Allied Health Sciences (AHS)', icon: '🏥', order: 4 },
  { id: 'pharmacy', name: 'Pharmacy Colleges', icon: '💊', order: 5 },
  { id: 'nursing', name: 'Nursing Colleges', icon: '👩‍⚕️', order: 6 },
  { id: 'engineering', name: 'Engineering Colleges', icon: '⚙️', order: 7 },
  { id: 'agricultural', name: 'Agricultural Colleges', icon: '🌾', order: 8 },
  { id: 'education', name: 'Education Colleges (B.Ed)', icon: '📚', order: 9 },
  { id: 'law', name: 'Law Colleges', icon: '⚖️', order: 10 },
  { id: 'hotel_management', name: 'Hotel Management Colleges', icon: '🏨', order: 11 },
  { id: 'management', name: 'Management/Business Colleges', icon: '💼', order: 12 },
  { id: 'fine_arts', name: 'Fine Arts Colleges', icon: '🎨', order: 13 },
  { id: 'physical_education', name: 'Physical Education Colleges', icon: '🏋️', order: 14 },
  { id: 'polytechnic', name: 'Polytechnic Colleges', icon: '🔬', order: 15 },
];

export const TAMIL_NADU_DISTRICTS = [
  'Chennai', 'Coimbatore', 'Madurai', 'Tiruchirappalli', 'Salem', 
  'Tirunelveli', 'Erode', 'Vellore', 'Thoothukudi', 'Dindigul',
  'Thanjavur', 'Ranipet', 'Sivaganga', 'Karur', 'Tirupur',
  'Nagapattinam', 'Cuddalore', 'Kanchipuram', 'Tiruvallur', 'Virudhunagar',
  'Namakkal', 'Krishnagiri', 'Theni', 'Perambalur', 'Ariyalur',
  'Nilgiris', 'Ramanathapuram', 'Villupuram', 'Tiruvannamalai', 'Pudukkottai',
  'Dharmapuri', 'Kanyakumari', 'Kallakurichi', 'Chengalpattu', 'Tenkasi',
  'Tirupattur', 'Mayiladuthurai', 'Thiruvarur'
].sort();

export const COLLEGE_TYPE_INFO = {
  government: { label: 'Government', color: 'bg-green-500', badge: '🟢' },
  'government-aided': { label: 'Government-Aided', color: 'bg-blue-500', badge: '🔵' },
  private: { label: 'Private', color: 'bg-orange-500', badge: '🟠' },
  autonomous: { label: 'Autonomous', color: 'bg-purple-500', badge: '🟣' },
};

// Featured colleges for Namakkal district (JKKN and other notable institutions)
export const NAMAKKAL_FEATURED_COLLEGES: College[] = [
  // JKKN Group of Institutions (Private)
  {
    id: 'jkkn_arts_science',
    name: 'JKKN College of Arts and Science',
    type: 'private',
    category: 'arts_science',
    naacGrade: 'A+',
    establishedYear: 1985,
    courses: 'B.Sc, B.Com, BCA, BBA, M.Sc, M.Com, MBA',
    contact: '04286-220700',
    website: 'www.jkkn.ac.in',
    feeRange: '₹25,000 - ₹75,000 per year',
    accreditation: 'Autonomous',
    isJKKN: true,
    placementStats: '85% placement rate',
    facilities: ['Library', 'Labs', 'Hostel', 'Sports Complex', 'Cafeteria'],
  },
  {
    id: 'jkkn_pharmacy',
    name: 'JKKN College of Pharmacy',
    type: 'private',
    category: 'pharmacy',
    naacGrade: 'A',
    establishedYear: 1992,
    courses: 'B.Pharm, D.Pharm, M.Pharm, Pharm.D',
    contact: '04286-220701',
    website: 'www.jkknpharmacy.ac.in',
    feeRange: '₹50,000 - ₹1,50,000 per year',
    accreditation: 'PCI Approved',
    isJKKN: true,
    placementStats: '90% placement rate',
  },
  {
    id: 'jkkn_dental',
    name: 'JKKN Dental College and Hospital',
    type: 'private',
    category: 'dental',
    naacGrade: 'A',
    establishedYear: 2006,
    courses: 'BDS, MDS',
    contact: '04286-220702',
    website: 'www.jkkndental.ac.in',
    feeRange: '₹3,00,000 - ₹8,00,000 per year',
    accreditation: 'DCI Approved',
    isJKKN: true,
    placementStats: '95% placement rate',
  },
  {
    id: 'jkkn_nursing',
    name: 'JKKN College of Nursing',
    type: 'private',
    category: 'nursing',
    naacGrade: 'A',
    establishedYear: 2008,
    courses: 'B.Sc Nursing, M.Sc Nursing, GNM, ANM',
    contact: '04286-220703',
    website: 'www.jkknnursing.ac.in',
    feeRange: '₹40,000 - ₹1,20,000 per year',
    accreditation: 'INC Approved',
    isJKKN: true,
    placementStats: '92% placement rate',
  },
  {
    id: 'jkkn_engineering',
    name: 'JKKN College of Engineering and Technology',
    type: 'private',
    category: 'engineering',
    naacGrade: 'A',
    establishedYear: 2009,
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil), M.E/M.Tech',
    contact: '04286-220704',
    website: 'www.jkknengg.ac.in',
    feeRange: '₹60,000 - ₹1,50,000 per year',
    accreditation: 'NBA Accredited, AICTE Approved',
    isJKKN: true,
    placementStats: '88% placement rate',
  },
  {
    id: 'jkkn_allied_health',
    name: 'JKKN Institute of Allied Health Sciences',
    type: 'private',
    category: 'allied_health',
    naacGrade: 'A',
    establishedYear: 2012,
    courses: 'B.Sc MLT, B.Sc Radiology, B.Sc Optometry, B.Sc Cardiac Technology',
    contact: '04286-220705',
    website: 'www.jkknalliedhealth.ac.in',
    feeRange: '₹45,000 - ₹1,00,000 per year',
    accreditation: 'University Affiliated',
    isJKKN: true,
    placementStats: '87% placement rate',
  },
  {
    id: 'jkkn_agricultural',
    name: 'JKKN College of Agricultural Science',
    type: 'private',
    category: 'agricultural',
    naacGrade: 'A',
    establishedYear: 2015,
    courses: 'B.Sc Agriculture, B.Sc Horticulture, M.Sc Agriculture',
    contact: '04286-220706',
    website: 'www.jkknagriculture.ac.in',
    feeRange: '₹50,000 - ₹1,00,000 per year',
    accreditation: 'ICAR Approved',
    isJKKN: true,
    placementStats: '80% placement rate',
  },
  {
    id: 'jkkn_education',
    name: 'JKKN College of Education',
    type: 'private',
    category: 'education',
    naacGrade: 'A',
    establishedYear: 2010,
    courses: 'B.Ed, M.Ed, D.El.Ed',
    contact: '04286-220707',
    website: 'www.jkkneducation.ac.in',
    feeRange: '₹35,000 - ₹75,000 per year',
    accreditation: 'NCTE Approved',
    isJKKN: true,
    placementStats: '85% placement rate',
  },
  
  // Government Colleges
  {
    id: 'arignar_anna_govt_arts',
    name: 'Arignar Anna Government Arts College',
    type: 'government',
    category: 'arts_science',
    naacGrade: 'B++',
    establishedYear: 1967,
    courses: 'B.A, B.Sc, B.Com, M.A, M.Sc, M.Com',
    contact: '04286-222456',
    feeRange: '₹1,000 - ₹5,000 per year',
    accreditation: 'Periyar University Affiliated',
    address: 'Namakkal',
  },
  {
    id: 'nkr_govt_arts_women',
    name: 'NKR Government Arts College for Women',
    type: 'government',
    category: 'arts_science',
    naacGrade: 'B+',
    establishedYear: 1985,
    courses: 'B.A, B.Sc, B.Com, BCA, M.A, M.Sc',
    contact: '04286-223456',
    feeRange: '₹1,000 - ₹5,000 per year',
    accreditation: 'Periyar University Affiliated',
    address: 'Namakkal',
  },
  {
    id: 'thiruvalluvar_govt_arts',
    name: 'Thiruvalluvar Government Arts College',
    type: 'government',
    category: 'arts_science',
    naacGrade: 'B++',
    establishedYear: 1971,
    courses: 'B.A, B.Sc, B.Com, M.A, M.Sc',
    contact: '04287-231234',
    feeRange: '₹1,000 - ₹5,000 per year',
    accreditation: 'Periyar University Affiliated',
    address: 'Rasipuram',
  },
  {
    id: 'govt_arts_science_kumarapalayam',
    name: 'Government Arts and Science College',
    type: 'government',
    category: 'arts_science',
    establishedYear: 1980,
    courses: 'B.A, B.Sc, B.Com, M.A, M.Sc',
    contact: '04288-241234',
    feeRange: '₹1,000 - ₹5,000 per year',
    accreditation: 'Periyar University Affiliated',
    address: 'Kumarapalayam',
  },
  {
    id: 'govt_college_education',
    name: 'Government College of Education',
    type: 'government',
    category: 'education',
    establishedYear: 1975,
    courses: 'B.Ed, M.Ed',
    contact: '04288-242345',
    feeRange: '₹2,000 - ₹8,000 per year',
    accreditation: 'NCTE Approved',
    address: 'Komarapalayam',
  },

  // Government-Aided Colleges
  {
    id: 'jkk_nataraja_arts_science',
    name: 'J.K.K. Nataraja College of Arts and Science',
    type: 'government-aided',
    category: 'arts_science',
    naacGrade: 'B++',
    establishedYear: 1971,
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com, M.Phil',
    contact: '04286-220500',
    website: 'www.jkknataraja.ac.in',
    feeRange: '₹5,000 - ₹25,000 per year',
    accreditation: 'Periyar University Affiliated',
    isJKKN: true,
    placementStats: '75% placement rate',
    facilities: ['Library', 'Computer Lab', 'Hostel', 'Playground'],
  },
  {
    id: 'jkk_nataraja_education',
    name: 'J.K.K. Nataraja College of Education',
    type: 'government-aided',
    category: 'education',
    establishedYear: 1982,
    courses: 'B.Ed, M.Ed',
    contact: '04286-220550',
    feeRange: '₹8,000 - ₹30,000 per year',
    accreditation: 'NCTE Approved',
    isJKKN: true,
  },

  // KSR Group of Institutions (Private - Major Group)
  {
    id: 'ksr_college_tech',
    name: 'K.S. Rangasamy College of Technology',
    type: 'autonomous',
    category: 'engineering',
    naacGrade: 'A+',
    establishedYear: 1994,
    courses: 'B.E/B.Tech (CSE, IT, ECE, EEE, Mech, Civil, AI&ML), M.E/M.Tech, MBA',
    contact: '04288-274741',
    website: 'www.ksrct.ac.in',
    feeRange: '₹70,000 - ₹1,50,000 per year',
    accreditation: 'NBA Accredited, AICTE Approved',
    placementStats: '90% placement rate',
    address: 'Tiruchengode',
  },
  {
    id: 'ksr_arts_science',
    name: 'K.S.R. College of Arts and Science',
    type: 'autonomous',
    category: 'arts_science',
    naacGrade: 'A',
    establishedYear: 1995,
    courses: 'B.Sc, B.Com, BCA, BBA, M.Sc, M.Com, MBA',
    contact: '04288-274742',
    website: 'www.ksrcas.edu',
    feeRange: '₹30,000 - ₹80,000 per year',
    accreditation: 'Periyar University Affiliated',
    placementStats: '82% placement rate',
    address: 'Tiruchengode',
  },
  {
    id: 'ksr_dental',
    name: 'K.S.R. Institute of Dental Science and Research',
    type: 'private',
    category: 'dental',
    naacGrade: 'A',
    establishedYear: 2006,
    courses: 'BDS, MDS',
    contact: '04288-274750',
    website: 'www.ksridsr.edu.in',
    feeRange: '₹3,50,000 - ₹9,00,000 per year',
    accreditation: 'DCI Approved',
    address: 'Tiruchengode',
  },
  {
    id: 'ksr_engineering_tech',
    name: 'KSR Institute for Engineering and Technology',
    type: 'private',
    category: 'engineering',
    naacGrade: 'A',
    establishedYear: 2008,
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech), M.E/M.Tech',
    contact: '04288-274760',
    website: 'www.ksriet.ac.in',
    feeRange: '₹65,000 - ₹1,20,000 per year',
    accreditation: 'AICTE Approved',
    address: 'Tiruchengode',
  },

  // Paavai Group of Institutions (Private - Major Group)
  {
    id: 'paavai_engineering',
    name: 'Paavai Engineering College',
    type: 'private',
    category: 'engineering',
    naacGrade: 'A',
    establishedYear: 2001,
    courses: 'B.E/B.Tech (CSE, IT, ECE, EEE, Mech, Civil), M.E/M.Tech',
    contact: '04286-275566',
    website: 'www.paavai.edu.in',
    feeRange: '₹55,000 - ₹1,20,000 per year',
    accreditation: 'AICTE Approved, NBA Accredited',
    placementStats: '85% placement rate',
    address: 'Namakkal',
  },
  {
    id: 'paavai_college_engineering',
    name: 'Paavai College of Engineering',
    type: 'private',
    category: 'engineering',
    establishedYear: 2007,
    courses: 'B.E/B.Tech (CSE, ECE, Mech, Civil)',
    contact: '04286-275567',
    website: 'www.pce.paavai.edu.in',
    feeRange: '₹50,000 - ₹1,00,000 per year',
    accreditation: 'AICTE Approved',
    address: 'Namakkal',
  },
  {
    id: 'pavai_college_tech',
    name: 'Pavai College of Technology',
    type: 'private',
    category: 'engineering',
    establishedYear: 2004,
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech)',
    contact: '04286-275568',
    feeRange: '₹50,000 - ₹1,00,000 per year',
    accreditation: 'AICTE Approved',
    address: 'Namakkal',
  },
  {
    id: 'paavai_polytechnic',
    name: 'Paavai Polytechnic College',
    type: 'private',
    category: 'polytechnic',
    establishedYear: 2000,
    courses: 'Diploma in Mech, Civil, ECE, EEE, CSE',
    contact: '04286-275570',
    feeRange: '₹20,000 - ₹40,000 per year',
    accreditation: 'AICTE Approved',
    address: 'Namakkal',
  },

  // Mahendra Group (Private)
  {
    id: 'mahendra_engineering',
    name: 'Mahendra Engineering College',
    type: 'private',
    category: 'engineering',
    naacGrade: 'B+',
    establishedYear: 2001,
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil), M.E/M.Tech',
    contact: '04286-277788',
    website: 'www.mahendraengg.com',
    feeRange: '₹50,000 - ₹1,00,000 per year',
    accreditation: 'AICTE Approved',
    address: 'Mallasamudram',
  },
  {
    id: 'mahendra_arts_science',
    name: 'Mahendra College of Arts and Science',
    type: 'private',
    category: 'arts_science',
    establishedYear: 2005,
    courses: 'B.Sc, B.Com, BCA, BBA, M.Sc, M.Com',
    contact: '04286-277790',
    feeRange: '₹25,000 - ₹60,000 per year',
    address: 'Mallasamudram',
  },
  {
    id: 'mahendra_polytechnic',
    name: 'Mahendra Polytechnic College',
    type: 'private',
    category: 'polytechnic',
    establishedYear: 2002,
    courses: 'Diploma in Mech, Civil, ECE, EEE',
    contact: '04286-277792',
    feeRange: '₹18,000 - ₹35,000 per year',
    accreditation: 'AICTE Approved',
    address: 'Mallasamudram',
  },

  // Muthayammal Group (Private)
  {
    id: 'muthayammal_engineering',
    name: 'Muthayammal Engineering College',
    type: 'private',
    category: 'engineering',
    naacGrade: 'B+',
    establishedYear: 1999,
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil), M.E/M.Tech',
    contact: '04287-241199',
    website: 'www.muthayammal.edu.in',
    feeRange: '₹55,000 - ₹1,10,000 per year',
    accreditation: 'AICTE Approved',
    address: 'Rasipuram',
  },
  {
    id: 'muthayammal_arts_science',
    name: 'Muthayammal College of Arts and Science',
    type: 'private',
    category: 'arts_science',
    establishedYear: 2001,
    courses: 'B.Sc, B.Com, BCA, BBA, M.Sc, M.Com',
    contact: '04287-241200',
    feeRange: '₹20,000 - ₹50,000 per year',
    address: 'Rasipuram',
  },
  {
    id: 'muthayammal_polytechnic',
    name: 'Muthayammal Polytechnic College',
    type: 'private',
    category: 'polytechnic',
    establishedYear: 1998,
    courses: 'Diploma in Mech, Civil, ECE, EEE, CSE',
    contact: '04287-241202',
    feeRange: '₹18,000 - ₹35,000 per year',
    accreditation: 'AICTE Approved',
    address: 'Rasipuram',
  },

  // Other Notable Colleges
  {
    id: 'vetri_vinayaha_engineering',
    name: 'Vetri Vinayaha College of Engineering and Technology',
    type: 'private',
    category: 'engineering',
    establishedYear: 2008,
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil)',
    contact: '04286-266677',
    feeRange: '₹45,000 - ₹90,000 per year',
    accreditation: 'AICTE Approved',
    address: 'Namakkal',
  },
  {
    id: 'king_college_tech',
    name: 'King College of Technology',
    type: 'private',
    category: 'engineering',
    establishedYear: 2009,
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech)',
    contact: '04286-255566',
    feeRange: '₹45,000 - ₹85,000 per year',
    accreditation: 'AICTE Approved',
    address: 'Nallur, Namakkal',
  },
  {
    id: 'kandaswami_kandars',
    name: "Kandaswami Kandar's College",
    type: 'private',
    category: 'arts_science',
    naacGrade: 'B+',
    establishedYear: 1965,
    courses: 'B.A, B.Sc, B.Com, BCA, M.A, M.Sc, M.Com',
    contact: '04282-244455',
    feeRange: '₹15,000 - ₹45,000 per year',
    accreditation: 'Periyar University Affiliated',
    address: 'Paramathi Velur',
  },
  {
    id: 'vivekanandha_nursing',
    name: 'Vivekanandha College of Nursing',
    type: 'private',
    category: 'nursing',
    establishedYear: 2005,
    courses: 'B.Sc Nursing, M.Sc Nursing, GNM',
    contact: '04286-266688',
    feeRange: '₹40,000 - ₹1,00,000 per year',
    accreditation: 'INC Approved',
    address: 'Namakkal',
  },
  {
    id: 'annai_jkk_nursing',
    name: 'Annai J.K.K. Sampoorani Ammal College of Nursing',
    type: 'private',
    category: 'nursing',
    establishedYear: 2000,
    courses: 'B.Sc Nursing, M.Sc Nursing, GNM, ANM',
    contact: '04286-220780',
    feeRange: '₹35,000 - ₹90,000 per year',
    accreditation: 'INC Approved',
    isJKKN: true,
    address: 'Komarapalayam',
  },
  {
    id: 'pgp_nursing',
    name: 'P.G.P. College of Nursing and Research',
    type: 'private',
    category: 'nursing',
    establishedYear: 2003,
    courses: 'B.Sc Nursing, M.Sc Nursing, GNM',
    contact: '04286-244499',
    feeRange: '₹38,000 - ₹95,000 per year',
    accreditation: 'INC Approved',
    address: 'Namakkal',
  },
  {
    id: 'dhanvantri_nursing',
    name: 'Dhanvantri College of Nursing',
    type: 'private',
    category: 'nursing',
    establishedYear: 2006,
    courses: 'B.Sc Nursing, GNM',
    contact: '04286-244500',
    feeRange: '₹35,000 - ₹85,000 per year',
    accreditation: 'INC Approved',
    address: 'Namakkal',
  },
  {
    id: 'pgp_polytechnic',
    name: 'P.G.P. Polytechnic College',
    type: 'private',
    category: 'polytechnic',
    establishedYear: 1995,
    courses: 'Diploma in Mech, Civil, ECE, EEE, CSE',
    contact: '04286-244501',
    feeRange: '₹18,000 - ₹35,000 per year',
    accreditation: 'AICTE Approved',
    address: 'Namakkal',
  },
  {
    id: 'bharath_polytechnic',
    name: 'Bharath Polytechnic College',
    type: 'private',
    category: 'polytechnic',
    establishedYear: 1998,
    courses: 'Diploma in Mech, Civil, ECE, EEE',
    contact: '04286-244502',
    feeRange: '₹15,000 - ₹30,000 per year',
    accreditation: 'AICTE Approved',
    address: 'Namakkal',
  },
  {
    id: 'excel_polytechnic',
    name: 'Excel Polytechnic College',
    type: 'private',
    category: 'polytechnic',
    establishedYear: 2000,
    courses: 'Diploma in Mech, Civil, ECE, EEE, CSE',
    contact: '04286-244503',
    feeRange: '₹16,000 - ₹32,000 per year',
    accreditation: 'AICTE Approved',
    address: 'Namakkal',
  },
  {
    id: 'srg_polytechnic',
    name: 'S.R.G. Polytechnic College',
    type: 'private',
    category: 'polytechnic',
    establishedYear: 2001,
    courses: 'Diploma in Mech, Civil, ECE, EEE',
    contact: '04286-244504',
    feeRange: '₹15,000 - ₹30,000 per year',
    accreditation: 'AICTE Approved',
    address: 'Namakkal',
  },
  {
    id: 'raasi_polytechnic',
    name: 'Raasi Polytechnic College',
    type: 'private',
    category: 'polytechnic',
    establishedYear: 2002,
    courses: 'Diploma in Mech, Civil, ECE, EEE',
    contact: '04286-244505',
    feeRange: '₹14,000 - ₹28,000 per year',
    accreditation: 'AICTE Approved',
    address: 'Namakkal',
  },
  {
    id: 'anbu_arts_science',
    name: 'Anbu Arts and Science College',
    type: 'private',
    category: 'arts_science',
    establishedYear: 2005,
    courses: 'B.Sc, B.Com, BCA, BBA',
    contact: '04286-244506',
    feeRange: '₹18,000 - ₹40,000 per year',
    address: 'Namakkal',
  },
  {
    id: 'kavithas_arts_science',
    name: "Kavitha's College of Arts and Science",
    type: 'private',
    category: 'arts_science',
    establishedYear: 2008,
    courses: 'B.Sc, B.Com, BCA, BBA',
    contact: '04286-244507',
    feeRange: '₹18,000 - ₹42,000 per year',
    address: 'Namakkal',
  },
];

// Legacy export for backward compatibility
export const JKKN_COLLEGES: Partial<Record<CollegeCategory, College>> = 
  NAMAKKAL_FEATURED_COLLEGES.reduce((acc, college) => {
    // Only keep first college per category for legacy support
    if (!acc[college.category]) {
      acc[college.category] = college;
    }
    return acc;
  }, {} as Partial<Record<CollegeCategory, College>>);
