import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

// Support 10 Indian regional languages
export type Language = 'en' | 'ta' | 'hi' | 'te' | 'kn' | 'ml' | 'bn' | 'mr' | 'gu' | 'pa';

// Language metadata for UI display
export const SUPPORTED_LANGUAGES: Array<{
  code: Language;
  name: string;
  nativeName: string;
  flag: string;
}> = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिंदी', flag: '🇮🇳' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', flag: '🇮🇳' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇮🇳' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', flag: '🇮🇳' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', flag: '🇮🇳' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations - English and Tamil are fully supported, others fall back to English
const translations: Record<Language, Record<string, string>> = {
  en: {
    // TopBar
    'topbar.aiChat': 'AI Chat',
    'topbar.login': 'Login',
    'topbar.register': 'Register',
    'topbar.careerPath': 'CAREER PATH - 2026-2032',
    
    // Navigation
    'nav.home': 'Home',
    'nav.careerHub': 'Career Hub',
    'nav.dashboard': 'Dashboard',
    'nav.aboutJkkn': 'About Us',
    'nav.careerGuidance': 'Career Guidance',
    'nav.jobPortal': 'Job Portal',
    'nav.contact': 'Contact',
    'nav.institutionName': 'வழிகாட்டி',
    'nav.tagline': 'Discover, Design, Do',
    
    // Hero Section
    'hero.badge': 'CAREER PATH - 2026-2032',
    'hero.title': 'VAZHIKATTI:',
    'hero.subtitle': 'Discover, Design, Do - வழிகாட்டி',
    'hero.tamilSubtitle': 'கண்டறி, வடிவமை, செய்',
    'hero.description': 'Empowering Learners & 12th Students with AI-powered career guidance, skill development and placement opportunities.',
    'hero.register12th': 'Register as 12th Learner',
    'hero.registerLearner': 'Register as Learner',
    'hero.whoIsFor': 'Who is this for?',
    'hero.12thLearners': '12th Learners',
    'hero.12thLearnersDesc': 'Discover careers & plan your future',
    'hero.learners': 'Learners',
    'hero.learnersDesc': 'Build skills & connect with employers',
    'hero.employers': 'Employers',
    'hero.employersDesc': 'Hire talented graduates',
    'hero.exploreMore': 'Explore More',
    
    // Services Section
    'services.badge': 'Complete Support System',
    'services.title': 'Your Complete Career Journey',
    'services.description': 'From self-discovery to job offers, VAZHIKATTI supports every stage of your journey.',
    'services.careerAssessment': 'Career Assessment',
    'services.careerAssessmentDesc': 'AI-powered psychometric tests to discover your personality, strengths, and best-fit careers.',
    'services.careerPathFinder': 'Career Path Finder',
    'services.careerPathFinderDesc': 'Explore what to do after 10th & 12th, with clear education paths mapped to real careers.',
    'services.jobPortal': 'Job Portal',
    'services.jobPortalDesc': 'Apply to curated jobs, internships, and 12th-pass roles with a single profile.',
    'services.skillDevelopment': 'Skill Development',
    'services.skillDevelopmentDesc': 'Learn technical, communication, and life skills with focused courses and practice tasks.',
    'services.expertCounseling': 'Expert Counseling',
    'services.expertCounselingDesc': 'Book one-on-one sessions with Senior Learners and counselors to clarify doubts.',
    'services.aiAssistant': 'AI Career Assistant',
    'services.aiAssistantDesc': 'Ask AI anything about careers, courses, jobs, or admissions—24/7.',
    
    // Footer
    'footer.title': 'Discover, Design, Do - வழிகாட்டி',
    'footer.tagline': 'AI-Powered Career Guidance Platform',
    'footer.copyright': '© 2025 வழிகாட்டி. All Rights Reserved.',
    'footer.about': 'About Us',
    'footer.events': 'Events',
    'footer.contact': 'Contact',
    'footer.admin': 'Admin',
    
    // CTA Section
    'cta.title': 'Ready to Shape Your Future?',
    'cta.description': 'Join thousands of learners who have discovered their career path with VAZHIKATTI.',
    'cta.startJourney': 'Start Your Journey',
    'cta.exploreJobs': 'Explore Jobs',
    
    // Common
    'common.loading': 'Loading...',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.submit': 'Submit',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.viewAll': 'View All',
    'common.learnMore': 'Learn More',
    'common.change': 'Change',
    'common.startAssessment': 'Start Assessment',
    'common.refresh': 'Refresh',
    'common.loadMore': 'Load More',
    'common.clearFilters': 'Clear all filters',
    'common.noResults': 'No results found',
    
    // AI Career Predictor
    'predictor.title': 'AI Career Predictor',
    'predictor.subtitle': 'Get AI-powered career predictions based on your interests and skills',
    'predictor.predictCareer': 'Predict My Career',
    'predictor.selectStream': 'Select Your Stream',
    'predictor.selectPercentage': 'Expected 12th Percentage',
    'predictor.selectInterests': 'Select Your Interests',
    'predictor.selectInterestsDesc': 'Choose up to 3 areas that excite you the most',
    'predictor.selectPriorities': 'What matters most to you?',
    'predictor.selectPrioritiesDesc': 'Pick up to 2 priorities',
    'predictor.budgetDuration': 'Budget & Duration',
    'predictor.budget': 'Budget for Education',
    'predictor.duration': 'Preferred Course Duration',
    'predictor.analyzing': 'Analyzing your interests...',
    'predictor.matching': 'Matching with 200+ courses...',
    'predictor.finding': 'Finding best courses for you...',
    'predictor.generating': 'Generating recommendations...',
    'predictor.yourRecommendations': 'Your Course Recommendations',
    'predictor.showingResults': 'Showing courses based on your profile',
    'predictor.matchScore': 'Match Score',
    'predictor.fees': 'Fees',
    'predictor.entranceExam': 'Entrance Exam',
    'predictor.viewDetails': 'View Details',
    'predictor.compare': 'Compare',
    'predictor.downloadPdf': 'Download PDF',
    'predictor.shareWhatsApp': 'Share on WhatsApp',
    'predictor.print': 'Print',
    'predictor.showFavorites': 'Show Favorites Only',
    'predictor.clearFilters': 'Clear Filters',
    'predictor.sortBy': 'Sort By',
    'predictor.filterBy': 'Filter',
    'predictor.allDurations': 'All Durations',
    'predictor.shortCourses': 'Short (2-3 years)',
    'predictor.mediumCourses': 'Medium (4 years)',
    'predictor.longCourses': 'Long (5+ years)',
    'predictor.allFees': 'All Fees',
    'predictor.lowFees': 'Under ₹1L',
    'predictor.mediumFees': '₹1L - ₹3L',
    'predictor.highFees': 'Above ₹3L',
    'predictor.allExams': 'All Exams',
    'predictor.step': 'Step',
    'predictor.of': 'of',
    'predictor.basicInfo': 'Basic Info',
    'predictor.interestsPriorities': 'Interests & Priorities',
    
    // Interest Cards
    'interest.technology': 'Technology & Computers',
    'interest.science': 'Science & Research',
    'interest.healthcare': 'Healthcare & Medicine',
    'interest.business': 'Business & Finance',
    'interest.law': 'Law & Justice',
    'interest.arts': 'Arts & Design',
    'interest.aviation': 'Aviation & Travel',
    'interest.construction': 'Building & Construction',
    'interest.media': 'Media & Journalism',
    'interest.teaching': 'Teaching & Education',
    'interest.agriculture': 'Agriculture & Nature',
    'interest.defence': 'Defence & Security',
    'interest.hospitality': 'Hotel & Hospitality',
    'interest.data': 'Data & Analytics',
    
    // Priority Options
    'priority.salary': 'High Salary',
    'priority.security': 'Job Security',
    'priority.balance': 'Work-Life Balance',
    'priority.growth': 'Fast Growth',
    'priority.helping': 'Helping Others',
    
    // Streams
    'stream.pcm': 'Science (PCM - Physics, Chemistry, Mathematics)',
    'stream.pcb': 'Science (PCB - Physics, Chemistry, Biology)',
    'stream.pcmb': 'Science (PCMB - All four subjects)',
    'stream.commerce_math': 'Commerce (with Mathematics)',
    'stream.commerce': 'Commerce (without Mathematics)',
    'stream.arts': 'Arts / Humanities',
    
    // Career Assessment 12th Learners
    'assessment12.title': 'What Should I Study After 12th?',
    'assessment12.tamilTitle': '12-ஆம் வகுப்புக்குப் பிறகு என்ன படிக்க வேண்டும்?',
    'assessment12.subtitle': 'Confused about your future? Let AI help you discover the perfect course based on your interests, skills and personality',
    'assessment12.introHeading': "Don't worry! Tell us your stream and we'll find the perfect course for YOU",
    'assessment12.introDesc': 'Take our AI-powered assessment to discover courses that match your personality, interests, and career goals.',
    'assessment12.welcomeBack': 'Welcome back!',
    'assessment12.completedAssessments': 'You\'re a {stream} student with {count} completed assessment(s).',
    'assessment12.startJourney': 'Start Your Discovery Journey',
    'assessment12.takeAnother': 'Take Another Assessment',
    'assessment12.viewPastResults': 'View Past Results',
    'assessment12.questions': 'Questions',
    'assessment12.scenarioBased': 'Scenario-based questions',
    'assessment12.minutes': 'Minutes',
    'assessment12.quickInsightful': 'Quick and insightful',
    'assessment12.courses': 'Courses',
    'assessment12.personalizedRecs': 'Personalized recommendations',
    'assessment12.selectStreamTitle': 'First, tell us about your 12th standard',
    'assessment12.selectStreamDesc': 'Select your stream to get personalized course recommendations',
    'assessment12.detailsTitle': 'A few more details...',
    'assessment12.detailsDesc': 'This helps us give you better recommendations',
    'assessment12.marksLabel': 'Your expected/obtained 12th marks:',
    'assessment12.returningUser': 'Returning user: We\'ll show you completely new questions you haven\'t seen before!',
    'assessment12.streamPCM': 'Science - PCM',
    'assessment12.streamPCMSub': 'Physics, Chemistry, Mathematics',
    'assessment12.streamPCB': 'Science - PCB',
    'assessment12.streamPCBSub': 'Physics, Chemistry, Biology',
    'assessment12.streamPCMB': 'Science - PCMB',
    'assessment12.streamPCMBSub': 'Physics, Chemistry, Maths & Biology',
    'assessment12.streamCommerce': 'Commerce',
    'assessment12.streamCommerceSub': 'Accountancy, Business Studies, Economics',
    'assessment12.streamArts': 'Arts / Humanities',
    'assessment12.streamArtsSub': 'History, Geography, Languages, Psychology',
    
    // Industry Trends Page
    'industry.pageTitle': "India's Job Market 2026 - Career Trends",
    'industry.pageTitleTamil': 'இந்தியாவின் வேலை வாய்ப்பு 2026 - தொழில் போக்குகள்',
    'industry.knowIndustries': 'Know which industries are hiring & skills you need',
    'industry.knowIndustriesTamil': 'எந்த துறைகள் வேலை வழங்குகின்றன என்பதை அறியுங்கள்',
    'industry.jobAlerts': 'Job Alerts',
    'industry.subscribed': 'Subscribed',
    'industry.downloadPdf': 'Download PDF',
    'industry.manageAlerts': 'Manage Job Alerts',
    'industry.subscribeAlerts': 'Subscribe to Job Alerts',
    'industry.activeSubscription': 'Active Subscription',
    'industry.unsubscribe': 'Unsubscribe from Alerts',
    'industry.nameOptional': 'Name (Optional)',
    'industry.emailAddress': 'Email Address',
    'industry.selectSectors': 'Select Sectors',
    'industry.preferredLocations': 'Preferred Locations',
    'industry.minimumSalary': 'Minimum Salary (LPA)',
    'industry.anySalary': 'Any Salary',
    'industry.subscribing': 'Subscribing...',
    'industry.subscribeToAlerts': 'Subscribe to Alerts',
    'industry.unsubscribeNote': "We'll send you relevant job alerts. You can unsubscribe anytime.",
    'industry.sectorsSelected': 'sector(s) selected',
    'industry.highGrowthSectors': 'Sectors with High Hiring Growth',
    'industry.highGrowthSectorsTamil': 'அதிக வேலை வளர்ச்சி உள்ள துறைகள்',
    'industry.salaryRange': 'Salary Range',
    'industry.topCompanies': 'Top Companies Hiring',
    'industry.coursesToConsider': 'Courses to Consider',
    'industry.tnColleges': 'Tamil Nadu Colleges',
    'industry.careerPaths': 'Career Paths',
    'industry.whyGrowing': 'Why This Sector is Growing',
    'industry.technicalSkills': 'Technical Skills in Demand',
    'industry.softSkills': 'Soft Skills Required',
    'industry.demandLevel': 'Demand',
    'industry.importanceLevel': 'Importance',
    'industry.streamRoadmaps': 'Career Roadmaps by Stream',
    'industry.bestPaths': 'Best Paths',
    'industry.recommendedCourses': 'Recommended Courses',
    'industry.yearlySkillPlan': 'Year-by-Year Skill Plan',
    'industry.salaryTrends': 'Salary Trends by Industry',
    'industry.entryLevel': 'Entry Level',
    'industry.experienced': 'Experienced',
    'industry.liveJobOpenings': 'Live Job Openings',
    'industry.liveJobOpeningsTamil': 'நேரடி வேலை வாய்ப்புகள்',
    'industry.allJobs': 'All',
    'industry.savedJobs': 'Saved',
    'industry.searchJobs': 'Search jobs, companies, locations...',
    'industry.hotJob': 'Hot',
    'industry.addToCompare': 'Add to Compare',
    'industry.removeFromCompare': 'Remove from Compare',
    'industry.compareJobs': 'Compare Jobs',
    'industry.selectJobsCompare': 'Select 2-4 jobs to compare',
    'industry.sectors': 'Sectors',
    'industry.skills': 'Skills',
    'industry.newJobs': 'New Jobs',
    'industry.futureReady': 'Future Ready',
    
    // Job Portal Page
    'jobportal.findDreamJob': 'Find Your Dream Job',
    'jobportal.searchPlaceholder': 'Search jobs, companies...',
    'jobportal.jobsFound': 'jobs found',
    'jobportal.refresh': 'Refresh',
    'jobportal.loadMore': 'Load More Jobs',
    'jobportal.noJobsFound': 'No jobs found matching your criteria.',
    'jobportal.clearFilters': 'Clear all filters',
    'jobportal.allJobs': 'All Jobs',
    'jobportal.filters': 'Filters',
    'jobportal.applyFilters': 'Apply Filters',
    'jobportal.clearAll': 'Clear All',
    'jobportal.location': 'Location',
    'jobportal.city': 'City',
    'jobportal.salaryRange': 'Salary Range',
    'jobportal.experience': 'Experience',
    'jobportal.jobType': 'Job Type',
    'jobportal.walkinOnly': 'Walk-in Only',
    'jobportal.fullTime': 'Full-time',
    'jobportal.partTime': 'Part-time',
    'jobportal.contract': 'Contract',
    'jobportal.internship': 'Internship',
    'jobportal.callNow': 'Call Now',
    'jobportal.whatsapp': 'WhatsApp',
    'jobportal.featured': 'Featured',
    'jobportal.walkin': 'Walk-in',
    'jobportal.walkinDetails': 'Walk-in Details',
    'jobportal.interviewDate': 'Interview Date',
    'jobportal.interviewTime': 'Interview Time',
    'jobportal.interviewVenue': 'Interview Venue',
    'jobportal.salary': 'Salary',
    'jobportal.qualification': 'Qualification',
    'jobportal.vacancies': 'Vacancies',
    'jobportal.postedAgo': 'Posted',
    'jobportal.description': 'Description',
    'jobportal.responsibilities': 'Responsibilities',
    'jobportal.requirements': 'Requirements',
    'jobportal.documentsRequired': 'Documents Required',
    'jobportal.benefits': 'Benefits',
    'jobportal.contactInfo': 'Contact Information',
    'jobportal.shareJob': 'Share Job',
    'jobportal.openMaps': 'Open in Maps',
    'jobportal.fresher': 'Fresher',
    'jobportal.years': 'years',
    'jobportal.perMonth': '/month',
    'jobportal.perYear': '/year',
    'jobportal.perDay': '/day',
    'jobportal.negotiable': 'Negotiable',
    
    // Registration Forms - 12th Learner
    'reg12.pageTitle': 'Register as 12th Learner',
    'reg12.yourJourney': 'Your Journey',
    'reg12.stepOf': 'Step {current} of {total}',
    'reg12.progress': 'Progress',
    'reg12.whyRegister': 'Why Register?',
    'reg12.benefit1': 'AI-Powered Career Guidance',
    'reg12.benefit2': 'Personalized Course Recommendations',
    'reg12.benefit3': 'Connect with Top Institutions',
    'reg12.benefit4': 'Free Career Assessment',
    'reg12.personalInfo': 'Personal Info',
    'reg12.education': 'Education',
    'reg12.interests': 'Interests',
    'reg12.review': 'Review',
    'reg12.tellAboutYourself': 'Tell us about yourself',
    'reg12.educationalBackground': 'Your educational background',
    'reg12.passionateAbout': 'What are you passionate about?',
    'reg12.reviewInfo': 'Review your information',
    'reg12.fullName': 'Full Name',
    'reg12.enterFullName': 'Enter your full name',
    'reg12.phoneNumber': 'Phone Number',
    'reg12.emailAddress': 'Email Address',
    'reg12.emailOptional': 'your@email.com (optional)',
    'reg12.dateOfBirth': 'Date of Birth',
    'reg12.schoolName': 'School Name',
    'reg12.enterSchoolName': 'Enter your school name',
    'reg12.board': 'Board',
    'reg12.selectBoard': 'Select your board',
    'reg12.stream': 'Stream',
    'reg12.selectStream': 'Select your stream',
    'reg12.expectedYear': 'Expected Year of Passing',
    'reg12.selectYear': 'Select year',
    'reg12.preferredCourses': 'Preferred Courses',
    'reg12.preferredCoursesPlaceholder': 'e.g., Engineering, Medicine, Arts',
    'reg12.careerInterests': 'Career Interests',
    'reg12.careerInterestsPlaceholder': 'e.g., Software Development, Healthcare',
    'reg12.preferredLocation': 'Preferred Location',
    'reg12.selectLocation': 'Select location',
    'reg12.reviewYourInfo': 'Review Your Information',
    'reg12.name': 'Name',
    'reg12.phone': 'Phone',
    'reg12.email': 'Email',
    'reg12.school': 'School',
    'reg12.location': 'Location',
    'reg12.notProvided': 'Not provided',
    'reg12.back': 'Back',
    'reg12.next': 'Next',
    'reg12.submitRegistration': 'Submit Registration',
    'reg12.registrationSuccess': 'Registration successful! We\'ll be in touch soon.',
    'reg12.registrationFailed': 'Registration failed. Please try again.',
    'reg12.science': 'Science',
    'reg12.commerce': 'Commerce',
    'reg12.artsHumanities': 'Arts/Humanities',
    'reg12.tamilNadu': 'Tamil Nadu',
    'reg12.karnataka': 'Karnataka',
    'reg12.kerala': 'Kerala',
    'reg12.anywhereIndia': 'Anywhere in India',
    
    // Registration Forms - Learner
    'regLearner.pageTitle': 'Register as Learner',
    'regLearner.subtitle': 'Find your dream job and advance your career',
    'regLearner.personalInfo': 'Personal Info',
    'regLearner.education': 'Education',
    'regLearner.fullName': 'Full Name',
    'regLearner.fullNamePlaceholder': 'e.g., Ramesh Kumar',
    'regLearner.emailAddress': 'Email Address',
    'regLearner.emailPlaceholder': 'e.g., ramesh@example.com',
    'regLearner.mobileNumber': 'Mobile Number',
    'regLearner.mobilePlaceholder': 'e.g., 9876543210',
    'regLearner.dateOfBirth': 'Date of Birth',
    'regLearner.district': 'District',
    'regLearner.selectDistrict': 'Select district',
    'regLearner.placeTown': 'Place/Town',
    'regLearner.placePlaceholder': 'e.g., Gandhipuram, T. Nagar',
    'regLearner.institution': 'Institution/College',
    'regLearner.institutionPlaceholder': 'e.g., Anna University',
    'regLearner.degree': 'Degree/Qualification',
    'regLearner.selectDegree': 'Select degree',
    'regLearner.specialization': 'Specialization/Major',
    'regLearner.specializationPlaceholder': 'e.g., Computer Science, Mechanical Engineering',
    'regLearner.graduationYear': 'Graduation Year',
    'regLearner.selectGradYear': 'Select year',
    'regLearner.back': 'Back',
    'regLearner.next': 'NEXT',
    'regLearner.submitRegistration': 'Submit Registration',
    'regLearner.submitting': 'Submitting...',
    'regLearner.registrationSuccess': 'Registration successful! Welcome to Career Hub.',
    'regLearner.fixErrors': 'Please fix the errors in the form',
    'regLearner.registrationFailed': 'Registration failed. Please try again.',
    'regLearner.degree10th': '10th Pass',
    'regLearner.degree12th': '12th Pass',
    'regLearner.degreeDiploma': 'Diploma',
    'regLearner.degreeIti': 'ITI',
    'regLearner.degreeBachelors': "Bachelor's Degree",
    'regLearner.degreeMasters': "Master's Degree",
    'regLearner.degreePhd': 'PhD',
    
    // Registration Forms - Employer
    'regEmployer.pageTitle': 'Register as Employer',
    'regEmployer.subtitle': 'Connect with talented graduates from our institutions',
    'regEmployer.companyInfo': 'Company Info',
    'regEmployer.contactPerson': 'Contact Person',
    'regEmployer.hiringNeeds': 'Hiring Needs',
    'regEmployer.review': 'Review',
    'regEmployer.companyName': 'Company Name',
    'regEmployer.enterCompanyName': 'Enter company name',
    'regEmployer.industry': 'Industry',
    'regEmployer.selectIndustry': 'Select industry',
    'regEmployer.companySize': 'Company Size',
    'regEmployer.selectCompanySize': 'Select company size',
    'regEmployer.website': 'Website',
    'regEmployer.websitePlaceholder': 'https://www.company.com',
    'regEmployer.contactPersonName': 'Contact Person Name',
    'regEmployer.fullName': 'Full name',
    'regEmployer.emailAddress': 'Email Address',
    'regEmployer.emailPlaceholder': 'hr@company.com',
    'regEmployer.phoneNumber': 'Phone Number',
    'regEmployer.phonePlaceholder': '9876543210',
    'regEmployer.designation': 'Designation',
    'regEmployer.designationPlaceholder': 'e.g., HR Manager, Talent Acquisition Lead',
    'regEmployer.rolesHiring': 'Roles You\'re Hiring For',
    'regEmployer.rolesPlaceholder': 'e.g., Software Engineer, Data Analyst, Nurse',
    'regEmployer.experienceLevel': 'Experience Level Required',
    'regEmployer.selectExperience': 'Select experience level',
    'regEmployer.hiringLocations': 'Hiring Locations',
    'regEmployer.locationsPlaceholder': 'e.g., Chennai, Bangalore, Remote',
    'regEmployer.hiringTimeline': 'Hiring Timeline',
    'regEmployer.selectTimeline': 'Select timeline',
    'regEmployer.reviewYourInfo': 'Review Your Information',
    'regEmployer.company': 'Company',
    'regEmployer.contactName': 'Contact Name',
    'regEmployer.contactEmail': 'Contact Email',
    'regEmployer.hiringRoles': 'Hiring Roles',
    'regEmployer.locations': 'Locations',
    'regEmployer.notProvided': 'Not provided',
    'regEmployer.back': 'Back',
    'regEmployer.next': 'Next',
    'regEmployer.submitRegistration': 'Submit Registration',
    'regEmployer.registrationSuccess': 'Registration successful!',
    'regEmployer.registrationFailed': 'Registration failed. Please try again.',
    'regEmployer.industryIt': 'IT / Software',
    'regEmployer.industryHealthcare': 'Healthcare / Pharma',
    'regEmployer.industryManufacturing': 'Manufacturing',
    'regEmployer.industryFinance': 'Finance / Banking',
    'regEmployer.industryEducation': 'Education',
    'regEmployer.industryRetail': 'Retail / E-commerce',
    'regEmployer.industryConsulting': 'Consulting',
    'regEmployer.industryOther': 'Other',
    'regEmployer.size1_50': '1-50 employees',
    'regEmployer.size51_200': '51-200 employees',
    'regEmployer.size201_500': '201-500 employees',
    'regEmployer.size501_1000': '501-1000 employees',
    'regEmployer.size1000plus': '1000+ employees',
    'regEmployer.expFresher': 'Freshers Only',
    'regEmployer.exp0_2': '0-2 years',
    'regEmployer.exp2_5': '2-5 years',
    'regEmployer.expMixed': 'Mixed (Fresher + Experienced)',
    'regEmployer.timelineImmediate': 'Immediate',
    'regEmployer.timeline1Month': 'Within 1 month',
    'regEmployer.timeline3Months': 'Within 3 months',
    'regEmployer.timeline6Months': 'Within 6 months',
    
    // Career Chat - Suggested Questions
    'chat.popularQuestions': 'Popular Questions for 12th Students',
    'chat.streamSpecificQuestions': 'Stream-Specific Questions',
    'chat.welcomeTitle': "Hello! I'm your AI Career Counselor",
    'chat.welcomeDesc': "Ask me anything about careers, courses, colleges, or guidance. I'm here to help you find your path!",
    'chat.welcomeTamil': 'தொழில், படிப்புகள், கல்லூரிகள் பற்றி என்னிடம் கேளுங்கள்!',
    'chat.inputPlaceholder': 'Ask me about careers, courses, or colleges...',
    
    // Career Planning Questions
    'chat.q1': 'What are the best career options after 12th Science (PCM)?',
    'chat.q2': 'Which courses have the highest salary potential?',
    'chat.q3': 'How do I choose between Engineering and Medicine?',
    'chat.q4': 'What are the emerging careers with high growth?',
    'chat.q5': 'Which entrance exams should I prepare for?',
    'chat.q6': 'What are the best colleges in Tamil Nadu?',
    'chat.q7': 'Can I pursue abroad studies after 12th?',
    'chat.q8': 'What skills should I develop for my career?',
    
    // Stream-Specific Questions
    'chat.stream1': 'Career options for PCB students',
    'chat.stream2': 'Commerce stream best courses',
    'chat.stream3': 'Arts stream career paths',
    'chat.stream4': 'PCMB career combinations',
    
    // Exam Preparation Questions
    'chat.examPrepHeader': 'Exam Preparation Tips',
    'chat.exam1': 'How to prepare for JEE Main in 3 months?',
    'chat.exam2': 'Best study plan for NEET preparation',
    'chat.exam3': 'Tips to crack CUET for top universities',
    'chat.exam4': 'How to manage board exams and entrance exams together?',
    
    // Scholarship & Financial Aid Questions
    'chat.scholarshipHeader': 'Scholarship & Financial Aid',
    'chat.scholarship1': 'What scholarships are available for 12th students?',
    'chat.scholarship2': 'How to apply for government education loans?',
    'chat.scholarship3': 'Merit-based scholarships for engineering students',
    'chat.scholarship4': 'Financial aid options for studying abroad',
  },
  ta: {
    // TopBar
    'topbar.aiChat': 'AI அரட்டை',
    'topbar.login': 'உள்நுழை',
    'topbar.register': 'பதிவு',
    'topbar.careerPath': 'தொழில் பாதை - 2026-2032',
    
    // Navigation
    'nav.home': 'முகப்பு',
    'nav.careerHub': 'தொழில் மையம்',
    'nav.dashboard': 'டாஷ்போர்டு',
    'nav.aboutJkkn': 'எங்களை பற்றி',
    'nav.careerGuidance': 'தொழில் வழிகாட்டுதல்',
    'nav.jobPortal': 'வேலை போர்டல்',
    'nav.contact': 'தொடர்பு',
    'nav.institutionName': 'வழிகாட்டி',
    'nav.tagline': 'கண்டறி, வடிவமை, செய்',
    
    // Hero Section
    'hero.badge': 'தொழில் பாதை - 2026-2032',
    'hero.title': 'AI ஹொரைசன்ஸ்:',
    'hero.subtitle': 'கண்டறி, வடிவமை, செய் - வழிகாட்டி',
    'hero.tamilSubtitle': 'Discover, Design, Do',
    'hero.description': 'கற்பவர்கள் மற்றும் 12ஆம் வகுப்பு மாணவர்களுக்கு AI-இயங்கும் தொழில் வழிகாட்டுதல், திறன் மேம்பாடு மற்றும் வேலைவாய்ப்புகளை வழங்குகிறது.',
    'hero.register12th': '12ஆம் வகுப்பு மாணவராக பதிவு செய்க',
    'hero.registerLearner': 'கற்பவராக பதிவு செய்க',
    'hero.whoIsFor': 'இது யாருக்கானது?',
    'hero.12thLearners': '12ஆம் வகுப்பு மாணவர்கள்',
    'hero.12thLearnersDesc': 'தொழில்களை கண்டறிந்து உங்கள் எதிர்காலத்தை திட்டமிடுங்கள்',
    'hero.learners': 'கற்பவர்கள்',
    'hero.learnersDesc': 'திறன்களை வளர்த்து முதலாளிகளுடன் இணையுங்கள்',
    'hero.employers': 'முதலாளிகள்',
    'hero.employersDesc': 'திறமையான பட்டதாரிகளை பணியமர்த்துங்கள்',
    'hero.exploreMore': 'மேலும் ஆராயுங்கள்',
    
    // Services Section
    'services.badge': 'முழுமையான ஆதரவு அமைப்பு',
    'services.title': 'உங்கள் முழுமையான தொழில் பயணம்',
    'services.description': 'சுய கண்டுபிடிப்பிலிருந்து வேலை வாய்ப்புகள் வரை, AI ஹொரைசன்ஸ் உங்கள் பயணத்தின் ஒவ்வொரு கட்டத்தையும் ஆதரிக்கிறது.',
    'services.careerAssessment': 'தொழில் மதிப்பீடு',
    'services.careerAssessmentDesc': 'உங்கள் ஆளுமை, பலங்கள் மற்றும் சிறந்த தொழில்களை கண்டறிய AI-இயங்கும் மனநல சோதனைகள்.',
    'services.careerPathFinder': 'தொழில் பாதை கண்டுபிடிப்பான்',
    'services.careerPathFinderDesc': '10வது மற்றும் 12வது வகுப்புக்கு பிறகு என்ன செய்யலாம் என்பதை ஆராயுங்கள், உண்மையான தொழில்களுக்கான தெளிவான கல்வி பாதைகள்.',
    'services.jobPortal': 'வேலை போர்டல்',
    'services.jobPortalDesc': 'ஒரே சுயவிவரத்துடன் தொகுக்கப்பட்ட வேலைகள், இன்டர்ன்ஷிப்கள் மற்றும் 12வது பாஸ் பதவிகளுக்கு விண்ணப்பிக்கவும்.',
    'services.skillDevelopment': 'திறன் மேம்பாடு',
    'services.skillDevelopmentDesc': 'கவனமான படிப்புகள் மற்றும் பயிற்சி பணிகளுடன் தொழில்நுட்ப, தொடர்பு மற்றும் வாழ்க்கை திறன்களை கற்றுக்கொள்ளுங்கள்.',
    'services.expertCounseling': 'நிபுணர் ஆலோசனை',
    'services.expertCounselingDesc': 'சந்தேகங்களை தெளிவுபடுத்த மூத்த கற்பவர்கள் மற்றும் ஆலோசகர்களுடன் ஒன்றுக்கொன்று அமர்வுகளை பதிவு செய்யுங்கள்.',
    'services.aiAssistant': 'AI தொழில் உதவியாளர்',
    'services.aiAssistantDesc': 'தொழில்கள், படிப்புகள், வேலைகள் அல்லது சேர்க்கைகள் பற்றி AI-யிடம் எதையும் கேளுங்கள்—24/7.',
    
    // Footer
    'footer.title': 'கண்டறி, வடிவமை, செய் - வழிகாட்டி',
    'footer.tagline': 'AI-இயங்கும் தொழில் வழிகாட்டுதல் தளம்',
    'footer.copyright': '© 2025 வழிகாட்டி. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
    'footer.about': 'எங்களை பற்றி',
    'footer.events': 'நிகழ்வுகள்',
    'footer.contact': 'தொடர்பு',
    'footer.admin': 'நிர்வாகி',
    
    // CTA Section
    'cta.title': 'உங்கள் எதிர்காலத்தை வடிவமைக்க தயாரா?',
    'cta.description': 'AI ஹொரைசன்ஸுடன் தங்கள் தொழில் பாதையை கண்டறிந்த ஆயிரக்கணக்கான கற்பவர்களுடன் சேருங்கள்.',
    'cta.startJourney': 'உங்கள் பயணத்தை தொடங்குங்கள்',
    'cta.exploreJobs': 'வேலைகளை ஆராயுங்கள்',
    
    // Common
    'common.loading': 'ஏற்றுகிறது...',
    'common.back': 'பின்னால்',
    'common.next': 'அடுத்து',
    'common.submit': 'சமர்ப்பி',
    'common.cancel': 'ரத்து செய்',
    'common.save': 'சேமி',
    'common.search': 'தேடு',
    'common.filter': 'வடிகட்டு',
    'common.viewAll': 'அனைத்தும் காண்க',
    'common.learnMore': 'மேலும் அறிக',
    'common.change': 'மாற்று',
    'common.startAssessment': 'மதிப்பீட்டை தொடங்கு',
    
    // AI Career Predictor
    'predictor.title': 'AI தொழில் கணிப்பான்',
    'predictor.subtitle': 'உங்கள் ஆர்வங்கள் மற்றும் திறன்களின் அடிப்படையில் AI-இயங்கும் தொழில் கணிப்புகளைப் பெறுங்கள்',
    'predictor.predictCareer': 'எனது தொழிலைக் கணி',
    'predictor.selectStream': 'உங்கள் பிரிவைத் தேர்ந்தெடுக்கவும்',
    'predictor.selectPercentage': 'எதிர்பார்க்கப்படும் 12ஆம் வகுப்பு சதவீதம்',
    'predictor.selectInterests': 'உங்கள் ஆர்வங்களைத் தேர்ந்தெடுக்கவும்',
    'predictor.selectInterestsDesc': 'உங்களை மிகவும் உற்சாகப்படுத்தும் 3 துறைகளைத் தேர்ந்தெடுக்கவும்',
    'predictor.selectPriorities': 'உங்களுக்கு மிக முக்கியமானது என்ன?',
    'predictor.selectPrioritiesDesc': '2 முன்னுரிமைகளைத் தேர்ந்தெடுக்கவும்',
    'predictor.budgetDuration': 'பட்ஜெட் & கால அளவு',
    'predictor.budget': 'கல்விக்கான பட்ஜெட்',
    'predictor.duration': 'விரும்பிய படிப்பு கால அளவு',
    'predictor.analyzing': '🧠 உங்கள் ஆர்வங்களை பகுப்பாய்வு செய்கிறது...',
    'predictor.matching': '📊 200+ படிப்புகளுடன் பொருத்துகிறது...',
    'predictor.finding': '🎓 உங்களுக்கு சிறந்த படிப்புகளை கண்டறிகிறது...',
    'predictor.generating': '✨ பரிந்துரைகளை உருவாக்குகிறது...',
    'predictor.yourRecommendations': 'உங்கள் படிப்பு பரிந்துரைகள்',
    'predictor.showingResults': 'உங்கள் சுயவிவரத்தின் அடிப்படையில் படிப்புகளைக் காட்டுகிறது',
    'predictor.matchScore': 'பொருத்த மதிப்பெண்',
    'predictor.fees': 'கட்டணம்',
    'predictor.entranceExam': 'நுழைவுத் தேர்வு',
    'predictor.viewDetails': 'விவரங்களைக் காண்க',
    'predictor.compare': 'ஒப்பிடு',
    'predictor.downloadPdf': 'PDF பதிவிறக்கு',
    'predictor.shareWhatsApp': 'WhatsApp-இல் பகிர்',
    'predictor.print': 'அச்சிடு',
    'predictor.showFavorites': 'பிடித்தவை மட்டும் காட்டு',
    'predictor.clearFilters': 'வடிகட்டிகளை அழி',
    'predictor.sortBy': 'வரிசைப்படுத்து',
    'predictor.filterBy': 'வடிகட்டு',
    'predictor.allDurations': 'அனைத்து கால அளவுகள்',
    'predictor.shortCourses': 'குறுகிய (2-3 ஆண்டுகள்)',
    'predictor.mediumCourses': 'நடுத்தர (4 ஆண்டுகள்)',
    'predictor.longCourses': 'நீண்ட (5+ ஆண்டுகள்)',
    'predictor.allFees': 'அனைத்து கட்டணங்கள்',
    'predictor.lowFees': '₹1L கீழ்',
    'predictor.mediumFees': '₹1L - ₹3L',
    'predictor.highFees': '₹3L மேல்',
    'predictor.allExams': 'அனைத்து தேர்வுகள்',
    'predictor.step': 'படி',
    'predictor.of': '/',
    'predictor.basicInfo': 'அடிப்படை தகவல்',
    'predictor.interestsPriorities': 'ஆர்வங்கள் & முன்னுரிமைகள்',
    
    // Interest Cards
    'interest.technology': 'தொழில்நுட்பம் & கணினிகள்',
    'interest.science': 'அறிவியல் & ஆராய்ச்சி',
    'interest.healthcare': 'சுகாதாரம் & மருத்துவம்',
    'interest.business': 'வணிகம் & நிதி',
    'interest.law': 'சட்டம் & நீதி',
    'interest.arts': 'கலை & வடிவமைப்பு',
    'interest.aviation': 'விமானம் & பயணம்',
    'interest.construction': 'கட்டிடம் & நிர்மாணம்',
    'interest.media': 'ஊடகம் & பத்திரிகை',
    'interest.teaching': 'கற்பித்தல் & கல்வி',
    'interest.agriculture': 'வேளாண்மை & இயற்கை',
    'interest.defence': 'பாதுகாப்பு & பாதுகாப்பு',
    'interest.hospitality': 'ஹோட்டல் & விருந்தோம்பல்',
    'interest.data': 'தரவு & பகுப்பாய்வு',
    
    // Priority Options
    'priority.salary': 'உயர் சம்பளம்',
    'priority.security': 'வேலை பாதுகாப்பு',
    'priority.balance': 'வேலை-வாழ்க்கை சமநிலை',
    'priority.growth': 'விரைவான வளர்ச்சி',
    'priority.helping': 'பிறருக்கு உதவுதல்',
    
    // Streams
    'stream.pcm': 'அறிவியல் (PCM - இயற்பியல், வேதியியல், கணிதம்)',
    'stream.pcb': 'அறிவியல் (PCB - இயற்பியல், வேதியியல், உயிரியல்)',
    'stream.pcmb': 'அறிவியல் (PCMB - நான்கு பாடங்களும்)',
    'stream.commerce_math': 'வணிகம் (கணிதத்துடன்)',
    'stream.commerce': 'வணிகம் (கணிதம் இல்லாமல்)',
    'stream.arts': 'கலை / மனிதநேயம்',
    
    // Career Assessment 12th Learners
    'assessment12.title': 'What Should I Study After 12th?',
    'assessment12.tamilTitle': '12-ஆம் வகுப்புக்குப் பிறகு என்ன படிக்க வேண்டும்?',
    'assessment12.subtitle': 'உங்கள் எதிர்காலம் குறித்து குழப்பமா? உங்கள் ஆர்வங்கள், திறன்கள் மற்றும் ஆளுமையின் அடிப்படையில் சரியான படிப்பைக் கண்டறிய AI உதவட்டும்',
    'assessment12.introHeading': 'கவலைப்படாதீர்கள்! உங்கள் பிரிவைச் சொல்லுங்கள், உங்களுக்கு சரியான படிப்பைக் கண்டறிவோம்',
    'assessment12.introDesc': 'உங்கள் ஆளுமை, ஆர்வங்கள் மற்றும் தொழில் இலக்குகளுக்கு பொருந்தும் படிப்புகளைக் கண்டறிய எங்கள் AI-இயங்கும் மதிப்பீட்டை எடுங்கள்.',
    'assessment12.welcomeBack': 'மீண்டும் வருக!',
    'assessment12.completedAssessments': 'நீங்கள் {stream} மாணவர், {count} மதிப்பீடு(கள்) முடித்துள்ளீர்கள்.',
    'assessment12.startJourney': 'உங்கள் கண்டுபிடிப்பு பயணத்தை தொடங்குங்கள்',
    'assessment12.takeAnother': 'மற்றொரு மதிப்பீட்டை எடுங்கள்',
    'assessment12.viewPastResults': 'முந்தைய முடிவுகளைக் காண்க',
    'assessment12.questions': 'கேள்விகள்',
    'assessment12.scenarioBased': 'சூழ்நிலை அடிப்படையிலான கேள்விகள்',
    'assessment12.minutes': 'நிமிடங்கள்',
    'assessment12.quickInsightful': 'விரைவான மற்றும் நுண்ணறிவான',
    'assessment12.courses': 'படிப்புகள்',
    'assessment12.personalizedRecs': 'தனிப்பயனாக்கப்பட்ட பரிந்துரைகள்',
    'assessment12.selectStreamTitle': 'முதலில், உங்கள் 12ஆம் வகுப்பு பற்றி சொல்லுங்கள்',
    'assessment12.selectStreamDesc': 'தனிப்பயனாக்கப்பட்ட படிப்பு பரிந்துரைகளைப் பெற உங்கள் பிரிவைத் தேர்ந்தெடுக்கவும்',
    'assessment12.detailsTitle': 'இன்னும் சில விவரங்கள்...',
    'assessment12.detailsDesc': 'இது சிறந்த பரிந்துரைகளை வழங்க உதவுகிறது',
    'assessment12.marksLabel': 'உங்கள் எதிர்பார்க்கப்படும்/பெற்ற 12ஆம் வகுப்பு மதிப்பெண்கள்:',
    'assessment12.returningUser': 'திரும்பி வரும் பயனர்: நீங்கள் முன்பு பார்க்காத புதிய கேள்விகளைக் காட்டுவோம்!',
    'assessment12.streamPCM': 'அறிவியல் - PCM',
    'assessment12.streamPCMSub': 'இயற்பியல், வேதியியல், கணிதம்',
    'assessment12.streamPCB': 'அறிவியல் - PCB',
    'assessment12.streamPCBSub': 'இயற்பியல், வேதியியல், உயிரியல்',
    'assessment12.streamPCMB': 'அறிவியல் - PCMB',
    'assessment12.streamPCMBSub': 'இயற்பியல், வேதியியல், கணிதம் & உயிரியல்',
    'assessment12.streamCommerce': 'வணிகம்',
    'assessment12.streamCommerceSub': 'கணக்கியல், வணிக ஆய்வுகள், பொருளாதாரம்',
    'assessment12.streamArts': 'கலை / மனிதநேயம்',
    'assessment12.streamArtsSub': 'வரலாறு, புவியியல், மொழிகள், உளவியல்',
    
    // Industry Trends Page
    'industry.pageTitle': 'இந்தியாவின் வேலை வாய்ப்பு 2026 - தொழில் போக்குகள்',
    'industry.pageTitleTamil': "India's Job Market 2026 - Career Trends",
    'industry.knowIndustries': 'எந்த துறைகள் வேலை வழங்குகின்றன என்பதை அறியுங்கள்',
    'industry.knowIndustriesTamil': 'Know which industries are hiring & skills you need',
    'industry.jobAlerts': 'வேலை எச்சரிக்கைகள்',
    'industry.subscribed': 'சந்தா செலுத்தப்பட்டது',
    'industry.downloadPdf': 'PDF பதிவிறக்கு',
    'industry.manageAlerts': 'வேலை எச்சரிக்கைகளை நிர்வகி',
    'industry.subscribeAlerts': 'வேலை எச்சரிக்கைகளுக்கு சந்தா செலுத்து',
    'industry.activeSubscription': 'செயலில் உள்ள சந்தா',
    'industry.unsubscribe': 'எச்சரிக்கைகளிலிருந்து விலகு',
    'industry.nameOptional': 'பெயர் (விருப்பம்)',
    'industry.emailAddress': 'மின்னஞ்சல் முகவரி',
    'industry.selectSectors': 'துறைகளைத் தேர்ந்தெடுக்கவும்',
    'industry.preferredLocations': 'விருப்பமான இடங்கள்',
    'industry.minimumSalary': 'குறைந்தபட்ச சம்பளம் (LPA)',
    'industry.anySalary': 'ஏதேனும் சம்பளம்',
    'industry.subscribing': 'சந்தா செலுத்துகிறது...',
    'industry.subscribeToAlerts': 'எச்சரிக்கைகளுக்கு சந்தா செலுத்து',
    'industry.unsubscribeNote': 'தொடர்புடைய வேலை எச்சரிக்கைகளை அனுப்புவோம். எப்போது வேண்டுமானாலும் விலகலாம்.',
    'industry.sectorsSelected': 'துறை(கள்) தேர்ந்தெடுக்கப்பட்டன',
    'industry.highGrowthSectors': 'அதிக வேலை வளர்ச்சி உள்ள துறைகள்',
    'industry.highGrowthSectorsTamil': 'Sectors with High Hiring Growth',
    'industry.salaryRange': 'சம்பள வரம்பு',
    'industry.topCompanies': 'முன்னணி நிறுவனங்கள்',
    'industry.coursesToConsider': 'பரிசீலிக்க வேண்டிய படிப்புகள்',
    'industry.tnColleges': 'தமிழ்நாடு கல்லூரிகள்',
    'industry.careerPaths': 'தொழில் பாதைகள்',
    'industry.whyGrowing': 'இந்த துறை ஏன் வளர்கிறது',
    'industry.technicalSkills': 'தேவையான தொழில்நுட்ப திறன்கள்',
    'industry.softSkills': 'தேவையான மென் திறன்கள்',
    'industry.demandLevel': 'தேவை',
    'industry.importanceLevel': 'முக்கியத்துவம்',
    'industry.streamRoadmaps': 'பிரிவு வாரியான தொழில் வரைபடங்கள்',
    'industry.bestPaths': 'சிறந்த பாதைகள்',
    'industry.recommendedCourses': 'பரிந்துரைக்கப்பட்ட படிப்புகள்',
    'industry.yearlySkillPlan': 'ஆண்டுவாரியான திறன் திட்டம்',
    'industry.salaryTrends': 'துறைவாரியான சம்பள போக்குகள்',
    'industry.entryLevel': 'ஆரம்ப நிலை',
    'industry.experienced': 'அனுபவமுள்ள',
    'industry.liveJobOpenings': 'நேரடி வேலை வாய்ப்புகள்',
    'industry.liveJobOpeningsTamil': 'Live Job Openings',
    'industry.allJobs': 'அனைத்தும்',
    'industry.savedJobs': 'சேமித்தவை',
    'industry.searchJobs': 'வேலைகள், நிறுவனங்கள், இடங்களைத் தேடு...',
    'industry.hotJob': 'பிரபலம்',
    'industry.addToCompare': 'ஒப்பிட சேர்',
    'industry.removeFromCompare': 'ஒப்பிடலிருந்து நீக்கு',
    'industry.compareJobs': 'வேலைகளை ஒப்பிடு',
    'industry.selectJobsCompare': 'ஒப்பிட 2-4 வேலைகளைத் தேர்ந்தெடுக்கவும்',
    'industry.sectors': 'துறைகள்',
    'industry.skills': 'திறன்கள்',
    'industry.newJobs': 'புதிய வேலைகள்',
    'industry.futureReady': 'எதிர்கால தயார்',
    
    // Job Portal Page
    'jobportal.findDreamJob': 'உங்கள் கனவு வேலையைக் கண்டறியுங்கள்',
    'jobportal.searchPlaceholder': 'வேலைகள், நிறுவனங்களைத் தேடு...',
    'jobportal.jobsFound': 'வேலைகள் கண்டறியப்பட்டன',
    'jobportal.refresh': 'புதுப்பி',
    'jobportal.loadMore': 'மேலும் வேலைகளை ஏற்று',
    'jobportal.noJobsFound': 'உங்கள் தேடலுக்கு பொருந்தும் வேலைகள் இல்லை.',
    'jobportal.clearFilters': 'அனைத்து வடிகட்டிகளையும் அழி',
    'jobportal.allJobs': 'அனைத்து வேலைகள்',
    'jobportal.filters': 'வடிகட்டிகள்',
    'jobportal.applyFilters': 'வடிகட்டிகளைப் பயன்படுத்து',
    'jobportal.clearAll': 'அனைத்தையும் அழி',
    'jobportal.location': 'இடம்',
    'jobportal.city': 'நகரம்',
    'jobportal.salaryRange': 'சம்பள வரம்பு',
    'jobportal.experience': 'அனுபவம்',
    'jobportal.jobType': 'வேலை வகை',
    'jobportal.walkinOnly': 'நேர்காணல் மட்டும்',
    'jobportal.fullTime': 'முழு நேரம்',
    'jobportal.partTime': 'பகுதி நேரம்',
    'jobportal.contract': 'ஒப்பந்தம்',
    'jobportal.internship': 'இன்டர்ன்ஷிப்',
    'jobportal.callNow': 'இப்போது அழை',
    'jobportal.whatsapp': 'வாட்ஸ்அப்',
    'jobportal.featured': 'சிறப்பு',
    'jobportal.walkin': 'நேர்காணல்',
    'jobportal.walkinDetails': 'நேர்காணல் விவரங்கள்',
    'jobportal.interviewDate': 'நேர்காணல் தேதி',
    'jobportal.interviewTime': 'நேர்காணல் நேரம்',
    'jobportal.interviewVenue': 'நேர்காணல் இடம்',
    'jobportal.salary': 'சம்பளம்',
    'jobportal.qualification': 'தகுதி',
    'jobportal.vacancies': 'காலிப்பணியிடங்கள்',
    'jobportal.postedAgo': 'வெளியிடப்பட்டது',
    'jobportal.description': 'விளக்கம்',
    'jobportal.responsibilities': 'பொறுப்புகள்',
    'jobportal.requirements': 'தேவைகள்',
    'jobportal.documentsRequired': 'தேவையான ஆவணங்கள்',
    'jobportal.benefits': 'நன்மைகள்',
    'jobportal.contactInfo': 'தொடர்பு தகவல்',
    'jobportal.shareJob': 'வேலையைப் பகிர்',
    'jobportal.openMaps': 'வரைபடத்தில் திற',
    'jobportal.fresher': 'புதியவர்',
    'jobportal.years': 'ஆண்டுகள்',
    'jobportal.perMonth': '/மாதம்',
    'jobportal.perYear': '/ஆண்டு',
    'jobportal.perDay': '/நாள்',
    'jobportal.negotiable': 'பேச்சுவார்த்தைக்கு உட்பட்டது',
    
    // Registration Forms - 12th Learner
    'reg12.pageTitle': '12ஆம் வகுப்பு மாணவராக பதிவு செய்க',
    'reg12.yourJourney': 'உங்கள் பயணம்',
    'reg12.stepOf': 'படி {current} / {total}',
    'reg12.progress': 'முன்னேற்றம்',
    'reg12.whyRegister': 'ஏன் பதிவு செய்ய வேண்டும்?',
    'reg12.benefit1': 'AI-இயங்கும் தொழில் வழிகாட்டுதல்',
    'reg12.benefit2': 'தனிப்பயனாக்கப்பட்ட படிப்பு பரிந்துரைகள்',
    'reg12.benefit3': 'சிறந்த நிறுவனங்களுடன் இணையுங்கள்',
    'reg12.benefit4': 'இலவச தொழில் மதிப்பீடு',
    'reg12.personalInfo': 'தனிப்பட்ட தகவல்',
    'reg12.education': 'கல்வி',
    'reg12.interests': 'ஆர்வங்கள்',
    'reg12.review': 'மறுஆய்வு',
    'reg12.tellAboutYourself': 'உங்களைப் பற்றி சொல்லுங்கள்',
    'reg12.educationalBackground': 'உங்கள் கல்வி பின்னணி',
    'reg12.passionateAbout': 'உங்கள் ஆர்வம் என்ன?',
    'reg12.reviewInfo': 'உங்கள் தகவலை மறுஆய்வு செய்யுங்கள்',
    'reg12.fullName': 'முழு பெயர்',
    'reg12.enterFullName': 'உங்கள் முழு பெயரை உள்ளிடுங்கள்',
    'reg12.phoneNumber': 'தொலைபேசி எண்',
    'reg12.emailAddress': 'மின்னஞ்சல் முகவரி',
    'reg12.emailOptional': 'your@email.com (விருப்பம்)',
    'reg12.dateOfBirth': 'பிறந்த தேதி',
    'reg12.schoolName': 'பள்ளி பெயர்',
    'reg12.enterSchoolName': 'உங்கள் பள்ளி பெயரை உள்ளிடுங்கள்',
    'reg12.board': 'வாரியம்',
    'reg12.selectBoard': 'உங்கள் வாரியத்தைத் தேர்ந்தெடுக்கவும்',
    'reg12.stream': 'பிரிவு',
    'reg12.selectStream': 'உங்கள் பிரிவைத் தேர்ந்தெடுக்கவும்',
    'reg12.expectedYear': 'எதிர்பார்க்கப்படும் தேர்ச்சி ஆண்டு',
    'reg12.selectYear': 'ஆண்டைத் தேர்ந்தெடுக்கவும்',
    'reg12.preferredCourses': 'விரும்பிய படிப்புகள்',
    'reg12.preferredCoursesPlaceholder': 'எ.கா., பொறியியல், மருத்துவம், கலை',
    'reg12.careerInterests': 'தொழில் ஆர்வங்கள்',
    'reg12.careerInterestsPlaceholder': 'எ.கா., மென்பொருள் மேம்பாடு, சுகாதாரம்',
    'reg12.preferredLocation': 'விரும்பிய இடம்',
    'reg12.selectLocation': 'இடத்தைத் தேர்ந்தெடுக்கவும்',
    'reg12.reviewYourInfo': 'உங்கள் தகவலை மறுஆய்வு செய்யுங்கள்',
    'reg12.name': 'பெயர்',
    'reg12.phone': 'தொலைபேசி',
    'reg12.email': 'மின்னஞ்சல்',
    'reg12.school': 'பள்ளி',
    'reg12.location': 'இடம்',
    'reg12.notProvided': 'வழங்கப்படவில்லை',
    'reg12.back': 'பின்னால்',
    'reg12.next': 'அடுத்து',
    'reg12.submitRegistration': 'பதிவை சமர்ப்பிக்கவும்',
    'reg12.registrationSuccess': 'பதிவு வெற்றிகரமாக முடிந்தது! விரைவில் தொடர்பு கொள்வோம்.',
    'reg12.registrationFailed': 'பதிவு தோல்வியடைந்தது. மீண்டும் முயற்சிக்கவும்.',
    'reg12.science': 'அறிவியல்',
    'reg12.commerce': 'வணிகம்',
    'reg12.artsHumanities': 'கலை/மனிதநேயம்',
    'reg12.tamilNadu': 'தமிழ்நாடு',
    'reg12.karnataka': 'கர்நாடகா',
    'reg12.kerala': 'கேரளா',
    'reg12.anywhereIndia': 'இந்தியாவில் எங்கும்',
    
    // Registration Forms - Learner
    'regLearner.pageTitle': 'கற்பவராக பதிவு செய்க',
    'regLearner.subtitle': 'உங்கள் கனவு வேலையைக் கண்டறிந்து உங்கள் தொழிலை முன்னேற்றுங்கள்',
    'regLearner.personalInfo': 'தனிப்பட்ட தகவல்',
    'regLearner.education': 'கல்வி',
    'regLearner.fullName': 'முழு பெயர்',
    'regLearner.fullNamePlaceholder': 'எ.கா., ரமேஷ் குமார்',
    'regLearner.emailAddress': 'மின்னஞ்சல் முகவரி',
    'regLearner.emailPlaceholder': 'எ.கா., ramesh@example.com',
    'regLearner.mobileNumber': 'மொபைல் எண்',
    'regLearner.mobilePlaceholder': 'எ.கா., 9876543210',
    'regLearner.dateOfBirth': 'பிறந்த தேதி',
    'regLearner.district': 'மாவட்டம்',
    'regLearner.selectDistrict': 'மாவட்டத்தைத் தேர்ந்தெடுக்கவும்',
    'regLearner.placeTown': 'இடம்/ஊர்',
    'regLearner.placePlaceholder': 'எ.கா., காந்திபுரம், டி. நகர்',
    'regLearner.institution': 'நிறுவனம்/கல்லூரி',
    'regLearner.institutionPlaceholder': 'எ.கா., அண்ணா பல்கலைக்கழகம்',
    'regLearner.degree': 'பட்டம்/தகுதி',
    'regLearner.selectDegree': 'பட்டத்தைத் தேர்ந்தெடுக்கவும்',
    'regLearner.specialization': 'சிறப்பு/முக்கிய பாடம்',
    'regLearner.specializationPlaceholder': 'எ.கா., கணினி அறிவியல், இயந்திரவியல் பொறியியல்',
    'regLearner.graduationYear': 'பட்டம் பெற்ற ஆண்டு',
    'regLearner.selectGradYear': 'ஆண்டைத் தேர்ந்தெடுக்கவும்',
    'regLearner.back': 'பின்னால்',
    'regLearner.next': 'அடுத்து',
    'regLearner.submitRegistration': 'பதிவை சமர்ப்பிக்கவும்',
    'regLearner.submitting': 'சமர்ப்பிக்கிறது...',
    'regLearner.registrationSuccess': 'பதிவு வெற்றிகரமாக முடிந்தது! JKKN தொழில் மையத்திற்கு வரவேற்கிறோம்.',
    'regLearner.fixErrors': 'படிவத்தில் உள்ள பிழைகளை சரிசெய்யவும்',
    'regLearner.registrationFailed': 'பதிவு தோல்வியடைந்தது. மீண்டும் முயற்சிக்கவும்.',
    'regLearner.degree10th': '10ஆம் வகுப்பு தேர்ச்சி',
    'regLearner.degree12th': '12ஆம் வகுப்பு தேர்ச்சி',
    'regLearner.degreeDiploma': 'டிப்ளோமா',
    'regLearner.degreeIti': 'ஐடிஐ',
    'regLearner.degreeBachelors': 'இளங்கலை பட்டம்',
    'regLearner.degreeMasters': 'முதுகலை பட்டம்',
    'regLearner.degreePhd': 'முனைவர் பட்டம்',
    
    // Registration Forms - Employer
    'regEmployer.pageTitle': 'முதலாளியாக பதிவு செய்க',
    'regEmployer.subtitle': 'JKKN நிறுவனங்களின் திறமையான பட்டதாரிகளுடன் இணையுங்கள்',
    'regEmployer.companyInfo': 'நிறுவன தகவல்',
    'regEmployer.contactPerson': 'தொடர்பு நபர்',
    'regEmployer.hiringNeeds': 'பணியமர்த்தல் தேவைகள்',
    'regEmployer.review': 'மறுஆய்வு',
    'regEmployer.companyName': 'நிறுவன பெயர்',
    'regEmployer.enterCompanyName': 'நிறுவன பெயரை உள்ளிடுங்கள்',
    'regEmployer.industry': 'துறை',
    'regEmployer.selectIndustry': 'துறையைத் தேர்ந்தெடுக்கவும்',
    'regEmployer.companySize': 'நிறுவன அளவு',
    'regEmployer.selectCompanySize': 'நிறுவன அளவைத் தேர்ந்தெடுக்கவும்',
    'regEmployer.website': 'இணையதளம்',
    'regEmployer.websitePlaceholder': 'https://www.company.com',
    'regEmployer.contactPersonName': 'தொடர்பு நபர் பெயர்',
    'regEmployer.fullName': 'முழு பெயர்',
    'regEmployer.emailAddress': 'மின்னஞ்சல் முகவரி',
    'regEmployer.emailPlaceholder': 'hr@company.com',
    'regEmployer.phoneNumber': 'தொலைபேசி எண்',
    'regEmployer.phonePlaceholder': '9876543210',
    'regEmployer.designation': 'பதவி',
    'regEmployer.designationPlaceholder': 'எ.கா., HR மேலாளர், திறமை கையகப்படுத்துதல் தலைவர்',
    'regEmployer.rolesHiring': 'பணியமர்த்தும் பதவிகள்',
    'regEmployer.rolesPlaceholder': 'எ.கா., மென்பொருள் பொறியாளர், தரவு ஆய்வாளர், செவிலியர்',
    'regEmployer.experienceLevel': 'தேவையான அனுபவ நிலை',
    'regEmployer.selectExperience': 'அனுபவ நிலையைத் தேர்ந்தெடுக்கவும்',
    'regEmployer.hiringLocations': 'பணியமர்த்தும் இடங்கள்',
    'regEmployer.locationsPlaceholder': 'எ.கா., சென்னை, பெங்களூரு, ரிமோட்',
    'regEmployer.hiringTimeline': 'பணியமர்த்தல் காலக்கெடு',
    'regEmployer.selectTimeline': 'காலக்கெடுவைத் தேர்ந்தெடுக்கவும்',
    'regEmployer.reviewYourInfo': 'உங்கள் தகவலை மறுஆய்வு செய்யுங்கள்',
    'regEmployer.company': 'நிறுவனம்',
    'regEmployer.contactName': 'தொடர்பு பெயர்',
    'regEmployer.contactEmail': 'தொடர்பு மின்னஞ்சல்',
    'regEmployer.hiringRoles': 'பணியமர்த்தும் பதவிகள்',
    'regEmployer.locations': 'இடங்கள்',
    'regEmployer.notProvided': 'வழங்கப்படவில்லை',
    'regEmployer.back': 'பின்னால்',
    'regEmployer.next': 'அடுத்து',
    'regEmployer.submitRegistration': 'பதிவை சமர்ப்பிக்கவும்',
    'regEmployer.registrationSuccess': 'பதிவு வெற்றிகரமாக முடிந்தது!',
    'regEmployer.registrationFailed': 'பதிவு தோல்வியடைந்தது. மீண்டும் முயற்சிக்கவும்.',
    'regEmployer.industryIt': 'ஐடி / மென்பொருள்',
    'regEmployer.industryHealthcare': 'சுகாதாரம் / மருந்து',
    'regEmployer.industryManufacturing': 'உற்பத்தி',
    'regEmployer.industryFinance': 'நிதி / வங்கி',
    'regEmployer.industryEducation': 'கல்வி',
    'regEmployer.industryRetail': 'சில்லறை / இ-வணிகம்',
    'regEmployer.industryConsulting': 'ஆலோசனை',
    'regEmployer.industryOther': 'மற்றவை',
    'regEmployer.size1_50': '1-50 பணியாளர்கள்',
    'regEmployer.size51_200': '51-200 பணியாளர்கள்',
    'regEmployer.size201_500': '201-500 பணியாளர்கள்',
    'regEmployer.size501_1000': '501-1000 பணியாளர்கள்',
    'regEmployer.size1000plus': '1000+ பணியாளர்கள்',
    'regEmployer.expFresher': 'புதியவர்கள் மட்டும்',
    'regEmployer.exp0_2': '0-2 ஆண்டுகள்',
    'regEmployer.exp2_5': '2-5 ஆண்டுகள்',
    'regEmployer.expMixed': 'கலவை (புதியவர் + அனுபவமுள்ளவர்)',
    'regEmployer.timelineImmediate': 'உடனடியாக',
    'regEmployer.timeline1Month': '1 மாதத்திற்குள்',
    'regEmployer.timeline3Months': '3 மாதங்களுக்குள்',
    'regEmployer.timeline6Months': '6 மாதங்களுக்குள்',
    
    // Career Chat - Suggested Questions
    'chat.popularQuestions': '12ஆம் வகுப்பு மாணவர்களுக்கான பிரபலமான கேள்விகள்',
    'chat.streamSpecificQuestions': 'பாடப்பிரிவு சார்ந்த கேள்விகள்',
    'chat.welcomeTitle': 'வணக்கம்! நான் உங்கள் AI தொழில் ஆலோசகர்',
    'chat.welcomeDesc': 'தொழில்கள், படிப்புகள், கல்லூரிகள் அல்லது வழிகாட்டுதல் பற்றி என்னிடம் எதையும் கேளுங்கள்!',
    'chat.welcomeTamil': 'Ask me about careers, courses, or colleges!',
    'chat.inputPlaceholder': 'தொழில்கள், படிப்புகள் அல்லது கல்லூரிகள் பற்றி கேளுங்கள்...',
    
    // Career Planning Questions
    'chat.q1': '12ஆம் வகுப்பு அறிவியல் (PCM) பிறகு சிறந்த தொழில் வாய்ப்புகள் என்ன?',
    'chat.q2': 'எந்த படிப்புகள் அதிக சம்பள வாய்ப்புகளைக் கொண்டுள்ளன?',
    'chat.q3': 'பொறியியல் மற்றும் மருத்துவத்திற்கு இடையே எப்படி தேர்வு செய்வது?',
    'chat.q4': 'அதிக வளர்ச்சியுள்ள வளர்ந்து வரும் தொழில்கள் என்ன?',
    'chat.q5': 'எந்த நுழைவுத் தேர்வுகளுக்கு தயாராக வேண்டும்?',
    'chat.q6': 'தமிழ்நாட்டில் சிறந்த கல்லூரிகள் எவை?',
    'chat.q7': '12ஆம் வகுப்புக்குப் பிறகு வெளிநாட்டில் படிக்க முடியுமா?',
    'chat.q8': 'என் தொழிலுக்கு என்ன திறன்களை வளர்க்க வேண்டும்?',
    
    // Stream-Specific Questions
    'chat.stream1': 'PCB மாணவர்களுக்கான தொழில் வாய்ப்புகள்',
    'chat.stream2': 'வணிகப் பாடப்பிரிவு சிறந்த படிப்புகள்',
    'chat.stream3': 'கலைப் பாடப்பிரிவு தொழில் பாதைகள்',
    'chat.stream4': 'PCMB தொழில் சேர்க்கைகள்',
    
    // Exam Preparation Questions
    'chat.examPrepHeader': 'தேர்வு தயாரிப்பு குறிப்புகள்',
    'chat.exam1': '3 மாதங்களில் JEE Main-க்கு எப்படி தயாராவது?',
    'chat.exam2': 'NEET தயாரிப்புக்கான சிறந்த படிப்பு திட்டம்',
    'chat.exam3': 'சிறந்த பல்கலைக்கழகங்களுக்கான CUET-ஐ வெல்ல குறிப்புகள்',
    'chat.exam4': 'போர்டு தேர்வுகள் மற்றும் நுழைவுத் தேர்வுகளை எப்படி நிர்வகிப்பது?',
    
    // Scholarship & Financial Aid Questions
    'chat.scholarshipHeader': 'உதவித்தொகை & நிதி உதவி',
    'chat.scholarship1': '12ஆம் வகுப்பு மாணவர்களுக்கு என்ன உதவித்தொகைகள் உள்ளன?',
    'chat.scholarship2': 'அரசு கல்விக் கடன்களுக்கு எப்படி விண்ணப்பிப்பது?',
    'chat.scholarship3': 'பொறியியல் மாணவர்களுக்கான தகுதி அடிப்படையிலான உதவித்தொகைகள்',
    'chat.scholarship4': 'வெளிநாட்டில் படிக்க நிதி உதவி விருப்பங்கள்',
  },
  // Hindi - Comprehensive translations
  hi: {
    // TopBar & Navigation
    'topbar.aiChat': 'AI चैट',
    'topbar.login': 'लॉगिन',
    'topbar.register': 'रजिस्टर',
    'topbar.careerPath': 'करियर पथ - 2026-2032',
    'nav.home': 'होम',
    'nav.careerHub': 'करियर हब',
    'nav.careerAssessment': 'करियर मूल्यांकन',
    'nav.findColleges': 'कॉलेज खोजें',
    'nav.scholarships': 'छात्रवृत्ति खोजक',
    'nav.cutoffCalculator': 'कटऑफ कैलकुलेटर',
    'nav.entranceExams': 'प्रवेश परीक्षाएं',
    'nav.governmentJobs': 'सरकारी नौकरियां',
    'nav.counselingSimulator': 'काउंसलिंग सिम्युलेटर',
    'nav.pyq': 'पिछले वर्ष के प्रश्न',
    'nav.tagline': 'खोजें, डिज़ाइन करें, करें',
    
    // Homepage
    'hero.title': 'AI होराइज़न्स:',
    'hero.subtitle': 'खोजें, डिज़ाइन करें, करें',
    'hero.description': 'तमिलनाडु छात्रों के लिए AI-संचालित करियर मार्गदर्शन',
    
    // Career Assessment
    'assessment.title': 'अपना मूल्यांकन चुनें',
    'assessment.aiChat': 'करियर AI चैट',
    'assessment.aiChatDesc': 'AI करियर काउंसलर से चैट करें - कोई भी करियर संबंधित प्रश्न तुरंत पूछें',
    'assessment.startChat': 'चैट शुरू करें',
    'assessment.unlimited': 'असीमित',
    'assessment.voiceSupport': 'वॉयस सपोर्ट',
    
    // Career Predictor
    'predictor.title': 'AI करियर प्रेडिक्टर',
    'predictor.subtitle': 'अपनी रुचियों और कौशल के आधार पर AI-संचालित करियर भविष्यवाणियां प्राप्त करें',
    'predictor.predictCareer': 'मेरा करियर भविष्यवाणी करें',
    'predictor.basicInfo': 'बुनियादी जानकारी',
    'predictor.selectStream': 'अपनी स्ट्रीम चुनें',
    'predictor.selectPercentage': 'अपेक्षित 12वीं प्रतिशत',
    'predictor.selectInterests': 'अपनी रुचियां चुनें',
    'predictor.selectInterestsDesc': '3 क्षेत्र चुनें जो आपको सबसे ज्यादा उत्साहित करते हैं',
    'predictor.yourRecommendations': 'आपकी कोर्स सिफारिशें',
    
    // Interests
    'interest.technology': 'टेक्नोलॉजी और कंप्यूटर',
    'interest.science': 'विज्ञान और अनुसंधान',
    'interest.healthcare': 'स्वास्थ्य सेवा और चिकित्सा',
    'interest.business': 'व्यापार और वित्त',
    'interest.law': 'कानून और न्याय',
    'interest.arts': 'कला और डिज़ाइन',
    'interest.aviation': 'विमानन और यात्रा',
    'interest.construction': 'भवन और निर्माण',
    'interest.media': 'मीडिया और पत्रकारिता',
    'interest.teaching': 'शिक्षण और शिक्षा',
    'interest.agriculture': 'कृषि और प्रकृति',
    'interest.defence': 'रक्षा और सुरक्षा',
    'interest.hospitality': 'होटल और आतिथ्य',
    'interest.data': 'डेटा और एनालिटिक्स',
    
    // Preferences
    'pref.whatMatters': 'आपके लिए सबसे महत्वपूर्ण क्या है?',
    'pref.pickPriorities': '2 प्राथमिकताएं चुनें',
    'pref.highSalary': 'उच्च वेतन',
    'pref.jobSecurity': 'नौकरी की सुरक्षा',
    'pref.workLifeBalance': 'कार्य-जीवन संतुलन',
    'pref.fastGrowth': 'तेज़ विकास',
    'pref.helpingOthers': 'दूसरों की मदद करना',
    'pref.budget': 'शिक्षा के लिए बजट',
    'pref.duration': 'पसंदीदा कोर्स अवधि',
    
    // Government Exams
    'govExam.title': 'सरकारी परीक्षा मॉक टेस्ट',
    'govExam.desc': 'श्रेणी-वार अभ्यास प्रश्नों के साथ सरकारी परीक्षाओं की तैयारी करें',
    'govExam.aiQuestions': 'AI प्रश्न',
    'govExam.generateFresh': 'AI का उपयोग करके नए प्रश्न बनाएं',
    'govExam.defence': 'रक्षा और अर्धसैनिक',
    'govExam.railway': 'रेलवे नौकरियां',
    'govExam.ssc': 'SSC',
    'govExam.banking': 'बैंकिंग और बीमा',
    'govExam.tnState': 'तमिलनाडु राज्य सरकार',
    'govExam.otherCentral': 'अन्य केंद्र सरकार',
    'govExam.questions': 'प्रश्न',
    'govExam.start': 'शुरू करें',
    
    // Common
    'common.loading': 'लोड हो रहा है...',
    'common.back': 'वापस',
    'common.next': 'अगला',
    'common.submit': 'जमा करें',
    'common.search': 'खोजें',
    'common.filter': 'फ़िल्टर',
    'common.download': 'डाउनलोड',
    'common.viewDetails': 'विवरण देखें',
    'common.startTest': 'टेस्ट शुरू करें',
    'common.predictCareer': 'मेरा करियर भविष्यवाणी करें',
    
    // Footer
    'footer.rights': 'सर्वाधिकार सुरक्षित',
    'footer.privacy': 'गोपनीयता नीति',
    'footer.terms': 'सेवा की शर्तें',
    
    // Language Selector
    'lang.select': 'भाषा चुनें',
    'lang.current': 'वर्तमान भाषा',
  },
  // Telugu - Comprehensive translations
  te: {
    'topbar.aiChat': 'AI చాట్',
    'topbar.login': 'లాగిన్',
    'topbar.register': 'రిజిస్టర్',
    'nav.home': 'హోమ్',
    'nav.careerHub': 'కెరీర్ హబ్',
    'nav.careerAssessment': 'కెరీర్ అసెస్‌మెంట్',
    'nav.governmentJobs': 'ప్రభుత్వ ఉద్యోగాలు',
    'nav.entranceExams': 'ప్రవేశ పరీక్షలు',
    'hero.title': 'AI హోరైజన్స్:',
    'common.loading': 'లోడ్ అవుతోంది...',
    'common.back': 'వెనుకకు',
    'common.next': 'తదుపరి',
    'common.submit': 'సమర్పించు',
    'common.search': 'వెతకండి',
    'lang.select': 'భాష ఎంచుకోండి',
  },
  // Kannada - Comprehensive translations
  kn: {
    'topbar.aiChat': 'AI ಚಾಟ್',
    'topbar.login': 'ಲಾಗಿನ್',
    'topbar.register': 'ನೋಂದಣಿ',
    'nav.home': 'ಮುಖಪುಟ',
    'nav.careerHub': 'ಕೆರಿಯರ್ ಹಬ್',
    'nav.careerAssessment': 'ಕೆರಿಯರ್ ಮೌಲ್ಯಮಾಪನ',
    'nav.governmentJobs': 'ಸರ್ಕಾರಿ ಉದ್ಯೋಗಗಳು',
    'nav.entranceExams': 'ಪ್ರವೇಶ ಪರೀಕ್ಷೆಗಳು',
    'hero.title': 'AI ಹೊರೈಜನ್ಸ್:',
    'common.loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    'common.back': 'ಹಿಂದೆ',
    'common.next': 'ಮುಂದೆ',
    'common.submit': 'ಸಲ್ಲಿಸಿ',
    'common.search': 'ಹುಡುಕಿ',
    'lang.select': 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
  },
  // Malayalam - Comprehensive translations
  ml: {
    'topbar.aiChat': 'AI ചാറ്റ്',
    'topbar.login': 'ലോഗിൻ',
    'topbar.register': 'രജിസ്റ്റർ',
    'nav.home': 'ഹോം',
    'nav.careerHub': 'കരിയർ ഹബ്',
    'nav.careerAssessment': 'കരിയർ അസെസ്മെന്റ്',
    'nav.governmentJobs': 'സർക്കാർ ജോലികൾ',
    'nav.entranceExams': 'പ്രവേശന പരീക്ഷകൾ',
    'hero.title': 'AI ഹൊറൈസൺസ്:',
    'common.loading': 'ലോഡ് ചെയ്യുന്നു...',
    'common.back': 'പിന്നോട്ട്',
    'common.next': 'അടുത്തത്',
    'common.submit': 'സമർപ്പിക്കുക',
    'common.search': 'തിരയുക',
    'lang.select': 'ഭാഷ തിരഞ്ഞെടുക്കുക',
  },
  // Bengali - Comprehensive translations
  bn: {
    'topbar.aiChat': 'AI চ্যাট',
    'topbar.login': 'লগইন',
    'topbar.register': 'নিবন্ধন',
    'nav.home': 'হোম',
    'nav.careerHub': 'ক্যারিয়ার হাব',
    'nav.careerAssessment': 'ক্যারিয়ার মূল্যায়ন',
    'nav.governmentJobs': 'সরকারি চাকরি',
    'nav.entranceExams': 'প্রবেশিকা পরীক্ষা',
    'hero.title': 'AI হোরাইজন্স:',
    'common.loading': 'লোড হচ্ছে...',
    'common.back': 'পিছনে',
    'common.next': 'পরবর্তী',
    'common.submit': 'জমা দিন',
    'common.search': 'খুঁজুন',
    'lang.select': 'ভাষা নির্বাচন করুন',
  },
  // Marathi - Comprehensive translations
  mr: {
    'topbar.aiChat': 'AI चॅट',
    'topbar.login': 'लॉगिन',
    'topbar.register': 'नोंदणी',
    'nav.home': 'मुख्यपृष्ठ',
    'nav.careerHub': 'करिअर हब',
    'nav.careerAssessment': 'करिअर मूल्यांकन',
    'nav.governmentJobs': 'सरकारी नोकऱ्या',
    'nav.entranceExams': 'प्रवेश परीक्षा',
    'hero.title': 'AI होरायझन्स:',
    'common.loading': 'लोड होत आहे...',
    'common.back': 'मागे',
    'common.next': 'पुढे',
    'common.submit': 'सबमिट करा',
    'common.search': 'शोधा',
    'lang.select': 'भाषा निवडा',
  },
  // Gujarati - Comprehensive translations
  gu: {
    'topbar.aiChat': 'AI ચેટ',
    'topbar.login': 'લૉગિન',
    'topbar.register': 'નોંધણી',
    'nav.home': 'હોમ',
    'nav.careerHub': 'કારકિર્દી હબ',
    'nav.careerAssessment': 'કારકિર્દી મૂલ્યાંકન',
    'nav.governmentJobs': 'સરકારી નોકરીઓ',
    'nav.entranceExams': 'પ્રવેશ પરીક્ષાઓ',
    'hero.title': 'AI હોરાઇઝન્સ:',
    'common.loading': 'લોડ થઈ રહ્યું છે...',
    'common.back': 'પાછળ',
    'common.next': 'આગળ',
    'common.submit': 'સબમિટ કરો',
    'common.search': 'શોધો',
    'lang.select': 'ભાષા પસંદ કરો',
  },
  // Punjabi - Comprehensive translations
  pa: {
    'topbar.aiChat': 'AI ਚੈਟ',
    'topbar.login': 'ਲੌਗਇਨ',
    'topbar.register': 'ਰਜਿਸਟਰ',
    'nav.home': 'ਘਰ',
    'nav.careerHub': 'ਕੈਰੀਅਰ ਹੱਬ',
    'nav.careerAssessment': 'ਕੈਰੀਅਰ ਮੁਲਾਂਕਣ',
    'nav.governmentJobs': 'ਸਰਕਾਰੀ ਨੌਕਰੀਆਂ',
    'nav.entranceExams': 'ਦਾਖਲਾ ਪ੍ਰੀਖਿਆਵਾਂ',
    'hero.title': 'AI ਹੋਰਾਈਜ਼ਨਸ:',
    'common.loading': 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
    'common.back': 'ਪਿੱਛੇ',
    'common.next': 'ਅੱਗੇ',
    'common.submit': 'ਜਮ੍ਹਾਂ ਕਰੋ',
    'common.search': 'ਖੋਜੋ',
    'lang.select': 'ਭਾਸ਼ਾ ਚੁਣੋ',
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const stored = localStorage.getItem('jkkn_language');
      // Validate stored language is still supported
      if (stored && SUPPORTED_LANGUAGES.some(l => l.code === stored)) {
        return stored as Language;
      }
      return 'en';
    }
    return 'en';
  });

  // Save language to localStorage whenever it changes
  useEffect(() => {
    localStorage.setItem('jkkn_language', language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    // Try current language first, then fall back to Tamil (for Tamil-specific content), then English
    return translations[language]?.[key] || translations['ta']?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
