import { EntranceExam, CategoryInfo, StateInfo, IndianState } from './types';

export const indianStates: StateInfo[] = [
  { id: 'all', label: 'All India', shortCode: 'ALL' },
  { id: 'national', label: 'National Level', shortCode: 'NAT' },
  { id: 'andhra-pradesh', label: 'Andhra Pradesh', shortCode: 'AP' },
  { id: 'assam', label: 'Assam', shortCode: 'AS' },
  { id: 'bihar', label: 'Bihar', shortCode: 'BR' },
  { id: 'chhattisgarh', label: 'Chhattisgarh', shortCode: 'CG' },
  { id: 'delhi', label: 'Delhi', shortCode: 'DL' },
  { id: 'goa', label: 'Goa', shortCode: 'GA' },
  { id: 'gujarat', label: 'Gujarat', shortCode: 'GJ' },
  { id: 'haryana', label: 'Haryana', shortCode: 'HR' },
  { id: 'himachal-pradesh', label: 'Himachal Pradesh', shortCode: 'HP' },
  { id: 'jharkhand', label: 'Jharkhand', shortCode: 'JH' },
  { id: 'karnataka', label: 'Karnataka', shortCode: 'KA' },
  { id: 'kerala', label: 'Kerala', shortCode: 'KL' },
  { id: 'madhya-pradesh', label: 'Madhya Pradesh', shortCode: 'MP' },
  { id: 'maharashtra', label: 'Maharashtra', shortCode: 'MH' },
  { id: 'manipur', label: 'Manipur', shortCode: 'MN' },
  { id: 'meghalaya', label: 'Meghalaya', shortCode: 'ML' },
  { id: 'mizoram', label: 'Mizoram', shortCode: 'MZ' },
  { id: 'nagaland', label: 'Nagaland', shortCode: 'NL' },
  { id: 'odisha', label: 'Odisha', shortCode: 'OR' },
  { id: 'punjab', label: 'Punjab', shortCode: 'PB' },
  { id: 'rajasthan', label: 'Rajasthan', shortCode: 'RJ' },
  { id: 'sikkim', label: 'Sikkim', shortCode: 'SK' },
  { id: 'tamil-nadu', label: 'Tamil Nadu', shortCode: 'TN' },
  { id: 'telangana', label: 'Telangana', shortCode: 'TS' },
  { id: 'tripura', label: 'Tripura', shortCode: 'TR' },
  { id: 'uttar-pradesh', label: 'Uttar Pradesh', shortCode: 'UP' },
  { id: 'uttarakhand', label: 'Uttarakhand', shortCode: 'UK' },
  { id: 'west-bengal', label: 'West Bengal', shortCode: 'WB' },
];

export const examCategories: CategoryInfo[] = [
  {
    id: 'engineering',
    label: 'Engineering / Technology',
    icon: '⚙️',
    color: 'text-[#1976D2]',
    bgColor: 'bg-[#E3F2FD]',
    borderColor: 'border-[#1976D2]',
  },
  {
    id: 'medical',
    label: 'Medical / Pharmacy',
    icon: '🏥',
    color: 'text-[#D32F2F]',
    bgColor: 'bg-[#FFEBEE]',
    borderColor: 'border-[#D32F2F]',
  },
  {
    id: 'management',
    label: 'Management / Law',
    icon: '💼',
    color: 'text-[#7B1FA2]',
    bgColor: 'bg-[#F3E5F5]',
    borderColor: 'border-[#7B1FA2]',
  },
  {
    id: 'design',
    label: 'Design / Architecture',
    icon: '🎨',
    color: 'text-[#F59E0B]',
    bgColor: 'bg-[#FFF8E1]',
    borderColor: 'border-[#F59E0B]',
  },
  {
    id: 'agriculture',
    label: 'Agriculture / Veterinary',
    icon: '🌾',
    color: 'text-[#2E7D32]',
    bgColor: 'bg-[#E8F5E9]',
    borderColor: 'border-[#2E7D32]',
  },
  {
    id: 'other',
    label: 'Other Professional',
    icon: '🎖️',
    color: 'text-[#455A64]',
    bgColor: 'bg-[#ECEFF1]',
    borderColor: 'border-[#455A64]',
  },
];

export const entranceExams: EntranceExam[] = [
  // ============ ENGINEERING EXAMS ============
  {
    id: 'jee-main',
    name: 'JEE Main',
    fullForm: 'Joint Entrance Examination Main',
    conductingBody: 'National Testing Agency (NTA)',
    examMode: 'Computer Based Test (CBT)',
    duration: '3 hours',
    syllabus: ['Physics - 25 Questions (100 marks)', 'Chemistry - 25 Questions (100 marks)', 'Mathematics - 25 Questions (100 marks)', 'Total: 75 Questions, 300 Marks'],
    eligibility: ['12th pass with PCM', 'Minimum 75% (65% for SC/ST) or Top 20 percentile', 'Age: No upper limit', 'Maximum 3 consecutive attempts'],
    importantDates: {
      registration: 'November 2024',
      examDate: 'January & April 2025',
      resultDate: 'February & May 2025',
    },
    applicationFee: {
      general: '₹1,000',
      scst: '₹500',
    },
    collegesAccepting: ['31 NITs', '26 IIITs', 'GFTIs', 'State Engineering Colleges via JoSAA'],
    officialWebsite: 'https://jeemain.nta.nic.in',
    category: 'engineering',
    state: 'national',
  },
  {
    id: 'jee-advanced',
    name: 'JEE Advanced',
    fullForm: 'Joint Entrance Examination Advanced',
    conductingBody: 'IIT (Rotating - IIT Madras 2025)',
    examMode: 'Computer Based Test (CBT)',
    duration: '3 hours each (Paper 1 & 2)',
    syllabus: ['Advanced Physics', 'Advanced Chemistry', 'Advanced Mathematics', 'Conceptual & application-based questions'],
    eligibility: ['Top 2,50,000 JEE Main qualifiers only', 'Age: Born on or after Oct 1, 2000', 'Maximum 2 attempts in consecutive years', '12th with 75% (65% for SC/ST)'],
    importantDates: {
      registration: 'April 2025',
      examDate: 'May 2025',
      resultDate: 'June 2025',
    },
    applicationFee: {
      general: '₹2,800',
      scst: '₹1,400',
    },
    collegesAccepting: ['23 IITs across India', 'IIT Bombay', 'IIT Delhi', 'IIT Madras', 'IIT Kanpur'],
    officialWebsite: 'https://jeeadv.ac.in',
    category: 'engineering',
    state: 'national',
  },
  {
    id: 'bitsat',
    name: 'BITSAT',
    fullForm: 'Birla Institute of Technology and Science Admission Test',
    conductingBody: 'BITS Pilani',
    examMode: 'Computer Based Test (CBT)',
    duration: '3 hours (No breaks)',
    syllabus: ['Physics - 40 Questions', 'Chemistry - 40 Questions', 'Mathematics - 45 Questions', 'English - 10 Questions', 'Logical Reasoning - 25 Questions', 'Total: 130 Questions (No negative marking for bonus)'],
    eligibility: ['12th pass with PCM', 'Minimum 75% aggregate with 60% in each PCM subject', 'First class in all subjects', 'No age limit'],
    importantDates: {
      registration: 'January 2025',
      examDate: 'May-June 2025',
      resultDate: 'July 2025',
    },
    applicationFee: {
      general: '₹4,500',
      scst: '₹4,500',
    },
    collegesAccepting: ['BITS Pilani (Rajasthan)', 'BITS Goa', 'BITS Hyderabad', 'BITS Dubai'],
    officialWebsite: 'https://www.bitsadmission.com',
    category: 'engineering',
    state: 'national',
  },
  {
    id: 'tnea',
    name: 'TNEA',
    fullForm: 'Tamil Nadu Engineering Admissions',
    conductingBody: 'Anna University',
    examMode: 'Merit Based (No Exam)',
    duration: 'N/A - Based on 12th marks',
    syllabus: ['12th PCM marks considered', 'Cutoff calculation formula'],
    eligibility: ['12th pass with PCM', 'Tamil Nadu domicile', 'Minimum 50% in PCM'],
    importantDates: {
      registration: 'May 2025',
      examDate: 'N/A (Merit based)',
      resultDate: 'July 2025',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    collegesAccepting: ['Anna University', '500+ Engineering Colleges in Tamil Nadu'],
    officialWebsite: 'https://www.tneaonline.org',
    category: 'engineering',
    state: 'tamil-nadu',
  },
  // State Level Engineering Exams
  {
    id: 'mht-cet',
    name: 'MHT-CET',
    fullForm: 'Maharashtra Common Entrance Test',
    conductingBody: 'State CET Cell, Maharashtra',
    examMode: 'Computer Based Test (CBT)',
    duration: '90 minutes per paper (3 papers)',
    syllabus: ['Physics - 50 Questions', 'Chemistry - 50 Questions', 'Mathematics - 50 Questions', 'Total: 150 Questions', 'Based on Maharashtra HSC + JEE Main syllabus'],
    eligibility: ['12th pass with PCM', 'Maharashtra domicile preferred', 'Minimum 45% (40% for reserved)', 'Open to all state students'],
    importantDates: {
      registration: 'February 2025',
      examDate: 'April-May 2025',
      resultDate: 'June 2025',
    },
    applicationFee: {
      general: '₹800',
      scst: '₹600',
    },
    collegesAccepting: ['COEP Pune', 'VJTI Mumbai', 'PICT Pune', 'SPIT Mumbai', '400+ Maharashtra Engineering Colleges'],
    officialWebsite: 'https://cetcell.mahacet.org',
    category: 'engineering',
    state: 'maharashtra',
  },
  {
    id: 'wbjee',
    name: 'WBJEE',
    fullForm: 'West Bengal Joint Entrance Examination',
    conductingBody: 'West Bengal Joint Entrance Examinations Board',
    examMode: 'Pen & Paper (OMR) - Offline',
    duration: '2 hours per paper',
    syllabus: ['Paper 1: Mathematics - 75 Questions', 'Paper 2: Physics - 40 Questions + Chemistry - 40 Questions', 'Total: 155 Questions', 'WB Board + CBSE syllabus'],
    eligibility: ['12th pass with PCM', 'Minimum 45% aggregate', 'No domicile requirement (open to all)', 'Age: No limit'],
    importantDates: {
      registration: 'December 2024',
      examDate: 'April 2025',
      resultDate: 'June 2025',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹400',
    },
    collegesAccepting: ['Jadavpur University', 'IIEST Shibpur', 'Kalyani Govt Engg College', 'WBUT Colleges', '200+ Engineering Colleges in WB'],
    officialWebsite: 'https://wbjeeb.nic.in',
    category: 'engineering',
    state: 'west-bengal',
  },
  {
    id: 'ap-eamcet',
    name: 'AP EAMCET',
    fullForm: 'Andhra Pradesh Engineering, Agriculture & Medical Common Entrance Test',
    conductingBody: 'JNTU Kakinada (on behalf of APSCHE)',
    examMode: 'Computer Based Test (CBT)',
    duration: '3 hours',
    syllabus: ['Mathematics - 80 Questions', 'Physics - 40 Questions', 'Chemistry - 40 Questions', 'Total: 160 Questions', 'AP Intermediate syllabus'],
    eligibility: ['12th/Intermediate with PCM', 'AP domicile mandatory', 'Minimum 45% (40% for reserved)', 'Age: No limit'],
    importantDates: {
      registration: 'March 2025',
      examDate: 'May 2025',
      resultDate: 'June 2025',
    },
    applicationFee: {
      general: '₹650',
      scst: '₹450',
    },
    collegesAccepting: ['JNTU Kakinada', 'AU College of Engineering Vizag', 'SVUCE Tirupati', '300+ AP Engineering Colleges'],
    officialWebsite: 'https://cets.apsche.ap.gov.in',
    category: 'engineering',
    state: 'andhra-pradesh',
  },
  {
    id: 'ts-eamcet',
    name: 'TS EAMCET',
    fullForm: 'Telangana State Engineering, Agriculture & Medical Common Entrance Test',
    conductingBody: 'JNTU Hyderabad (on behalf of TSCHE)',
    examMode: 'Computer Based Test (CBT)',
    duration: '3 hours',
    syllabus: ['Mathematics - 80 Questions', 'Physics - 40 Questions', 'Chemistry - 40 Questions', 'Total: 160 Questions', 'Telangana Intermediate syllabus'],
    eligibility: ['12th/Intermediate with PCM', 'Telangana domicile required', 'Minimum 45% (40% for reserved)', 'Age: No limit'],
    importantDates: {
      registration: 'March 2025',
      examDate: 'May 2025',
      resultDate: 'June 2025',
    },
    applicationFee: {
      general: '₹800',
      scst: '₹400',
    },
    collegesAccepting: ['JNTU Hyderabad', 'Osmania University', 'CBIT Hyderabad', 'Vasavi College', '300+ Telangana Engineering Colleges'],
    officialWebsite: 'https://eamcet.tsche.ac.in',
    category: 'engineering',
    state: 'telangana',
  },
  {
    id: 'keam',
    name: 'KEAM',
    fullForm: 'Kerala Engineering Architecture Medical',
    conductingBody: 'Commissioner for Entrance Examinations (CEE), Kerala',
    examMode: 'Pen & Paper (OMR)',
    duration: '2.5 hours per paper',
    syllabus: ['Physics', 'Chemistry', 'Mathematics', 'Kerala +2 syllabus'],
    eligibility: ['12th pass with PCM', 'Kerala domicile', 'Minimum 45% in PCM'],
    importantDates: {
      registration: 'February 2025',
      examDate: 'May 2025',
      resultDate: 'June 2025',
    },
    applicationFee: {
      general: '₹1,000',
      scst: '₹500',
    },
    collegesAccepting: ['CET Trivandrum', 'NIT Calicut', 'GEC Thrissur', '180+ Kerala Engineering Colleges'],
    officialWebsite: 'https://cee.kerala.gov.in',
    category: 'engineering',
    state: 'kerala',
  },
  {
    id: 'kcet',
    name: 'KCET',
    fullForm: 'Karnataka Common Entrance Test',
    conductingBody: 'Karnataka Examination Authority (KEA)',
    examMode: 'Pen & Paper (OMR)',
    duration: '80 minutes per subject',
    syllabus: ['Physics', 'Chemistry', 'Mathematics', 'Karnataka PUC syllabus'],
    eligibility: ['12th PUC with PCM', 'Karnataka domicile', 'Minimum 45% (40% for reserved)'],
    importantDates: {
      registration: 'February 2025',
      examDate: 'April 2025',
      resultDate: 'June 2025',
    },
    applicationFee: {
      general: '₹650',
      scst: '₹500',
    },
    collegesAccepting: ['RVCE Bangalore', 'MSRIT', 'BMS Bangalore', '200+ Karnataka Engineering Colleges'],
    officialWebsite: 'https://cetonline.karnataka.gov.in',
    category: 'engineering',
    state: 'karnataka',
  },
  {
    id: 'comedk',
    name: 'COMEDK UGET',
    fullForm: 'Consortium of Medical, Engineering and Dental Colleges of Karnataka',
    conductingBody: 'COMEDK',
    examMode: 'Computer Based Test (CBT)',
    duration: '3 hours',
    syllabus: ['Physics - 60 Questions', 'Chemistry - 60 Questions', 'Mathematics - 60 Questions', 'Total: 180 Questions', 'CBSE/ICSE/State Board syllabus'],
    eligibility: ['12th pass with PCM', 'No domicile restriction (open to all India)', 'Minimum 45% in PCM', 'Age: No limit'],
    importantDates: {
      registration: 'January 2025',
      examDate: 'May 2025',
      resultDate: 'June 2025',
    },
    applicationFee: {
      general: '₹2,000',
      scst: '₹2,000',
    },
    collegesAccepting: ['RVCE Bangalore', 'BMS College', 'PESIT', 'MSRIT', '190+ Private Engineering Colleges in Karnataka'],
    officialWebsite: 'https://www.comedk.org',
    category: 'engineering',
    state: 'karnataka',
  },
  {
    id: 'gujcet',
    name: 'GUJCET',
    fullForm: 'Gujarat Common Entrance Test',
    conductingBody: 'Gujarat Secondary & Higher Secondary Education Board',
    examMode: 'Pen & Paper (OMR)',
    duration: '3 hours',
    syllabus: ['Physics - 40 Questions', 'Chemistry - 40 Questions', 'Mathematics - 40 Questions', 'Total: 120 Questions', 'Gujarat Board syllabus'],
    eligibility: ['12th pass with PCM', 'Gujarat domicile', 'Minimum 45%', 'Age: No limit'],
    importantDates: {
      registration: 'January 2025',
      examDate: 'March 2025',
      resultDate: 'May 2025',
    },
    applicationFee: {
      general: '₹300',
      scst: '₹300',
    },
    collegesAccepting: ['LDCE Ahmedabad', 'SVNIT Surat', 'DDIT Nadiad', '100+ Gujarat Engineering Colleges'],
    officialWebsite: 'https://gujcet.gseb.org',
    category: 'engineering',
    state: 'gujarat',
  },
  {
    id: 'upsee',
    name: 'UPSEE/AKTU',
    fullForm: 'Uttar Pradesh State Entrance Examination',
    conductingBody: 'Dr. APJ Abdul Kalam Technical University',
    examMode: 'Computer Based Test (CBT)',
    duration: '3 hours',
    syllabus: ['Physics - 50 Questions', 'Chemistry - 50 Questions', 'Mathematics - 50 Questions', 'Total: 150 Questions', 'UP Board + CBSE syllabus'],
    eligibility: ['12th pass with PCM', 'No domicile requirement', 'Minimum 45%', 'Age: No limit'],
    importantDates: {
      registration: 'January 2025',
      examDate: 'April 2025',
      resultDate: 'May 2025',
    },
    applicationFee: {
      general: '₹1,300',
      scst: '₹650',
    },
    collegesAccepting: ['HBTU Kanpur', 'IET Lucknow', 'KNIT Sultanpur', 'BIET Jhansi', '400+ UP Engineering Colleges'],
    officialWebsite: 'https://aktu.ac.in',
    category: 'engineering',
    state: 'uttar-pradesh',
  },
  {
    id: 'ojee',
    name: 'OJEE',
    fullForm: 'Odisha Joint Entrance Examination',
    conductingBody: 'Odisha JEE Committee',
    examMode: 'Computer Based Test (CBT)',
    duration: '3 hours',
    syllabus: ['Physics', 'Chemistry', 'Mathematics', 'Odisha +2 syllabus'],
    eligibility: ['12th pass with PCM', 'Odisha domicile preferred', 'Minimum 45%'],
    importantDates: {
      registration: 'February 2025',
      examDate: 'May 2025',
      resultDate: 'June 2025',
    },
    applicationFee: {
      general: '₹1,000',
      scst: '₹500',
    },
    collegesAccepting: ['CET Bhubaneswar', 'VSSUT Burla', 'IGIT Sarang', '100+ Odisha Engineering Colleges'],
    officialWebsite: 'https://ojee.nic.in',
    category: 'engineering',
    state: 'odisha',
  },
  {
    id: 'viteee',
    name: 'VITEEE',
    fullForm: 'Vellore Institute of Technology Engineering Entrance Examination',
    conductingBody: 'VIT University',
    examMode: 'Computer Based Test (CBT)',
    duration: '2.5 hours',
    syllabus: ['Physics - 35 Questions', 'Chemistry - 35 Questions', 'Mathematics/Biology - 40 Questions', 'English - 5 Questions', 'Aptitude - 10 Questions'],
    eligibility: ['12th pass with PCM/PCB', 'Minimum 60% aggregate in PCM/PCB', 'Age: Born after July 1, 2003', 'No negative marking'],
    importantDates: {
      registration: 'November 2024',
      examDate: 'April 2025',
      resultDate: 'May 2025',
    },
    applicationFee: {
      general: '₹1,350',
      scst: '₹1,350',
    },
    collegesAccepting: ['VIT Vellore', 'VIT Chennai', 'VIT AP (Amaravati)', 'VIT Bhopal'],
    officialWebsite: 'https://viteee.vit.ac.in',
    category: 'engineering',
    state: 'national',
  },
  {
    id: 'srmjeee',
    name: 'SRMJEEE',
    fullForm: 'SRM Joint Engineering Entrance Examination',
    conductingBody: 'SRM Institute of Science and Technology',
    examMode: 'Computer Based Test (CBT)',
    duration: '2.5 hours',
    syllabus: ['Physics - 35 Questions', 'Chemistry - 35 Questions', 'Mathematics/Biology - 40 Questions', 'English - 5 Questions', 'Aptitude - 10 Questions'],
    eligibility: ['12th pass with PCM/PCB', 'Minimum 50% aggregate', 'No age limit', 'Total 125 Questions'],
    importantDates: {
      registration: 'October 2024',
      examDate: 'April-May 2025',
      resultDate: 'May 2025',
    },
    applicationFee: {
      general: '₹1,200',
      scst: '₹1,200',
    },
    collegesAccepting: ['SRM Chennai (Kattankulathur)', 'SRM AP (Amaravati)', 'SRM Sonepat (NCR)', 'SRM Sikkim'],
    officialWebsite: 'https://www.srmist.edu.in',
    category: 'engineering',
    state: 'national',
  },
  {
    id: 'kiitee',
    name: 'KIITEE',
    fullForm: 'Kalinga Institute of Industrial Technology Entrance Examination',
    conductingBody: 'KIIT University, Odisha',
    examMode: 'Computer Based Test (CBT)',
    duration: '3 hours',
    syllabus: ['Physics - 40 Questions', 'Chemistry - 40 Questions', 'Mathematics - 40 Questions', 'Total 120 Questions', 'No negative marking'],
    eligibility: ['12th pass with PCM', 'Minimum 60% aggregate in PCM', 'Age: No limit', 'Candidates appearing for 12th can also apply'],
    importantDates: {
      registration: 'November 2024',
      examDate: 'April 2025',
      resultDate: 'May 2025',
    },
    applicationFee: {
      general: '₹1,250',
      scst: '₹1,250',
    },
    collegesAccepting: ['KIIT Bhubaneswar', 'KIIT School of Computer Engineering', 'KIIT School of Electronics', 'KIIT School of Mechanical'],
    officialWebsite: 'https://kiitee.kiit.ac.in',
    category: 'engineering',
    state: 'odisha',
  },

  // ============ MEDICAL EXAMS ============
  {
    id: 'neet-ug',
    name: 'NEET UG',
    fullForm: 'National Eligibility cum Entrance Test (Undergraduate)',
    conductingBody: 'National Testing Agency (NTA)',
    examMode: 'Pen & Paper (OMR)',
    duration: '3 hours 20 minutes',
    syllabus: ['Physics', 'Chemistry', 'Biology (Botany & Zoology)', 'Class 11 & 12 NCERT'],
    eligibility: ['12th pass with PCB', 'Minimum 50% (40% for SC/ST)', 'Age: 17-25 years'],
    importantDates: {
      registration: 'February 2025',
      examDate: 'May 2025',
      resultDate: 'June 2025',
    },
    applicationFee: {
      general: '₹1,700',
      scst: '₹1,000',
    },
    collegesAccepting: ['AIIMS', 'JIPMER', 'Government Medical Colleges', 'Private Medical Colleges'],
    officialWebsite: 'https://neet.nta.nic.in',
    category: 'medical',
  },
  {
    id: 'neet-pg',
    name: 'NEET PG',
    fullForm: 'National Eligibility cum Entrance Test (Postgraduate)',
    conductingBody: 'National Board of Examinations (NBE)',
    examMode: 'Computer Based Test (CBT)',
    duration: '3.5 hours',
    syllabus: ['All MBBS subjects', 'Clinical subjects', 'Pre-clinical subjects'],
    eligibility: ['MBBS degree holders', 'Completed internship', 'MCI/NMC registration'],
    importantDates: {
      registration: 'December 2024',
      examDate: 'March 2025',
      resultDate: 'April 2025',
    },
    applicationFee: {
      general: '₹4,250',
      scst: '₹3,250',
    },
    collegesAccepting: ['Government PG Medical Colleges', 'Private PG Medical Colleges'],
    officialWebsite: 'https://nbe.edu.in',
    category: 'medical',
  },
  {
    id: 'gpat',
    name: 'GPAT',
    fullForm: 'Graduate Pharmacy Aptitude Test',
    conductingBody: 'National Testing Agency (NTA)',
    examMode: 'Computer Based Test (CBT)',
    duration: '3 hours',
    syllabus: ['Pharmaceutics', 'Pharmacology', 'Pharmaceutical Chemistry', 'Pharmacognosy'],
    eligibility: ['B.Pharm degree holders', 'Final year B.Pharm students'],
    importantDates: {
      registration: 'November 2024',
      examDate: 'February 2025',
      resultDate: 'March 2025',
    },
    applicationFee: {
      general: '₹2,000',
      scst: '₹1,000',
    },
    collegesAccepting: ['NIPER', 'Government Pharmacy Colleges', 'Private M.Pharm Colleges'],
    officialWebsite: 'https://gpat.nta.nic.in',
    category: 'medical',
  },
  {
    id: 'jipmer',
    name: 'JIPMER MBBS',
    fullForm: 'Jawaharlal Institute of Postgraduate Medical Education and Research',
    conductingBody: 'JIPMER Puducherry (Now via NEET)',
    examMode: 'Through NEET UG',
    duration: 'N/A - NEET Score used',
    syllabus: ['Physics', 'Chemistry', 'Biology', 'As per NEET syllabus'],
    eligibility: ['NEET qualified', 'Minimum 50% in PCB', 'Age: 17-25 years'],
    importantDates: {
      registration: 'Via NEET 2025',
      examDate: 'NEET: May 2025',
      resultDate: 'June 2025',
    },
    applicationFee: {
      general: 'Via NEET',
      scst: 'Via NEET',
    },
    collegesAccepting: ['JIPMER Puducherry', 'JIPMER Karaikal'],
    officialWebsite: 'https://jipmer.edu.in',
    category: 'medical',
  },
  {
    id: 'aiims-mbbs',
    name: 'AIIMS MBBS',
    fullForm: 'All India Institute of Medical Sciences MBBS Admission',
    conductingBody: 'AIIMS (Now via NEET)',
    examMode: 'Through NEET UG',
    duration: 'N/A - NEET Score used',
    syllabus: ['Physics', 'Chemistry', 'Biology', 'As per NEET syllabus'],
    eligibility: ['NEET qualified', 'Minimum 60% in PCB', 'Age: 17-25 years'],
    importantDates: {
      registration: 'Via NEET 2025',
      examDate: 'NEET: May 2025',
      resultDate: 'June 2025',
    },
    applicationFee: {
      general: 'Via NEET',
      scst: 'Via NEET',
    },
    collegesAccepting: ['AIIMS Delhi', 'AIIMS Jodhpur', 'AIIMS Bhopal', '23 AIIMS across India'],
    officialWebsite: 'https://aiimsexams.ac.in',
    category: 'medical',
  },
  {
    id: 'neet-mds',
    name: 'NEET MDS',
    fullForm: 'National Eligibility cum Entrance Test - Master of Dental Surgery',
    conductingBody: 'National Board of Examinations (NBE)',
    examMode: 'Computer Based Test (CBT)',
    duration: '3 hours',
    syllabus: ['All BDS subjects', 'Clinical Dentistry', 'Pre-clinical subjects'],
    eligibility: ['BDS degree holders', 'Completed internship', 'DCI registration'],
    importantDates: {
      registration: 'November 2024',
      examDate: 'March 2025',
      resultDate: 'April 2025',
    },
    applicationFee: {
      general: '₹4,250',
      scst: '₹3,250',
    },
    collegesAccepting: ['Government Dental Colleges', 'Private MDS Colleges'],
    officialWebsite: 'https://nbe.edu.in',
    category: 'medical',
  },
  {
    id: 'aiims-nursing',
    name: 'AIIMS Nursing',
    fullForm: 'AIIMS B.Sc Nursing Entrance Exam',
    conductingBody: 'AIIMS New Delhi',
    examMode: 'Computer Based Test (CBT)',
    duration: '2 hours',
    syllabus: ['Physics', 'Chemistry', 'Biology', 'General Knowledge'],
    eligibility: ['12th pass with PCB', 'Minimum 60% aggregate', 'Age: 17-25 years'],
    importantDates: {
      registration: 'March 2025',
      examDate: 'June 2025',
      resultDate: 'July 2025',
    },
    applicationFee: {
      general: '₹1,500',
      scst: '₹1,200',
    },
    collegesAccepting: ['AIIMS Delhi', 'AIIMS branches across India'],
    officialWebsite: 'https://aiimsexams.ac.in',
    category: 'medical',
  },
  {
    id: 'ap-eamcet-medical',
    name: 'AP EAMCET (Medical)',
    fullForm: 'AP Engineering, Agriculture & Medical Common Entrance Test - Medical Stream',
    conductingBody: 'JNTU Kakinada (on behalf of APSCHE)',
    examMode: 'Computer Based Test (CBT)',
    duration: '3 hours',
    syllabus: ['Biology', 'Physics', 'Chemistry', 'AP Intermediate syllabus'],
    eligibility: ['12th/Intermediate with BiPC', 'AP domicile', 'Minimum 45% (40% for reserved)'],
    importantDates: {
      registration: 'March 2025',
      examDate: 'May 2025',
      resultDate: 'June 2025',
    },
    applicationFee: {
      general: '₹650',
      scst: '₹450',
    },
    collegesAccepting: ['AP Government Medical Colleges', 'AP Pharmacy Colleges', 'Agriculture Universities'],
    officialWebsite: 'https://cets.apsche.ap.gov.in',
    category: 'medical',
  },

  // ============ MANAGEMENT & LAW EXAMS ============
  {
    id: 'cat',
    name: 'CAT',
    fullForm: 'Common Admission Test',
    conductingBody: 'IIMs (Rotating)',
    examMode: 'Computer Based Test (CBT)',
    duration: '2 hours',
    syllabus: ['Verbal Ability', 'Data Interpretation', 'Logical Reasoning', 'Quantitative Ability'],
    eligibility: ['Graduation with 50% (45% for SC/ST)', 'Final year students eligible'],
    importantDates: {
      registration: 'August 2024',
      examDate: 'November 2024',
      resultDate: 'January 2025',
    },
    applicationFee: {
      general: '₹2,400',
      scst: '₹1,200',
    },
    collegesAccepting: ['20 IIMs', 'Top B-Schools', 'FMS Delhi', 'MDI Gurgaon'],
    officialWebsite: 'https://iimcat.ac.in',
    category: 'management',
  },
  {
    id: 'clat',
    name: 'CLAT',
    fullForm: 'Common Law Admission Test',
    conductingBody: 'Consortium of NLUs',
    examMode: 'Computer Based Test (CBT)',
    duration: '2 hours',
    syllabus: ['English Language', 'Current Affairs', 'Legal Reasoning', 'Logical Reasoning', 'Quantitative Techniques'],
    eligibility: ['12th pass with 45% (40% for SC/ST)', 'No age limit for UG'],
    importantDates: {
      registration: 'October 2024',
      examDate: 'December 2024',
      resultDate: 'January 2025',
    },
    applicationFee: {
      general: '₹4,000',
      scst: '₹3,500',
    },
    collegesAccepting: ['22 NLUs across India', 'Top Private Law Schools'],
    officialWebsite: 'https://consortiumofnlus.ac.in',
    category: 'management',
  },
  {
    id: 'mat',
    name: 'MAT',
    fullForm: 'Management Aptitude Test',
    conductingBody: 'AIMA',
    examMode: 'Paper/Computer/Remote Based',
    duration: '2.5 hours',
    syllabus: ['Language Comprehension', 'Mathematical Skills', 'Data Analysis', 'Intelligence & Critical Reasoning', 'Indian & Global Environment'],
    eligibility: ['Graduation in any discipline', 'Final year students eligible'],
    importantDates: {
      registration: 'Quarterly',
      examDate: 'Feb, May, Sep, Dec 2025',
      resultDate: 'Within 2 weeks',
    },
    applicationFee: {
      general: '₹2,100',
      scst: '₹2,100',
    },
    collegesAccepting: ['600+ B-Schools', 'JBIMS', 'PUMBA', 'Many MBA colleges'],
    officialWebsite: 'https://mat.aima.in',
    category: 'management',
  },
  {
    id: 'xat',
    name: 'XAT',
    fullForm: 'Xavier Aptitude Test',
    conductingBody: 'XLRI Jamshedpur',
    examMode: 'Computer Based Test (CBT)',
    duration: '3 hours',
    syllabus: ['Verbal & Logical Ability', 'Decision Making', 'Quantitative Ability', 'General Knowledge'],
    eligibility: ['Graduation with 50%', 'Final year students eligible'],
    importantDates: {
      registration: 'July 2024',
      examDate: 'January 2025',
      resultDate: 'February 2025',
    },
    applicationFee: {
      general: '₹2,200',
      scst: '₹2,200',
    },
    collegesAccepting: ['XLRI', 'XIMB', 'XIM Bhubaneswar', '160+ B-Schools'],
    officialWebsite: 'https://xatonline.in',
    category: 'management',
  },
  {
    id: 'ailet',
    name: 'AILET',
    fullForm: 'All India Law Entrance Test',
    conductingBody: 'National Law University Delhi',
    examMode: 'Computer Based Test (CBT)',
    duration: '1.5 hours',
    syllabus: ['English', 'General Knowledge', 'Legal Aptitude', 'Logical Reasoning', 'Quantitative Aptitude'],
    eligibility: ['12th pass with 50%', 'Age: No upper limit for UG'],
    importantDates: {
      registration: 'October 2024',
      examDate: 'December 2024',
      resultDate: 'January 2025',
    },
    applicationFee: {
      general: '₹3,500',
      scst: '₹1,500',
    },
    collegesAccepting: ['NLU Delhi'],
    officialWebsite: 'https://nationallawuniversitydelhi.in',
    category: 'management',
  },
  {
    id: 'lsat-india',
    name: 'LSAT India',
    fullForm: 'Law School Admission Test India',
    conductingBody: 'Pearson VUE',
    examMode: 'Computer Based Test (CBT)',
    duration: '2 hours 20 minutes',
    syllabus: ['Analytical Reasoning', 'Logical Reasoning', 'Reading Comprehension'],
    eligibility: ['12th pass or equivalent', 'No age limit'],
    importantDates: {
      registration: 'September 2024',
      examDate: 'January 2025',
      resultDate: 'February 2025',
    },
    applicationFee: {
      general: '₹3,999',
      scst: '₹3,999',
    },
    collegesAccepting: ['Jindal Global Law School', 'UPES', 'Nirma University', '90+ Law Schools'],
    officialWebsite: 'https://www.lsatindia.in',
    category: 'management',
  },

  // ============ DESIGN & ARCHITECTURE EXAMS ============
  {
    id: 'nata',
    name: 'NATA',
    fullForm: 'National Aptitude Test in Architecture',
    conductingBody: 'Council of Architecture',
    examMode: 'Computer Based Test',
    duration: '3 hours',
    syllabus: ['Mathematics', 'General Aptitude', 'Drawing Test', 'Aesthetic Sensitivity'],
    eligibility: ['12th pass with Maths', 'Minimum 50% aggregate'],
    importantDates: {
      registration: 'January 2025',
      examDate: 'April & June 2025',
      resultDate: 'Within 3 weeks',
    },
    applicationFee: {
      general: '₹2,000',
      scst: '₹2,000',
    },
    collegesAccepting: ['Government Architecture Colleges', 'Private Architecture Colleges', 'SPA Delhi'],
    officialWebsite: 'https://www.nata.in',
    category: 'design',
  },
  {
    id: 'jee-main-paper2',
    name: 'JEE Main Paper 2',
    fullForm: 'JEE Main B.Arch/B.Planning',
    conductingBody: 'National Testing Agency (NTA)',
    examMode: 'Computer Based + Pen Paper (Drawing)',
    duration: '3 hours',
    syllabus: ['Mathematics', 'Aptitude Test', 'Drawing Test (B.Arch)', 'Planning Based Questions'],
    eligibility: ['12th pass with Maths', 'Minimum 50% aggregate'],
    importantDates: {
      registration: 'November 2024',
      examDate: 'January 2025',
      resultDate: 'February 2025',
    },
    applicationFee: {
      general: '₹1,000',
      scst: '₹500',
    },
    collegesAccepting: ['NITs (B.Arch)', 'IITs (B.Arch)', 'SPAs', 'CFTIs'],
    officialWebsite: 'https://jeemain.nta.nic.in',
    category: 'design',
  },
  {
    id: 'nid-dat',
    name: 'NID DAT',
    fullForm: 'National Institute of Design - Design Aptitude Test',
    conductingBody: 'NID Ahmedabad',
    examMode: 'Computer Based + Studio Test',
    duration: 'Prelims: 3 hrs, Mains: 2 days',
    syllabus: ['Design Aptitude', 'Creative Ability', 'Visual Perception', 'Observation Skills'],
    eligibility: ['12th pass for B.Des', 'Graduation for M.Des'],
    importantDates: {
      registration: 'October 2024',
      examDate: 'January 2025',
      resultDate: 'March 2025',
    },
    applicationFee: {
      general: '₹3,000',
      scst: '₹1,500',
    },
    collegesAccepting: ['NID Ahmedabad', 'NID Gandhinagar', 'NID Kurukshetra', 'NID Jorhat'],
    officialWebsite: 'https://admissions.nid.edu',
    category: 'design',
  },
  {
    id: 'uceed',
    name: 'UCEED',
    fullForm: 'Undergraduate Common Entrance Examination for Design',
    conductingBody: 'IIT Bombay',
    examMode: 'Computer Based Test',
    duration: '3 hours',
    syllabus: ['Visualization & Spatial Ability', 'Observation & Design Sensitivity', 'Environmental & Social Awareness', 'Analytical & Logical Reasoning'],
    eligibility: ['12th pass', 'Age: Born on or after Oct 1, 2000'],
    importantDates: {
      registration: 'October 2024',
      examDate: 'January 2025',
      resultDate: 'March 2025',
    },
    applicationFee: {
      general: '₹3,600',
      scst: '₹1,800',
    },
    collegesAccepting: ['IIT Bombay', 'IIT Delhi', 'IIT Guwahati', 'IIT Hyderabad', 'IIITDM Jabalpur'],
    officialWebsite: 'https://www.uceed.iitb.ac.in',
    category: 'design',
  },
  {
    id: 'ceed',
    name: 'CEED',
    fullForm: 'Common Entrance Examination for Design',
    conductingBody: 'IIT Bombay',
    examMode: 'Computer Based Test',
    duration: '3 hours',
    syllabus: ['Visual Perception', 'Drawing', 'Design Thinking', 'Creativity'],
    eligibility: ['Graduation in any discipline', 'Final year students eligible'],
    importantDates: {
      registration: 'October 2024',
      examDate: 'January 2025',
      resultDate: 'March 2025',
    },
    applicationFee: {
      general: '₹3,600',
      scst: '₹1,800',
    },
    collegesAccepting: ['IIT Bombay', 'IIT Delhi', 'IIT Kanpur', 'IISc Bangalore'],
    officialWebsite: 'https://www.ceed.iitb.ac.in',
    category: 'design',
  },
  {
    id: 'nift',
    name: 'NIFT Entrance',
    fullForm: 'National Institute of Fashion Technology Entrance Exam',
    conductingBody: 'NIFT',
    examMode: 'Computer Based + Creative Ability Test',
    duration: 'GAT: 3 hrs, CAT: 3 hrs',
    syllabus: ['General Ability Test', 'Creative Ability Test', 'Situation Test'],
    eligibility: ['12th pass for UG', 'Graduation for PG'],
    importantDates: {
      registration: 'October 2024',
      examDate: 'February 2025',
      resultDate: 'April 2025',
    },
    applicationFee: {
      general: '₹3,000',
      scst: '₹1,500',
    },
    collegesAccepting: ['16 NIFT campuses across India'],
    officialWebsite: 'https://nift.ac.in',
    category: 'design',
  },

  // ============ AGRICULTURE & VETERINARY EXAMS ============
  {
    id: 'icar-aieea',
    name: 'ICAR AIEEA',
    fullForm: 'ICAR All India Entrance Examination for Admission',
    conductingBody: 'National Testing Agency (NTA)',
    examMode: 'Computer Based Test (CBT)',
    duration: '2.5 hours',
    syllabus: ['Physics', 'Chemistry', 'Biology/Mathematics/Agriculture', 'Class 11 & 12 syllabus'],
    eligibility: ['12th pass with PCB/PCM/Agriculture', 'Minimum 50% (40% for SC/ST)'],
    importantDates: {
      registration: 'March 2025',
      examDate: 'June 2025',
      resultDate: 'July 2025',
    },
    applicationFee: {
      general: '₹1,200',
      scst: '₹600',
    },
    collegesAccepting: ['64 Agricultural Universities', 'IARI', 'IVRI', 'NDRI', 'Veterinary Colleges'],
    officialWebsite: 'https://icar.nta.nic.in',
    category: 'agriculture',
  },
  {
    id: 'kcet-agriculture',
    name: 'KCET Agriculture',
    fullForm: 'Karnataka CET - Agriculture Stream',
    conductingBody: 'Karnataka Examination Authority',
    examMode: 'Pen & Paper (OMR)',
    duration: '1.5 hours per subject',
    syllabus: ['Biology', 'Physics', 'Chemistry', 'Mathematics (optional)'],
    eligibility: ['12th pass with PCB', 'Karnataka domicile', 'Minimum 45%'],
    importantDates: {
      registration: 'February 2025',
      examDate: 'April 2025',
      resultDate: 'June 2025',
    },
    applicationFee: {
      general: '₹650',
      scst: '₹500',
    },
    collegesAccepting: ['UAS Bangalore', 'UAS Dharwad', 'UAHS Shimoga', 'Karnataka Veterinary Colleges'],
    officialWebsite: 'https://cetonline.karnataka.gov.in',
    category: 'agriculture',
  },
  {
    id: 'tnau',
    name: 'TNAU Counselling',
    fullForm: 'Tamil Nadu Agricultural University Admission',
    conductingBody: 'TNAU',
    examMode: 'Merit Based (No Exam)',
    duration: 'N/A',
    syllabus: ['Based on +2 marks', 'PCB/PCM marks considered'],
    eligibility: ['12th pass with PCB/PCM', 'Tamil Nadu domicile', 'Minimum 50%'],
    importantDates: {
      registration: 'June 2025',
      examDate: 'N/A (Merit based)',
      resultDate: 'July 2025',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    collegesAccepting: ['TNAU Coimbatore', 'Agricultural colleges in TN', 'Horticultural colleges'],
    officialWebsite: 'https://www.tnau.ac.in',
    category: 'agriculture',
  },
  {
    id: 'ap-eamcet-agriculture',
    name: 'AP EAMCET (Agriculture)',
    fullForm: 'AP Engineering, Agriculture & Medical Common Entrance Test - Agriculture Stream',
    conductingBody: 'JNTU Kakinada',
    examMode: 'Computer Based Test (CBT)',
    duration: '3 hours',
    syllabus: ['Biology', 'Physics', 'Chemistry', 'AP Intermediate syllabus'],
    eligibility: ['12th/Intermediate with BiPC', 'AP domicile', 'Minimum 45%'],
    importantDates: {
      registration: 'March 2025',
      examDate: 'May 2025',
      resultDate: 'June 2025',
    },
    applicationFee: {
      general: '₹650',
      scst: '₹450',
    },
    collegesAccepting: ['Acharya NG Ranga Agricultural University', 'AP Veterinary Colleges', 'Agriculture Polytechnics'],
    officialWebsite: 'https://cets.apsche.ap.gov.in',
    category: 'agriculture',
  },

  // ============ OTHER PROFESSIONAL EXAMS ============
  {
    id: 'cuet-ug',
    name: 'CUET UG',
    fullForm: 'Common University Entrance Test - Undergraduate',
    conductingBody: 'National Testing Agency (NTA)',
    examMode: 'Computer Based Test (CBT)',
    duration: 'Varies by papers chosen',
    syllabus: ['Language Tests', 'Domain Subjects', 'General Test'],
    eligibility: ['12th pass', 'Eligibility varies by university'],
    importantDates: {
      registration: 'February 2025',
      examDate: 'May 2025',
      resultDate: 'June 2025',
    },
    applicationFee: {
      general: '₹650',
      scst: '₹550',
    },
    collegesAccepting: ['All Central Universities', 'DU', 'JNU', 'BHU', 'AMU', '200+ Universities'],
    officialWebsite: 'https://cuet.samarth.ac.in',
    category: 'other',
  },
  {
    id: 'nda',
    name: 'NDA',
    fullForm: 'National Defence Academy Examination',
    conductingBody: 'UPSC',
    examMode: 'Pen & Paper (OMR)',
    duration: '2.5 hours per paper',
    syllabus: ['Mathematics', 'General Ability Test', 'English', 'General Knowledge'],
    eligibility: ['12th pass (Science for Air/Navy)', 'Unmarried males', 'Age: 16.5-19.5 years'],
    importantDates: {
      registration: 'December 2024 / June 2025',
      examDate: 'April & September 2025',
      resultDate: 'Within 2 months',
    },
    applicationFee: {
      general: '₹100',
      scst: '₹0',
    },
    collegesAccepting: ['National Defence Academy Khadakwasla', 'Indian Military Academy'],
    officialWebsite: 'https://upsc.gov.in',
    category: 'other',
  },
  {
    id: 'cds',
    name: 'CDS',
    fullForm: 'Combined Defence Services Examination',
    conductingBody: 'UPSC',
    examMode: 'Pen & Paper (OMR)',
    duration: '2 hours per paper',
    syllabus: ['English', 'General Knowledge', 'Elementary Mathematics'],
    eligibility: ['Graduation (any discipline)', 'Unmarried', 'Age: 19-25 years'],
    importantDates: {
      registration: 'October 2024 / May 2025',
      examDate: 'February & September 2025',
      resultDate: 'Within 2 months',
    },
    applicationFee: {
      general: '₹200',
      scst: '₹0',
    },
    collegesAccepting: ['IMA Dehradun', 'OTA Chennai', 'Naval Academy', 'Air Force Academy'],
    officialWebsite: 'https://upsc.gov.in',
    category: 'other',
  },
  {
    id: 'hotel-management',
    name: 'NCHMCT JEE',
    fullForm: 'National Council for Hotel Management Joint Entrance Examination',
    conductingBody: 'National Testing Agency (NTA)',
    examMode: 'Computer Based Test (CBT)',
    duration: '3 hours',
    syllabus: ['Numerical Ability', 'Reasoning', 'English', 'General Knowledge', 'Aptitude for Service Sector'],
    eligibility: ['12th pass', 'Minimum 45% (40% for SC/ST)', 'Age: 22-25 years'],
    importantDates: {
      registration: 'January 2025',
      examDate: 'May 2025',
      resultDate: 'June 2025',
    },
    applicationFee: {
      general: '₹1,000',
      scst: '₹500',
    },
    collegesAccepting: ['IHMs across India', 'State Hotel Management Institutes', 'Private Hotel Schools'],
    officialWebsite: 'https://nchmjee.nta.nic.in',
    category: 'other',
  },
  {
    id: 'afcat',
    name: 'AFCAT',
    fullForm: 'Air Force Common Admission Test',
    conductingBody: 'Indian Air Force',
    examMode: 'Computer Based Test (CBT)',
    duration: '2 hours',
    syllabus: ['General Awareness', 'Verbal Ability', 'Numerical Ability', 'Reasoning', 'Military Aptitude'],
    eligibility: ['Graduation with 60%', 'Age: 20-24 years', 'Unmarried'],
    importantDates: {
      registration: 'December 2024 / June 2025',
      examDate: 'February & August 2025',
      resultDate: 'Within 3 months',
    },
    applicationFee: {
      general: '₹250',
      scst: '₹0',
    },
    collegesAccepting: ['Indian Air Force Academy Dundigal'],
    officialWebsite: 'https://afcat.cdac.in',
    category: 'other',
  },
  {
    id: 'cmat',
    name: 'CMAT',
    fullForm: 'Common Management Admission Test',
    conductingBody: 'National Testing Agency (NTA)',
    examMode: 'Computer Based Test (CBT)',
    duration: '3 hours',
    syllabus: ['Quantitative Techniques', 'Logical Reasoning', 'Language Comprehension', 'General Awareness', 'Innovation & Entrepreneurship'],
    eligibility: ['Graduation in any discipline', 'Final year students eligible'],
    importantDates: {
      registration: 'December 2024',
      examDate: 'January 2025',
      resultDate: 'February 2025',
    },
    applicationFee: {
      general: '₹2,000',
      scst: '₹1,000',
    },
    collegesAccepting: ['JBIMS Mumbai', 'KJ Somaiya', 'Great Lakes', '1000+ AICTE approved institutes'],
    officialWebsite: 'https://cmat.nta.nic.in',
    category: 'other',
  },
];

export const getExamsByCategory = (category: string): EntranceExam[] => {
  return entranceExams.filter(exam => exam.category === category);
};

export const getExamsByState = (state: IndianState): EntranceExam[] => {
  if (state === 'all') {
    return entranceExams;
  }
  if (state === 'national') {
    return entranceExams.filter(exam => exam.state === 'national' || !exam.state);
  }
  return entranceExams.filter(exam => exam.state === state || exam.state === 'national' || !exam.state);
};

export const getExamsByCategoryAndState = (category: string, state: IndianState): EntranceExam[] => {
  let exams = getExamsByCategory(category);
  if (state === 'all') {
    return exams;
  }
  if (state === 'national') {
    return exams.filter(exam => exam.state === 'national' || !exam.state);
  }
  return exams.filter(exam => exam.state === state || exam.state === 'national' || !exam.state);
};

export const getStatesWithExams = (): StateInfo[] => {
  const statesWithExams = new Set<string>();
  statesWithExams.add('all');
  statesWithExams.add('national');
  
  entranceExams.forEach(exam => {
    if (exam.state && exam.state !== 'national') {
      statesWithExams.add(exam.state);
    }
  });
  
  return indianStates.filter(state => statesWithExams.has(state.id));
};
