import { EntranceExam, CategoryInfo } from './types';

export const examCategories: CategoryInfo[] = [
  {
    id: 'engineering',
    label: 'Engineering',
    tamilLabel: 'பொறியியல்',
    icon: '⚙️',
    color: 'text-[#1976D2]',
    bgColor: 'bg-[#E3F2FD]',
    borderColor: 'border-[#1976D2]',
  },
  {
    id: 'medical',
    label: 'Medical & Health',
    tamilLabel: 'மருத்துவம்',
    icon: '🏥',
    color: 'text-[#D32F2F]',
    bgColor: 'bg-[#FFEBEE]',
    borderColor: 'border-[#D32F2F]',
  },
  {
    id: 'management',
    label: 'Management & Law',
    tamilLabel: 'மேலாண்மை & சட்டம்',
    icon: '💼',
    color: 'text-[#7B1FA2]',
    bgColor: 'bg-[#F3E5F5]',
    borderColor: 'border-[#7B1FA2]',
  },
  {
    id: 'agriculture',
    label: 'Agriculture',
    tamilLabel: 'வேளாண்மை',
    icon: '🌾',
    color: 'text-[#2E7D32]',
    bgColor: 'bg-[#E8F5E9]',
    borderColor: 'border-[#2E7D32]',
  },
  {
    id: 'design',
    label: 'Design & Arts',
    tamilLabel: 'வடிவமைப்பு',
    icon: '🎨',
    color: 'text-[#F59E0B]',
    bgColor: 'bg-[#FFF8E1]',
    borderColor: 'border-[#F59E0B]',
  },
  {
    id: 'defence',
    label: 'Defence & Others',
    tamilLabel: 'பாதுகாப்பு படை',
    icon: '🎖️',
    color: 'text-[#455A64]',
    bgColor: 'bg-[#ECEFF1]',
    borderColor: 'border-[#455A64]',
  },
];

export const entranceExams: EntranceExam[] = [
  // ============ ENGINEERING EXAMS ============
  {
    id: 'tnea',
    name: 'TNEA',
    tamilName: 'தமிழ்நாடு பொறியியல் சேர்க்கை',
    fullForm: 'Tamil Nadu Engineering Admissions',
    conductingBody: 'Anna University, Chennai',
    examMode: 'Merit Based (No Exam)',
    duration: 'N/A - Based on 12th marks',
    syllabus: [
      'No entrance exam',
      '12th HSC marks considered',
      'Cutoff = Maths + Physics/2 + Chemistry/2',
    ],
    eligibility: [
      'TN 12th HSC passed with PCM/PCB',
      'Minimum 50% in relevant subjects',
      'TN domicile or studied in TN',
    ],
    tnEligibility: 'Must be Tamil Nadu domicile or have studied in TN for 7+ years',
    importantDates: {
      registration: 'May 2025',
      examDate: 'N/A (Merit based)',
      resultDate: 'July 2025',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'Anna University CEG, Chennai',
      'Anna University MIT, Chennai',
      'GCT Coimbatore',
      'PSG Tech, Coimbatore',
      'TCE Madurai',
      '500+ TN Engineering Colleges',
    ],
    officialWebsite: 'https://www.tneaonline.org',
    category: 'engineering',
    hasJKKN: true,
    jkknColleges: ['JKKN College of Engineering & Technology, Namakkal'],
  },
  {
    id: 'jee-main',
    name: 'JEE Main',
    tamilName: 'ஜேஇஇ மெயின்',
    fullForm: 'Joint Entrance Examination Main',
    conductingBody: 'National Testing Agency (NTA)',
    examMode: 'Computer Based Test (CBT)',
    duration: '3 hours',
    syllabus: [
      'Physics - 25 Questions (100 marks)',
      'Chemistry - 25 Questions (100 marks)',
      'Mathematics - 25 Questions (100 marks)',
      'Total: 300 Marks',
    ],
    eligibility: [
      '12th pass with PCM',
      '75% in 12th (65% for SC/ST)',
      'Maximum 3 attempts',
    ],
    tnEligibility: 'TN students can apply for NITs (15% All India + 85% State quota at NIT Trichy)',
    importantDates: {
      registration: 'November 2024',
      examDate: 'January & April 2025',
      resultDate: 'February & May 2025',
    },
    applicationFee: {
      general: '₹1,000',
      scst: '₹500',
    },
    tnCollegesAccepting: [
      'NIT Trichy (Top NIT)',
      'IIIT Tiruchirappalli',
      'IIT Madras (via JEE Advanced)',
      'Other NITs across India',
    ],
    officialWebsite: 'https://jeemain.nta.nic.in',
    category: 'engineering',
  },
  {
    id: 'jee-advanced',
    name: 'JEE Advanced',
    tamilName: 'ஜேஇஇ அட்வான்ஸ்ட்',
    fullForm: 'Joint Entrance Examination Advanced',
    conductingBody: 'IIT Madras (2025)',
    examMode: 'Computer Based Test (CBT)',
    duration: '3 hours each (Paper 1 & 2)',
    syllabus: [
      'Advanced Physics',
      'Advanced Chemistry',
      'Advanced Mathematics',
      'Conceptual problems',
    ],
    eligibility: [
      'Top 2,50,000 in JEE Main',
      'Age: Born after Oct 1, 2000',
      'Maximum 2 consecutive attempts',
    ],
    tnEligibility: 'TN students eligible for IIT Madras (Chennai) - Premier institute in TN',
    importantDates: {
      registration: 'April 2025',
      examDate: 'May 2025',
      resultDate: 'June 2025',
    },
    applicationFee: {
      general: '₹2,800',
      scst: '₹1,400',
    },
    tnCollegesAccepting: [
      'IIT Madras, Chennai (#1 in India)',
      '23 IITs across India',
    ],
    officialWebsite: 'https://jeeadv.ac.in',
    category: 'engineering',
  },
  {
    id: 'viteee',
    name: 'VITEEE',
    tamilName: 'விஐடிஇஇஇ',
    fullForm: 'VIT Engineering Entrance Examination',
    conductingBody: 'VIT University, Vellore (TN)',
    examMode: 'Computer Based Test (CBT)',
    duration: '2 hours 30 minutes',
    syllabus: [
      'Physics - 35 Questions',
      'Chemistry - 35 Questions',
      'Maths/Biology - 40 Questions',
      'Aptitude - 15 Questions',
      'No negative marking',
    ],
    eligibility: [
      '12th with PCM/PCB',
      'Minimum 60% in PCM/PCB',
      'Born after July 1, 2003',
    ],
    tnEligibility: 'VIT Vellore is located in TN - Home state advantage for TN students',
    importantDates: {
      registration: 'November 2024',
      examDate: 'April-May 2025',
      resultDate: 'May 2025',
    },
    applicationFee: {
      general: '₹1,350',
      scst: '₹1,350',
    },
    tnCollegesAccepting: [
      'VIT Vellore (Main Campus, TN)',
      'VIT Chennai Campus',
      'VIT AP, VIT Bhopal',
    ],
    officialWebsite: 'https://viteee.vit.ac.in',
    category: 'engineering',
  },
  {
    id: 'srmjeee',
    name: 'SRMJEEE',
    tamilName: 'எஸ்ஆர்எம்ஜேஇஇஇ',
    fullForm: 'SRM Joint Engineering Entrance Examination',
    conductingBody: 'SRM Institute, Chennai (TN)',
    examMode: 'Computer Based Test (CBT)',
    duration: '2 hours 30 minutes',
    syllabus: [
      'Physics - 35 Questions',
      'Chemistry - 35 Questions',
      'Maths/Biology - 40 Questions',
      'Aptitude - 15 Questions',
    ],
    eligibility: [
      '12th with PCM/PCB',
      'Minimum 50% aggregate',
      'No age limit',
    ],
    tnEligibility: 'SRM Kattankulathur is TN based - Priority for TN students in counselling',
    importantDates: {
      registration: 'October 2024',
      examDate: 'April-May 2025',
      resultDate: 'May 2025',
    },
    applicationFee: {
      general: '₹1,200',
      scst: '₹1,200',
    },
    tnCollegesAccepting: [
      'SRM Kattankulathur (Main, TN)',
      'SRM Ramapuram, Chennai',
      'SRM Vadapalani, Chennai',
    ],
    officialWebsite: 'https://srmist.edu.in',
    category: 'engineering',
  },
  {
    id: 'bitsat',
    name: 'BITSAT',
    tamilName: 'பிட்சாட்',
    fullForm: 'BITS Admission Test',
    conductingBody: 'BITS Pilani',
    examMode: 'Computer Based Test (CBT)',
    duration: '3 hours',
    syllabus: [
      'Physics - 40 Questions',
      'Chemistry - 40 Questions',
      'Mathematics - 45 Questions',
      'English & Reasoning - 25 Questions',
    ],
    eligibility: [
      '12th with PCM',
      '75% aggregate, 60% each in PCM',
      'No age limit',
    ],
    tnEligibility: 'TN students eligible - BITS centers available in Chennai for exam',
    importantDates: {
      registration: 'January 2025',
      examDate: 'May-June 2025',
      resultDate: 'July 2025',
    },
    applicationFee: {
      general: '₹4,500',
      scst: '₹4,500',
    },
    tnCollegesAccepting: [
      'BITS Pilani',
      'BITS Goa',
      'BITS Hyderabad',
    ],
    officialWebsite: 'https://www.bitsadmission.com',
    category: 'engineering',
  },

  // ============ MEDICAL & HEALTH EXAMS ============
  {
    id: 'neet-ug',
    name: 'NEET-UG ⭐',
    tamilName: 'நீட் - மருத்துவ நுழைவுத் தேர்வு',
    fullForm: 'National Eligibility cum Entrance Test (ONLY EXAM FOR MBBS/BDS)',
    conductingBody: 'National Testing Agency (NTA)',
    examMode: 'Offline OMR Based',
    duration: '3 hrs 20 min',
    syllabus: [
      'Physics - 45+5 Questions (180 marks)',
      'Chemistry - 45+5 Questions (180 marks)',
      'Botany - 45+5 Questions (180 marks)',
      'Zoology - 45+5 Questions (180 marks)',
      'Total: 200 Questions | 720 Marks',
      '⭐ TAMIL Language Available ✓',
    ],
    eligibility: [
      '12th with PCB - 50% (40% SC/ST)',
      'Age: 17 years minimum',
      'Unlimited attempts',
      'MANDATORY for MBBS/BDS/BAMS/BHMS',
    ],
    tnEligibility: '85% State Quota for TN + 7.5% for TN Govt School Students | Tamil medium exam available',
    importantDates: {
      registration: 'Feb 2025',
      examDate: 'May 4, 2025',
      resultDate: 'June 2025',
    },
    applicationFee: {
      general: '₹1,700',
      scst: '₹1,000',
    },
    tnCollegesAccepting: [
      '36 Govt Medical Colleges in TN',
      'Madras Medical College, Chennai',
      'Stanley Medical College',
      'Coimbatore Medical College',
      'Madurai Medical College',
      'Private Medical Colleges',
    ],
    officialWebsite: 'https://neet.nta.nic.in',
    category: 'medical',
  },
  {
    id: 'tn-neet-counselling',
    name: 'TN NEET Counselling ⭐',
    tamilName: 'தமிழ்நாடு மருத்துவ கலந்தாய்வு',
    fullForm: 'Tamil Nadu Medical Admission Counselling (85% Seats for TN!)',
    conductingBody: 'TN Medical Selection Committee',
    examMode: 'Online Counselling',
    duration: 'Based on NEET Rank',
    syllabus: [
      'No separate exam',
      'Based on NEET-UG Score',
      'Choice filling online',
      'Document verification',
    ],
    eligibility: [
      'Valid NEET-UG Score',
      'TN Domicile / TN Nativity',
      'Studied in TN for 7+ years',
      '7.5% for TN Govt School Students',
    ],
    tnEligibility: '85% seats reserved for TN students! Govt college fee only ~₹14,000/year!',
    importantDates: {
      registration: 'June 2025',
      examDate: 'N/A (Counselling)',
      resultDate: 'July-Aug 2025',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      '36 Govt Medical Colleges',
      '15 Self-Financing Colleges',
      'Deemed Universities (SRM, Saveetha)',
      'Fee: ~₹14,000/year (Govt)',
    ],
    officialWebsite: 'https://tnmedicalselection.net',
    category: 'medical',
  },
  {
    id: 'bds-dental',
    name: 'BDS - Dental',
    tamilName: 'பல் மருத்துவம்',
    fullForm: 'Bachelor of Dental Surgery',
    conductingBody: 'Through NEET Score',
    examMode: 'Via NEET Score',
    duration: '5 years course',
    syllabus: [
      'Admission through NEET',
      'Same NEET exam as MBBS',
      'Separate counselling for BDS',
    ],
    eligibility: [
      'Valid NEET Score',
      '12th with PCB - 50%',
      'Age: 17+ years',
    ],
    tnEligibility: 'TN state quota available - Govt Dental Colleges in Chennai & Madurai',
    importantDates: {
      registration: 'June 2025',
      examDate: 'Via NEET (May 2025)',
      resultDate: 'July 2025',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'Govt Dental College, Chennai',
      'Govt Dental College, Madurai',
      'Meenakshi Dental College',
      'SRM Dental College',
      'Private Dental Colleges',
    ],
    officialWebsite: 'https://tnmedicalselection.net',
    category: 'medical',
  },
  {
    id: 'ayush-bams-bhms-bsms',
    name: 'AYUSH - BAMS/BHMS/BSMS',
    tamilName: 'ஆயுஷ் - சித்தா/ஆயுர்வேதா',
    fullForm: 'BAMS (Ayurveda) / BHMS (Homeopathy) / BSMS (Siddha)',
    conductingBody: 'Through NEET Score',
    examMode: 'Via NEET Score',
    duration: '5.5 years course',
    syllabus: [
      'Admission through NEET',
      'BSMS - Siddha Medicine (TN Special!)',
      'BAMS - Ayurvedic Medicine',
      'BHMS - Homeopathy',
    ],
    eligibility: [
      'Valid NEET Score',
      '12th with PCB - 50%',
      'Lower cutoff than MBBS',
    ],
    tnEligibility: 'BSMS (Siddha) is Tamil Nadu specialty! Govt Siddha Colleges available',
    importantDates: {
      registration: 'June 2025',
      examDate: 'Via NEET (May 2025)',
      resultDate: 'Aug 2025',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'Govt Siddha Medical College, Palayamkottai',
      'Govt Siddha Medical College, Chennai',
      'Govt Homeopathy College, Tirumangalam',
      'Sri Sairam Siddha Medical College',
    ],
    officialWebsite: 'https://tnmedicalselection.net',
    category: 'medical',
  },
  {
    id: 'bsc-nursing',
    name: 'B.Sc Nursing ⭐',
    tamilName: 'செவிலியர் படிப்பு',
    fullForm: 'Bachelor of Science in Nursing',
    conductingBody: 'TN Dr. MGR Medical University',
    examMode: 'Merit Based (12th Marks)',
    duration: '4 years course',
    syllabus: [
      'Based on 12th PCB Marks',
      'No NEET required (mostly)',
      'Direct merit admission',
      'Some colleges: Own entrance',
    ],
    eligibility: [
      '12th with PCB - 45%',
      'Age: 17-35 years',
      'Female & Male both eligible',
    ],
    tnEligibility: 'Govt nursing colleges through TN counselling - Many private options available',
    importantDates: {
      registration: 'June 2025',
      examDate: 'N/A (Merit)',
      resultDate: 'July 2025',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'Govt College of Nursing, Chennai',
      'MMC College of Nursing',
      'CMC Vellore Nursing',
      'Private Nursing Colleges',
    ],
    officialWebsite: 'https://tnmgrmu.ac.in',
    category: 'medical',
    hasJKKN: true,
    jkknColleges: ['JKKN College of Nursing, Namakkal'],
  },
  {
    id: 'bpharm',
    name: 'B.Pharm ⭐',
    tamilName: 'மருந்தியல் படிப்பு',
    fullForm: 'Bachelor of Pharmacy',
    conductingBody: 'TN Dr. MGR Medical University',
    examMode: 'Merit Based (12th Marks)',
    duration: '4 years course',
    syllabus: [
      'Based on 12th PCM/PCB Marks',
      'No entrance exam for most',
      'Direct merit admission',
    ],
    eligibility: [
      '12th with PCM or PCB - 50%',
      'Age: 17+ years',
      'Maths OR Biology accepted',
    ],
    tnEligibility: 'State quota for TN students in govt pharmacy colleges',
    importantDates: {
      registration: 'June 2025',
      examDate: 'N/A (Merit)',
      resultDate: 'July 2025',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'Madras Medical College (Pharmacy)',
      'JSS College of Pharmacy, Ooty',
      'PSG College of Pharmacy',
      'SRM College of Pharmacy',
    ],
    officialWebsite: 'https://tnmgrmu.ac.in',
    category: 'medical',
    hasJKKN: true,
    jkknColleges: ['JKKN College of Pharmacy, Namakkal'],
  },
  {
    id: 'allied-health',
    name: 'Allied Health Sciences ⭐',
    tamilName: 'துணை சுகாதாரம்',
    fullForm: 'BPT / BOT / BMLT / B.Sc Radiology & more',
    conductingBody: 'TN Dr. MGR Medical University',
    examMode: 'Merit Based (12th Marks)',
    duration: '3-4 years course',
    syllabus: [
      'BPT - Physiotherapy',
      'BOT - Occupational Therapy',
      'BMLT - Medical Lab Technology',
      'B.Sc Radiology, Cardiac Tech',
      'Based on 12th PCB marks',
    ],
    eligibility: [
      '12th with PCB - 50%',
      'Age: 17-25 years',
      'TN domicile preferred',
    ],
    tnEligibility: 'Growing demand! Excellent job opportunities in hospitals across TN',
    importantDates: {
      registration: 'June 2025',
      examDate: 'N/A (Merit)',
      resultDate: 'July 2025',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'MMC Allied Health Sciences',
      'Stanley Medical College',
      'PSG IMS, Coimbatore',
      'SRM Allied Health',
    ],
    officialWebsite: 'https://tnmgrmu.ac.in',
    category: 'medical',
    hasJKKN: true,
    jkknColleges: ['JKKN College of Allied Health Sciences, Namakkal'],
  },
  {
    id: 'jipmer-puducherry',
    name: 'JIPMER Puducherry',
    tamilName: 'ஜிப்மர் புதுச்சேரி',
    fullForm: 'Jawaharlal Institute of Postgraduate Medical Education',
    conductingBody: 'Through NEET Score',
    examMode: 'Via NEET Score',
    duration: '5.5 years MBBS',
    syllabus: [
      'Admission through NEET',
      'All India + Puducherry Quota',
      'Premier Medical Institute',
    ],
    eligibility: [
      'Valid NEET Score',
      '12th with PCB - 50%',
      'High NEET rank required',
    ],
    tnEligibility: 'Near Tamil Nadu - Very popular among TN students! Puducherry quota available',
    importantDates: {
      registration: 'June 2025',
      examDate: 'Via NEET (May 2025)',
      resultDate: 'July 2025',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'JIPMER Puducherry (Main)',
      'JIPMER Karaikal',
      'Government Institute',
      'Low fees, High quality',
    ],
    officialWebsite: 'https://jipmer.edu.in',
    category: 'medical',
  },

  // ============ MANAGEMENT & LAW ============
  {
    id: 'clat',
    name: 'CLAT',
    tamilName: 'சட்டப் படிப்பு நுழைவுத் தேர்வு',
    fullForm: 'Common Law Admission Test',
    conductingBody: 'Consortium of NLUs',
    examMode: 'Computer Based Test',
    duration: '2 hours',
    syllabus: [
      'English Language - 22-26 Q',
      'Current Affairs - 28-32 Q',
      'Legal Reasoning - 28-32 Q',
      'Logical Reasoning - 22-26 Q',
      'Quantitative - 10-14 Q',
      'Total: 150 Questions',
    ],
    eligibility: [
      '12th pass any stream',
      'No minimum marks (Gen)',
      '45% for SC/ST',
    ],
    tnEligibility: 'For TNNLU Trichy (Tamil Nadu National Law University) - Premier law school in TN!',
    importantDates: {
      registration: 'Aug-Nov 2024',
      examDate: 'Dec 2024',
      resultDate: 'Jan 2025',
    },
    applicationFee: {
      general: '₹4,000',
      scst: '₹3,500',
    },
    tnCollegesAccepting: [
      'TNNLU Tiruchirappalli (TN)',
      'NLSIU Bangalore',
      'NALSAR Hyderabad',
      '22 NLUs across India',
    ],
    officialWebsite: 'https://consortiumofnlus.ac.in',
    category: 'management',
  },
  {
    id: 'tn-law-direct',
    name: 'TN Law Colleges (Direct)',
    tamilName: 'தமிழ்நாடு சட்டக் கல்லூரிகள்',
    fullForm: 'Direct Admission to Law Colleges in TN',
    conductingBody: 'Various TN Universities',
    examMode: 'Merit Based (12th Marks)',
    duration: 'N/A - Merit based',
    syllabus: [
      'Based on 12th marks',
      'No entrance exam',
      '3-year LLB or 5-year BA LLB',
    ],
    eligibility: [
      '12th pass any stream',
      'Minimum 45% (40% reserved)',
      '3-year LLB: Graduate',
    ],
    tnEligibility: 'Direct admission to govt law colleges based on 12th marks - No exam needed!',
    importantDates: {
      registration: 'June 2025',
      examDate: 'N/A (Merit)',
      resultDate: 'July 2025',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'Govt Law College, Chennai',
      'Dr. Ambedkar Govt Law College',
      'Madras University Law Dept',
      'Private Law Colleges in TN',
    ],
    officialWebsite: 'https://unom.ac.in',
    category: 'management',
  },
  {
    id: 'bba-bca-bcom-direct',
    name: 'BBA/BCA/B.Com (Direct) ⭐',
    tamilName: 'BBA/BCA/B.Com நேரடி சேர்க்கை',
    fullForm: 'Direct Admission - No Entrance Exam',
    conductingBody: 'All TN Universities',
    examMode: 'Merit Based (12th Marks)',
    duration: '3 years course',
    syllabus: [
      'No entrance exam',
      'Based on 12th marks only',
      'Any stream accepted',
    ],
    eligibility: [
      '12th pass any stream',
      'Minimum 50% (varies)',
      'No age limit',
    ],
    tnEligibility: 'All TN universities accept 12th marks - Easy admission for TN students!',
    importantDates: {
      registration: 'May-June 2025',
      examDate: 'N/A (Merit)',
      resultDate: 'June-July 2025',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'Madras University',
      'Anna University',
      'Bharathiar University',
      'All TN Colleges',
    ],
    officialWebsite: 'https://unom.ac.in',
    category: 'management',
    hasJKKN: true,
    jkknColleges: ['JKKN Arts & Science College, Namakkal'],
  },
  {
    id: 'ca-cs-cma-foundation',
    name: 'CA/CS/CMA Foundation',
    tamilName: 'CA/CS/CMA அடித்தளப் படிப்பு',
    fullForm: 'Chartered Accountant / Company Secretary / Cost Accountant',
    conductingBody: 'ICAI / ICSI / ICMAI',
    examMode: 'Pen & Paper / Online',
    duration: '4 months foundation',
    syllabus: [
      'CA: Accounts, Law, Maths',
      'CS: Law, Economics, Accounts',
      'CMA: Accounts, Maths, Economics',
    ],
    eligibility: [
      'Can register after 12th',
      'Any stream accepted',
      'No minimum marks',
    ],
    tnEligibility: 'Start professional courses right after 12th! Exam centers across TN',
    importantDates: {
      registration: 'Anytime after 12th',
      examDate: 'May & Nov (CA/CMA), June & Dec (CS)',
      resultDate: '2 months after exam',
    },
    applicationFee: {
      general: '₹11,000-15,000',
      scst: 'Varies',
    },
    tnCollegesAccepting: [
      'Self-study / Coaching',
      'CA: icai.org',
      'CS: icsi.edu',
      'CMA: icmai.in',
    ],
    officialWebsite: 'https://icai.org',
    category: 'management',
  },

  // ============ AGRICULTURE ============
  {
    id: 'tnau',
    name: 'TNAU ⭐',
    tamilName: 'தமிழ்நாடு வேளாண் பல்கலைக்கழகம்',
    fullForm: 'Tamil Nadu Agricultural University (NO EXAM!)',
    conductingBody: 'TNAU, Coimbatore',
    examMode: 'Merit Based (12th Marks)',
    duration: '4 years B.Sc Agri',
    syllabus: [
      '⭐ NO ENTRANCE EXAM',
      'Based on 12th PCB/PCM marks',
      'Agriculture subject preference',
      'Cutoff based on aggregate',
    ],
    eligibility: [
      '12th with PCB/PCM - 50%',
      'TN domicile mandatory',
      'Age: 17-21 years',
    ],
    tnEligibility: '100% State Quota - Only TN students eligible! Low fees govt education',
    importantDates: {
      registration: 'May 2025',
      examDate: 'N/A (Merit)',
      resultDate: 'July 2025 (Counselling)',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'TNAU Coimbatore (Main)',
      'AC&RI Madurai',
      'AC&RI Trichy',
      'AC&RI Killikulam',
      '14+ TNAU Campuses',
    ],
    officialWebsite: 'https://tnau.ac.in',
    category: 'agriculture',
    hasJKKN: true,
    jkknColleges: ['JKKN College of Agricultural Science, Namakkal'],
  },
  {
    id: 'tanuvas',
    name: 'TANUVAS - Veterinary',
    tamilName: 'கால்நடை மருத்துவம்',
    fullForm: 'TN Veterinary & Animal Sciences University',
    conductingBody: 'TANUVAS, Chennai',
    examMode: 'Via NEET Score',
    duration: '5.5 years B.V.Sc',
    syllabus: [
      'B.V.Sc: Through NEET Score',
      'B.F.Sc (Fisheries): 12th marks',
      'B.Tech Food: 12th PCM marks',
    ],
    eligibility: [
      'B.V.Sc: Valid NEET Score',
      '12th with PCB - 50%',
      'TN domicile mandatory',
    ],
    tnEligibility: 'Only TN students - Madras Veterinary College is one of the oldest in Asia!',
    importantDates: {
      registration: 'June 2025',
      examDate: 'Via NEET',
      resultDate: 'Aug 2025',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'Madras Veterinary College, Chennai',
      'VC&RI Namakkal',
      'VC&RI Tirunelveli',
      'Fisheries College, Thoothukudi',
    ],
    officialWebsite: 'https://tanuvas.ac.in',
    category: 'agriculture',
  },
  {
    id: 'icar-aieea',
    name: 'ICAR AIEEA',
    tamilName: 'ஐசிஏஆர் தேசிய தேர்வு',
    fullForm: 'ICAR All India Entrance Examination',
    conductingBody: 'NTA for ICAR',
    examMode: 'Computer Based Test',
    duration: '2.5 hours',
    syllabus: [
      'Physics - 50 Questions',
      'Chemistry - 50 Questions',
      'Biology/Maths - 50 Questions',
      'Total: 150 Q, 600 Marks',
    ],
    eligibility: [
      '12th with PCB/PCM - 50%',
      'Age: 16.5+ years',
      'All India applicants',
    ],
    tnEligibility: 'For Central Agricultural Universities - ICAR quota in TNAU also available',
    importantDates: {
      registration: 'March 2025',
      examDate: 'June 2025',
      resultDate: 'July 2025',
    },
    applicationFee: {
      general: '₹1,000',
      scst: '₹500',
    },
    tnCollegesAccepting: [
      'TNAU (ICAR Quota)',
      'IARI New Delhi',
      'NDRI Karnal',
      '75+ ICAR Institutes',
    ],
    officialWebsite: 'https://icar.nta.nic.in',
    category: 'agriculture',
  },

  // ============ DESIGN & ARTS ============
  {
    id: 'nift-chennai',
    name: 'NIFT Chennai ⭐',
    tamilName: 'நிஃப்ட் சென்னை',
    fullForm: 'National Institute of Fashion Technology (TN Campus!)',
    conductingBody: 'NIFT',
    examMode: 'CAT + GAT + Situation Test',
    duration: '4 years B.Des',
    syllabus: [
      'CAT - Creative Ability Test',
      'GAT - General Ability Test',
      'Situation Test (shortlisted)',
      'Drawing & Design skills',
    ],
    eligibility: [
      '12th pass any stream',
      'No minimum marks',
      'Age: Below 24 years',
    ],
    tnEligibility: 'NIFT Chennai Campus in TN! Premier fashion design institute',
    importantDates: {
      registration: 'Oct-Dec 2024',
      examDate: 'Feb 2025',
      resultDate: 'April 2025',
    },
    applicationFee: {
      general: '₹2,500',
      scst: '₹1,250',
    },
    tnCollegesAccepting: [
      'NIFT Chennai (TN Campus)',
      'NIFT Delhi',
      'NIFT Mumbai',
      '18 NIFT Campuses',
    ],
    officialWebsite: 'https://nift.ac.in',
    category: 'design',
  },
  {
    id: 'nid-dat',
    name: 'NID DAT',
    tamilName: 'என்ஐடி வடிவமைப்பு தேர்வு',
    fullForm: 'National Institute of Design Entrance',
    conductingBody: 'NID, Ahmedabad',
    examMode: 'Prelims + Mains + Interview',
    duration: '4 years B.Des',
    syllabus: [
      'Design Aptitude Test',
      'Creative Ability',
      'Problem Solving',
      'Studio Test + Interview',
    ],
    eligibility: [
      '12th pass any stream',
      'No minimum marks',
      'Age: Below 20 years',
    ],
    tnEligibility: 'Premier design institute - Product, Graphic, Textile design courses',
    importantDates: {
      registration: 'Oct 2024',
      examDate: 'Jan 2025',
      resultDate: 'March 2025',
    },
    applicationFee: {
      general: '₹3,000',
      scst: '₹1,500',
    },
    tnCollegesAccepting: [
      'NID Ahmedabad',
      'NID Bangalore',
      'NID Andhra Pradesh',
    ],
    officialWebsite: 'https://nid.edu',
    category: 'design',
  },
  {
    id: 'jee-paper2-barch',
    name: 'JEE Main Paper 2 - B.Arch',
    tamilName: 'ஜேஇஇ கட்டிடக்கலை',
    fullForm: 'JEE Main Paper 2 for Architecture',
    conductingBody: 'NTA',
    examMode: 'CBT + Drawing',
    duration: '3 hours',
    syllabus: [
      'Mathematics - 25 Questions',
      'Aptitude - 50 Questions',
      'Drawing - 2 Questions',
      'Total: 400 Marks',
    ],
    eligibility: [
      '12th with Maths - 50%',
      'Physics, Chemistry required',
      'No age limit',
    ],
    tnEligibility: 'For B.Arch at NIT Trichy & Anna University School of Architecture',
    importantDates: {
      registration: 'Nov 2024',
      examDate: 'April 2025',
      resultDate: 'May 2025',
    },
    applicationFee: {
      general: '₹1,000',
      scst: '₹500',
    },
    tnCollegesAccepting: [
      'Anna University SAP',
      'NIT Trichy (B.Arch)',
      'SRM Architecture',
      'VIT School of Architecture',
    ],
    officialWebsite: 'https://jeemain.nta.nic.in',
    category: 'design',
  },

  // ============ DEFENCE & OTHERS ============
  {
    id: 'nda',
    name: 'NDA',
    tamilName: 'தேசிய பாதுகாப்பு அகாடமி',
    fullForm: 'National Defence Academy Examination',
    conductingBody: 'UPSC',
    examMode: 'Pen & Paper (OMR)',
    duration: '2.5 hrs each (2 papers)',
    syllabus: [
      'Paper 1: Mathematics - 300 marks',
      'Paper 2: GAT (English + GK) - 600 marks',
      'SSB Interview - 900 marks',
    ],
    eligibility: [
      '12th pass (PCM for Tech entry)',
      'Male candidates',
      'Age: 16.5 - 19.5 years',
      'Unmarried',
    ],
    tnEligibility: 'OTA Chennai for CDS training! Many TN officers in Armed Forces',
    importantDates: {
      registration: 'Dec 2024 / May 2025',
      examDate: 'April & Sept 2025',
      resultDate: 'May & Oct 2025',
    },
    applicationFee: {
      general: '₹100',
      scst: 'Nil',
    },
    tnCollegesAccepting: [
      'NDA Khadakwasla, Pune',
      'OTA Chennai',
      'Indian Military Academy',
      'Air Force Academy',
    ],
    officialWebsite: 'https://upsc.gov.in',
    category: 'defence',
  },
  {
    id: 'navy-btech',
    name: 'Indian Navy B.Tech Entry',
    tamilName: 'இந்திய கடற்படை B.Tech',
    fullForm: 'Indian Navy 10+2 B.Tech Entry',
    conductingBody: 'Indian Navy',
    examMode: 'Through JEE Main Score',
    duration: '4 years B.Tech',
    syllabus: [
      'JEE Main Score used',
      'No separate exam',
      'SSB Interview after shortlist',
    ],
    eligibility: [
      'JEE Main qualified',
      '12th PCM - 70%',
      'Male, Age: 17-19.5 years',
    ],
    tnEligibility: 'Free B.Tech at Naval Academy! Chennai has naval base INS Adyar',
    importantDates: {
      registration: 'Dec-Jan 2025',
      examDate: 'Via JEE Main',
      resultDate: 'Shortlist in March',
    },
    applicationFee: {
      general: 'Nil',
      scst: 'Nil',
    },
    tnCollegesAccepting: [
      'Indian Naval Academy, Ezhimala',
      'INS Shivaji (Training)',
      'Free education + Stipend',
    ],
    officialWebsite: 'https://joinindiannavy.gov.in',
    category: 'defence',
  },
  {
    id: 'army-tes',
    name: 'Indian Army TES',
    tamilName: 'இந்திய ராணுவம் TES',
    fullForm: 'Technical Entry Scheme - Indian Army',
    conductingBody: 'Indian Army',
    examMode: 'Direct SSB Interview',
    duration: '5 years (1yr + 4yr B.Tech)',
    syllabus: [
      'No written exam',
      'Direct SSB Interview',
      'Based on 12th marks',
    ],
    eligibility: [
      '12th PCM - 70%',
      'Male, Age: 16.5-19.5 years',
      'Unmarried',
    ],
    tnEligibility: 'Direct officer entry! No exam - Only SSB based on 12th marks',
    importantDates: {
      registration: 'July-Aug & Jan-Feb',
      examDate: 'SSB Interview',
      resultDate: 'After SSB',
    },
    applicationFee: {
      general: 'Nil',
      scst: 'Nil',
    },
    tnCollegesAccepting: [
      'OTA Chennai (Nearby)',
      'CME Pune',
      'MCTE Mhow',
      'Free B.Tech + Army Career',
    ],
    officialWebsite: 'https://joinindianarmy.nic.in',
    category: 'defence',
  },
  {
    id: 'nchmct-jee',
    name: 'NCHMCT JEE ⭐',
    tamilName: 'ஹோட்டல் மேலாண்மை',
    fullForm: 'Hotel Management Entrance - IHM Chennai in TN!',
    conductingBody: 'NTA for NCHMCT',
    examMode: 'Computer Based Test',
    duration: '3 hours',
    syllabus: [
      'Numerical Ability - 30 Q',
      'Reasoning & Aptitude - 30 Q',
      'General Knowledge - 30 Q',
      'English Language - 60 Q',
      'Service Aptitude - 50 Q',
    ],
    eligibility: [
      '12th pass any stream',
      'Minimum 45% (40% SC/ST)',
      'Age: 25 years max (Gen)',
    ],
    tnEligibility: 'IHM Chennai is located in TN! State quota available for TN students',
    importantDates: {
      registration: 'Jan-March 2025',
      examDate: 'May 2025',
      resultDate: 'June 2025',
    },
    applicationFee: {
      general: '₹1,000',
      scst: '₹500',
    },
    tnCollegesAccepting: [
      'IHM Chennai (TN Campus)',
      'IHM Mumbai',
      'IHM Delhi',
      '21 Central IHMs',
    ],
    officialWebsite: 'https://nchmct.org',
    category: 'defence',
  },
];

// Utility functions
export const getExamsByCategory = (category: string): EntranceExam[] => {
  return entranceExams.filter((exam) => exam.category === category);
};

export const getExamById = (id: string): EntranceExam | undefined => {
  return entranceExams.find((exam) => exam.id === id);
};

export const getCategoryInfo = (categoryId: string): CategoryInfo | undefined => {
  return examCategories.find((cat) => cat.id === categoryId);
};
