import { EntranceExam, CategoryInfo } from './types';

export const examCategories: CategoryInfo[] = [
  {
    id: 'engineering',
    label: 'Engineering',
    tamilLabel: 'பொறியியல்',
    icon: '⚙️',
    color: 'text-[#1976D2]',
    bgColor: 'bg-[#E3F2FD]',
    borderColor: 'border-[#1976D2]',
  },
  {
    id: 'medical',
    label: 'Medical & Health',
    tamilLabel: 'மருத்துவம்',
    icon: '🏥',
    color: 'text-[#D32F2F]',
    bgColor: 'bg-[#FFEBEE]',
    borderColor: 'border-[#D32F2F]',
  },
  {
    id: 'management',
    label: 'Management & Law',
    tamilLabel: 'மேலாண்மை & சட்டம்',
    icon: '💼',
    color: 'text-[#7B1FA2]',
    bgColor: 'bg-[#F3E5F5]',
    borderColor: 'border-[#7B1FA2]',
  },
  {
    id: 'agriculture',
    label: 'Agriculture',
    tamilLabel: 'வேளாண்மை',
    icon: '🌾',
    color: 'text-[#2E7D32]',
    bgColor: 'bg-[#E8F5E9]',
    borderColor: 'border-[#2E7D32]',
  },
  {
    id: 'design',
    label: 'Design & Arts',
    tamilLabel: 'வடிவமைப்பு',
    icon: '🎨',
    color: 'text-[#F59E0B]',
    bgColor: 'bg-[#FFF8E1]',
    borderColor: 'border-[#F59E0B]',
  },
  {
    id: 'defence',
    label: 'Defence & Others',
    tamilLabel: 'பாதுகாப்பு படை',
    icon: '🎖️',
    color: 'text-[#455A64]',
    bgColor: 'bg-[#ECEFF1]',
    borderColor: 'border-[#455A64]',
  },
];

export const entranceExams: EntranceExam[] = [
  // ============ ENGINEERING EXAMS ============
  {
    id: 'tnea',
    name: 'TNEA',
    tamilName: 'தமிழ்நாடு பொறியியல் சேர்க்கை',
    fullForm: 'Tamil Nadu Engineering Admissions',
    conductingBody: 'Anna University, Chennai',
    examMode: 'Merit Based (No Exam)',
    duration: 'N/A - Based on 12th marks',
    syllabus: [
      'No entrance exam',
      '12th HSC marks considered',
      'Cutoff = Maths + Physics/2 + Chemistry/2',
    ],
    eligibility: [
      'TN 12th HSC passed with PCM/PCB',
      'Minimum 50% in relevant subjects',
      'TN domicile or studied in TN',
    ],
    tnEligibility: 'Must be Tamil Nadu domicile or have studied in TN for 7+ years',
    importantDates: {
      registration: 'May 2025',
      examDate: 'N/A (Merit based)',
      resultDate: 'July 2025',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'Anna University CEG, Chennai',
      'Anna University MIT, Chennai',
      'GCT Coimbatore',
      'PSG Tech, Coimbatore',
      'TCE Madurai',
      '500+ TN Engineering Colleges',
    ],
    officialWebsite: 'https://www.tneaonline.org',
    category: 'engineering',
    hasJKKN: true,
    jkknColleges: ['JKKN College of Engineering & Technology, Namakkal'],
  },
  {
    id: 'jee-main',
    name: 'JEE Main',
    tamilName: 'ஜேஇஇ மெயின்',
    fullForm: 'Joint Entrance Examination Main',
    conductingBody: 'National Testing Agency (NTA)',
    examMode: 'Computer Based Test (CBT)',
    duration: '3 hours',
    syllabus: [
      'Physics - 25 Questions (100 marks)',
      'Chemistry - 25 Questions (100 marks)',
      'Mathematics - 25 Questions (100 marks)',
      'Total: 300 Marks',
    ],
    eligibility: [
      '12th pass with PCM',
      '75% in 12th (65% for SC/ST)',
      'Maximum 3 attempts',
    ],
    tnEligibility: 'TN students can apply for NITs (15% All India + 85% State quota at NIT Trichy)',
    importantDates: {
      registration: 'November 2024',
      examDate: 'January & April 2025',
      resultDate: 'February & May 2025',
    },
    applicationFee: {
      general: '₹1,000',
      scst: '₹500',
    },
    tnCollegesAccepting: [
      'NIT Trichy (Top NIT)',
      'IIIT Tiruchirappalli',
      'IIT Madras (via JEE Advanced)',
      'Other NITs across India',
    ],
    officialWebsite: 'https://jeemain.nta.nic.in',
    category: 'engineering',
  },
  {
    id: 'jee-advanced',
    name: 'JEE Advanced',
    tamilName: 'ஜேஇஇ அட்வான்ஸ்ட்',
    fullForm: 'Joint Entrance Examination Advanced',
    conductingBody: 'IIT Madras (2025)',
    examMode: 'Computer Based Test (CBT)',
    duration: '3 hours each (Paper 1 & 2)',
    syllabus: [
      'Advanced Physics',
      'Advanced Chemistry',
      'Advanced Mathematics',
      'Conceptual problems',
    ],
    eligibility: [
      'Top 2,50,000 in JEE Main',
      'Age: Born after Oct 1, 2000',
      'Maximum 2 consecutive attempts',
    ],
    tnEligibility: 'TN students eligible for IIT Madras (Chennai) - Premier institute in TN',
    importantDates: {
      registration: 'April 2025',
      examDate: 'May 2025',
      resultDate: 'June 2025',
    },
    applicationFee: {
      general: '₹2,800',
      scst: '₹1,400',
    },
    tnCollegesAccepting: [
      'IIT Madras, Chennai (#1 in India)',
      '23 IITs across India',
    ],
    officialWebsite: 'https://jeeadv.ac.in',
    category: 'engineering',
  },
  {
    id: 'viteee',
    name: 'VITEEE',
    tamilName: 'விஐடிஇஇஇ',
    fullForm: 'VIT Engineering Entrance Examination',
    conductingBody: 'VIT University, Vellore (TN)',
    examMode: 'Computer Based Test (CBT)',
    duration: '2 hours 30 minutes',
    syllabus: [
      'Physics - 35 Questions',
      'Chemistry - 35 Questions',
      'Maths/Biology - 40 Questions',
      'Aptitude - 15 Questions',
      'No negative marking',
    ],
    eligibility: [
      '12th with PCM/PCB',
      'Minimum 60% in PCM/PCB',
      'Born after July 1, 2003',
    ],
    tnEligibility: 'VIT Vellore is located in TN - Home state advantage for TN students',
    importantDates: {
      registration: 'November 2024',
      examDate: 'April-May 2025',
      resultDate: 'May 2025',
    },
    applicationFee: {
      general: '₹1,350',
      scst: '₹1,350',
    },
    tnCollegesAccepting: [
      'VIT Vellore (Main Campus, TN)',
      'VIT Chennai Campus',
      'VIT AP, VIT Bhopal',
    ],
    officialWebsite: 'https://viteee.vit.ac.in',
    category: 'engineering',
  },
  {
    id: 'srmjeee',
    name: 'SRMJEEE',
    tamilName: 'எஸ்ஆர்எம்ஜேஇஇஇ',
    fullForm: 'SRM Joint Engineering Entrance Examination',
    conductingBody: 'SRM Institute, Chennai (TN)',
    examMode: 'Computer Based Test (CBT)',
    duration: '2 hours 30 minutes',
    syllabus: [
      'Physics - 35 Questions',
      'Chemistry - 35 Questions',
      'Maths/Biology - 40 Questions',
      'Aptitude - 15 Questions',
    ],
    eligibility: [
      '12th with PCM/PCB',
      'Minimum 50% aggregate',
      'No age limit',
    ],
    tnEligibility: 'SRM Kattankulathur is TN based - Priority for TN students in counselling',
    importantDates: {
      registration: 'October 2024',
      examDate: 'April-May 2025',
      resultDate: 'May 2025',
    },
    applicationFee: {
      general: '₹1,200',
      scst: '₹1,200',
    },
    tnCollegesAccepting: [
      'SRM Kattankulathur (Main, TN)',
      'SRM Ramapuram, Chennai',
      'SRM Vadapalani, Chennai',
    ],
    officialWebsite: 'https://srmist.edu.in',
    category: 'engineering',
  },
  {
    id: 'bitsat',
    name: 'BITSAT',
    tamilName: 'பிட்சாட்',
    fullForm: 'BITS Admission Test',
    conductingBody: 'BITS Pilani',
    examMode: 'Computer Based Test (CBT)',
    duration: '3 hours',
    syllabus: [
      'Physics - 40 Questions',
      'Chemistry - 40 Questions',
      'Mathematics - 45 Questions',
      'English & Reasoning - 25 Questions',
    ],
    eligibility: [
      '12th with PCM',
      '75% aggregate, 60% each in PCM',
      'No age limit',
    ],
    tnEligibility: 'TN students eligible - BITS centers available in Chennai for exam',
    importantDates: {
      registration: 'January 2025',
      examDate: 'May-June 2025',
      resultDate: 'July 2025',
    },
    applicationFee: {
      general: '₹4,500',
      scst: '₹4,500',
    },
    tnCollegesAccepting: [
      'BITS Pilani',
      'BITS Goa',
      'BITS Hyderabad',
    ],
    officialWebsite: 'https://www.bitsadmission.com',
    category: 'engineering',
  },

  // ============ MEDICAL & HEALTH EXAMS ============
  {
    id: 'neet-ug',
    name: 'NEET-UG ⭐',
    tamilName: 'நீட் - மருத்துவ நுழைவுத் தேர்வு',
    fullForm: 'National Eligibility cum Entrance Test (ONLY EXAM FOR MBBS/BDS)',
    conductingBody: 'National Testing Agency (NTA)',
    examMode: 'Offline OMR Based',
    duration: '3 hrs 20 min',
    syllabus: [
      'Physics - 45+5 Questions (180 marks)',
      'Chemistry - 45+5 Questions (180 marks)',
      'Botany - 45+5 Questions (180 marks)',
      'Zoology - 45+5 Questions (180 marks)',
      'Total: 200 Questions | 720 Marks',
      '⭐ TAMIL Language Available ✓',
    ],
    eligibility: [
      '12th with PCB - 50% (40% SC/ST)',
      'Age: 17 years minimum',
      'Unlimited attempts',
      'MANDATORY for MBBS/BDS/BAMS/BHMS',
    ],
    tnEligibility: '85% State Quota for TN + 7.5% for TN Govt School Students | Tamil medium exam available',
    importantDates: {
      registration: 'Feb 2025',
      examDate: 'May 4, 2025',
      resultDate: 'June 2025',
    },
    applicationFee: {
      general: '₹1,700',
      scst: '₹1,000',
    },
    tnCollegesAccepting: [
      '36 Govt Medical Colleges in TN',
      'Madras Medical College, Chennai',
      'Stanley Medical College',
      'Coimbatore Medical College',
      'Madurai Medical College',
      'Private Medical Colleges',
    ],
    officialWebsite: 'https://neet.nta.nic.in',
    category: 'medical',
  },
  {
    id: 'tn-neet-counselling',
    name: 'TN NEET Counselling ⭐',
    tamilName: 'தமிழ்நாடு மருத்துவ கலந்தாய்வு',
    fullForm: 'Tamil Nadu Medical Admission Counselling (85% Seats for TN!)',
    conductingBody: 'TN Medical Selection Committee',
    examMode: 'Online Counselling',
    duration: 'Based on NEET Rank',
    syllabus: [
      'No separate exam',
      'Based on NEET-UG Score',
      'Choice filling online',
      'Document verification',
    ],
    eligibility: [
      'Valid NEET-UG Score',
      'TN Domicile / TN Nativity',
      'Studied in TN for 7+ years',
      '7.5% for TN Govt School Students',
    ],
    tnEligibility: '85% seats reserved for TN students! Govt college fee only ~₹14,000/year!',
    importantDates: {
      registration: 'June 2025',
      examDate: 'N/A (Counselling)',
      resultDate: 'July-Aug 2025',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      '36 Govt Medical Colleges',
      '15 Self-Financing Colleges',
      'Deemed Universities (SRM, Saveetha)',
      'Fee: ~₹14,000/year (Govt)',
    ],
    officialWebsite: 'https://tnmedicalselection.net',
    category: 'medical',
  },
  {
    id: 'bds-dental',
    name: 'BDS - Dental',
    tamilName: 'பல் மருத்துவம்',
    fullForm: 'Bachelor of Dental Surgery',
    conductingBody: 'Through NEET Score',
    examMode: 'Via NEET Score',
    duration: '5 years course',
    syllabus: [
      'Admission through NEET',
      'Same NEET exam as MBBS',
      'Separate counselling for BDS',
    ],
    eligibility: [
      'Valid NEET Score',
      '12th with PCB - 50%',
      'Age: 17+ years',
    ],
    tnEligibility: 'TN state quota available - Govt Dental Colleges in Chennai & Madurai',
    importantDates: {
      registration: 'June 2025',
      examDate: 'Via NEET (May 2025)',
      resultDate: 'July 2025',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'Govt Dental College, Chennai',
      'Govt Dental College, Madurai',
      'Meenakshi Dental College',
      'SRM Dental College',
      'Private Dental Colleges',
    ],
    officialWebsite: 'https://tnmedicalselection.net',
    category: 'medical',
  },
  {
    id: 'ayush-bams-bhms-bsms',
    name: 'AYUSH - BAMS/BHMS/BSMS',
    tamilName: 'ஆயுஷ் - சித்தா/ஆயுர்வேதா',
    fullForm: 'BAMS (Ayurveda) / BHMS (Homeopathy) / BSMS (Siddha)',
    conductingBody: 'Through NEET Score',
    examMode: 'Via NEET Score',
    duration: '5.5 years course',
    syllabus: [
      'Admission through NEET',
      'BSMS - Siddha Medicine (TN Special!)',
      'BAMS - Ayurvedic Medicine',
      'BHMS - Homeopathy',
    ],
    eligibility: [
      'Valid NEET Score',
      '12th with PCB - 50%',
      'Lower cutoff than MBBS',
    ],
    tnEligibility: 'BSMS (Siddha) is Tamil Nadu specialty! Govt Siddha Colleges available',
    importantDates: {
      registration: 'June 2025',
      examDate: 'Via NEET (May 2025)',
      resultDate: 'Aug 2025',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'Govt Siddha Medical College, Palayamkottai',
      'Govt Siddha Medical College, Chennai',
      'Govt Homeopathy College, Tirumangalam',
      'Sri Sairam Siddha Medical College',
    ],
    officialWebsite: 'https://tnmedicalselection.net',
    category: 'medical',
  },
  {
    id: 'bsc-nursing',
    name: 'B.Sc Nursing ⭐',
    tamilName: 'செவிலியர் படிப்பு',
    fullForm: 'Bachelor of Science in Nursing',
    conductingBody: 'TN Dr. MGR Medical University',
    examMode: 'Merit Based (12th Marks)',
    duration: '4 years course',
    syllabus: [
      'Based on 12th PCB Marks',
      'No NEET required (mostly)',
      'Direct merit admission',
      'Some colleges: Own entrance',
    ],
    eligibility: [
      '12th with PCB - 45%',
      'Age: 17-35 years',
      'Female & Male both eligible',
    ],
    tnEligibility: 'Govt nursing colleges through TN counselling - Many private options available',
    importantDates: {
      registration: 'June 2025',
      examDate: 'N/A (Merit)',
      resultDate: 'July 2025',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'Govt College of Nursing, Chennai',
      'MMC College of Nursing',
      'CMC Vellore Nursing',
      'Private Nursing Colleges',
    ],
    officialWebsite: 'https://tnmgrmu.ac.in',
    category: 'medical',
    hasJKKN: true,
    jkknColleges: ['JKKN College of Nursing, Namakkal'],
  },
  {
    id: 'bpharm',
    name: 'B.Pharm ⭐',
    tamilName: 'மருந்தியல் படிப்பு',
    fullForm: 'Bachelor of Pharmacy',
    conductingBody: 'TN Dr. MGR Medical University',
    examMode: 'Merit Based (12th Marks)',
    duration: '4 years course',
    syllabus: [
      'Based on 12th PCM/PCB Marks',
      'No entrance exam for most',
      'Direct merit admission',
    ],
    eligibility: [
      '12th with PCM or PCB - 50%',
      'Age: 17+ years',
      'Maths OR Biology accepted',
    ],
    tnEligibility: 'State quota for TN students in govt pharmacy colleges',
    importantDates: {
      registration: 'June 2025',
      examDate: 'N/A (Merit)',
      resultDate: 'July 2025',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'Madras Medical College (Pharmacy)',
      'JSS College of Pharmacy, Ooty',
      'PSG College of Pharmacy',
      'SRM College of Pharmacy',
    ],
    officialWebsite: 'https://tnmgrmu.ac.in',
    category: 'medical',
    hasJKKN: true,
    jkknColleges: ['JKKN College of Pharmacy, Namakkal'],
  },
  {
    id: 'allied-health',
    name: 'Allied Health Sciences ⭐',
    tamilName: 'துணை சுகாதாரம்',
    fullForm: 'BPT / BOT / BMLT / B.Sc Radiology & more',
    conductingBody: 'TN Dr. MGR Medical University',
    examMode: 'Merit Based (12th Marks)',
    duration: '3-4 years course',
    syllabus: [
      'BPT - Physiotherapy',
      'BOT - Occupational Therapy',
      'BMLT - Medical Lab Technology',
      'B.Sc Radiology, Cardiac Tech',
      'Based on 12th PCB marks',
    ],
    eligibility: [
      '12th with PCB - 50%',
      'Age: 17-25 years',
      'TN domicile preferred',
    ],
    tnEligibility: 'Growing demand! Excellent job opportunities in hospitals across TN',
    importantDates: {
      registration: 'June 2025',
      examDate: 'N/A (Merit)',
      resultDate: 'July 2025',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'MMC Allied Health Sciences',
      'Stanley Medical College',
      'PSG IMS, Coimbatore',
      'SRM Allied Health',
    ],
    officialWebsite: 'https://tnmgrmu.ac.in',
    category: 'medical',
    hasJKKN: true,
    jkknColleges: ['JKKN College of Allied Health Sciences, Namakkal'],
  },
  {
    id: 'jipmer-puducherry',
    name: 'JIPMER Puducherry',
    tamilName: 'ஜிப்மர் புதுச்சேரி',
    fullForm: 'Jawaharlal Institute of Postgraduate Medical Education',
    conductingBody: 'Through NEET Score',
    examMode: 'Via NEET Score',
    duration: '5.5 years MBBS',
    syllabus: [
      'Admission through NEET',
      'All India + Puducherry Quota',
      'Premier Medical Institute',
    ],
    eligibility: [
      'Valid NEET Score',
      '12th with PCB - 50%',
      'High NEET rank required',
    ],
    tnEligibility: 'Near Tamil Nadu - Very popular among TN students! Puducherry quota available',
    importantDates: {
      registration: 'June 2025',
      examDate: 'Via NEET (May 2025)',
      resultDate: 'July 2025',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'JIPMER Puducherry (Main)',
      'JIPMER Karaikal',
      'Government Institute',
      'Low fees, High quality',
    ],
    officialWebsite: 'https://jipmer.edu.in',
    category: 'medical',
  },

  // ============ MANAGEMENT & LAW ============
  {
    id: 'cuet-ug',
    name: 'CUET-UG',
    tamilName: 'சியூஇடி யூஜி',
    fullForm: 'Common University Entrance Test',
    conductingBody: 'National Testing Agency (NTA)',
    examMode: 'Computer Based Test (CBT)',
    duration: '45-60 min per section',
    syllabus: [
      'Section 1: Language (Tamil available)',
      'Section 2: Domain Subjects',
      'Section 3: General Test',
    ],
    eligibility: [
      '12th pass any stream',
      'Varies by university',
      'No age limit',
    ],
    tnEligibility: 'Tamil medium option available - TN students can take exam in Tamil',
    importantDates: {
      registration: 'February 2025',
      examDate: 'May 2025',
      resultDate: 'June 2025',
    },
    applicationFee: {
      general: '₹650',
      scst: '₹550',
    },
    tnCollegesAccepting: [
      'Delhi University',
      'BHU, Varanasi',
      'Pondicherry University (near TN)',
      'Central Universities',
    ],
    officialWebsite: 'https://cuet.samarth.ac.in',
    category: 'management',
  },
  {
    id: 'clat',
    name: 'CLAT',
    tamilName: 'சிலாட்',
    fullForm: 'Common Law Admission Test',
    conductingBody: 'Consortium of NLUs',
    examMode: 'Computer Based Test (CBT)',
    duration: '2 hours',
    syllabus: [
      'English Language - 22-26 Q',
      'Current Affairs - 28-32 Q',
      'Legal Reasoning - 28-32 Q',
      'Logical Reasoning - 22-26 Q',
      'Quantitative - 10-14 Q',
    ],
    eligibility: [
      '12th pass any stream',
      'No min marks for General',
      'No age limit for UG',
    ],
    tnEligibility: 'TN students eligible for TNNLU (Tamil Nadu National Law University, Tiruchirappalli)',
    importantDates: {
      registration: 'July 2024',
      examDate: 'December 2024',
      resultDate: 'January 2025',
    },
    applicationFee: {
      general: '₹4,000',
      scst: '₹3,500',
    },
    tnCollegesAccepting: [
      'TNNLU Tiruchirappalli (TN)',
      'NLSIU Bangalore',
      'NALSAR Hyderabad',
      '22 NLUs across India',
    ],
    officialWebsite: 'https://consortiumofnlus.ac.in',
    category: 'management',
  },
  {
    id: 'tancet',
    name: 'TANCET',
    tamilName: 'டான்செட்',
    fullForm: 'Tamil Nadu Common Entrance Test',
    conductingBody: 'Anna University, Chennai',
    examMode: 'Computer Based Test (CBT)',
    duration: '2 hours',
    syllabus: [
      'MBA: Aptitude, Reasoning, English',
      'MCA: Maths, Computer Science',
      'M.E/M.Tech: Engg subjects',
      '100 Questions, 100 Marks',
    ],
    eligibility: [
      'Graduate in relevant field',
      'Minimum 50% (45% reserved)',
      'TN domicile preferred',
    ],
    tnEligibility: 'Exclusively for PG admissions in TN colleges - TN domicile gets state quota',
    importantDates: {
      registration: 'January 2025',
      examDate: 'March-April 2025',
      resultDate: 'May 2025',
    },
    applicationFee: {
      general: '₹650',
      scst: '₹325',
    },
    tnCollegesAccepting: [
      'Anna University (MBA/MCA)',
      'Govt Colleges in TN',
      'University Departments',
    ],
    officialWebsite: 'https://tancet.annauniv.edu',
    category: 'management',
  },

  // ============ AGRICULTURE ============
  {
    id: 'tnau-ug',
    name: 'TNAU Admission',
    tamilName: 'தமிழ்நாடு வேளாண் பல்கலை',
    fullForm: 'Tamil Nadu Agricultural University',
    conductingBody: 'TNAU, Coimbatore',
    examMode: 'Merit Based on 12th',
    duration: 'N/A - Merit based',
    syllabus: [
      'No entrance exam',
      '12th PCB/PCM marks',
      'Agriculture subject preferred',
    ],
    eligibility: [
      '12th with PCB/PCM',
      'Minimum 50% (45% reserved)',
      'TN domicile mandatory',
    ],
    tnEligibility: 'Only TN domicile students eligible - 100% state quota',
    importantDates: {
      registration: 'May 2025',
      examDate: 'N/A (Merit)',
      resultDate: 'July 2025',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'TNAU Coimbatore (Main)',
      'AC&RI Madurai',
      'AC&RI Killikulam',
      '14+ TNAU Colleges',
    ],
    officialWebsite: 'https://tnau.ac.in',
    category: 'agriculture',
    hasJKKN: true,
    jkknColleges: ['JKKN College of Agricultural Science, Namakkal'],
  },
  {
    id: 'icar-aieea',
    name: 'ICAR AIEEA',
    tamilName: 'ஐசிஏஆர் ஏஐஇஇஏ',
    fullForm: 'ICAR All India Entrance Exam',
    conductingBody: 'NTA for ICAR',
    examMode: 'Computer Based Test (CBT)',
    duration: '2 hours 30 minutes',
    syllabus: [
      'Physics - 50 Questions',
      'Chemistry - 50 Questions',
      'Biology/Maths - 50 Questions',
    ],
    eligibility: [
      '12th with PCB/PCM',
      'Minimum 50% (40% SC/ST)',
      'Age: 16.5+ years',
    ],
    tnEligibility: 'TN students can get admission in TNAU through ICAR quota as well',
    importantDates: {
      registration: 'March 2025',
      examDate: 'June 2025',
      resultDate: 'July 2025',
    },
    applicationFee: {
      general: '₹1,000',
      scst: '₹500',
    },
    tnCollegesAccepting: [
      'TNAU Coimbatore (ICAR quota)',
      'IARI New Delhi',
      '75+ ICAR Institutes',
    ],
    officialWebsite: 'https://icar.nta.nic.in',
    category: 'agriculture',
  },
  {
    id: 'tanuvas',
    name: 'TANUVAS',
    tamilName: 'தமிழ்நாடு கால்நடை அறிவியல்',
    fullForm: 'TN Veterinary & Animal Sciences University',
    conductingBody: 'TANUVAS, Chennai',
    examMode: 'NEET / Merit Based',
    duration: 'N/A - Based on NEET',
    syllabus: [
      'B.V.Sc: Based on NEET',
      'B.F.Sc: Based on 12th PCB',
      'B.Tech Food: Based on 12th PCM',
    ],
    eligibility: [
      'B.V.Sc: Valid NEET + PCB',
      'Other courses: 50% in 12th',
      'TN domicile mandatory',
    ],
    tnEligibility: 'Only TN domicile - State-run veterinary and fisheries education',
    importantDates: {
      registration: 'June 2025',
      examDate: 'N/A (Counselling)',
      resultDate: 'August 2025',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'Madras Veterinary College',
      'VC&RI Namakkal',
      'Fisheries College, Thoothukudi',
    ],
    officialWebsite: 'https://tanuvas.ac.in',
    category: 'agriculture',
  },

  // ============ DESIGN & ARTS ============
  {
    id: 'nata',
    name: 'NATA',
    tamilName: 'நாடா',
    fullForm: 'National Aptitude Test in Architecture',
    conductingBody: 'Council of Architecture',
    examMode: 'Online + Drawing Test',
    duration: '3 hours',
    syllabus: [
      'Drawing Test - Sketching, 2D/3D',
      'PCM Aptitude Test',
      'Aesthetic Sensitivity',
    ],
    eligibility: [
      '12th with Maths (50%)',
      'Aggregate 50% in PCM',
      'No age limit',
    ],
    tnEligibility: 'TN students eligible for B.Arch in Anna University and private colleges',
    importantDates: {
      registration: 'January 2025',
      examDate: 'April 2025',
      resultDate: 'May 2025',
    },
    applicationFee: {
      general: '₹2,000',
      scst: '₹2,000',
    },
    tnCollegesAccepting: [
      'Anna University (SAP)',
      'Hindustan University',
      'SRM University',
      'Architecture colleges in TN',
    ],
    officialWebsite: 'https://nata.in',
    category: 'design',
  },
  {
    id: 'jee-paper2',
    name: 'JEE Main Paper 2',
    tamilName: 'ஜேஇஇ பேப்பர் 2 (B.Arch)',
    fullForm: 'JEE Main Paper 2 (B.Arch/B.Planning)',
    conductingBody: 'NTA',
    examMode: 'CBT + Drawing',
    duration: '3 hours',
    syllabus: [
      'Maths - 25 Questions',
      'Aptitude - 50 Questions',
      'Drawing - 2 Questions',
    ],
    eligibility: [
      '12th with Maths',
      '50% aggregate',
      'Physics, Chemistry required',
    ],
    tnEligibility: 'For NITs B.Arch program - NIT Trichy has B.Arch course',
    importantDates: {
      registration: 'November 2024',
      examDate: 'April 2025',
      resultDate: 'May 2025',
    },
    applicationFee: {
      general: '₹1,000',
      scst: '₹500',
    },
    tnCollegesAccepting: [
      'NIT Trichy (B.Arch)',
      'SPAs (Schools of Planning)',
      'IIT Roorkee',
    ],
    officialWebsite: 'https://jeemain.nta.nic.in',
    category: 'design',
  },
  {
    id: 'nid-dat',
    name: 'NID DAT',
    tamilName: 'என்ஐடி டேட்',
    fullForm: 'National Institute of Design Entrance',
    conductingBody: 'NID, Ahmedabad',
    examMode: 'Prelims (CBT) + Mains',
    duration: '3 hours each',
    syllabus: [
      'Design Aptitude Test',
      'Creative Ability',
      'Problem Solving',
      'Studio Test + Interview',
    ],
    eligibility: [
      '12th pass any stream',
      'No minimum marks',
      'Age: Below 20 years',
    ],
    tnEligibility: 'TN students can apply - Design entrance for premier design institute',
    importantDates: {
      registration: 'October 2024',
      examDate: 'January 2025',
      resultDate: 'March 2025',
    },
    applicationFee: {
      general: '₹3,000',
      scst: '₹1,500',
    },
    tnCollegesAccepting: [
      'NID Ahmedabad',
      'NID Bangalore',
      'NID Haryana',
    ],
    officialWebsite: 'https://admissions.nid.edu',
    category: 'design',
  },

  // ============ DEFENCE & OTHERS ============
  {
    id: 'nda',
    name: 'NDA',
    tamilName: 'என்டிஏ',
    fullForm: 'National Defence Academy Examination',
    conductingBody: 'UPSC',
    examMode: 'Pen & Paper (OMR)',
    duration: '2.5 hours each (2 papers)',
    syllabus: [
      'Paper 1: Mathematics (300 marks)',
      'Paper 2: GAT (600 marks)',
      'SSB Interview (900 marks)',
    ],
    eligibility: [
      '12th pass (PCM for Tech)',
      'Age: 16.5 - 19.5 years',
      'Unmarried male/female',
    ],
    tnEligibility: 'TN students eligible - Officers Training Academy (OTA) is located in Chennai',
    importantDates: {
      registration: 'December 2024',
      examDate: 'April 2025 (NDA I)',
      resultDate: 'May 2025',
    },
    applicationFee: {
      general: '₹100',
      scst: 'Nil',
    },
    tnCollegesAccepting: [
      'NDA Khadakwasla',
      'OTA Chennai (for CDS)',
      'Indian Military Academy',
    ],
    officialWebsite: 'https://upsc.gov.in',
    category: 'defence',
  },
  {
    id: 'afcat',
    name: 'AFCAT',
    tamilName: 'ஏஎஃப்சேட்',
    fullForm: 'Air Force Common Admission Test',
    conductingBody: 'Indian Air Force',
    examMode: 'Computer Based Test',
    duration: '2 hours',
    syllabus: [
      'General Awareness',
      'Verbal Ability',
      'Numerical Ability',
      'Reasoning & Military Aptitude',
    ],
    eligibility: [
      'Graduate (60% for Flying)',
      'Age: 20-24 years (Flying)',
      'Unmarried',
    ],
    tnEligibility: 'After graduation - TN students can join Indian Air Force as officers',
    importantDates: {
      registration: 'December 2024',
      examDate: 'February 2025',
      resultDate: 'April 2025',
    },
    applicationFee: {
      general: '₹250',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'Air Force Academy, Hyderabad',
      'Air Force Training Establishments',
    ],
    officialWebsite: 'https://afcat.cdac.in',
    category: 'defence',
  },
  {
    id: 'tnpsc-group4',
    name: 'TNPSC Group 4',
    tamilName: 'டிஎன்பிஎஸ்சி குரூப் 4',
    fullForm: 'TN Public Service Commission Group IV',
    conductingBody: 'TNPSC',
    examMode: 'Pen & Paper (OMR)',
    duration: '3 hours',
    syllabus: [
      'General Studies - 75 Q',
      'Aptitude - 25 Q',
      'Tamil Language - 100 Q',
    ],
    eligibility: [
      'SSLC (10th) pass',
      'Age: 18-30 years',
      'TN domicile mandatory',
    ],
    tnEligibility: 'Only for TN residents - Entry level govt jobs for 10th/12th pass',
    importantDates: {
      registration: 'As per notification',
      examDate: 'As per notification',
      resultDate: '2-3 months after exam',
    },
    applicationFee: {
      general: '₹150',
      scst: 'Nil',
    },
    tnCollegesAccepting: [
      'TN Government Services',
      'VAO, Junior Assistant',
      'Bill Collector posts',
    ],
    officialWebsite: 'https://tnpsc.gov.in',
    category: 'defence',
  },
  {
    id: 'indian-navy',
    name: 'Indian Navy SSR/AA',
    tamilName: 'இந்திய கடற்படை',
    fullForm: 'Indian Navy Sailor Recruitment',
    conductingBody: 'Indian Navy',
    examMode: 'Computer Based Test',
    duration: '1 hour',
    syllabus: [
      'English',
      'Science',
      'Mathematics',
      'General Awareness',
    ],
    eligibility: [
      '12th pass with PCM (SSR)',
      '12th pass any stream (AA)',
      'Age: 17-20 years',
    ],
    tnEligibility: 'TN coastal students have advantage - Naval base in Chennai (INS Adyar)',
    importantDates: {
      registration: 'Twice a year',
      examDate: 'As per notification',
      resultDate: '1-2 months after exam',
    },
    applicationFee: {
      general: 'Nil',
      scst: 'Nil',
    },
    tnCollegesAccepting: [
      'INS Chilka (Training)',
      'Naval Dockyards',
      'Indian Naval Ships',
    ],
    officialWebsite: 'https://joinindiannavy.gov.in',
    category: 'defence',
  },
];

// Utility functions
export const getExamsByCategory = (category: string): EntranceExam[] => {
  return entranceExams.filter((exam) => exam.category === category);
};

export const getExamById = (id: string): EntranceExam | undefined => {
  return entranceExams.find((exam) => exam.id === id);
};

export const getCategoryInfo = (categoryId: string): CategoryInfo | undefined => {
  return examCategories.find((cat) => cat.id === categoryId);
};
