import { GovernmentExam } from './types';

export const governmentExams: GovernmentExam[] = [
  // DEFENCE & PARAMILITARY
  {
    id: 'nda',
    name: 'NDA (National Defence Academy)',
    nameTamil: 'தேசிய பாதுகாப்பு அகாடமி',
    category: 'defence',
    qualification: '12th Pass',
    ageMin: 16.5,
    ageMax: 19.5,
    salaryMin: 56100,
    salaryMax: 177500,
    examPattern: 'Written + SSB Interview',
    selectionProcess: ['Written Exam', 'SSB Interview (5 days)', 'Medical Examination'],
    applyLink: 'https://upsc.gov.in',
    nextExamDate: '2026-04-06',
    applicationStatus: 'upcoming',
    description: 'Join Indian Army, Navy or Air Force as an Officer through NDA',
    posts: ['Army', 'Navy', 'Air Force'],
  },
  {
    id: 'coast-guard-navik',
    name: 'Indian Coast Guard Navik',
    nameTamil: 'இந்திய கடலோர காவல் நாவிக்',
    category: 'defence',
    qualification: '12th Pass',
    ageMin: 18,
    ageMax: 22,
    salaryMin: 21700,
    salaryMax: 69100,
    examPattern: 'Stage I + Stage II + Medical',
    selectionProcess: ['Stage I (Online)', 'Stage II (Physical/Medical)', 'Training'],
    applyLink: 'https://joinindiancoastguard.cdac.in',
    nextExamDate: '2026-02-15',
    applicationStatus: 'open',
    description: 'Serve in Indian Coast Guard as Navik (General Duty/Domestic Branch)',
    posts: ['Navik GD', 'Navik DB'],
  },
  {
    id: 'agniveer-army',
    name: 'Agniveer Army',
    nameTamil: 'அக்னிவீர் ராணுவம்',
    category: 'defence',
    qualification: '12th Pass',
    ageMin: 17.5,
    ageMax: 23,
    salaryMin: 30000,
    salaryMax: 40000,
    examPattern: 'CEE + Physical + Medical',
    selectionProcess: ['Online Registration', 'CEE Exam', 'Physical Fitness Test', 'Medical'],
    applyLink: 'https://joinindianarmy.nic.in',
    nextExamDate: '2026-03-01',
    applicationStatus: 'upcoming',
    description: '4-year service in Indian Army with Seva Nidhi package',
    posts: ['Agniveer General Duty', 'Agniveer Technical', 'Agniveer Clerk/SKT'],
  },
  {
    id: 'agniveer-navy',
    name: 'Agniveer Navy',
    nameTamil: 'அக்னிவீர் கடற்படை',
    category: 'defence',
    qualification: '12th Pass',
    ageMin: 17.5,
    ageMax: 23,
    salaryMin: 30000,
    salaryMax: 40000,
    examPattern: 'Written + Physical + Medical',
    selectionProcess: ['Online Exam', 'Physical Fitness Test', 'Medical Examination'],
    applyLink: 'https://joinindiannavy.gov.in',
    nextExamDate: '2026-02-20',
    applicationStatus: 'open',
    description: '4-year service in Indian Navy with career opportunities',
    posts: ['Agniveer SSR', 'Agniveer MR'],
  },
  {
    id: 'agniveer-airforce',
    name: 'Agniveer Air Force',
    nameTamil: 'அக்னிவீர் விமானப்படை',
    category: 'defence',
    qualification: '12th Pass',
    ageMin: 17.5,
    ageMax: 21,
    salaryMin: 30000,
    salaryMax: 40000,
    examPattern: 'Phase I + Phase II + Medical',
    selectionProcess: ['Online Test', 'Physical Fitness Test', 'Adaptability Test', 'Medical'],
    applyLink: 'https://agnipathvayu.cdac.in',
    nextExamDate: '2026-01-25',
    applicationStatus: 'open',
    description: 'Serve in Indian Air Force as Agniveer Vayu',
    posts: ['Agniveer Vayu'],
  },
  {
    id: 'bsf-constable',
    name: 'BSF Constable',
    nameTamil: 'எல்லை பாதுகாப்பு படை கான்ஸ்டபிள்',
    category: 'defence',
    qualification: '12th Pass',
    ageMin: 18,
    ageMax: 23,
    salaryMin: 21700,
    salaryMax: 69100,
    examPattern: 'Written + PST/PET + Medical',
    selectionProcess: ['Written Exam', 'Physical Standard Test', 'Physical Efficiency Test', 'Medical'],
    applyLink: 'https://bsf.nic.in',
    nextExamDate: null,
    applicationStatus: 'closed',
    description: 'Join Border Security Force as Constable (GD)',
  },
  {
    id: 'crpf-constable',
    name: 'CRPF Constable',
    nameTamil: 'மத்திய ரிசர்வ் போலீஸ் படை கான்ஸ்டபிள்',
    category: 'defence',
    qualification: '12th Pass',
    ageMin: 18,
    ageMax: 23,
    salaryMin: 21700,
    salaryMax: 69100,
    examPattern: 'Written + PST/PET + Medical',
    selectionProcess: ['Written Exam', 'Physical Test', 'Medical Examination', 'Document Verification'],
    applyLink: 'https://crpf.gov.in',
    nextExamDate: null,
    applicationStatus: 'closed',
    description: 'Central Reserve Police Force Constable recruitment',
  },
  {
    id: 'cisf-constable',
    name: 'CISF Constable',
    nameTamil: 'மத்திய தொழில்துறை பாதுகாப்பு படை',
    category: 'defence',
    qualification: '12th Pass',
    ageMin: 18,
    ageMax: 23,
    salaryMin: 21700,
    salaryMax: 69100,
    examPattern: 'Written + PST/PET + Medical',
    selectionProcess: ['Written Exam', 'Physical Standard Test', 'Physical Efficiency Test', 'Medical'],
    applyLink: 'https://cisfrectt.in',
    nextExamDate: '2026-03-15',
    applicationStatus: 'upcoming',
    description: 'Central Industrial Security Force Constable/Fire',
  },
  {
    id: 'rpf-constable',
    name: 'RPF Constable',
    nameTamil: 'ரயில்வே பாதுகாப்பு படை கான்ஸ்டபிள்',
    category: 'defence',
    qualification: '12th Pass',
    ageMin: 18,
    ageMax: 25,
    salaryMin: 21700,
    salaryMax: 69100,
    examPattern: 'CBT + PET/PMT + Document Verification',
    selectionProcess: ['Computer Based Test', 'Physical Efficiency Test', 'Physical Measurement Test', 'Document Verification'],
    applyLink: 'https://rpf.indianrailways.gov.in',
    nextExamDate: '2026-04-10',
    applicationStatus: 'upcoming',
    description: 'Railway Protection Force Constable recruitment',
  },

  // RAILWAY JOBS
  {
    id: 'rrb-ntpc',
    name: 'RRB NTPC (12th Pass Posts)',
    nameTamil: 'ரயில்வே NTPC (12வது தேர்ச்சி)',
    category: 'railway',
    qualification: '12th Pass',
    ageMin: 18,
    ageMax: 33,
    salaryMin: 19900,
    salaryMax: 63200,
    examPattern: 'CBT-1 + CBT-2 + Typing/CBAT',
    selectionProcess: ['CBT Stage 1', 'CBT Stage 2', 'Skill Test (if applicable)', 'Document Verification'],
    applyLink: 'https://rrbcdg.gov.in',
    nextExamDate: '2026-05-01',
    applicationStatus: 'upcoming',
    description: 'Non-Technical Popular Categories: Commercial Cum Ticket Clerk, Account Clerk, etc.',
    posts: ['Commercial Cum Ticket Clerk', 'Account Clerk', 'Junior Clerk', 'Trains Clerk'],
  },
  {
    id: 'rrb-group-d',
    name: 'RRB Group D',
    nameTamil: 'ரயில்வே குரூப் டி',
    category: 'railway',
    qualification: '12th Pass',
    ageMin: 18,
    ageMax: 33,
    salaryMin: 18000,
    salaryMax: 56900,
    examPattern: 'CBT + PET + Document Verification',
    selectionProcess: ['Computer Based Test', 'Physical Efficiency Test', 'Document Verification', 'Medical Examination'],
    applyLink: 'https://rrbcdg.gov.in',
    nextExamDate: '2026-06-15',
    applicationStatus: 'upcoming',
    description: 'Track Maintainer, Helper, and other Group D posts in Railways',
    posts: ['Track Maintainer Grade IV', 'Helper/Assistant', 'Hospital Attendant'],
  },
  {
    id: 'railway-apprentice',
    name: 'Railway Apprentice',
    nameTamil: 'ரயில்வே பயிற்சி நாடுநர்',
    category: 'railway',
    qualification: '12th Pass',
    ageMin: 15,
    ageMax: 24,
    salaryMin: 8000,
    salaryMax: 9000,
    examPattern: 'Merit Based + Trade Test',
    selectionProcess: ['Online Application', 'Merit List', 'Document Verification', 'Medical'],
    applyLink: 'https://rfrth.apprenticeshipindia.gov.in',
    nextExamDate: '2026-01-30',
    applicationStatus: 'open',
    description: 'Apprenticeship training in various trades under Indian Railways',
    posts: ['Fitter', 'Electrician', 'Welder', 'Mechanic', 'Turner'],
  },

  // SSC (Staff Selection Commission)
  {
    id: 'ssc-chsl',
    name: 'SSC CHSL',
    nameTamil: 'SSC கம்பைன்ட் ஹயர் செகண்டரி',
    category: 'ssc',
    qualification: '12th Pass',
    ageMin: 18,
    ageMax: 27,
    salaryMin: 25500,
    salaryMax: 81100,
    examPattern: 'Tier-1 (CBE) + Tier-2 (CBE) + Skill Test',
    selectionProcess: ['Tier-1 Computer Based Exam', 'Tier-2 Computer Based Exam', 'Skill Test/Typing Test', 'Document Verification'],
    applyLink: 'https://ssc.nic.in',
    nextExamDate: '2026-03-01',
    applicationStatus: 'open',
    description: 'LDC, DEO, PA/SA posts in Central Government ministries',
    posts: ['LDC (Lower Division Clerk)', 'DEO (Data Entry Operator)', 'PA/SA (Postal Assistant/Sorting Assistant)'],
  },
  {
    id: 'ssc-mts',
    name: 'SSC MTS',
    nameTamil: 'SSC மல்டி டாஸ்கிங் ஸ்டாஃப்',
    category: 'ssc',
    qualification: '12th Pass',
    ageMin: 18,
    ageMax: 25,
    salaryMin: 18000,
    salaryMax: 56900,
    examPattern: 'Computer Based Exam + PET',
    selectionProcess: ['Computer Based Examination', 'Physical Efficiency Test', 'Document Verification'],
    applyLink: 'https://ssc.nic.in',
    nextExamDate: '2026-04-15',
    applicationStatus: 'upcoming',
    description: 'Multi Tasking Staff (Non-Technical) in various Central Govt offices',
  },
  {
    id: 'ssc-gd',
    name: 'SSC GD Constable',
    nameTamil: 'SSC GD கான்ஸ்டபிள்',
    category: 'ssc',
    qualification: '12th Pass',
    ageMin: 18,
    ageMax: 23,
    salaryMin: 21700,
    salaryMax: 69100,
    examPattern: 'CBE + PET/PST + Medical',
    selectionProcess: ['Computer Based Exam', 'Physical Efficiency Test', 'Physical Standard Test', 'Medical Examination', 'Document Verification'],
    applyLink: 'https://ssc.nic.in',
    nextExamDate: '2026-02-01',
    applicationStatus: 'open',
    description: 'Constable (GD) in BSF, CISF, CRPF, SSB, ITBP, AR, SSF',
  },
  {
    id: 'ssc-stenographer',
    name: 'SSC Stenographer',
    nameTamil: 'SSC சுருக்கெழுத்தர்',
    category: 'ssc',
    qualification: '12th Pass',
    ageMin: 18,
    ageMax: 27,
    salaryMin: 25500,
    salaryMax: 81100,
    examPattern: 'CBE + Skill Test (Stenography)',
    selectionProcess: ['Computer Based Exam', 'Skill Test (Stenography)', 'Document Verification'],
    applyLink: 'https://ssc.nic.in',
    nextExamDate: '2026-05-20',
    applicationStatus: 'upcoming',
    description: 'Stenographer Grade C & D in various Central Govt ministries',
    posts: ['Stenographer Grade C', 'Stenographer Grade D'],
  },

  // BANKING & INSURANCE
  {
    id: 'ibps-clerk',
    name: 'IBPS Clerk',
    nameTamil: 'IBPS கிளர்க்',
    category: 'banking',
    qualification: '12th Pass',
    ageMin: 20,
    ageMax: 28,
    salaryMin: 28000,
    salaryMax: 42000,
    examPattern: 'Prelims + Mains',
    selectionProcess: ['Preliminary Exam', 'Mains Exam', 'Provisional Allotment'],
    applyLink: 'https://ibps.in',
    nextExamDate: '2026-08-01',
    applicationStatus: 'upcoming',
    description: 'Clerical cadre in 11 Public Sector Banks',
  },
  {
    id: 'sbi-clerk',
    name: 'SBI Clerk',
    nameTamil: 'SBI கிளர்க்',
    category: 'banking',
    qualification: '12th Pass',
    ageMin: 20,
    ageMax: 28,
    salaryMin: 26000,
    salaryMax: 40000,
    examPattern: 'Prelims + Mains',
    selectionProcess: ['Preliminary Exam', 'Mains Exam', 'Local Language Test'],
    applyLink: 'https://sbi.co.in/careers',
    nextExamDate: '2026-07-15',
    applicationStatus: 'upcoming',
    description: 'Junior Associate (Customer Support & Sales) in SBI',
  },
  {
    id: 'rrb-office-assistant',
    name: 'RRB Office Assistant',
    nameTamil: 'RRB அலுவலக உதவியாளர்',
    category: 'banking',
    qualification: '12th Pass',
    ageMin: 18,
    ageMax: 28,
    salaryMin: 20000,
    salaryMax: 35000,
    examPattern: 'Prelims + Mains',
    selectionProcess: ['Preliminary Exam', 'Mains Exam', 'Interview (if applicable)'],
    applyLink: 'https://ibps.in',
    nextExamDate: '2026-09-01',
    applicationStatus: 'upcoming',
    description: 'Office Assistant (Multipurpose) in Regional Rural Banks',
  },
  {
    id: 'lic-ado',
    name: 'LIC ADO',
    nameTamil: 'LIC அப்ரென்டிஸ் டெவலப்மென்ட் ஆபிசர்',
    category: 'banking',
    qualification: '12th Pass',
    ageMin: 21,
    ageMax: 30,
    salaryMin: 35000,
    salaryMax: 50000,
    examPattern: 'Prelims + Mains + Interview',
    selectionProcess: ['Preliminary Exam', 'Mains Exam', 'Interview'],
    applyLink: 'https://licindia.in/careers',
    nextExamDate: null,
    applicationStatus: 'closed',
    description: 'Apprentice Development Officer in Life Insurance Corporation',
  },
  {
    id: 'india-post-gds',
    name: 'India Post GDS',
    nameTamil: 'இந்திய தபால் கிராமிய டாக் சேவக்',
    category: 'banking',
    qualification: '12th Pass',
    ageMin: 18,
    ageMax: 40,
    salaryMin: 12000,
    salaryMax: 14500,
    examPattern: 'Merit Based (10th Marks)',
    selectionProcess: ['Online Application', 'Merit List Based on 10th Marks', 'Document Verification'],
    applyLink: 'https://indiapostgdsonline.gov.in',
    nextExamDate: '2026-01-15',
    applicationStatus: 'open',
    description: 'Gramin Dak Sevak (Branch Postmaster, ABPM, Dak Sevak)',
    posts: ['Branch Postmaster', 'Assistant Branch Postmaster', 'Dak Sevak'],
  },

  // STATE GOVERNMENT - TAMIL NADU
  {
    id: 'tnpsc-group4',
    name: 'TNPSC Group 4',
    nameTamil: 'TNPSC குரூப் 4',
    category: 'state',
    qualification: '12th Pass',
    ageMin: 18,
    ageMax: 30,
    salaryMin: 19500,
    salaryMax: 62000,
    examPattern: 'Single Paper (200 Questions)',
    selectionProcess: ['Written Exam', 'Certificate Verification', 'Counselling'],
    applyLink: 'https://tnpsc.gov.in',
    nextExamDate: '2026-06-01',
    applicationStatus: 'upcoming',
    description: 'VAO, Junior Assistant, Typist, Steno-Typist in TN Govt',
    posts: ['VAO (Village Administrative Officer)', 'Junior Assistant', 'Typist', 'Steno-Typist'],
  },
  {
    id: 'tn-police-constable',
    name: 'TN Police Constable',
    nameTamil: 'தமிழ்நாடு போலீஸ் கான்ஸ்டபிள்',
    category: 'state',
    qualification: '12th Pass',
    ageMin: 18,
    ageMax: 24,
    salaryMin: 21900,
    salaryMax: 69100,
    examPattern: 'Written + Physical + Medical',
    selectionProcess: ['Written Exam', 'Physical Measurement Test', 'Endurance Test', 'Medical Examination'],
    applyLink: 'https://tnusrb.tn.gov.in',
    nextExamDate: '2026-04-01',
    applicationStatus: 'upcoming',
    description: 'Constable (Grade II) in Tamil Nadu Police',
  },
  {
    id: 'tn-forest-guard',
    name: 'TN Forest Guard',
    nameTamil: 'தமிழ்நாடு வன காவலர்',
    category: 'state',
    qualification: '12th Pass',
    ageMin: 18,
    ageMax: 26,
    salaryMin: 20600,
    salaryMax: 65500,
    examPattern: 'Written + Physical + Medical',
    selectionProcess: ['Written Exam', 'Physical Test', 'Medical Examination'],
    applyLink: 'https://forests.tn.gov.in',
    nextExamDate: null,
    applicationStatus: 'closed',
    description: 'Forest Guard and Forest Watcher in TN Forest Department',
    posts: ['Forest Guard', 'Forest Watcher'],
  },
  {
    id: 'tneb-assessor',
    name: 'TNEB Assessor',
    nameTamil: 'TNEB மதிப்பீட்டாளர்',
    category: 'state',
    qualification: '12th Pass',
    ageMin: 18,
    ageMax: 30,
    salaryMin: 20000,
    salaryMax: 63200,
    examPattern: 'Written Exam + Interview',
    selectionProcess: ['Written Exam', 'Interview', 'Document Verification'],
    applyLink: 'https://tangedco.gov.in',
    nextExamDate: null,
    applicationStatus: 'closed',
    description: 'Assessor post in Tamil Nadu Electricity Board',
  },
  {
    id: 'coop-bank-clerk',
    name: 'Cooperative Bank Clerk',
    nameTamil: 'கூட்டுறவு வங்கி கிளர்க்',
    category: 'state',
    qualification: '12th Pass',
    ageMin: 18,
    ageMax: 30,
    salaryMin: 20000,
    salaryMax: 45000,
    examPattern: 'Written Exam + Interview',
    selectionProcess: ['Written Exam', 'Interview', 'Document Verification'],
    applyLink: 'https://drbtn.org',
    nextExamDate: '2026-03-20',
    applicationStatus: 'upcoming',
    description: 'Clerk/Assistant in TN Cooperative Banks',
  },
  {
    id: 'vao',
    name: 'Village Administrative Officer',
    nameTamil: 'கிராம நிர்வாக அலுவலர்',
    category: 'state',
    qualification: '12th Pass',
    ageMin: 18,
    ageMax: 30,
    salaryMin: 19500,
    salaryMax: 62000,
    examPattern: 'TNPSC Group 4',
    selectionProcess: ['TNPSC Group 4 Exam', 'Certificate Verification', 'Counselling'],
    applyLink: 'https://tnpsc.gov.in',
    nextExamDate: '2026-06-01',
    applicationStatus: 'upcoming',
    description: 'Village level administrative officer in Revenue Department',
  },

  // OTHER CENTRAL GOVT
  {
    id: 'army-clerk',
    name: 'Indian Army Clerk/SKT',
    nameTamil: 'இந்திய ராணுவ கிளர்க்/SKT',
    category: 'central',
    qualification: '12th Pass',
    ageMin: 17.5,
    ageMax: 23,
    salaryMin: 30000,
    salaryMax: 40000,
    examPattern: 'CEE + Physical + Medical',
    selectionProcess: ['Online Registration', 'Common Entrance Exam', 'Physical Test', 'Medical'],
    applyLink: 'https://joinindianarmy.nic.in',
    nextExamDate: '2026-03-01',
    applicationStatus: 'upcoming',
    description: 'Clerk/Store Keeper Technical in Indian Army (Agniveer)',
  },
  {
    id: 'fci-watchman',
    name: 'FCI Watchman',
    nameTamil: 'FCI காவலாளி',
    category: 'central',
    qualification: '12th Pass',
    ageMin: 18,
    ageMax: 25,
    salaryMin: 18000,
    salaryMax: 56900,
    examPattern: 'Written + Physical',
    selectionProcess: ['Written Exam', 'Physical Endurance Test', 'Document Verification'],
    applyLink: 'https://fci.gov.in',
    nextExamDate: null,
    applicationStatus: 'closed',
    description: 'Watchman post in Food Corporation of India',
  },
  {
    id: 'nvs-lab-attendant',
    name: 'NVS Lab Attendant',
    nameTamil: 'NVS ஆய்வக உதவியாளர்',
    category: 'central',
    qualification: '12th Pass',
    ageMin: 18,
    ageMax: 30,
    salaryMin: 18000,
    salaryMax: 56900,
    examPattern: 'Written Exam',
    selectionProcess: ['Written Exam', 'Document Verification'],
    applyLink: 'https://navodaya.gov.in',
    nextExamDate: '2026-02-28',
    applicationStatus: 'open',
    description: 'Lab Attendant in Navodaya Vidyalaya Samiti schools',
  },
  {
    id: 'kvs-non-teaching',
    name: 'KVS Non-Teaching Staff',
    nameTamil: 'KVS பயிற்றா பணியாளர்கள்',
    category: 'central',
    qualification: '12th Pass',
    ageMin: 18,
    ageMax: 30,
    salaryMin: 18000,
    salaryMax: 56900,
    examPattern: 'Written Exam + Skill Test',
    selectionProcess: ['Written Exam', 'Skill Test (if applicable)', 'Document Verification'],
    applyLink: 'https://kvsangathan.nic.in',
    nextExamDate: null,
    applicationStatus: 'closed',
    description: 'Non-Teaching positions in Kendriya Vidyalaya Sangathan',
    posts: ['LDC', 'UDC', 'Lab Attendant', 'Library Attendant'],
  },
];

export const categoryInfo = {
  defence: { label: 'Defence & Paramilitary', emoji: '🪖', color: 'from-green-600 to-emerald-700', bgColor: 'bg-green-50', borderColor: 'border-green-400' },
  railway: { label: 'Railway Jobs', emoji: '🚂', color: 'from-blue-600 to-indigo-700', bgColor: 'bg-blue-50', borderColor: 'border-blue-400' },
  ssc: { label: 'SSC', emoji: '📋', color: 'from-purple-600 to-violet-700', bgColor: 'bg-purple-50', borderColor: 'border-purple-400' },
  banking: { label: 'Banking & Insurance', emoji: '🏦', color: 'from-amber-600 to-orange-700', bgColor: 'bg-amber-50', borderColor: 'border-amber-400' },
  state: { label: 'Tamil Nadu State Govt', emoji: '🏛️', color: 'from-rose-600 to-red-700', bgColor: 'bg-rose-50', borderColor: 'border-rose-400' },
  central: { label: 'Other Central Govt', emoji: '🇮🇳', color: 'from-cyan-600 to-teal-700', bgColor: 'bg-cyan-50', borderColor: 'border-cyan-400' },
};
