-- Startup Guide Database Tables
-- Run this in Supabase SQL Editor

-- User startup profiles (onboarding data)
CREATE TABLE IF NOT EXISTS startup_user_profiles (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  field TEXT NOT NULL,
  sub_domain TEXT NOT NULL,
  location TEXT NOT NULL,
  experience TEXT NOT NULL,
  onboarding_complete BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id)
);

-- Weekly tasks generated by AI
CREATE TABLE IF NOT EXISTS startup_weekly_tasks (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  day INTEGER NOT NULL CHECK (day >= 1 AND day <= 7),
  task_title TEXT NOT NULL,
  task_description TEXT NOT NULL,
  goal TEXT NOT NULL,
  is_completed BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, day)
);

-- Daily reflections submitted by user
CREATE TABLE IF NOT EXISTS startup_daily_reflections (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  day INTEGER NOT NULL CHECK (day >= 1 AND day <= 7),
  reflection_text TEXT NOT NULL,
  submitted_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, day)
);

-- AI-detected problems from reflections
CREATE TABLE IF NOT EXISTS startup_detected_problems (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  problem_statement TEXT NOT NULL,
  pain_score INTEGER CHECK (pain_score >= 1 AND pain_score <= 10),
  target_customer TEXT,
  market_size INTEGER,
  uniqueness INTEGER,
  existing_gaps INTEGER,
  validated BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id)
);

-- Surveys generated for problem validation
CREATE TABLE IF NOT EXISTS startup_surveys (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  questions JSONB NOT NULL,
  share_link TEXT NOT NULL,
  problem_statement TEXT NOT NULL,
  target_customer TEXT,
  response_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id)
);

-- Survey responses from public respondents (no auth required)
CREATE TABLE IF NOT EXISTS startup_survey_responses (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  survey_id UUID REFERENCES startup_surveys(id) ON DELETE CASCADE,
  respondent_answers JSONB NOT NULL,
  submitted_at TIMESTAMPTZ DEFAULT now()
);

-- Product roadmaps generated by AI
CREATE TABLE IF NOT EXISTS startup_product_roadmaps (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  mvp_title TEXT NOT NULL,
  mvp_description TEXT NOT NULL,
  build_tool TEXT,
  business_model TEXT,
  week_steps JSONB,
  recommended_tools JSONB,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id)
);

-- Chat history for AI Mentor
CREATE TABLE IF NOT EXISTS startup_chat_history (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Startup scores
CREATE TABLE IF NOT EXISTS startup_scores (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  score INTEGER DEFAULT 0,
  onboarding_points INTEGER DEFAULT 0,
  task_points INTEGER DEFAULT 0,
  problem_points INTEGER DEFAULT 0,
  survey_points INTEGER DEFAULT 0,
  mvp_points INTEGER DEFAULT 0,
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id)
);

-- Enable RLS
ALTER TABLE startup_user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE startup_weekly_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE startup_daily_reflections ENABLE ROW LEVEL SECURITY;
ALTER TABLE startup_detected_problems ENABLE ROW LEVEL SECURITY;
ALTER TABLE startup_surveys ENABLE ROW LEVEL SECURITY;
ALTER TABLE startup_survey_responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE startup_product_roadmaps ENABLE ROW LEVEL SECURITY;
ALTER TABLE startup_chat_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE startup_scores ENABLE ROW LEVEL SECURITY;

-- RLS Policies for authenticated users
CREATE POLICY "Users can manage own profile" ON startup_user_profiles FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage own tasks" ON startup_weekly_tasks FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage own reflections" ON startup_daily_reflections FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage own problems" ON startup_detected_problems FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage own surveys" ON startup_surveys FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Anyone can read surveys for public page" ON startup_surveys FOR SELECT USING (true);
CREATE POLICY "Anyone can submit survey responses" ON startup_survey_responses FOR INSERT WITH CHECK (true);
CREATE POLICY "Survey owners can read responses" ON startup_survey_responses FOR SELECT USING (
  EXISTS (SELECT 1 FROM startup_surveys WHERE startup_surveys.id = survey_id AND startup_surveys.user_id = auth.uid())
);
CREATE POLICY "Users can manage own roadmaps" ON startup_product_roadmaps FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage own chat" ON startup_chat_history FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage own scores" ON startup_scores FOR ALL USING (auth.uid() = user_id);

-- Function to increment survey response count
CREATE OR REPLACE FUNCTION increment_survey_response_count()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE startup_surveys SET response_count = response_count + 1 WHERE id = NEW.survey_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER on_survey_response_insert
AFTER INSERT ON startup_survey_responses
FOR EACH ROW EXECUTE FUNCTION increment_survey_response_count();
